INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2, CONCAT('07-Ghost'), CONCAT('Barsburg Empire', CHAR(39), 's Military Academy is known for training elites who bring victory to the empire. Students of the academy freely utilize an ability called "Zaiphon" to fight, while the types of Zaiphon usable depends on the nature of the soldier.<br>
<br>Teito Klein, a student at the academy, is one of the most promising soldiers produced. Although ridiculed by everyone for being a sklave (German for slave) with no memories of his past, he is befriended by a fellow student called Mikage. While preparing for the final exam, Teito uncovers a dark secret related to his past. When an attempt to assassinate Ayanami, a high-ranking official who killed his father, fails, Teito is locked away awaiting punishment.<br>
<br>Only wanting the best for Teito, Mikage helps him escape. Teito ends up at the 7th District Church where he is taken in by the bishops. It is here that Teito attempts to evade the grasp of Ayanami and the Military, so he can rediscover his memories and learn why he is the person that can change the fate of the world.<br>
<br>[Written by MAL Rewrite]'), 2, '2009-04-07', '2009-09-22', 'Spring 2009', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/22605.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1, 2, '"Aka no Kakera (緋色のカケラ)"', ' by Suzuki Yuki', 'js-theme-songs', 'https://open.spotify.com/track/3GmN2UFru2DSK2pTzuxT9q')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (2, 2, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4, 2, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5, 2, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (6, 2, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (7, 2, 5);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2, 2, 2);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1, 2, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2, 2, 2);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (3, 2, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (4, 2, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13, 2, 1, CONCAT('The Future Of Painful Thoughts Is'), '2009-04-07', 'https://ebd.cda.pl/620x395/639897886');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14, 2, 2, CONCAT('Nostalgic Memories Accompany Pain'), '2009-04-14', 'https://ebd.cda.pl/620x395/6398972f4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15, 2, 3, CONCAT('My Innocent Child, Sleep Within The Light'), '2009-04-21', 'https://ebd.cda.pl/620x395/63989937b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16, 2, 4, CONCAT('To the Depths of the Earnest Prayer'), '2009-04-28', 'https://ebd.cda.pl/620x395/63989993d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17, 2, 5, CONCAT('Hot Tears, Gently Fill His Heart...'), '2009-05-05', 'https://ebd.cda.pl/620x395/63989754b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18, 2, 6, CONCAT('The Path of Justice Lead to Light'), '2009-05-12', 'https://ebd.cda.pl/620x395/639899681');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19, 2, 7, CONCAT('Does the Soul that was Devoured by the Wings, Dream of Its Beloved Child?'), '2009-05-19', 'https://ebd.cda.pl/620x395/6398984fa');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20, 2, 8, CONCAT('Half of His Soul Arouses a Sad Awakening'), '2009-05-26', 'https://ebd.cda.pl/620x395/639905025');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21, 2, 9, CONCAT('The Color of His Soul Will be Forever...'), '2009-06-02', 'https://ebd.cda.pl/620x395/6398987fc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22, 2, 10, CONCAT('That Is But One Form of Atonement'), '2009-06-09', 'https://ebd.cda.pl/620x395/6399002e3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23, 2, 11, CONCAT('Atonement For Loved Ones Is...'), '2009-06-16', 'https://ebd.cda.pl/620x395/639900857');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24, 2, 12, CONCAT('The Darkness Called "Pain" Treads Ever Closer...'), '2009-06-23', 'https://ebd.cda.pl/620x395/6398990bc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25, 2, 13, CONCAT('Down the Path of Light I See...'), '2009-06-30', 'https://ebd.cda.pl/620x395/63990172a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26, 2, 14, CONCAT('A Reason to Fight Together... The Right to be Called Brothers in Arms'), '2009-07-07', 'https://ebd.cda.pl/620x395/6399014f9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27, 2, 15, CONCAT('That Day, I was With Him'), '2009-07-14', 'https://ebd.cda.pl/620x395/639901194');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28, 2, 16, CONCAT('The Truth lies Deep within the Darkness Where Light Cannot Reach'), '2009-07-21', 'https://ebd.cda.pl/620x395/63990053f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29, 2, 17, CONCAT('The Family With Wings of Darkness, Enshrounded in Misery, Flies Down'), '2009-07-28', 'https://ebd.cda.pl/620x395/639902985');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30, 2, 18, CONCAT('The One Who Must be Forgiven Drown in Darkness... The One Who Loves Him is Filled With Tears'), '2009-08-04', 'https://ebd.cda.pl/620x395/63990357d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31, 2, 19, CONCAT('The One-Sided, Yet Never Dying Love Finds Itself...'), '2009-08-11', 'https://ebd.cda.pl/620x395/639903235');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32, 2, 20, CONCAT('They Both Offer a Requiem'), '2009-08-18', 'https://ebd.cda.pl/620x395/63990538a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33, 2, 21, CONCAT('Therefore, You Pass Through the Door of the Defeated'), '2009-08-25', 'https://ebd.cda.pl/620x395/6399020c8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34, 2, 22, CONCAT('Led by the Light in the Water`s Depths, He Spies Upon...'), '2009-09-01', 'https://ebd.cda.pl/620x395/639902698');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35, 2, 23, CONCAT('Before the Darkness of the Heart'), '2009-09-08', 'https://ebd.cda.pl/620x395/639905647');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36, 2, 24, CONCAT('The Justice of Those Who Lack Love is... . Oh Heart That is Stolen by Darkness, Forever...'), '2009-09-15', 'https://ebd.cda.pl/620x395/63990446a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (37, 2, 25, CONCAT('The Heart Is Led by the Truth Repeated on the Other Side...'), '2009-09-22', 'https://ebd.cda.pl/620x395/639903814');
