INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (6, CONCAT('18if'), CONCAT('Waking up in a strange bedroom in a dream world, teenager Haruto Tsukishiro finds a strange app on his phone. When he activates the program, an odd woman appears and tries to drag him to her realm. Luckily, a mysterious, white-haired girl severs their connection and helps him escape, revealing that the woman is a witch however, their conversation is cut short. As Haruto enters the realm again, he meets an anthropomorphic, talking cat named Katsumi Kanzaki. While the witch', CHAR(39), 's minions pursue them, the white-haired girl opens a door for them to escape.<br>
<br>After their ordeal, Haruto describes their savior—which only he can see—and Katsumi, the leading authority on dream world research, realizes that she must be "Lily," a being that resurfaces repeatedly across multiple dreamscapes. Hoping to leave the dream world through a blue door, they enter the witch', CHAR(39), 's realm once again. Finding themselves in peril, Lily reveals the truth to Haruto: witches suffer from "Sleeping Beauty Syndrome," a coma-like sleep state induced by torment in their real world lives. Thus, they cannot wake until they are defeated in the dream world.<br>
<br>After finally defeating the witch and locating the blue door, Haruto and Katsumi say their farewells, promising to meet up in the real world. However, when Haruto exits through the door he awakens in the dream world bedroom once more. Seeking answers, Haruto and Katsumi try to uncover the mysteries of the witches, Lily, and Haruto', CHAR(39), 's own inability to leave the dream world.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-07-07', '2017-09-29', 'Summer 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/86743.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (4, 6, '"Red Doors feat. Yoshikazu Mera (Red Doors feat.米良美一)"', ' by TeddyLoid', 'js-theme-songs', 'https://open.spotify.com/track/5rwwkjgyLuFTqJLD4PblXB')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (14, 6, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (15, 6, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (6, 6, 5);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (74, 6, 1, CONCAT('The Witch of Thunder'), '2017-07-07', 'https://ebd.cda.pl/620x368/148206133');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (75, 6, 2, CONCAT('Time Stopped at Age 12'), '2017-07-14', 'https://ebd.cda.pl/620x368/15046837a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (76, 6, 3, CONCAT('The Witch of First Love'), '2017-07-21', 'https://ebd.cda.pl/620x368/15053694e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (77, 6, 4, CONCAT('The Witch of Gluttony'), '2017-07-28', 'https://ebd.cda.pl/620x368/150545466');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (78, 6, 5, CONCAT('The Witch of Ordinariness'), '2017-08-04', 'https://ebd.cda.pl/620x368/151478187');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (79, 6, 6, CONCAT('Curses Return Upon the Casters'), '2017-08-11', 'https://ebd.cda.pl/620x368/152241062');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (80, 6, 7, CONCAT('And now There are none...'), '2017-08-18', 'https://ebd.cda.pl/620x368/1529792b0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (81, 6, 8, CONCAT('Threshold'), '2017-08-25', 'https://ebd.cda.pl/620x368/15386336c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (82, 6, 9, CONCAT('Idols Don', CHAR(39), 't Go to the Bathroom!'), '2017-09-01', 'https://ebd.cda.pl/620x368/1546439d9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (83, 6, 10, CONCAT('Dream Dimension α'), '2017-09-08', 'https://video.sibnet.ru/shell.php?videoid=3881840');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (84, 6, 11, CONCAT('The Thorn Cross Association'), '2017-09-15', 'https://ebd.cda.pl/620x368/157739143');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (85, 6, 12, CONCAT('The Witch Wars'), '2017-09-22', 'https://drive.google.com/file/d/1OuRqoXsU3eZAf3y62v7x_kRYniuPTRX7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (86, 6, 13, CONCAT('Eve', CHAR(39), 's Sigh'), '2017-09-29', 'https://drive.google.com/file/d/1iWP0o0USHM4DLOunhBjotqYZaGavmsxV/preview');
