INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (7, CONCAT('22/7'), CONCAT('Miu Takigawa views the world from behind the safety of her bangs, content with peacefully passing unnoticed through life. Reserved and timid, Miu struggles to converse with or even smile at customers when at her part time job, but she works tirelessly to support her mother and precious little sister, Haru. It is a shock when a letter arrives from the entertainment company GIP, announcing that she has been chosen as a candidate for their new project. <br>
<br>Miu decides to accept the invitation and heads to the meeting spot where the eccentric ensemble of other candidates filter in, all summoned by their own letters. Not long after, the girls are escorted by a manager to a luxurious secret facility, where it is explained that they must follow the mysterious directions of "The Wall," whose orders are absolute. <br>
<br>The 24th of December, 2016, will see the birth of idols like no other on that day, the group 22/7 will debut, whether or not Miu and the other members are ready to take the stage.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2020-01-11', '2020-03-28', 'Winter 2020', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1485/108385.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (5, 7, '"Muzui (ムズイ)"', ' by 22/7', 'js-theme-songs', 'https://open.spotify.com/track/6WgPTB2vJe3BuRI86rULNb')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (7, 7, 6);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (5, 7, 5);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (6, 7, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (87, 7, 1, CONCAT('Goodbye Small World'), '2020-01-11', 'https://ebd.cda.pl/620x368/440278264');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (88, 7, 2, CONCAT('Amid the Dizziness'), NULL, 'https://ebd.cda.pl/620x368/4450616ce');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (89, 7, 3, CONCAT('Hello New World'), NULL, 'https://ebd.cda.pl/620x368/449204660');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (90, 7, 4, CONCAT('The Promised Flower'), NULL, 'https://ebd.cda.pl/620x368/4559651ff');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (91, 7, 5, CONCAT('Just Flip It Over!'), NULL, 'https://ebd.cda.pl/620x368/458953416');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (92, 7, 6, CONCAT('Between the Even and Odd Numbers'), NULL, 'https://ebd.cda.pl/620x368/460025052');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (93, 7, 7, CONCAT('Happy☆Jet☆Coaster'), NULL, 'https://drive.google.com/file/d/1yBBJS8iTRdBEYQfSXkWMMTgyKhrp8Afv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (94, 7, 8, CONCAT('Dreaming Robot'), NULL, 'https://drive.google.com/file/d/1EfUHl4jZnjn9OzHEVdVCXBRwA51a4CPb/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (95, 7, 9, CONCAT('Lullaby of the Stars'), NULL, 'https://ebd.cda.pl/620x368/481657139');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (96, 7, 10, CONCAT('Goodbye to Our World'), NULL, 'https://drive.google.com/file/d/1ykSHPOcgJC4TCH-NbsjJ2yXAqkbRDCBl/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (97, 7, 11, CONCAT('Chasing Our Dreams'), NULL, 'https://ebd.cda.pl/620x368/4899787ac');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (98, 7, 12, CONCAT('22/7 (nanabun no nijyuuni)'), NULL, 'https://ebd.cda.pl/620x368/49140077d');
