INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (9, CONCAT('3D Kanojo: Real Girl'), CONCAT('For Hikari Tsutsui, life within the two-dimensional realm is much simpler. Socially inept and awkward, he immerses himself in video games and anime, only to be relentlessly ridiculed and ostracized by his classmates. Sharing his misery is Yuuto Itou, his only friend, who wears cat ears and is equally obsessed with the world of games. <br>
<br>After being forced to clean the pool as punishment for arriving late, Tsutsui meets Iroha Igarashi, but he attempts to steer clear of her, as her notoriety precedes her. Brazenly blunt, loathed by female classmates, and infamous for messing around with boys, Tsutsui believes that getting involved with her would cause nothing but problems. <br><br>3D Kanojo: Real Girl is a story revolving around these two outcasts—a boy full of emotions he has never experienced before, struggling to lay them bare, and a girl who strives to break him out of his shell.<br>
<br>[Written by MAL Rewrite]'), 1, '2018-04-04', '2018-06-20', 'Spring 2018', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1327/93616.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (7, 9, '"Daiji na Koto (だいじなこと)"', ' by Quruli', 'js-theme-songs', 'https://open.spotify.com/track/1IxKVKHJq31OqdeibxB6aO')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (6, 9, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (9, 9, 8);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (121, 9, 1, CONCAT('About the Time I First Met Her.'), '2018-04-04', 'https://drive.google.com/file/d/1j0_nligPMTgT9rlneqXKrk1Suu5ubhYA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (122, 9, 2, CONCAT('About the Time My Chastity Was in a Predicament.'), '2018-04-11', 'https://drive.google.com/file/d/1_XJUnTUC4ruc5sUhPNsxqWIPwbOHEWOi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (123, 9, 3, CONCAT('About the Time Normies Made Me Even Worse.'), '2018-04-18', 'https://ebd.cda.pl/620x395/61615559e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (124, 9, 4, CONCAT('About My Dark Times'), '2018-04-25', 'https://ebd.cda.pl/620x395/616159132');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (125, 9, 5, CONCAT('About When I Tried to Make Summer Memories.'), '2018-05-02', 'https://ebd.cda.pl/620x395/6162767bd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (126, 9, 6, CONCAT('About the Way I Apologize.'), '2018-05-09', 'https://ebd.cda.pl/620x395/616277002');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (127, 9, 7, CONCAT('About the Two Girls and Me.'), '2018-05-16', 'https://ebd.cda.pl/620x395/6162941c0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (128, 9, 8, CONCAT('About How Camping Was a High-Level Event for Me.'), '2018-05-23', 'https://ebd.cda.pl/620x395/6162944c5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (129, 9, 9, CONCAT('About Our Mutual Misunderstandings.'), '2018-05-30', 'https://ebd.cda.pl/620x395/61640936e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (130, 9, 10, CONCAT('About My Confession.'), '2018-06-06', 'https://ebd.cda.pl/620x395/616437559');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (131, 9, 11, CONCAT('About the Love of a Best Friend That I Worry About.'), '2018-06-13', 'https://ebd.cda.pl/620x395/6164537cb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (132, 9, 12, CONCAT('About the Shape of Our Love.'), '2018-06-20', 'https://ebd.cda.pl/620x395/6183773f8');
