INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (15, CONCAT('91 Days'), CONCAT('As a child living in the town of Lawless, Angelo Lagusa has witnessed a tragedy: his parents and younger brother have been mercilessly slaughtered by the Vanetti mafia family. Losing everything he holds dear, he leaves both his name and hometown behind, adopting the new identity of Avilio Bruno.<br>
<br>Seven years later, Avilio finally has his chance for revenge when he receives a mysterious letter prompting him to return to Lawless. Obliging, he soon encounters the Vanetti don', CHAR(39), 's son, Nero, and seeks to befriend him using the skills he has quietly honed for years.<br>
<br>Set during the Prohibition era, 91 Days tells the story of Avilio', CHAR(39), 's dark, bloodstained path to vengeance, as he slowly ends each of the men involved in the killing of his family.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-07-09', '2016-10-01', 'Summer 2016', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/80515.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (11, 15, '"Signal"', ' by TK from Ling Tosite Sigure', 'js-theme-songs', 'https://open.spotify.com/track/7mfK0QZL3lo6Fup1nF0qO7')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (37, 15, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (38, 15, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (39, 15, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (16, 15, 12);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (165, 15, 1, CONCAT('Night of the Murder'), '2016-07-09', 'https://drive.google.com/file/d/1uBMFEZTFE0niSc4PnYRIrHB3tiqB_pwO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (166, 15, 2, CONCAT('Phantom of Falsehood'), '2016-07-16', 'https://drive.google.com/file/d/1cpFgKZF9epS_UH4V5fa0tmEnZQroWYaz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (167, 15, 3, CONCAT('Where the Footfalls Lead'), '2016-07-23', 'https://drive.google.com/file/d/1po7Tu-WvsyE4nxL2vQqnNMls7OOPG68V/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (168, 15, 4, CONCAT('Losing to Win, and What Comes After'), '2016-07-30', 'https://drive.google.com/file/d/1wP3--zZ0BL4544sdtqb_QwP3ql2M8dRK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (169, 15, 5, CONCAT('Blood Will Have Blood'), '2016-08-06', 'https://drive.google.com/file/d/1WSzDL4rKc6REnDGXeeXUY8wNsT5JPdMD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (170, 15, 6, CONCAT('To Slaughter a Pig'), '2016-08-13', 'https://drive.google.com/file/d/1QhoNkJ-hfM3kFAvNQJ-pleAm4Pwq8_io/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (171, 15, 7, CONCAT('A Poor Player'), '2016-08-20', 'https://drive.google.com/file/d/1mM9qQAG3DEP52fGlXR7zrypDNsptgl2V/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (172, 15, 8, CONCAT('Behind the Curtain'), '2016-09-03', 'https://drive.google.com/file/d/1OPQAGXQzxWfH3GRki_R8cfEv_MaBN3Lp/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (173, 15, 9, CONCAT('Black and Deep Desires'), '2016-09-10', 'https://drive.google.com/file/d/1qKHb-en_8_0n-aH-Qxa2Q5PAeQhliTOG/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (174, 15, 10, CONCAT('Proof of Good Faith'), '2016-09-17', 'https://drive.google.com/file/d/1Cfr4ebgoEVXVnkPhGkdeWG0rlbHzMFl8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (175, 15, 11, CONCAT('All for Nothing'), '2016-09-24', 'https://drive.google.com/file/d/1a3xJBJLn7Id46C-QLmcR4iWidlhNTKV4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (176, 15, 12, CONCAT('Slipping Through the Dirty Sky'), '2016-10-01', 'https://drive.google.com/file/d/1o60QHIedjYhR-hOxMTIlkprhj0ZkdV17/preview');
