INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (39, CONCAT('Aggressive Retsuko'), CONCAT('Whether it be facing misogynistic remarks from her boss or being pressured by condescending co-workers, stress is just another part of the job for 25-year-old red panda Retsuko. Despite being one of the most diligent workers at her office, her diminutiveness and modesty often lead her to be exploited by her colleagues. However, when her irritation hits the limit, Retsuko brings forth her unique brand of letting off steam: aggressive death metal karaoke bashing the idiocy and hypocrisy of her co-workers', CHAR(39), ' actions and work life. Although this venting only takes place in her mind, it gives her an outlet to counter her frustration in a world where hierarchy and appearances reign supreme.<br>
<br>[Written by MAL Rewrite] '), 4, '2016-04-02', '2018-03-31', 'Spring 2016', '1 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/84193.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (43, 39, 28);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (54, 39, 23);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (55, 39, 17);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (435, 39, 1, CONCAT('Stress Relief'), '2016-04-02', 'https://www.mp4upload.com/embed-fm2r30jasiyc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (436, 39, 2, CONCAT('Kabae'), '2016-04-09', 'https://www.mp4upload.com/embed-d6bzdvckjs79.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (437, 39, 3, CONCAT('King of Old-timers'), '2016-04-23', 'https://www.mp4upload.com/embed-ufrmub0fc66e.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (438, 39, 4, CONCAT('Yoga Studio'), '2016-04-30', 'https://www.mp4upload.com/embed-zzfl1g5ko7ro.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (439, 39, 5, CONCAT('Depressing Drinking'), '2016-05-07', 'https://streamtape.com/e/9v4OPVpdr0CaWdM/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (440, 39, 6, CONCAT('Mysterious Yoga Instructor'), '2016-05-14', 'https://www.mp4upload.com/embed-5hymrrwyrjo6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (441, 39, 7, CONCAT('Daily Relaxing Time'), '2016-05-21', 'https://www.mp4upload.com/embed-cs65r4bvyp5s.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (442, 39, 8, CONCAT('The Rush Hour'), '2016-05-28', 'https://www.mp4upload.com/embed-w7s7gcio63bh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (443, 39, 9, CONCAT('Kabae', CHAR(39), 's Visit'), '2016-06-04', 'https://www.mp4upload.com/embed-2utlzk3r5gkj.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (444, 39, 10, CONCAT('Exciting Overtime Work'), '2016-06-11', 'https://www.mp4upload.com/embed-xb7t0ugafjam.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (445, 39, 11, CONCAT('Director Gori', CHAR(39), 's Love Problem'), '2016-06-18', 'https://www.mp4upload.com/embed-upioyshho5vv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (446, 39, 12, CONCAT('Cute Junior'), '2016-06-25', 'https://www.mp4upload.com/embed-v3woue3so3ih.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (447, 39, 13, CONCAT('Young? Or Not Young?'), '2016-07-03', 'https://www.mp4upload.com/embed-u0nuueu6875b.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (448, 39, 14, CONCAT('Yokosawa'), '2016-07-10', 'https://www.mp4upload.com/embed-fr57z8vmd2ke.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (449, 39, 15, CONCAT('Retsuko', CHAR(39), 's Curry'), '2016-07-17', 'https://www.mp4upload.com/embed-gct4fsgfysnv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (450, 39, 16, CONCAT('Like'), '2016-07-23', 'https://www.mp4upload.com/embed-xxn3jc29wahh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (451, 39, 17, CONCAT('Making Tea'), '2016-07-30', 'https://www.mp4upload.com/embed-za9it20sasti.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (452, 39, 18, CONCAT('Air Conditioning War'), '2016-08-06', 'https://www.mp4upload.com/embed-wq6x7e3arrro.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (453, 39, 19, CONCAT('Retsuko', CHAR(39), 's Holiday'), '2016-08-13', 'https://www.mp4upload.com/embed-gt7mhwcdys73.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (454, 39, 20, CONCAT('Makeup Touch-up'), '2016-08-20', 'https://www.mp4upload.com/embed-mprdg37owgsr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (455, 39, 21, CONCAT('I Don', CHAR(39), 't Wanna Go To Work'), '2016-08-27', 'https://www.mp4upload.com/embed-1ewqcf8733oc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (456, 39, 22, CONCAT('Favoritism'), '2016-09-03', 'https://www.mp4upload.com/embed-oufw9a2tiwg0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (457, 39, 23, CONCAT('Woman With an Agena'), '2016-09-10', 'https://www.mp4upload.com/embed-zbwdadik3edp.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (458, 39, 24, CONCAT('Ms. Mashiro'), '2016-09-17', 'https://www.mp4upload.com/embed-yysm94pqdoza.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (459, 39, 25, CONCAT('Retsuko', CHAR(39), 's Souvenirs'), '2016-09-24', 'https://streamtape.com/e/lWx4kAqOZysaKe/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (460, 39, 26, CONCAT('Woman That Doesn', CHAR(39), 't Listen'), '2016-10-01', 'https://streamtape.com/e/qj1r1Ye800Fz8Gd/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (461, 39, 27, CONCAT('At the Family Restaurant'), '2016-10-08', 'https://streamtape.com/e/Pb6RrAY2mlF0303/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (462, 39, 28, CONCAT('Borrowed Book'), '2016-10-15', 'https://streamtape.com/e/9OaLejoQ7Jia0Jb/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (463, 39, 29, CONCAT('Organising a Meeting'), '2016-10-22', 'https://www.mp4upload.com/embed-mgt16dat6zd1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (464, 39, 30, CONCAT('The Blah-blah Girl'), '2016-10-29', 'https://www.mp4upload.com/embed-mqnjdbl57hbh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (465, 39, 31, CONCAT('Celebratory Picture'), '2016-11-05', 'https://www.mp4upload.com/embed-dzx7syt3b46e.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (466, 39, 32, CONCAT('Carefully Spoken Words'), '2016-11-12', 'https://www.mp4upload.com/embed-0jwhd6ov9zs2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (467, 39, 33, CONCAT('Woman That Won', CHAR(39), 't Go Home'), '2016-11-19', 'https://www.mp4upload.com/embed-e7fqldrkxz3v.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (468, 39, 34, CONCAT('Hopeless Boyfriend'), '2016-11-26', 'https://www.mp4upload.com/embed-75bmah0obkad.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (469, 39, 35, CONCAT('Woman Who Hate Each Other'), '2016-12-03', 'https://www.mp4upload.com/embed-e4zy60j5x9lp.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (470, 39, 36, CONCAT('Gossiping Busted'), '2016-12-10', 'https://www.mp4upload.com/embed-b6fdr71vc6tn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (471, 39, 37, CONCAT('Someone Who Looks Like She Has a Boyfriend'), '2016-12-17', 'https://www.mp4upload.com/embed-ss2o8momnpox.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (472, 39, 38, CONCAT('Christmas'), '2016-12-24', 'https://www.mp4upload.com/embed-tua175vni2f3.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (473, 39, 39, CONCAT('New Year', CHAR(39), 's Resolution'), '2017-01-07', 'https://www.mp4upload.com/embed-u66tt3s5lo9u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (474, 39, 40, CONCAT('Sales Clerk'), '2017-01-14', 'https://streamtape.com/e/zrVzXPLYjpTe6B/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (475, 39, 41, CONCAT('Embarrassing DVD'), '2017-01-21', 'https://www.mp4upload.com/embed-fo6qer7ja0kh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (476, 39, 42, CONCAT('Resasuke'), '2017-01-28', 'https://www.mp4upload.com/embed-pwk98bhweuaw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (477, 39, 43, CONCAT('Pre-Valentine', CHAR(39), 's Day'), '2017-02-04', 'https://www.mp4upload.com/embed-l1aqoszer18n.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (478, 39, 44, CONCAT('Valentine', CHAR(39), 's Day'), '2017-02-11', 'https://www.mp4upload.com/embed-6vf37sysvylg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (479, 39, 45, CONCAT('Cold'), '2017-02-18', 'https://www.mp4upload.com/embed-nfbomgc21faz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (480, 39, 46, CONCAT('Peek'), '2017-02-25', 'https://www.mp4upload.com/embed-q7etrwpv6wuc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (481, 39, 47, CONCAT('Countermeasures to Snoring'), '2017-03-04', 'https://www.mp4upload.com/embed-drcl6quucc09.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (482, 39, 48, CONCAT('Just Not That Into You'), '2017-03-11', 'https://www.mp4upload.com/embed-9v2spc8xhsnf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (483, 39, 49, CONCAT('The Boss', CHAR(39), ' Suggestion'), '2017-03-18', 'https://www.mp4upload.com/embed-a8h1w2i6scfj.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (484, 39, 50, CONCAT('Flower Viewing'), '2017-03-25', 'https://www.mp4upload.com/embed-ka7xqb7pexjs.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (485, 39, 51, CONCAT('April Fool', CHAR(39), 's'), '2017-04-01', 'https://www.mp4upload.com/embed-186vmc86lm6l.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (486, 39, 52, CONCAT('New Recruit 1'), '2017-04-08', 'https://www.mp4upload.com/embed-wf7d7sr4590g.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (487, 39, 53, CONCAT('Trip to the Convenience Store'), '2017-04-15', 'https://www.mp4upload.com/embed-xfq8vkwox24s.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (488, 39, 54, CONCAT('Trap of the Elevator'), '2017-04-22', 'https://www.mp4upload.com/embed-wq69qzdj4qkq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (489, 39, 55, CONCAT('Wall of Kabae'), '2017-04-29', 'https://www.mp4upload.com/embed-9vcaaf19v77u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (490, 39, 56, CONCAT('Self-conscious Gorilla'), '2017-05-06', 'https://www.mp4upload.com/embed-cn9eqt54gfja.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (491, 39, 57, CONCAT('New Recruit 2'), '2017-05-13', 'https://www.mp4upload.com/embed-qfiz57xyppj9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (492, 39, 58, CONCAT('The Whereabouts of the Present'), '2017-05-20', 'https://www.mp4upload.com/embed-4yampl2iajf0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (493, 39, 59, CONCAT('Trap of an All-you-can-drink Pub'), '2017-05-27', 'https://www.mp4upload.com/embed-sfbwe5fmtcxv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (494, 39, 60, CONCAT('Over-meticulous Man'), '2017-06-03', 'https://www.mp4upload.com/embed-p438i6kyofpx.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (495, 39, 61, CONCAT('I', CHAR(39), 'm Different From You'), '2017-06-10', 'https://www.mp4upload.com/embed-6sgwc0rs6vjr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (496, 39, 62, CONCAT('Support From the Junior'), '2017-06-17', 'https://www.mp4upload.com/embed-vwjxg986szoh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (497, 39, 63, CONCAT('Man That Never Fixes'), '2017-06-24', 'https://www.mp4upload.com/embed-2awwn6r3s8c4.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (498, 39, 64, CONCAT('Spoiler Alert'), '2017-07-01', 'https://www.mp4upload.com/embed-w3ufsby7yfmg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (499, 39, 65, CONCAT('Kabae', CHAR(39), 's Diet'), '2017-07-08', 'https://www.mp4upload.com/embed-jt17z77ey9z3.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (500, 39, 66, CONCAT('Meeting'), '2017-07-15', 'https://www.mp4upload.com/embed-nc9xehid7w96.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (501, 39, 67, CONCAT('Wandering Old Man'), '2017-07-22', 'https://www.mp4upload.com/embed-eejfz24z6u9l.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (502, 39, 68, CONCAT('Scorching Summer Sun'), '2017-07-29', 'https://www.mp4upload.com/embed-ib6uzxh2dzft.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (503, 39, 69, CONCAT('Fashion Police'), '2017-08-05', 'https://www.mp4upload.com/embed-7pf1u46jda5c.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (504, 39, 70, CONCAT('Dear Mother of That Child'), '2017-08-12', 'https://www.mp4upload.com/embed-6q93ezev8588.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (505, 39, 71, CONCAT('It', CHAR(39), 's Not Abut You'), '2017-08-19', 'https://www.mp4upload.com/embed-blg4qo53jef9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (506, 39, 72, CONCAT('Clueless Man'), '2017-09-02', 'https://www.mp4upload.com/embed-wew81b3qvcs5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (507, 39, 73, CONCAT('You Had a Boyfriend?'), '2017-09-09', 'https://www.mp4upload.com/embed-fassg7s8sd27.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (508, 39, 74, CONCAT('Retsuko', CHAR(39), 's Grandma'), '2017-09-16', 'https://www.mp4upload.com/embed-6zxuahaupdut.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (509, 39, 75, CONCAT('Let Me Have A Bite'), '2017-09-23', 'https://www.mp4upload.com/embed-sb33lt15os4u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (510, 39, 76, CONCAT('Pretending to Be Busy'), '2017-09-30', 'https://www.mp4upload.com/embed-db61hs794m2p.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (511, 39, 77, CONCAT('Who?'), '2017-10-07', 'https://www.mp4upload.com/embed-2h3dt55eqrlj.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (512, 39, 78, CONCAT('Stop Working Overtime'), '2017-10-14', 'https://www.mp4upload.com/embed-fl0hb50k5303.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (513, 39, 79, CONCAT('Woman Looking For Her Metro Card'), '2017-10-21', 'https://www.mp4upload.com/embed-tnhbo8fz0hxs.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (514, 39, 80, CONCAT('Promise'), '2017-10-28', 'https://www.mp4upload.com/embed-fm2bc74u2leu.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (515, 39, 81, CONCAT('Retsuko', CHAR(39), 's Birthday'), '2017-11-04', 'https://www.mp4upload.com/embed-m9py6a5v8l7s.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (516, 39, 82, CONCAT('Lazy Junior'), '2017-11-11', 'https://www.mp4upload.com/embed-kj5s7bwsg4o1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (517, 39, 83, CONCAT('Woman Who Is Too Polite'), '2017-11-18', 'https://www.mp4upload.com/embed-tz3ld3pclb5u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (518, 39, 84, CONCAT('Listen!'), '2017-11-25', 'https://www.mp4upload.com/embed-op5oquf4ta9f.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (519, 39, 85, CONCAT('Who Do You Think You Are?'), '2017-12-02', 'https://www.mp4upload.com/embed-2wt2l2y3d7sq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (520, 39, 86, CONCAT('That Thing'), '2017-12-09', 'https://www.mp4upload.com/embed-m7tbcqwfln5v.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (521, 39, 87, CONCAT('Winter Illumination'), '2017-12-16', 'https://www.mp4upload.com/embed-ynh4a95swzno.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (522, 39, 88, CONCAT('Revival of the Holy Night'), '2017-12-23', 'https://www.mp4upload.com/embed-vzjlp88i6k8v.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (523, 39, 89, CONCAT('Dad Language'), '2018-01-13', 'https://www.mp4upload.com/embed-26xcaq1r4nhg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (524, 39, 90, CONCAT('Friend Request From the Boss'), '2018-01-20', 'https://www.mp4upload.com/embed-0kw8nili82eu.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (525, 39, 91, CONCAT('Social Media With the Boss'), '2018-01-27', 'https://www.mp4upload.com/embed-hl5iox0chk7a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (526, 39, 92, CONCAT('Magazine Freebies'), '2018-02-03', 'https://www.mp4upload.com/embed-e634yziu20rl.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (527, 39, 93, CONCAT('Valentine', CHAR(39), 's Day 2'), '2018-02-10', 'https://www.mp4upload.com/embed-fktikpd5ji9p.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (528, 39, 94, CONCAT('Indecisive'), '2018-02-17', 'https://www.mp4upload.com/embed-yduf0ptniq77.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (529, 39, 95, CONCAT('Pick Up The Phone'), '2018-02-24', 'https://www.mp4upload.com/embed-8akya9lqzbx9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (530, 39, 96, CONCAT('Unimpressed'), '2018-03-03', 'https://www.mp4upload.com/embed-esyf6jyaiigs.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (531, 39, 97, CONCAT('You Can', CHAR(39), 't Say That!'), '2018-03-10', 'https://www.mp4upload.com/embed-21rvfmkou0l0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (532, 39, 98, CONCAT('White Day'), '2018-03-17', 'https://www.mp4upload.com/embed-wgy3fsy5vdis.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (533, 39, 99, CONCAT('Flower Viewing 2'), '2018-03-24', 'https://www.mp4upload.com/embed-d7b4a89bzs85.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (534, 39, 100, CONCAT('The Final Episode'), '2018-03-31', 'https://www.mp4upload.com/embed-0nd0aapvg5in.html');
