INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (42, CONCAT('Aho Girl'), CONCAT('Yoshiko Hanabatake is an idiot beyond all belief. Somehow managing to consistently score zeroes on all of her tests and consumed by an absurd obsession with bananas, her senseless acts have caused even her own mother to lose all hope. Only one person is up to the task of keeping her insanity in check: childhood friend Akuru "A-kun" Akutsu.<br>
<br>Though he bemoans the ridiculous behavior he has to endure, the studious but terrifying A-kun is always ready to put an end to any stupidity Yoshiko gets up to, with no qualms about using physical force. Unfortunately, no matter how many times he attempts to knock some sense into her, the girl bounces right back to her usual shenanigans, even dragging in some other eccentrics along for the ride. Try as he might to rein in her nonsense, every moment is unpredictable with Yoshiko and her profound idiocy on the loose.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-07-04', '2017-09-19', 'Summer 2017', '12 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/86665.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (27, 42, '"Zenryoku☆Summer! (全力☆Summer!)"', ' by angela', 'js-theme-songs', 'https://open.spotify.com/track/7KB5xzVUFKgLACMtYX0g7G')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (24, 42, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (92, 42, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (93, 42, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (46, 42, 30);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (597, 42, 1, CONCAT('She', CHAR(39), 's Here! Aho Girl!'), '2017-07-04', 'https://drive.google.com/file/d/0B3FQEG0g6x4ha0d4eHo2M2k1Qk0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (598, 42, 2, CONCAT('Aho Girl Multiplies!'), '2017-07-11', 'https://drive.google.com/file/d/1ak3J3z0fnSIfQVZdPg85KpEAdA5ZROYv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (599, 42, 3, CONCAT('Security in Senior Citizenship! Aho Girl!'), '2017-07-18', 'https://drive.google.com/file/d/17EkM7T3liYJ1-EhPBJcwyXIrcNZM1Upo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (600, 42, 4, CONCAT('Charge! Aho Girl!'), '2017-07-25', 'https://drive.google.com/file/d/1cyAyA-JV_9WNlZl3OS3AKku-CeSUQ9k8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (601, 42, 5, CONCAT('Summertime! Aho Girl!'), '2017-08-01', 'https://drive.google.com/file/d/11XpJLBeoeEndwJT2GxyGBPlvVCRqTL5e/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (602, 42, 6, CONCAT('A Hot Summer! Aho Girl'), '2017-08-08', 'https://drive.google.com/file/d/1_oposD9wh6scR28vvc33hFbZb0bJ_zyn/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (603, 42, 7, CONCAT('The Gal! Aho Girl!'), '2017-08-15', 'https://drive.google.com/file/d/1MOpMcFZ4Phsyz6xIKoCmcLAghTBx8kVc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (604, 42, 8, CONCAT('Like an Angel! Aho Girl!'), '2017-08-22', 'https://drive.google.com/file/d/1uBgjOKuvDEaK-s6PSkk6JDv9eBA0yJF6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (605, 42, 9, CONCAT('Festival! Aho Girl!'), '2017-08-29', 'https://drive.google.com/file/d/1YU8JARwacRJBOqXelxylJ1-st4YxLXpi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (606, 42, 10, CONCAT('Drive! Aho Girl!'), '2017-09-05', 'https://drive.google.com/file/d/1BKvAiPzazVpnr0TVkuS3hiw3G-2JnKLO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (607, 42, 11, CONCAT('Final Battle! Decisive Blow! Aho Girl'), '2017-09-12', 'https://drive.google.com/file/d/1hhgwC-969dJlChDsyHqlvNkTr7E8e581/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (608, 42, 12, CONCAT('Meeting... And! Aho Girl'), '2017-09-19', 'https://drive.google.com/file/d/1JVtCY1spPek8_O08rOfVDuoPOWTZp0Ho/preview');
