INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (70, CONCAT('Aldnoah.Zero'), CONCAT('The discovery of a hypergate on the Moon once allowed the human race to teleport to Mars. Those who chose to settle there unearthed a technology far more advanced than that of their home planet, which they named "Aldnoah." This discovery led to the founding of the Vers Empire of Mars and a declaration of war against the "Terrans," those who stayed behind on Earth. However, a battle on the moon—later called "Heaven', CHAR(39), 's Fall"—caused the hypergate to explode, destroying the moon and leading the two planets to establish an uneasy ceasefire.<br>
<br>Their peace was a fragile one, however. Fifteen years later, high school student Inaho Kaizuka witnesses the plotted assassination of the Vers Empire', CHAR(39), 's Princess Asseylum Vers Allusia, who had come to Earth in hopes of repairing the relationship between the empire and its homeland. The ceasefire is shattered, and the Martians declare war on the Terrans once again. In the face of this insurmountable enemy, Inaho and his friends must now fight against the Vers Empire to settle the war once and for all.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-07-06', '2014-09-21', 'Summer 2014', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/60263.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (158, 70, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (159, 70, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (81, 70, 6);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (82, 70, 45);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (73, 70, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (74, 70, 25);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1078, 70, 1, CONCAT('Princess of Vers / Princess of Mars'), '2014-07-06', 'https://ebd.cda.pl/620x395/4957250e8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1079, 70, 2, CONCAT('Beyond the Horizon / The Longest Day on Earth'), '2014-07-13', 'https://ebd.cda.pl/620x395/4957262e0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1080, 70, 3, CONCAT('The Children', CHAR(39), 's Echelon / Boys on the Battlefield'), '2014-07-20', 'https://ebd.cda.pl/620x395/4957265a1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1081, 70, 4, CONCAT('Point of No Return / Knight in Pursuit'), '2014-07-27', 'https://ebd.cda.pl/620x395/4957268fc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1082, 70, 5, CONCAT('Phantom of The Emperor / Ahead of an Audience'), '2014-08-03', 'https://ebd.cda.pl/620x395/495727461');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1083, 70, 6, CONCAT('Steel Step Suite / Island of Memory'), '2014-08-10', 'https://ebd.cda.pl/620x395/4957277b0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1084, 70, 7, CONCAT('The Boys of Earth / The Two Meet Each Other'), '2014-08-17', 'https://drive.google.com/file/d/1u1OLSx1nAesm3fmtg-hCPfwf3NIc19iu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1085, 70, 8, CONCAT('Then and Now / A Day When We Saw a Bird'), '2014-08-24', 'https://ebd.cda.pl/620x395/4957286d6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1086, 70, 9, CONCAT('Darkness Visible / Reminiscent Device'), '2014-08-31', 'https://ebd.cda.pl/620x395/4957289de');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1087, 70, 10, CONCAT('Before the War / Til Going to be a Storm'), '2014-09-07', 'https://ebd.cda.pl/620x395/495729222');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1088, 70, 11, CONCAT('Wind, Snow and Stars / Battle of Novosterisk'), '2014-09-14', 'https://drive.google.com/file/d/1Ls-bhuJ0i-tpzhpn3_UW0f787V_YPM6O/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1089, 70, 12, CONCAT('Childhood', CHAR(39), 's End / Even though the Heaven Falls'), '2014-09-21', 'https://drive.google.com/file/d/1ztUsaUW_11_0eNzCh1D9h41AM5Yf4Meh/preview');
