INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (80, CONCAT('Amanchu! Advance'), CONCAT('Second season of Amanchu!.'), 2, '2018-04-07', '2018-06-23', 'Spring 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1095/95063.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (183, 80, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (184, 80, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (185, 80, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (92, 80, 47);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (81, 80, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (82, 80, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1206, 80, 1, CONCAT('The Story of One Summer Night and a Confession'), NULL, 'https://vidoza.net/embed-w0u4es4xhh5a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1207, 80, 2, CONCAT('The Story of Midsummer and the Sparkling Eyes'), NULL, 'https://embed.tune.pk/play/7786002');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1208, 80, 3, CONCAT('The Story of the Pro and the Expert of Happiness'), NULL, 'https://vidoza.net/embed-ly2azn3c4br5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1209, 80, 4, CONCAT('The Story of Autumn and a Tender Happiness'), NULL, 'https://vidoza.net/4qijw92obfas');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1210, 80, 5, CONCAT('The Story of the Jet-Black Mermaid and the Solitude of 18m Under'), NULL, 'https://embed.tune.pk/play/7826947');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1211, 80, 6, CONCAT('The Story of a Halloween Night', CHAR(39), 's Dream'), NULL, 'https://streamtape.com/e/Al6Q2zBW2xIX38p/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1212, 80, 7, CONCAT('The Story of the Neverending School Festival'), NULL, 'https://streamtape.com/e/QJGpL068kYC0MM1/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1213, 80, 8, CONCAT('The Story of Fleeting, Unfulfilled Desires'), NULL, 'https://streamtape.com/e/1zZe0V6198Fyol/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1214, 80, 9, CONCAT('The Story of Tears and an Endless Dream'), NULL, 'https://streamtape.com/e/jq74mGg1kJizeQk/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1215, 80, 10, CONCAT('The Story of a New Beginning and New Feelings'), NULL, 'https://streamtape.com/e/wOjBRbkYeaFJRge/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1216, 80, 11, CONCAT('The Story of Cold, Flames, and Well Wishes'), NULL, 'https://streamtape.com/e/VWp1W2ld0dFKRPz/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1217, 80, 12, CONCAT(' The Story of Future Possibilities'), NULL, 'https://streamtape.com/e/Jv6Wr4gaK4TjxzV/');
