INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (83, CONCAT('Amnesia'), CONCAT('After fainting at work, a young lady awakens in the back room of the café she works at with no memory of her life or those around her. Two of her friends, whom she soon learns are named Shin and Toma, are called to help her get home safely. Once she is alone, she meets a spectral boy named Orion that only she can see and hear. He explains that she lost her memories because of his chance visit to her world, so he vows to help her remember who she is.<br>
<br>However, regaining her departed memories without worrying those around her may be more difficult than she realizes. In addition to the gloomy Shin and the protective Toma, she must be wary of arousing the suspicions of the captivating Ikki, the quick-witted Kent, and a mysterious man who lurks in the distance. As her amnesia entangles her in the lives of each of these men, her fragmented memories return piece by piece, and the mysteries of her circumstances slowly come to light.<br>
<br>[Written by MAL Rewrite]'), 1, '2013-01-07', '2013-03-25', 'Winter 2013', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1311/128738.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (50, 83, '"Zoetrope"', ' by Nagi Yanagi', 'js-theme-songs', 'https://open.spotify.com/track/65PGC6leDElkZDEklRvMcM')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (41, 83, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (191, 83, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (192, 83, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (193, 83, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (194, 83, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (95, 83, 50);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1242, 83, 1, CONCAT('I'), '2013-01-07', 'https://drive.google.com/file/d/1NJO98wd4FPycWwCQ7arwmLX6It06HgLz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1243, 83, 2, CONCAT('II'), '2013-01-14', 'https://drive.google.com/file/d/1Z-TBLbGyc67ivwB7KEcT3j01aLjfAp8k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1244, 83, 3, CONCAT('III'), '2013-01-21', 'https://drive.google.com/file/d/1E528dvYAcOICOWDmk9dqQ_V_8VeMDG5o/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1245, 83, 4, CONCAT('IV'), '2013-01-28', 'https://drive.google.com/file/d/1RYw0DN2DXNIbHwKy08oV97tA5xdgNlqF/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1246, 83, 5, CONCAT('V'), '2013-02-04', 'https://drive.google.com/file/d/1UZ5YbCTDw4VqRdEy8UAkcelecdpc69fz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1247, 83, 6, CONCAT('VI'), '2013-02-11', 'https://drive.google.com/file/d/1IiM3iANTi8y8o4M1nZRY5ydJjKomY3b9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1248, 83, 7, CONCAT('VII'), '2013-02-18', 'https://drive.google.com/file/d/1tOLqGdopoh6bq8QNP_OxKIYJ3S51hMYg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1249, 83, 8, CONCAT('VIII'), '2013-02-25', 'https://drive.google.com/file/d/1D07tGS3LanDfusDQx-hKrRfrEeI7LwYY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1250, 83, 9, CONCAT('IX'), '2013-03-04', 'https://drive.google.com/file/d/1jx2n9Dcqwab9Yo6xdgVMLdbM1APGGDzz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1251, 83, 10, CONCAT('X'), '2013-03-11', 'https://drive.google.com/file/d/1FROu1WQMhHjnnLD98MbD5jhTZ37fBUtF/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1252, 83, 11, CONCAT('XI'), '2013-03-18', 'https://drive.google.com/file/d/1n7XwS_BiCP74gul6kVZiD7XidGo-IrzK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1253, 83, 12, CONCAT('XII'), '2013-03-25', 'https://drive.google.com/file/d/1CoCX48e_mSG6K8312rHYtWhdvJpcJV8W/preview');
