INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (91, CONCAT('Anima Yell!'), CONCAT('Kohane Hatoya’s most lovable trait is also her greatest flaw. She loves to help others no matter how far she has to go in order to get the job done. Her biggest inspiration to do so comes to light when she sees what cheerleading looks like for the first time in middle school. Now a highschooler but as enthusiastic as ever, Kohane wants nothing more than to start her very own cheerleading squad. She', CHAR(39), 's encouraged by her best friend, Uki Sawatari, who often has to help her get out of trouble.<br>
<br>There is just one problem: Kohane does not have any experience in cheerleading. She has absolutely no idea what to do, what to wear, or how to perform. To make matters worse, she has been scared of heights since childhood, and this new sport is full of stunts pulled far from the ground for a girl her size. Enter Hizume Arima, a former cheerleader who wishes to leave her pastime behind. Unfortunately for her, Kohane recognizes Hizume, and will stop at nothing just so she can lead the new squad, even if it means facing her childhood fear.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2018-10-07', '2018-12-23', 'Fall 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1051/93862.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (55, 91, '"Jump Up↑ Yell!! (ジャンプアップ↑エール!!)"', ' by Kaminoki Koukou Cheering-bu [Kohane Hatoya (Yuka Ozaki), Hizume Arima (Yuina Yamada), Uki Sawatari (Mikako Izawa), Kotetsu Tatejima (Tomori Kusunoki), Kana Ushiku (Haruka Shiraishi)]', 'js-theme-songs', 'https://open.spotify.com/track/0UuSK5e4JFW2xqYm9HYJ8f')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (211, 91, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (212, 91, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (213, 91, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (214, 91, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (105, 91, 55);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (90, 91, 10);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (91, 91, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1347, 91, 1, CONCAT('My First Time Cheerleading'), NULL, 'https://ebd.cda.pl/620x368/27228294d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1348, 91, 2, CONCAT('Cute Yet Cool'), NULL, 'https://drive.google.com/file/d/1P5TDq7hly0n_kcMR4Md8HbShlMX4NUcu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1349, 91, 3, CONCAT('The Cheer Association, Cheering for Love!'), NULL, 'https://drive.google.com/file/d/1XfhtIMeyD-7aDmqnLW3cFkWiQscr5DXY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1350, 91, 4, CONCAT('Let', CHAR(39), 's Cheer UP!'), NULL, 'https://drive.google.com/file/d/1dtk_u-muvlR0PKGC9MJGTiqoC2MNXFK5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1351, 91, 5, CONCAT('Arm Motions With a Smile'), NULL, 'https://drive.google.com/file/d/1XL3uu2cZZShmiT--PEM10G0tln6YkUAd/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1352, 91, 6, CONCAT('Super Exciting Double Base Thigh Stand!'), NULL, 'https://ebd.cda.pl/620x395/5652611ae');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1353, 91, 7, CONCAT('The One on Top Is Scared of Heights'), NULL, 'https://ebd.cda.pl/620x395/565257562');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1354, 91, 8, CONCAT('Senpai and Me'), NULL, 'https://drive.google.com/file/d/1wlj3JfGRkEcYAAsVNQmor1WXLNR-QZ-p/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1355, 91, 9, CONCAT('The Captain Is Chosen! Five-Person Cheer Squad'), NULL, 'https://drive.google.com/file/d/1GfpcAHchvU42n-vGI_OUN8zW5O4Xxc3W/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1356, 91, 10, CONCAT('Socks and Summer Training Camp'), NULL, 'https://drive.google.com/file/d/1SmQT7zstK-R_Xwrn2ZHbXCPScCYQHJtP/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1357, 91, 11, CONCAT('Exciting Shoulder Straddle'), NULL, 'https://ebd.cda.pl/620x395/5652581cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1358, 91, 12, CONCAT('One for All, All for One'), NULL, 'https://ebd.cda.pl/620x395/565257884');
