INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (94, CONCAT('Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.'), CONCAT('Jinta Yadomi is peacefully living as a recluse, spending his days away from school and playing video games at home instead. One hot summer day, his childhood friend, Meiko "Menma" Honma, appears and pesters him to grant a forgotten wish. He pays her no mind, which annoys her, but he doesn', CHAR(39), 't really care. After all, Menma already died years ago.<br>
<br>At first, Jinta thinks that he is merely hallucinating due to the summer heat, but he is later on convinced that what he sees truly is the ghost of Menma. Jinta and his group of childhood friends grew apart after her untimely death, but they are drawn together once more as they try to lay Menma', CHAR(39), 's spirit to rest. Re-living their pain and guilt, will they be able to find the strength to help not only Menma move on—but themselves as well?<br>
<br>[Written by MAL Rewrite]'), 1, '2011-04-15', '2011-06-24', 'Spring 2011', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/79697.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (58, 94, '"Circle Game (サークルゲーム)"', ' by Galileo Galilei', 'js-theme-songs', 'https://open.spotify.com/track/334N1ixdELhqz6JrGQuqw9')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (215, 94, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (216, 94, 8);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (217, 94, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (108, 94, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1391, 94, 1, CONCAT('Super Peace Busters'), '2011-04-15', 'https://drive.google.com/file/d/1orV7C3MtXnJXZwKIKTnrrQjusm6xoCsy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1392, 94, 2, CONCAT('The Hero Menma'), '2011-04-22', 'https://drive.google.com/file/d/1J6ucDPpAiOI6Yf4jUgI_jR8cvg2Rvecg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1393, 94, 3, CONCAT('Menma Search Party'), '2011-04-29', 'https://drive.google.com/file/d/1dHSJrv-83Isw-vxVx2w6c96H62tkcTSX/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1394, 94, 4, CONCAT('A White Dress, A Blue Ribbon'), '2011-05-06', 'https://drive.google.com/file/d/1x4-oN3aIE-uuSx4JfuAy5AM3Pzt7SXeF/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1395, 94, 5, CONCAT('Tunnels'), '2011-05-13', 'https://drive.google.com/file/d/1MLzhBB06i8gY3LdtLU5LD-tjoTLIMOcY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1396, 94, 6, CONCAT('Forget Me, Forget Me Not'), '2011-05-20', 'https://drive.google.com/file/d/1ZjbedglGQpYcd6luNWHkrBkyT2seFP8k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1397, 94, 7, CONCAT('True Wish'), '2011-05-27', 'https://drive.google.com/file/d/129xcOaDkjPBiu4QAkS3qlWa0WNKjyqpS/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1398, 94, 8, CONCAT('I Wonder'), '2011-06-03', 'https://drive.google.com/file/d/1Ze31zKSmJEUV9DEd0mklT-YBGgw1hPtv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1399, 94, 9, CONCAT('Menma and the Rest'), '2011-06-10', 'https://drive.google.com/file/d/17IsvGL7lEYGs8-6LOg15V3Wc7JdQOapa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1400, 94, 10, CONCAT('Fireworks'), '2011-06-17', 'https://drive.google.com/file/d/1T4cx3foDRjgFJ-Jf9rPrlqUrubMtqCHQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1401, 94, 11, CONCAT('The Flower That Bloomed That Summer'), '2011-06-24', 'https://drive.google.com/file/d/1tUyX_L6ML39bKZcN04AB_4z4tPWOnXun/preview');
