INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (112, CONCAT('Appare-Ranman!'), CONCAT('No dream is too big for Appare Sorrano, a socially-awkward inventor living in a small rural town in Japan in the late 19th century. Fascinated since childhood by the creation of steamships that can connect people across great distances, he', CHAR(39), 's learned to make machines of all kinds from various scientific texts. His goal is to sail across the sea, beyond the sky, and ultimately, to the other side of the moon.<br>
<br>Unfortunately, through a string of events, Appare finds himself stranded in the middle of the sea on his mini steamship. Floating alongside him is a skilled but cowardly samurai, Kosame Ishikki, who was tasked to keep his eccentric behavior in check. Just when all hope seems lost, a large steamship saves them and takes them to Los Angeles. With no money or plans, they decide to participate in the "Trans-America Wild Race," which gives Appare the chance to build his own automobile, and Kosame the opportunity to use the cash prize to return home. However, against rival racers and unknown challenges residing in the wilderness, just how far will this adventure take Appare and Kosame?<br>
<br>[Written by MAL Rewrite]'), 1, '2020-04-10', '2020-09-25', 'Spring 2020', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1087/111636.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (68, 112, '"I got it!"', ' by Mia REGINA', 'js-theme-songs', 'https://open.spotify.com/track/1TEwhell7ifaxT6VVw5B4E')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (126, 112, 52);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (112, 112, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (113, 112, 35);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1620, 112, 1, CONCAT('Sunny (Appare), with Occasional Showers (Kosame)'), '2020-04-10', 'https://ebd.cda.pl/620x368/49879342a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1621, 112, 2, CONCAT('In the Dark'), '2020-04-17', 'https://ebd.cda.pl/620x368/50347161d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1622, 112, 3, CONCAT('Duel'), '2020-04-24', 'https://ebd.cda.pl/620x368/50690788d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1623, 112, 4, CONCAT('Let It Go'), '2020-07-24', 'https://ebd.cda.pl/620x368/552508160');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1624, 112, 5, CONCAT('The Eve, and...'), '2020-07-31', 'https://video.sibnet.ru/shell.php?videoid=4026963');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1625, 112, 6, CONCAT('I Am Gil!'), '2020-08-07', 'https://video.sibnet.ru/shell.php?videoid=4033813');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1626, 112, 7, CONCAT('Fake'), '2020-08-14', 'https://video.sibnet.ru/shell.php?videoid=4040287');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1627, 112, 8, CONCAT('Heavy Rain'), '2020-08-21', 'https://video.sibnet.ru/shell.php?videoid=4049417');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1628, 112, 9, CONCAT('Short Break'), '2020-08-28', 'https://video.sibnet.ru/shell.php?videoid=4057993');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1629, 112, 10, CONCAT('The Bridge to Hell'), '2020-09-04', 'https://video.sibnet.ru/shell.php?videoid=4068018');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1630, 112, 11, CONCAT('Rain in the Dark Night'), '2020-09-11', 'https://video.sibnet.ru/shell.php?videoid=4079092');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1631, 112, 12, CONCAT('We Will Stop You!!'), '2020-09-18', 'https://video.sibnet.ru/shell.php?videoid=4087045');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1632, 112, 13, CONCAT('Over the Moon'), '2020-09-25', 'https://video.sibnet.ru/shell.php?videoid=4093209');
