INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (154, CONCAT('Back Arrow'), CONCAT('The world of Lingalind is surrounded by a mystical wall with seemingly nothing beyond its confines. Worshipped as the mother of the land, the wall delivers celestial gift capsules called "Rakuho', CHAR(39), '', CHAR(39), ' to locations across the continent. Arriving once a month, the capsules contain metallic armbands that allow the wearer to transform into a mechanical being known as a "Briheight." As a result, Lingalind is thrown into constant turmoil by its warring nations, all hoping to strengthen their military prowess by procuring the offerings for themselves.<br>
<br>One day, a Rakuho crash-lands in the countryside with an unexpected inhabitant—a mysterious black-haired man. All eyes are set on this strange newcomer, who calls himself "Back Arrow," when he claims to have hailed from a place beyond the wall—a revelation that can potentially unravel Lingalind', CHAR(39), 's entire dogmatic foundation.<br>
<br>[Written by MAL Rewrite]'), 1, '2021-01-09', '2021-06-19', 'Winter 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1373/111546.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (176, 154, 72);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2164, 154, 1, CONCAT('Do Guys From the Sky Have Undies?'), NULL, 'https://ebd.cda.pl/620x368/647056736');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2165, 154, 2, CONCAT('Is Having Dreams a Burden?'), NULL, 'https://ebd.cda.pl/620x368/6510980b6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2166, 154, 3, CONCAT('Does a Huge Ship Bring Hope?'), NULL, 'https://ebd.cda.pl/620x368/6549653ef');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2167, 154, 4, CONCAT('Does Genius Come When Least Expected?'), NULL, 'https://ebd.cda.pl/620x368/659106828');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2168, 154, 5, CONCAT('Is Today Yesterday', CHAR(39), 's Tomorrow?'), NULL, 'https://ebd.cda.pl/620x368/664971216');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2169, 154, 6, CONCAT('Are Pretty Boy Farms a Thing?'), NULL, 'https://ebd.cda.pl/620x368/6730343d8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2170, 154, 7, CONCAT('Is the Wall Really That Solid?'), NULL, 'https://ebd.cda.pl/620x368/6793214c5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2171, 154, 8, CONCAT('What is the Bloodstained Knight Hiding?'), NULL, 'https://ebd.cda.pl/620x368/68614935c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2172, 154, 9, CONCAT('Why Do Lips that Profess Love Hide Fangs?'), NULL, 'https://ebd.cda.pl/620x368/691308115');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2173, 154, 10, CONCAT('Can Have-Nots Have Backbone?'), NULL, 'https://ebd.cda.pl/620x368/69695329f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2174, 154, 11, CONCAT('Is This a Head-to-Head Fight?'), NULL, 'https://ebd.cda.pl/620x368/7025638ca');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2175, 154, 12, CONCAT('Is Too Much Pride A Problem?'), NULL, 'https://ebd.cda.pl/620x368/709562296');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2176, 154, 13, CONCAT('Do the Heavens Cry When the Princess Rises?'), NULL, 'https://ebd.cda.pl/620x368/7174132f9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2177, 154, 14, CONCAT('Is There Love on the Battlefield?'), NULL, 'https://ebd.cda.pl/620x368/72263478e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2178, 154, 15, CONCAT('What Will the Riots Produce?'), NULL, 'https://ebd.cda.pl/620x368/727458774');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2179, 154, 16, CONCAT('When People Want Peace, What Does God Want?'), NULL, 'https://ebd.cda.pl/620x368/732518006');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2180, 154, 17, CONCAT('Is This How They Rise Up?'), NULL, 'https://ebd.cda.pl/620x368/7385272bb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2181, 154, 18, CONCAT('Is This the World', CHAR(39), 's Truth?'), NULL, 'https://ebd.cda.pl/620x368/7437805ad');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2182, 154, 19, CONCAT('Can You Sort This Out?'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4315752');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2183, 154, 20, CONCAT('Does People', CHAR(39), 's Anger Reach God?'), NULL, 'https://ebd.cda.pl/620x368/754643551');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2184, 154, 21, CONCAT('Who Will Stop Me?'), NULL, 'https://ebd.cda.pl/620x368/760414631');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2185, 154, 22, CONCAT('But What Do I Live For?'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4328678');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2186, 154, 23, CONCAT('Does Destruction Rain From the Heavens?'), NULL, 'https://ebd.cda.pl/620x368/772078120');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2187, 154, 24, CONCAT('Do We Head for the Stars?'), NULL, 'https://ebd.cda.pl/620x368/77568731f');
