INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (158, CONCAT('Baka to Test to Shoukanjuu Ni!'), CONCAT('The blockheads of Class F return with more misadventures! Rather than desperately competing against the elite students in Class A for better facilities, they have other problems at hand. While the girls are constantly vying for the boys', CHAR(39), ' attention, Akihisa Yoshii and Yuuji Sakamoto are being blackmailed by a stalker who threatens to reveal their most embarrassing secrets to the whole school. Moreover,  everyone', CHAR(39), 's avatar starts to behave strangely. <br>
<br>Filled with more nosebleeds and eye-pokes, the boys of Class F must work together to discover the stalker', CHAR(39), 's identity and deal with the misfortunes that come with love among fools.<br>
<br>[Written by MAL Rewrite]'), 1, '2011-07-08', '2011-09-30', 'Summer 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/28992.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (105, 158, '"Eureka Baby (エウレカベイビー)"', ' by Natsuko Asou', 'js-theme-songs', 'https://open.spotify.com/track/71b4LW6k5jdVRCwANproHs');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (358, 158, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (359, 158, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (180, 158, 50);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (167, 158, 22);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (168, 158, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2204, 158, 1, CONCAT('Me, Everyone, and Swimming in the Ocean!'), '2011-07-08', 'https://drive.google.com/file/d/14xhLmXQTUBsTKOAOrU3t6xVuU_nrwe-D/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2205, 158, 2, CONCAT('Me, Yukata, and Festivities!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4090378');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2206, 158, 3, CONCAT('Me, That Girl, and a Stuffed Toy!'), NULL, 'https://drive.google.com/file/d/1amJiPVB0bPEnio2mg16DAW_6yp_ytjw0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2207, 158, 4, CONCAT('Me, TRUE Colors and a Man', CHAR(39), 's Dignity!'), NULL, 'https://drive.google.com/file/d/1LoSp3YkqCZBiopLxB0Sn2YuPjMV2TkZO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2208, 158, 5, CONCAT('Me, Peeking, and Training Camp!'), NULL, 'https://drive.google.com/file/d/1MrczYfDFLBUTr7qh8-yzBOHg3ESHkbMJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2209, 158, 6, CONCAT('Me, Peeking, and Guys', CHAR(39), ' Friendship!'), NULL, 'https://drive.google.com/file/d/1xCRfN4731pZgx8FcPbUOHKfy1Nu3KxJ7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2210, 158, 7, CONCAT('Me, Peeking, and Far Away Paradise!'), NULL, 'https://drive.google.com/file/d/1hb_BUvrmoQikEBtgeHRpAzBCLgnOtQrQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2211, 158, 8, CONCAT('Me, Japan, and Unknown Words!'), NULL, 'https://drive.google.com/file/d/1ivv1qyub5ZDkQ1OJGmYPe-3c0xNAxADc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2212, 158, 9, CONCAT('Me, Romance, and Negotiation Skills!'), NULL, 'https://drive.google.com/file/d/1HrQ6p7pB8VvJyFIeVtZn596SC9OuLcAs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2213, 158, 10, CONCAT('Me, Romance, and Love Skills!'), NULL, 'https://drive.google.com/file/d/1sD9Y_a1Eebv_uVCScLc1Sb3ErESYqOm2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2214, 158, 11, CONCAT('Yuuji, Shouko, and Childhood Memories!'), NULL, 'https://drive.google.com/file/d/13THkY0JWjYWwdX6f9WchAUw2dUqytDSf/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2215, 158, 12, CONCAT('Idiots, Clownery, and Requiem!'), NULL, 'https://drive.google.com/file/d/1IGl07QdXEc-pvksg9_N7UbhMYfE_SNZ6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2216, 158, 13, CONCAT('BAKA and TEST - Summon The Beasts!'), NULL, 'https://drive.google.com/file/d/1yS0cik2yKa59JbIq_syL2l-d2lYa2k_7/preview');
