INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (180, CONCAT('Baraou no Souretsu'), CONCAT('Richard Plantagenet has dedicated his whole life to becoming strong enough to fight alongside his father, the Duke of York. Together they have waged war to reclaim the right to the throne of England from King Henry VI and the House of Lancaster. However, the young Richard hides a secret—one that his mother scorns him for, which the cruel voices in his head never fail to remind him of. Even amid his personal turmoil, he is fortunate to find solace in the light of his father', CHAR(39), 's love. But when the War of the Roses takes a turn for the bloodier, the fervent ambitions of Richard grow while his old loyalties splinter, threatening to taint his family', CHAR(39), 's path to glory.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-01-09', '2022-06-26', 'Winter 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1046/118527.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (125, 180, '"Ware, Bara ni Insu (我, 薔薇に淫す)"', ' by Makoto Furukawa', 'js-theme-songs', 'https://open.spotify.com/track/1E6E8k6C9NTeEiEVCFEsIr');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (83, 180, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (405, 180, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (406, 180, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (407, 180, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (203, 180, 31);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2526, 180, 24, CONCAT('Requiem of the Rose King'), NULL, 'https://ebd.cda.pl/620x368/1129351328');
