INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (194, CONCAT('Beastars'), CONCAT('In a civilized society of anthropomorphic animals, an uneasy tension exists between carnivores and herbivores. At Cherryton Academy, this mutual distrust peaks after a predation incident results in the death of Tem, an alpaca in the school', CHAR(39), 's drama club. Tem', CHAR(39), 's friend Legoshi, a grey wolf in the stage crew, has been an object of fear and suspicion for his whole life. In the immediate aftermath of the tragedy, he continues to lay low and hide his menacing traits, much to the disapproval of Louis, a red deer and the domineering star actor of the drama club.<br>
<br>When Louis sneaks into the auditorium to train Tem', CHAR(39), 's replacement for an upcoming play, he assigns Legoshi to lookout duty. That very night, Legoshi has a fateful encounter with Haru, a white dwarf rabbit scorned by her peers. His growing feelings for Haru, complicated by his predatory instincts, force him to confront his own true nature, the circumstances surrounding the death of his friend, and the undercurrent of violence plaguing the world around him.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-10-10', '2019-12-26', 'Fall 2019', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1234/102008.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (138, 194, '"Le zoo"', ' by YURiKA', 'js-theme-songs', 'https://open.spotify.com/track/4MD7NIoJrvqTveOK8yyBZ6');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (90, 194, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (456, 194, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (457, 194, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (217, 194, 79);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (200, 194, 23);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (201, 194, 4);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (202, 194, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2736, 194, 1, CONCAT('The Moon and the Beast'), '2019-10-10', 'https://drive.google.com/file/d/1sh9XX7szc5c7Xnndw7-D4yU4M6Ro3gH9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2737, 194, 2, CONCAT('The Academy', CHAR(39), 's Top Dogs'), '2019-10-17', 'https://drive.google.com/file/d/19ahcqReQq_DcvB4NCX_RFd_Nid-qyIIr/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2738, 194, 3, CONCAT('A Wolf is Born'), '2019-10-24', 'https://drive.google.com/file/d/1dtO35qoAhFVytPGuc1sH7Xfymlv_6Hwv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2739, 194, 4, CONCAT('Give It Your All'), '2019-10-31', 'https://drive.google.com/file/d/1IwwTQU_YXW9-1rvQigdnkQIyUbc9Y3xj/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2740, 194, 5, CONCAT('Two Sides to the Story'), '2019-11-07', 'https://drive.google.com/file/d/1OLkmtuvPy9zNuuT5NdM12mL3JEsbc2iL/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2741, 194, 6, CONCAT('Blurred Vision: Dream or Reality?'), '2019-11-14', 'https://drive.google.com/file/d/1yH_IucCvXGry0ySXB8CxW5MdACxz1VzH/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2742, 194, 7, CONCAT('Below the Fur Coat'), '2019-11-21', 'https://ebd.cda.pl/620x368/4188052cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2743, 194, 8, CONCAT('Caught like Floss in a Canine', CHAR(39), 's Tooth'), '2019-11-28', 'https://ebd.cda.pl/620x368/4208028ef');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2744, 194, 9, CONCAT('Into the Lion', CHAR(39), 's Den'), '2019-12-05', 'https://ebd.cda.pl/620x368/4229771ea');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2745, 194, 10, CONCAT('A Wolf in Sheep', CHAR(39), 's Clothing'), '2019-12-12', 'https://ebd.cda.pl/620x368/4271531b6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2746, 194, 11, CONCAT('To the Neon District'), '2019-12-19', 'https://ebd.cda.pl/620x368/496781010');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2747, 194, 12, CONCAT('In the Storm', CHAR(39), 's Wake'), '2019-12-26', 'https://ebd.cda.pl/620x368/4327445c4');
