INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (203, CONCAT('Bernard-jou Iwaku.'), CONCAT('​Sawako Machida—or "Miss Bernard," as she prefers to be called—can frequently be found in the school library with a book in hand. Whether or not she has read it, however, is another matter entirely. In her own words, Sawako finds it too much work to actually read, and would rather just make others believe she spends a lot of time reading. But in the same library where she constantly hangs out, there are other students who love books and are quite upset with her disdainful approach to reading their favorite titles.<br>
<br>As she pretends to read and discuss great literary works amid eccentric book lovers, Sawako finds herself learning something after all, as well as making new friends along the way.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-10-07', '2016-12-23', 'Fall 2016', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/81589.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (227, 203, 82);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2895, 203, 1, CONCAT('Miss Bernard Said'), '2016-10-07', 'https://tune.pk/video/shxskktynykq');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2896, 203, 2, CONCAT('Episode 2'), '2016-10-14', 'https://tune.pk/video/6728987');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2897, 203, 3, CONCAT('Episode 3'), '2016-10-21', 'https://www.mp4upload.com/embed-wl5yn8znt0un.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2898, 203, 4, CONCAT('Episode 4'), '2016-10-28', 'https://www.mp4upload.com/embed-zkedj5t3anu9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2899, 203, 5, CONCAT('Episode 5'), '2016-11-04', 'https://www.mp4upload.com/embed-eg278r0sgvj8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2900, 203, 6, CONCAT('Episode 6'), '2016-11-11', 'https://www.mp4upload.com/embed-m791mf51uu10.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2901, 203, 7, CONCAT('Used Bookstores'), NULL, 'https://www.mp4upload.com/embed-zqj9y6t3mlwy.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2902, 203, 8, CONCAT('Fermat', CHAR(39), 's Last Theorem'), NULL, 'https://www.mp4upload.com/embed-ox3nsug5n7vf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2903, 203, 9, CONCAT('Bus Stop'), NULL, 'https://www.mp4upload.com/embed-at9hx4a8gk4y.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2904, 203, 10, CONCAT('A Day Without Machida Sawako'), NULL, 'https://www.mp4upload.com/embed-h2nur1ph2ssq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2905, 203, 11, CONCAT('Exchanging Letters'), NULL, 'https://www.mp4upload.com/embed-u800w2xijyxq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2906, 203, 12, CONCAT('Solo Journey'), NULL, 'https://www.mp4upload.com/embed-vt8yb5yppwsg.html');
