INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (213, CONCAT('Birdie Wing: Golf Girls', CHAR(39), ' Story'), CONCAT('Infamous among those who gamble on golf games, Eve uses her exceptional skill in the sport to earn a living—by betting and winning against various opponents. Known as the "Rainbow Bullet," she vows to beat her foes and conquer the world of underground golf using only three clubs. However, the universe where Eve knows no defeat is shaken after she plays a clean game with Aoi Amawashi, a golfing prodigy that came to the country of Nafrece to enter a golf tournament. Armed with talent and born into the perfect environment for golf, Aoi the "Innocent Tyrant" calmly crushes her enemies with a bright smile on her face.<br>
<br>After their game-changing match, Eve and Aoi become intrigued with each other and promise to battle again someday. As Eve', CHAR(39), 's aggressive and risk-taking approach challenges the elite and steady playstyle of Aoi, the two geniuses may just manage to bring golf to unexpected heights.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-04-06', '2022-06-29', 'Spring 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1343/120488.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (238, 213, 86);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2993, 213, 1, CONCAT('Rainbow Bullet'), NULL, 'https://ebd.cda.pl/620x368/108446770f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2994, 213, 2, CONCAT('Innocent Tyrant'), NULL, 'https://ebd.cda.pl/620x368/10866217fc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2995, 213, 3, CONCAT('A Match Between Just the Two of Us'), NULL, 'https://dood.pm/e/8vzh4ospct3o');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2996, 213, 4, CONCAT('Vipère'), NULL, 'https://dood.pm/e/0aq4xij2ia2p');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2997, 213, 5, CONCAT('VR'), NULL, 'https://dood.pm/e/2rho4ga0d14k');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2998, 213, 6, CONCAT('Rebellion’s Cry'), NULL, 'https://dood.pm/e/czx84bimy4mr');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (2999, 213, 7, CONCAT('Purple Bullet'), NULL, 'https://dood.pm/e/0dq93jdqx6it');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3000, 213, 8, CONCAT('Final Bullet'), NULL, 'https://dood.pm/e/ta3ov8ls5d7h');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3001, 213, 9, CONCAT('Ichina Saotome Wants to Be a Pro Caddy!'), NULL, 'https://dood.pm/e/f0ed5lrbjq3r');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3002, 213, 10, CONCAT('Evangeline is Frightfully Upset'), NULL, 'https://dood.pm/e/37odqbwp67xj');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3003, 213, 11, CONCAT('No Matter How Tall a Weed Grows, It Will Never Reach the Sun'), NULL, 'https://dood.pm/e/ad4z94k0u1xh');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3004, 213, 12, CONCAT('Are Aoi and Eve okay together? The Doubles Championship Begins'), NULL, 'https://dood.pm/e/2pky9ky2s8sh');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3005, 213, 13, CONCAT('I Think Who Gets What Room Is Very Important For Girls'), NULL, 'https://dood.pm/e/3ly6vdtipnyd');
