INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (224, CONCAT('Black Lagoon Omake'), CONCAT('Special omake episodes from the Blu-Ray releases, showing the heroines and foes in funny, uncommon situations.'), 3, '2009-12-23', '2010-03-25', '', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/22266.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (108, 224, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (250, 224, 21);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (236, 224, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (237, 224, 40);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3281, 224, 1, CONCAT('Highschool Life'), '2009-12-23', 'https://youtube.com/embed/4THfseUuDFU');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3282, 224, 2, CONCAT('The Magical Girl'), '2009-12-23', 'https://youtube.com/embed/glG_kRqPLUE');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3283, 224, 3, CONCAT('The Melancholy of Balalaika'), '2010-02-10', 'https://youtube.com/embed/j4Xdqz-M5Tk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3284, 224, 4, CONCAT('Boys and Girls'), '2010-02-10', 'https://youtube.com/embed/ESUYGeM9lAI');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3285, 224, 5, CONCAT('Summer Evening Spooky Story Contest'), '2010-02-24', 'https://www.youtube.com/embed/HkS_eRN_eio');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3286, 224, 6, CONCAT('Viva! Youth!'), '2010-02-24', 'https://www.youtube.com/embed/eeGkQj2XEoc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3287, 224, 7, CONCAT('Go for it! Manzai Grand Prix!'), '2010-03-25', 'https://www.youtube.com/embed/-CuSc9mOCJ4');
