INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (232, CONCAT('Blend S'), CONCAT('Wishing to be independent, 16-year-old Maika Sakuranomiya is desperate to nail down a part-time job so that she can afford to study abroad. Unfortunately, her applications are constantly rejected due to the menacing look she unintentionally makes whenever she smiles, despite her otherwise cheerful disposition.<br>
<br>After yet another failed interview, she chances upon Café Stile, a coffee shop where the servers interact with the customers while roleplaying distinctive characteristics. The Italian store manager, Dino, becomes infatuated with Maika', CHAR(39), 's cuteness at first sight, and offers her a job as a waitress with a sadistic nature. Coupled with her inherent clumsiness, she successfully manages to serve a pair of masochistic customers in accordance with her new, ruthless persona. Alongside Kaho Hinata as the tsundere and Mafuyu Hoshikawa as the younger sister, Maika decides to make the most out of her unique quirk and cements her position in the cafe with merciless cruelty!<br>
<br>[Written by MAL Rewrite]'), 1, '2017-10-08', '2017-12-24', 'Fall 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/88286.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (261, 232, 6);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (244, 232, 18);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (245, 232, 16);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (246, 232, 17);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3717, 232, 1, CONCAT('First-Time Super Sadist'), '2017-10-08', 'https://drive.google.com/file/d/15sjozAjILBYRqdnuwSLg0Qt2ZahLs7qq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3718, 232, 2, CONCAT('Sweets Without Honor'), '2017-10-15', 'https://drive.google.com/file/d/1x19iEaAnWgmg7rtk9CXsm6a02zFZiFFu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3719, 232, 3, CONCAT('After the Date, Rated R'), '2017-10-22', 'https://drive.google.com/file/d/1Egm-JxlXxuf569KGGPedpt4m-pWoR9MC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3720, 232, 4, CONCAT('The New Girl is a Big Sister'), '2017-10-29', 'https://drive.google.com/file/d/1p7aAppy8YZSUL_dvJxlz5DzgNOy8TD-t/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3721, 232, 5, CONCAT('Rainy and Then Windy'), '2017-11-05', 'https://drive.google.com/file/d/1k7cEaUoSsWxDrD9nNCHVg6KPoOa0_CI_/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3722, 232, 6, CONCAT('By the Waterfront Et Cetera (For Adults)'), '2017-11-12', 'https://drive.google.com/file/d/1Ygtw3fmV-friCM1zHTljS0oZGVG_ZfZL/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3723, 232, 7, CONCAT('Busy with Bananas and Strawberries'), '2017-11-19', 'https://drive.google.com/file/d/14WyrBsYsDy19etjc2Kub_oDY0xAEZQpc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3724, 232, 8, CONCAT('An Idol Character, Too'), '2017-11-26', 'https://drive.google.com/file/d/1hnWofG2RTLSFwJ3FKT9n8b0Q4m56Fb_7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3725, 232, 9, CONCAT('Owner Inauguration, Sister Attack'), '2017-12-03', 'https://drive.google.com/file/d/1FdAwAe9rzmA07V5HfHSQCQFptZgr0454/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3726, 232, 10, CONCAT('I', CHAR(39), 'll Teach You'), '2017-12-10', 'https://drive.google.com/file/d/110NzXFv4DYql38hE2k-b1fR532eDzr2A/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3727, 232, 11, CONCAT('Good at Tsundere, Bad at Cornering'), '2017-12-17', 'https://drive.google.com/file/d/10gV_N6bcPNL_MYbX9cuQ9tbNvceq_jAc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3728, 232, 12, CONCAT('I Love You!'), '2017-12-24', 'https://drive.google.com/file/d/1TPSZ8UitLKGQEw6ARlwWn14SZMUBFb0P/preview');
