INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (237, CONCAT('Blue Dragon'), CONCAT('As Shu', CHAR(39), 's village was being attacked by an unknown enemy, he and his friends, Jiro and Kluke decide to defend their home. They soon meet warrior Zola and receive the powers of Shadow, an ability that let', CHAR(39), 's them transform their shadow into a powerful monster. Shu receives one of the most powerful monsters, Blue Dragon, and they all set out to defeat their enemy.<br>
<br>(Source: ANN)'), 1, '2007-04-07', '2008-03-29', 'Spring 2007', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/20597.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (169, 237, '"FRIEND"', ' by Keita Tachibana', 'js-theme-songs', 'https://open.spotify.com/track/3Irnh6hDGJLfoVja5AFPdn');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (170, 237, '"Fly So High"', ' by Yu Yamada', 'js-theme-songs', 'https://open.spotify.com/track/52TAjQKWNIYPJJJPoD8uCR');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (115, 237, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (549, 237, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (550, 237, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (551, 237, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (552, 237, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (267, 237, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (256, 237, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (257, 237, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3813, 237, 1, CONCAT('The Shadow Comes Forth'), NULL, 'https://www.mp4upload.com/embed-2oi76n5upt0b.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3814, 237, 2, CONCAT('The Blue Power'), NULL, 'https://www.mp4upload.com/embed-26fqq0srk320.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3815, 237, 3, CONCAT('Shu and Jiro'), NULL, 'https://www.mp4upload.com/embed-gyabxkef6tjg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3816, 237, 4, CONCAT('Underwear Is The Trump Card'), NULL, 'https://www.mp4upload.com/embed-dq8vvxx1kluv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3817, 237, 5, CONCAT('General Logi'), NULL, 'https://www.mp4upload.com/embed-2b844rpup7sa.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3818, 237, 6, CONCAT('Fluffy Fluffy Squeezy!'), NULL, 'https://www.mp4upload.com/embed-wr81agwf89vl.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3819, 237, 7, CONCAT('The Noblewoman', CHAR(39), 's Trap'), NULL, 'https://www.mp4upload.com/embed-wzfeyh5hbpia.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3820, 237, 8, CONCAT('Knight Master'), NULL, 'https://fcdn.stream/v/80ve77gg79j');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3821, 237, 9, CONCAT('Operation Marriage Proposal'), NULL, 'https://www.mp4upload.com/embed-e1s0y6mzbz2z.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3822, 237, 10, CONCAT('Logi Strikes'), NULL, 'https://dood.so/e/ulnhkrjzi822');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3823, 237, 11, CONCAT('Escape Through The Enemy Front'), '2007-06-16', 'https://dood.so/e/4o5t1p186n4g');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3824, 237, 12, CONCAT('Dragnov', CHAR(39), 's Last Stand'), NULL, 'https://www.mp4upload.com/embed-m1q4twn5tqes.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3825, 237, 13, CONCAT('Infiltrate!'), NULL, 'https://www.mp4upload.com/embed-kxmfkbib93z5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3826, 237, 14, CONCAT('Kluke', CHAR(39), 's Feelings'), NULL, 'https://www.mp4upload.com/embed-s8953810h0q6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3827, 237, 15, CONCAT('A Path Towards Hope'), NULL, 'https://www.mp4upload.com/embed-w8kof4q6sx64.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3828, 237, 16, CONCAT('The Book Of The Beginning'), NULL, 'https://www.mp4upload.com/embed-rbanckuut6fv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3829, 237, 17, CONCAT('Homeron Has Died'), NULL, 'https://www.mp4upload.com/embed-qdkm0gydxzb4.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3830, 237, 18, CONCAT('Dear Shadow'), NULL, 'https://www.mp4upload.com/embed-8n129xwij4cv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3831, 237, 19, CONCAT('The Mystery of the Ruins'), NULL, 'https://www.mp4upload.com/embed-wfkqmey6ulpt.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3832, 237, 20, CONCAT('The Captive Knight'), NULL, 'https://www.mp4upload.com/embed-4544mkefmmkd.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3833, 237, 21, CONCAT('The Informant', CHAR(39), 's Pursuit'), NULL, 'https://fcdn.stream/v/p6og8nw2x9j');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3834, 237, 22, CONCAT('Vanish Vanish Don', CHAR(39), 't!'), NULL, 'https://www.mp4upload.com/embed-7spup9mbyea0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3835, 237, 23, CONCAT('Towards the Great Blue Sky'), NULL, 'https://fcdn.stream/v/pmv5qln88vl');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3836, 237, 24, CONCAT('Pursuit of the Devil'), NULL, 'https://www.mp4upload.com/embed-fn77o4xprkdq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3837, 237, 25, CONCAT('Versus the Independent Flying Squadron'), NULL, 'https://fcdn.stream/v/1lo6x7q-lo5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3838, 237, 26, CONCAT('Cynthia', CHAR(39), 's Madness'), NULL, 'https://dood.so/e/44rrqf7w0zur');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3839, 237, 27, CONCAT('Into Logi', CHAR(39), 's Ship'), NULL, 'https://dood.so/e/hydjb7b3lh4g');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3840, 237, 28, CONCAT('Sneaky Sneaky Shock!'), NULL, 'https://fcdn.stream/v/1lo653jllv5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3841, 237, 29, CONCAT('The Extra Seven'), NULL, 'https://www.mp4upload.com/embed-gxgumvbytb39.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3842, 237, 30, CONCAT('The Dark Dragon'), NULL, 'https://www.mp4upload.com/embed-w3gex1zwfqwq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3843, 237, 31, CONCAT('The Powerful One'), NULL, 'https://www.mp4upload.com/embed-knnbbrhxrn0a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3844, 237, 32, CONCAT('The Shadow Wielder', CHAR(39), 's Apprentice'), NULL, 'https://www.mp4upload.com/embed-37xmtsv5wz2c.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3845, 237, 33, CONCAT('Panty Heaven'), NULL, 'https://www.mp4upload.com/embed-j7rw977hytmo.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3846, 237, 34, CONCAT('Gilliam Returns'), NULL, 'https://www.mp4upload.com/embed-dex10brpp7su.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3847, 237, 35, CONCAT('The Shining Hippo'), NULL, 'https://www.mp4upload.com/embed-1qbtvtt58yfq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3848, 237, 36, CONCAT('Whisper Whisper Boom!'), NULL, 'https://www.mp4upload.com/embed-3dofyfoic7x2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3849, 237, 37, CONCAT('Aerial Fortress Showdown'), NULL, 'https://www.mp4upload.com/embed-4lco0cncowdn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3850, 237, 38, CONCAT('The Final Battle'), NULL, 'https://www.mp4upload.com/embed-5sr7dyg4d86m.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3851, 237, 39, CONCAT('The Triumphant Return'), NULL, 'https://fcdn.stream/v/7z9-dxgj2vx');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3852, 237, 40, CONCAT('Rosekstan'), NULL, 'https://www.mp4upload.com/embed-lw1kcvistkl3.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3853, 237, 41, CONCAT('Bird in a Cage'), NULL, 'https://www.mp4upload.com/embed-dmxrlqxhlbbe.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3854, 237, 42, CONCAT('Awakening'), NULL, 'https://www.mp4upload.com/embed-b3jnpswsz73j.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3855, 237, 43, CONCAT('The Seven Soldiers of Light'), NULL, 'https://www.mp4upload.com/embed-u3s7lfpyasc2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3856, 237, 44, CONCAT('The Truth'), NULL, 'https://www.mp4upload.com/embed-4sfkwizwhytf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3857, 237, 45, CONCAT('Quiver Quiver Boing!'), NULL, 'https://www.mp4upload.com/embed-wp9tz607nz8i.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3858, 237, 46, CONCAT('Dissension'), NULL, 'https://www.mp4upload.com/embed-xkt86sf0zccg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3859, 237, 47, CONCAT('Into the Darkness'), NULL, 'https://www.mp4upload.com/embed-96mmq8zgxioh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3860, 237, 48, CONCAT('The Two Pledges'), NULL, 'https://www.mp4upload.com/embed-e3s30dw358zq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3861, 237, 49, CONCAT('Zola'), NULL, 'https://www.mp4upload.com/embed-96kav1b2tybo.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3862, 237, 50, CONCAT('Bonds'), NULL, 'https://www.mp4upload.com/embed-u4bvbebgx4b8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3863, 237, 51, CONCAT('Shu'), NULL, 'https://www.mp4upload.com/embed-sdn3hgpg7ayf.html');
