INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (239, CONCAT('Blue Lock'), CONCAT('Yoichi Isagi was mere moments away from scoring a goal that would have sent his high school soccer team to the nationals, but a split-second decision to pass the ball to his teammate cost him that reality. Bitter, confused, and disappointed, Isagi wonders if the outcome would have been different had he not made the pass. When the young striker returns home, an invitation from the Japan Football Union awaits him. Through an arbitrary and biased decision-making process, Isagi is one of three hundred U-18 strikers selected for a controversial project named Blue Lock. <br>
<br>The project', CHAR(39), 's ultimate goal is to turn one of the selected players into the star striker for the Japanese national team. To find the best participant, each diamond in the rough must compete against others through a series of solo and team competitions to rise to the top. Putting aside his ethical objections to the project, Isagi feels compelled to fight his way to the top, even if it means ruthlessly crushing the dreams of 299 aspiring young strikers.<br>
<br>[Written by MAL Rewrite]'), 1, '2022-10-09', NULL, 'Fall 2022', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1258/126929.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (116, 239, 1);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (269, 239, 90);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3890, 239, 1, CONCAT('Dream'), '2022-10-09', 'https://drive.google.com/file/d/1locp2niF4b0SMNoq0z2guuUcnKz99W7P/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3891, 239, 2, CONCAT('Monster'), '2022-10-16', 'https://video.sibnet.ru/shell.php?videoid=4921018');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3892, 239, 3, CONCAT('Soccer', CHAR(39), 's "Zero"'), '2022-10-23', 'https://drive.google.com/file/d/1ejEWCPXSfh2HP2jg5FUZkdKTqBFsxFW2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3893, 239, 4, CONCAT('Premonition and Intuition'), '2022-10-30', 'https://video.sibnet.ru/shell.php?videoid=4936032');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (3894, 239, 5, CONCAT('The One to Be Born'), '2022-11-06', 'https://ebd.cda.pl/620x368/12399141d6');
