INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (249, CONCAT('Boku wa Tomodachi ga Sukunai'), CONCAT('When Kodaka Hasegawa finds out that he will be transferring to a new school, he is determined to make a positive impression, and maybe even some friends. However, Kodaka discovers he is out of luck when he immediately gets labeled as a violent delinquent due to his blond hair and intimidating expression. Although a month has passed, Kodaka is still alone thanks to his notorious reputation. However, his life begins to change when he finds fellow loner Yozora Mikazuki talking to her imaginary friend in an empty classroom.<br>
<br>After sharing stories of their lonely high school life, Kodaka and Yozora decide to overcome the difficulties of making friends together by starting the Neighbor', CHAR(39), 's Club. Created for people who don', CHAR(39), 't have friends, daily activities involve learning social skills and how to fit in, which will hopefully allow them to make friends. Joined by the eroge-loving Sena Kashiwazaki, and other eccentric outcasts, Kodaka may finally have managed to find people he can call friends, in this club filled with hilarious oddballs.<br>
<br>[Written by MAL Rewrite]'), 1, '2011-10-07', '2011-12-23', 'Fall 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/32873.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (178, 249, '"Zannenkei Rinjinbu (Hoshi Futatsu Han) (残念系隣人部★★☆(星ふたつ半))"', ' by Tomodachi Tsukuritai (友達つくり隊) (Marina Inoue, Kanae Itou, Nozomi Yamamoto, Misato Fukuen, Kana Hanazawa, and Yuka Iguchi)', 'js-theme-songs', '')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (568, 249, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (569, 249, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (570, 249, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (280, 249, 92);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (275, 249, 22);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (276, 249, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4045, 249, 1, CONCAT('We Can', CHAR(39), 't Make Any Friends'), '2011-10-07', 'https://ebd.cda.pl/620x395/672757465');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4046, 249, 2, CONCAT('There', CHAR(39), 's No God in the Electric World'), '2011-10-14', 'https://ebd.cda.pl/620x395/672757159');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4047, 249, 3, CONCAT('There Are No Flags at the Swimming Pool'), '2011-10-21', 'https://ebd.cda.pl/620x395/6727286e8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4048, 249, 4, CONCAT('Underclassmen Don', CHAR(39), 't Hold Back'), '2011-10-28', 'https://ebd.cda.pl/620x395/6727280cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4049, 249, 5, CONCAT('This Time, the SAGA is a Serious Battle'), '2011-11-04', 'https://ebd.cda.pl/620x395/6727274a4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4050, 249, 6, CONCAT('There Aren', CHAR(39), 't Many Customers At the Karaoke Box'), '2011-11-11', 'https://ebd.cda.pl/620x395/672727716');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4051, 249, 7, CONCAT('My Cell Phone Doesn', CHAR(39), 't Get Many Calls'), '2011-11-18', 'https://ebd.cda.pl/620x395/672727151');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4052, 249, 8, CONCAT('School Swimsuits Don', CHAR(39), 't Appear'), '2011-11-25', 'https://ebd.cda.pl/620x395/67291282b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4053, 249, 9, CONCAT('The President', CHAR(39), 's Recollections are Painful'), '2011-12-02', 'https://ebd.cda.pl/620x395/67289307a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4054, 249, 10, CONCAT('No One Sleeps at Camp'), '2011-12-09', 'https://ebd.cda.pl/620x395/6728753a9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4055, 249, 11, CONCAT('Girls Are Super-Cute in Yukatas'), '2011-12-16', 'https://ebd.cda.pl/620x395/672875083');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4056, 249, 12, CONCAT('We Don', CHAR(39), 't Have Many Friends'), '2011-12-23', 'https://ebd.cda.pl/620x395/67287417e');
