INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (265, CONCAT('Bucchigire!'), CONCAT('Following a ruthless attack from an imperialist criminal gang known as the Masked Demons, Shinsengumi', CHAR(39), 's Eighth Division—the law-enforcing squad in Kyoto that remains faithful to the shogunate—is nearly annihilated, with its sole survivor, Heisuke Toudou, critically injured. Urged to rebuild the Shinsengumi by the local feudal lord, Katamori Matsudaira, Toudou decides to offer eight convicts the chance to redeem themselves: they must abandon their old names and become substitutes for the eight Shinsengumi captains. All accept but one, who ends up immediately executed by the former assassin Sakuya.<br>
<br>However, Toudou has a hard time transforming the seven reformed criminals into loyal servants. Due to his lack of discipline, the impulsive and vengeful Ichibanboshi, whose family perished at the hands of the Masked Demons, threatens the success of Toudou', CHAR(39), 's strategy. As Toudou pledges to protect the shogunate against imperialists and foreign invaders, other factions, such as Kogorou Katsura', CHAR(39), 's group, start to put their plans in motion with only one goal in mind—to seize power at the dusk of the Edo period.<br>
<br>[Written by MAL Rewrite]'), 2, '2022-07-08', '2022-09-23', 'Summer 2022', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1284/125491.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (130, 265, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (611, 265, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (612, 265, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (613, 265, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (614, 265, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (615, 265, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (300, 265, 1);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4229, 265, 1, CONCAT('Tabakare! Shinsengumi'), '2022-07-08', 'https://ebd.cda.pl/620x368/1139447949');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4230, 265, 2, CONCAT('Shine On! Keepsake Katana'), NULL, 'https://drive.google.com/file/d/1qaXO6NxdqZILFIQfBv1RLUtDldKkiaXs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4231, 265, 3, CONCAT('Disguise Yourself! Infiltrating the Red Light District'), NULL, 'https://drive.google.com/file/d/1yDoFZdUTF9zYnGTaz3lZsc_CUU_Cyccq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4232, 265, 4, CONCAT('Search! For the Mysterious Magical Swords'), NULL, 'https://ebd.cda.pl/620x368/1158971075');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4233, 265, 5, CONCAT('Show Them! The Pride of a Monk and a Doctor'), NULL, 'https://drive.google.com/file/d/1lOcu8vIe9-Derlod3OkcLRhokrUkwiQc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4234, 265, 6, CONCAT('Raid! The Crooked Shirakawaya'), NULL, 'https://drive.google.com/file/d/1Cfcqylu0A2wSGUUI6v9PbhcVFyc0Cxkg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4235, 265, 7, CONCAT('Prevent! The Dissolution of the Shinsengumi'), NULL, 'https://drive.google.com/file/d/1sSQwoz9t00_i5PhfXhpUBBcg_KPLmPtq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4236, 265, 8, CONCAT('Blitz! The Ikedaya Incident'), NULL, 'https://drive.google.com/file/d/1H4AP7Koow8qO2zsj3FDzDlqDF7MisyiV/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4237, 265, 9, CONCAT('Ponder! A Person', CHAR(39), 's Thoughts and a Demon', CHAR(39), 's Thoughts'), NULL, 'https://drive.google.com/file/d/1PnUreTewinPVLCuhSmSr9v1te2ZzyWcA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4238, 265, 10, CONCAT('Defend! The Black American Ships'), NULL, 'https://dood.pm/e/lwfp9fw63fwb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4239, 265, 11, CONCAT('Rush! To the Kyoto Showdown'), NULL, 'https://dood.pm/e/3spo7hr1gu6s');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4240, 265, 12, CONCAT('Shine On! The Shinsengumi of Criminals'), NULL, 'https://dood.pm/e/ez3168i063a2');
