INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (279, CONCAT('Byousoku 5 Centimeter'), CONCAT('What happens when two people love each other but just aren', CHAR(39), 't meant to be together? Takaki Toono and Akari Shinohara are childhood friends, but circumstances beyond their control tear them apart. They promise to stay in contact, and although the progression of time widens the distance between them, the chain of memories remains ever-present.<br><br>Byousoku 5 Centimeter is a romantic drama that focuses on the mundane and harsh reality of long-distance relationships. Stuck in the past and unable to make any new memories, Takaki and Akari cling to the hope of seeing each other again. They live their everyday lives half-heartedly, both hurting themselves and the people around them.<br>
<br>[Written by MAL Rewrite]'), 2, '2007-03-03', NULL, '', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1410/112994.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (199, 279, '"One more time, one more chance"', ' by Masayoshi Yamazaki', 'js-theme-songs', 'https://open.spotify.com/track/5YRDGgdOshUPA17m7yzY7p');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (649, 279, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (650, 279, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (651, 279, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (316, 279, 97);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4383, 279, 1, CONCAT('Cherry Blossom'), '2007-02-16', 'https://ebd.cda.pl/620x368/29755629b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4384, 279, 2, CONCAT('Cosmonaut'), '2007-03-03', 'https://ebd.cda.pl/800x450/29755629b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4385, 279, 3, CONCAT('5 Centimeters Per Second'), '2007-03-03', 'https://www.youtube.com/embed/LRJwFOLamUk');
