INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (298, CONCAT('Cardfight!! Vanguard G: Z'), CONCAT('Fourth season of Cardfight!! Vanguard G series.'), 1, '2017-10-08', '2018-04-01', 'Fall 2017', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1335/125017.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (211, 298, '"Jou no Hana (情ノ華)"', ' by Kiryuu', 'js-theme-songs', 'https://open.spotify.com/track/7DyjkJ6QeqoLEaPTM25NUv')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (335, 298, 23);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5104, 298, 1, CONCAT('Chrono Taken'), NULL, 'https://streamtape.com/e/YBOVzD79dyF3Jx/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5105, 298, 2, CONCAT('Challenge from the Apostles'), NULL, 'https://streamtape.com/e/kzrBZbmoZ4SO7ld/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5106, 298, 3, CONCAT('Blue Wave Marshal Valeos'), NULL, 'https://streamtape.com/e/vxd6Mog904F4ZL2/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5107, 298, 4, CONCAT('Zeroth Dragon'), NULL, 'https://streamtape.com/e/8VZJZaZrrOUlz2/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5108, 298, 5, CONCAT('Dragon Burning with Vengeance'), NULL, 'https://streamtape.com/e/Rm1oXYgMqGCk0P/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5109, 298, 6, CONCAT('Purging Overlord'), NULL, 'https://streamtape.com/e/laeY1Kgek3TOgo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5110, 298, 7, CONCAT('Relics Crisis'), NULL, 'https://streamtape.com/e/8OOB6w2RdlcoAV7/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5111, 298, 8, CONCAT('The Future We Secured'), NULL, 'https://streamtape.com/e/erPZY6o2wlcYR9q/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5112, 298, 9, CONCAT('Evil Governor Gredora'), NULL, 'https://streamtape.com/e/MXw2ZPWW2qCmJpm/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5113, 298, 10, CONCAT('The Man', CHAR(39), 's Finishing Hold'), NULL, 'https://streamtape.com/e/WoMe4wqXD4tblgQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5114, 298, 11, CONCAT('Evil God Bishop Gastille'), NULL, 'https://streamtape.com/e/WGAy0gY8JdSbvAW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5115, 298, 12, CONCAT('The Curse Known as Fate'), NULL, 'https://streamtape.com/e/6wVa14jabpTebg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5116, 298, 13, CONCAT('The Vessel of Gyze'), NULL, 'https://streamtape.com/e/8W8ej44ZjysoK6X/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5117, 298, 14, CONCAT('The Beginning of the End'), NULL, 'https://streamtape.com/e/ZKJvBlq4p0ty6O/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5118, 298, 15, CONCAT('Sworn Fight'), NULL, 'https://streamtape.com/e/wamLLz4jqyilkx/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5119, 298, 16, CONCAT('The Hope in Our Hands'), NULL, 'https://streamtape.com/e/d3RZWVOrWrUkY14/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5120, 298, 17, CONCAT('Land of Descent'), NULL, 'https://streamtape.com/e/7Y9LdomzDbtA32L/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5121, 298, 18, CONCAT('Dawn of the Decisive Battle'), NULL, 'https://streamtape.com/e/0WBX6zXagBFb8lR/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5122, 298, 19, CONCAT('Choice of the Jester'), NULL, 'https://streamtape.com/e/OAy3mDmMaXTZpWW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5123, 298, 20, CONCAT('Dragon Deity of Destruction, Gyze'), NULL, 'https://streamtape.com/e/vzXvalgOgwc4ZjK/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5124, 298, 21, CONCAT('The Void and Vanguard'), NULL, 'https://streamtape.com/e/plQVVPZWLdurmBq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5125, 298, 22, CONCAT('TRY3'), NULL, 'https://streamtape.com/e/m6KvzoqJ22UbKxW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5126, 298, 23, CONCAT('Dimensional Overstride'), NULL, 'https://streamtape.com/e/8K83oqr70buoVdp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5127, 298, 24, CONCAT('EXTRA TURN'), NULL, 'https://streamtape.com/e/bZA6M3y7jpiPVjb/');
