INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (293, CONCAT('Cardfight!! Vanguard (2018)'), CONCAT('The main protagonist Sendou Aichi, is a timid and mundane third-year middle school boy. The thing that supported Aichi', CHAR(39), 's heart, was the "Blaster Blade" card that he received as a child. It', CHAR(39), 's an important rare card from "Vanguard", a card game with the imaginary world of "Planet Cray" as its stage. From the day he reunited with the person who gave him that card "Toshiki Kai", Aichi', CHAR(39), 's everyday life began to change.<br>
<br>(Source: Crunchyroll)'), 1, '2018-05-05', '2019-05-04', 'Spring 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1408/96485.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (330, 293, 3);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4889, 293, 1, CONCAT('Stand Up, Vanguard!!'), '2018-05-05', 'https://streamtape.com/e/2bGdAbRO2dtZL00/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4890, 293, 2, CONCAT('Ride the Vanguard!!'), '2018-05-12', 'https://streamtape.com/e/xgRoWQZ8rpFwpy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4891, 293, 3, CONCAT('Who is the Strongest Fighter!!'), '2018-05-19', 'https://streamtape.com/e/wd1GJpL90LFJrJ6/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4892, 293, 4, CONCAT('Misaki', CHAR(39), 's Secret!!'), '2018-05-26', 'https://streamtape.com/e/RLg39p4l4qUd12y/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4893, 293, 5, CONCAT('Let', CHAR(39), 's Go To Card Capital!!'), NULL, 'https://streamtape.com/e/agyjg0v7kDfxgx0/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4894, 293, 6, CONCAT('Declaration of War!! Battle of the Shops'), NULL, 'https://streamtape.com/e/LYMekAgjXRfRRZy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4895, 293, 7, CONCAT('Unite!! Q4 (Quadrifoglio)'), NULL, 'https://streamtape.com/e/PwkwW0m1XXT0Vdr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4896, 293, 8, CONCAT('Turbulence!! Q4 VS NwO'), NULL, 'https://streamtape.com/e/BPjGZdOYA8hyL1m/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4897, 293, 9, CONCAT('Kai Loses!!'), NULL, 'https://streamtape.com/e/dpDgqkPyP6TkrBe/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4898, 293, 10, CONCAT('Wind of Aichi!!'), NULL, 'https://streamtape.com/e/LkbgkpPAzpsRRXW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4899, 293, 11, CONCAT('Battle of Men!!'), NULL, 'https://streamtape.com/e/Z3jD7KvrwltqWVw/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4900, 293, 12, CONCAT('Mysterious Adversary Asteroid!!'), NULL, 'https://streamtape.com/e/vYOPqGmqrwI41A1/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4901, 293, 13, CONCAT('Kamui!! Revenge of Determination'), NULL, 'https://streamtape.com/e/B48XVvKg7YUQWA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4902, 293, 14, CONCAT('Awaken!! PSYqualia'), NULL, 'https://streamtape.com/e/L2Be4MdwgYCRlx9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4903, 293, 15, CONCAT('FRIEND'), NULL, 'https://streamtape.com/e/Lqrk2mGVMQtaMm/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4904, 293, 16, CONCAT('Their Respective Feelings'), NULL, 'https://streamtape.com/e/w4p1aYD4B9hJd9G/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4905, 293, 17, CONCAT('A Jet Black Knight!! Blaster Dark'), NULL, 'https://streamtape.com/e/m6e9qYwrljUbg3Y/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4906, 293, 18, CONCAT('Kai and Ren, and Aichi Too'), NULL, 'https://streamtape.com/e/Wr23DmKQJacbV4M/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4907, 293, 19, CONCAT('Tetsu', CHAR(39), 's Motive'), NULL, 'https://streamtape.com/e/Rjzql7j4GMUdR0z/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4908, 293, 20, CONCAT('Reunion'), NULL, 'https://streamtape.com/e/lG1VDgAePgi7KOg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4909, 293, 21, CONCAT('Abyss of Darkness'), NULL, 'https://streamtape.com/e/A2mGMJkp9esXPa9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4910, 293, 22, CONCAT('A Serious Fight'), NULL, 'https://streamtape.com/e/prrx43q1GzCrrrD/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4911, 293, 23, CONCAT('A Little Beacon'), NULL, 'https://streamtape.com/e/vzOjZk8xzpSL9Y/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4912, 293, 24, CONCAT('Kai'), NULL, 'https://streamtape.com/e/gPyPrQWX3vH3Gj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4913, 293, 25, CONCAT('Vanguard'), NULL, 'https://streamtape.com/e/4W7Rz1o70XUKA9x/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4914, 293, 26, CONCAT('Vanguard Abnormality!? Unit Encyclopedia'), NULL, 'https://streamtape.com/e/4vG76rbZMDtraA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4915, 293, 27, CONCAT('Stand Up! High School Life!!'), NULL, 'https://streamtape.com/e/GedkkAezmRC1XLq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4916, 293, 28, CONCAT('Cardfight Club Initiated!'), NULL, 'https://streamtape.com/e/7k3b2LbVvYcVx2/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4917, 293, 29, CONCAT('New Allies'), NULL, 'https://streamtape.com/e/JWBDX8X6vdIjq9g/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4918, 293, 30, CONCAT('My Idol'), NULL, 'https://streamtape.com/e/X2d3VeReAltgvo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4919, 293, 31, CONCAT('The Backstage Boss'), NULL, 'https://streamtape.com/e/841qeoap92sowGg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4920, 293, 32, CONCAT('First Exchange Match'), NULL, 'https://streamtape.com/e/8W3vbdMkkOC808/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4921, 293, 33, CONCAT('Vanguard Koshien'), NULL, 'https://streamtape.com/e/r2dxB9wdYvt820/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4922, 293, 34, CONCAT('Another Vanguard'), NULL, 'https://streamtape.com/e/oed0gMMM41CW7y/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4923, 293, 35, CONCAT('Concert Master, Takuto'), NULL, 'https://streamtape.com/e/0866pOOAg9hKvQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4924, 293, 36, CONCAT('Destiny Conductor'), NULL, 'https://streamtape.com/e/7w6waZOKQaTBwO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4925, 293, 37, CONCAT('Invasion of the PSYqualia Zombie'), NULL, 'https://streamtape.com/e/xoy60w4Bw8clrB/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4926, 293, 38, CONCAT('Beyond Imagination!'), NULL, 'https://streamtape.com/e/APQ2JqwGReIXKq9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4927, 293, 39, CONCAT('True Strength'), NULL, 'https://streamtape.com/e/aZo4WBB9kZFx64M/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4928, 293, 40, CONCAT('True and Fake'), NULL, 'https://streamtape.com/e/orGlAw7GgLTJw9Y/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4929, 293, 41, CONCAT('Phantom Final Turn'), NULL, 'https://streamtape.com/e/0dbeWoLWDDib3me/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4930, 293, 42, CONCAT('Distorted Bonds'), NULL, 'https://streamtape.com/e/qWq66Arvk1FzrxO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4931, 293, 43, CONCAT('Called Walkers - Those Ruled by Fate'), NULL, 'https://streamtape.com/e/41G96Xxr2mCKD72/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4932, 293, 44, CONCAT('Entangled Fate'), NULL, 'https://streamtape.com/e/Qd0pmmlLpRf0aDD/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4933, 293, 45, CONCAT('Rivalry'), NULL, 'https://streamtape.com/e/YGWBzwA9lycrdw/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4934, 293, 46, CONCAT('The Vilest Enemy Aichi'), NULL, 'https://streamtape.com/e/D06DRkMJeJs31b/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4935, 293, 47, CONCAT('The Truth of Destiny Conductor'), NULL, 'https://streamtape.com/e/QrBAQBZeqzU06l0/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4936, 293, 48, CONCAT('Kai', CHAR(39), 's Memory'), NULL, 'https://streamtape.com/e/LQvljXV0edc4wG/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4937, 293, 49, CONCAT('Bonds'), NULL, 'https://streamtape.com/e/QbWwQxwBz2t0P78/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4938, 293, 50, CONCAT('The Day When Vanguard Disappears'), NULL, 'https://streamtape.com/e/6KWaOw3VdQh913G/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4939, 293, 51, CONCAT('Messiah'), NULL, 'https://streamtape.com/e/xbPkZzRqJqfv9l/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (4940, 293, 52, CONCAT('Vanguard Abnormality!? Unit Encyclopedia Grade 2!!'), NULL, 'https://streamtape.com/e/Mr0P0KbOyMcmXMR/');
