INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (318, CONCAT('Chitose Get You!!'), CONCAT('Chitose is an 11-year-old girl who is madly in love with an older guy named Hiroshi. He works at the town hall right next to the school and Chitose spends every day relentlessly pursuing him. Can Chitose ever convince Hiroshi to go out with her? '), 1, '2012-07-02', '2012-12-24', 'Summer 2012', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/50537.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (226, 318, '"Chitose Get You!! no Uta (ちとせげっちゅ!!の歌)"', ' by Sayaka Nakaya, Sora Tokui & MAKO', 'js-theme-songs', '');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (154, 318, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (730, 318, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (731, 318, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (732, 318, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (356, 318, 50);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5516, 318, 1, CONCAT('The Encounter Between Me and Onii-chan!!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=633440');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5517, 318, 2, CONCAT('The Marriage Meeting'), NULL, 'https://video.sibnet.ru/shell.php?videoid=636643');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5518, 318, 3, CONCAT('An Adult', CHAR(39), 's Charm?'), NULL, 'https://video.sibnet.ru/shell.php?videoid=642949');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5519, 318, 4, CONCAT('Daddy', CHAR(39), 's Child'), NULL, 'https://video.sibnet.ru/shell.php?videoid=648502');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5520, 318, 5, CONCAT('Hinako in Cosplay'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWa0UxdGtZdmExTG8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5521, 318, 6, CONCAT('Sketch'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWQ3BIMjRoOG1uYVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5522, 318, 7, CONCAT('Fire Drill'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWcFVpd1UzcjlYVHM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5523, 318, 8, CONCAT('All Together!'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWeUo4Z2RFZGRvM0U/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5524, 318, 9, CONCAT('The Usual Days'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWbzdPd2ZZWG9fY0E/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5525, 318, 10, CONCAT('Tanabata'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWRUhFV3Z5cXVqNk0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5526, 318, 11, CONCAT('The Teacher', CHAR(39), 's Achilles', CHAR(39), ' Heel?'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWb090M1B3d0JfQkU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5527, 318, 12, CONCAT('The Pool Opens'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWbTdPWlBwRDUwZjA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5528, 318, 13, CONCAT('Summer Festival'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWa1JTc1BFdmVYV00/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5529, 318, 14, CONCAT('Reading books in autumn?'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWaFVjeEhqdUswcU0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5530, 318, 15, CONCAT('Sports Festival'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWcURQUUw3aEg3SVE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5531, 318, 16, CONCAT('Mika Appears'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWU3g2YjBzTHFBck0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5532, 318, 17, CONCAT('The Meal'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWUmwtOE5jaDg0RGc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5533, 318, 18, CONCAT('Diet?'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWcWlOcEJTNktsa3M/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5534, 318, 19, CONCAT('Like a Girl'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWdVBsUmNHT0hxZ0U/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5535, 318, 20, CONCAT('Christmas'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWSkFGd3YwWWNXSFk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5536, 318, 21, CONCAT('Memories of Spring Cleaning'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWeGQ4NXY4X2J0bEE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5537, 318, 22, CONCAT('New Year', CHAR(39), 's Eve'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWaFJRUU1fWHJBdEE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5538, 318, 23, CONCAT('Visiting the Temple for the New Year'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWaVZteWpJbHpEUXc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5539, 318, 24, CONCAT('A Day in the Life of Kashiwabara'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWUjdKSk9KMlpTTFE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5540, 318, 25, CONCAT('Let', CHAR(39), 's Make It By Hand'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWMktrMWU3MUxxRnc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5541, 318, 26, CONCAT('Onii-chan, I Love You!'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWRUx6TTNJRUhXZ1k/preview');
