INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (358, CONCAT('Corpse Party: Tortured Souls - Bougyakusareta Tamashii no Jukyou'), CONCAT('Nine students gather in their high school at night to bid farewell to a friend. As is customary among many high school students, they perform a sort of ritual for them to remain friends forever, using small paper charms shaped like dolls.<br>
<br>However, the students do not realize that these charms are connected to Heavenly Host Academy—an elementary school that was destroyed years ago after a series of gruesome murders took place, a school that rests under the foundation of their very own Kisaragi Academy. Now, trapped in an alternate dimension with vengeful ghosts of the past, the students must work together to escape—or join the spirits of the damned forever.<br>
<br>A feast for mystery fanatics, gore-hounds, and horror fans alike, Corpse Party: Tortured Souls - Bougyakusareta Tamashii no Jukyou shows a sobering look at redemption, sacrifice, and how the past is always right behind, sometimes a little too close for comfort.<br>
<br>[Written by MAL Rewrite]'), 3, '2013-07-24', NULL, '', '29 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/78811.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (255, 358, '"Hoshikuzu no Ring (星屑のリング)"', ' by Asami Imai', 'js-theme-songs', 'https://open.spotify.com/track/56ExXQxdmHlR8rRqXHhwoa')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (835, 358, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (836, 358, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (837, 358, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (401, 358, 34);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6061, 358, 1, CONCAT('Multiple Separation'), '2013-07-24', 'https://ebd.cda.pl/620x395/8019302ed');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6062, 358, 2, CONCAT('Broken Hinges'), '2013-07-24', 'https://ebd.cda.pl/620x395/801931713');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6063, 358, 3, CONCAT('Unconveyed Feelings'), '2013-07-24', 'https://ebd.cda.pl/620x395/801931164');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6064, 358, 4, CONCAT('Sorrowful Truth'), '2013-07-24', 'https://ebd.cda.pl/620x395/801932037');
