INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (367, CONCAT('D.Gray-man Hallow'), CONCAT('Despite the recent Akuma attack, the members of the Black Order are in high spirits as they set about moving to a new base. Immediately upon his arrival, however, Allen Walker is suddenly called by the Central Agency and has his arm forcefully sealed by the Order. He is then led to a surprising meeting with his master, General Cross Marian, who reveals staggering secrets surrounding the enigmatic 14th Noah.<br>
<br>A phantom thief incident, the arrival of a mysterious group of Exorcists, the death of an important comrade, and an all-out battle against the Noah Family—just what does this mean for Allen, Yuu Kanda, and the rest of the Order? This is but the beginning of a series of strange, seemingly unconnected events that lead to something far greater.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-07-05', '2016-09-27', 'Summer 2016', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/80766.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (264, 367, '"Key -bring it on, my Destiny-"', ' by Lenny code fiction', 'js-theme-songs', 'https://open.spotify.com/track/0KujgwewlY2MoPfXyPeXOY')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (168, 367, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (851, 367, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (852, 367, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (410, 367, 23);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (381, 367, 11);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (382, 367, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6307, 367, 1, CONCAT('The Fourteenth'), '2016-07-05', 'https://drive.google.com/file/d/1MByjol731g66_11B0Wcr-TyyPhPo6eYN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6308, 367, 2, CONCAT('Lonely Boy'), '2016-07-12', 'https://drive.google.com/file/d/154fcond00sP0QUnY1XcqVQgGFUQ4rzY_/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6309, 367, 3, CONCAT('It’ll Be Fine If I Wash My Face'), '2016-07-19', 'https://drive.google.com/file/d/1-bI7Zj3UBSZQtIrym9v64o8blz2LIAs-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6310, 367, 4, CONCAT('Blood Crusade'), '2016-07-26', 'https://drive.google.com/file/d/1Djqw8z8BrEJf1AlrL1Og0iPrxDLu3zYy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6311, 367, 5, CONCAT('Alma Karma'), '2016-08-02', 'https://drive.google.com/file/d/1yOhVjmUrhOQQq04KsgItNodF9R5PmWcY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6312, 367, 6, CONCAT('Friend'), '2016-08-09', 'https://drive.google.com/file/d/1TP0PWMgXIVHZ3jORVgMBGx2s24WU5-fu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6313, 367, 7, CONCAT('The Truth about a Sterile Flower'), '2016-08-16', 'https://drive.google.com/file/d/1gNpMaIzsk4un0bzix8tSSDTqlV9R97SZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6314, 367, 8, CONCAT('Awakening'), '2016-08-23', 'https://drive.google.com/file/d/1QCj8y1NltDAO0D7FdF9j7FYYM_38TU54/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6315, 367, 9, CONCAT('Little Good-Bye'), '2016-08-30', 'https://drive.google.com/file/d/1gNxAxCPLgj_Zs7xXZFy5OwbuEhHbH4tC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6316, 367, 10, CONCAT('Sinner in Despair'), '2016-09-06', 'https://drive.google.com/file/d/1--KXB8mGa8113HsEUcbI5u2AmodPM0Hf/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6317, 367, 11, CONCAT('Hidden One'), '2016-09-13', 'https://drive.google.com/file/d/136s3G4gFLmdE880bFwk-bIfJzoifz9wT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6318, 367, 12, CONCAT('My Home'), '2016-09-20', 'https://drive.google.com/file/d/12YODAC1cf7OCRgkK4K-lfqHLdabcG0hK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6319, 367, 13, CONCAT('Walker'), '2016-09-27', 'https://drive.google.com/file/d/15Fk4YZcSPgbZCBueAcfPIezQ8U239bR3/preview');
