INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (381, CONCAT('Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen'), CONCAT('Hope', CHAR(39), 's Peak Academy', CHAR(39), 's unconventional class 77-B is about to have an even more eccentric addition: Chisa Yukizome, an alumna with the title of Super High School-Level Housekeeper—and their new homeroom teacher. Cheerful, passionate, and capable, Chisa immediately sets about correcting the students', CHAR(39), ' problematic behavior and strengthening their relationships. It may not be easy dealing with diverse pupils ranging from princesses and nurses to yakuza and impossibly lucky students, but anything is possible with the power of hope.<br>
<br>Meanwhile, Hajime Hinata, an unremarkable boy from the school', CHAR(39), 's Reserve Course, longs for a talent. One day, he has an unexpected meeting with class 77-B', CHAR(39), 's Super High School-Level Gamer Chiaki Nanami, who presents to him a new, hope-filled outlook on life. However, unbeknownst to him, the school', CHAR(39), 's upper echelon is about to execute a sinister project centered around Hajime that will bring Hope', CHAR(39), 's Peak—and the rest of the world—to its knees.<br><br>Zetsubou-hen chronicles the daily lives carried out at the talent-cultivating academy, and the darkness that lurks beneath. As despair slowly infects hope, plans are put into motion to start the Biggest, Most Awful, Most Tragic Event in Human History, and the end begins.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-07-14', '2016-09-22', 'Summer 2016', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/80932.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (273, 381, '"Kami-iro Awase (カミイロアワセ)"', ' by Binaria', 'js-theme-songs', 'https://open.spotify.com/track/77spgc3VsjeFMi8ged5cOO')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (890, 381, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (891, 381, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (892, 381, 4);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (425, 381, 49);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (399, 381, 37);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (400, 381, 4);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (401, 381, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (402, 381, 14);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6613, 381, 1, CONCAT('Hello Again, Hope', CHAR(39), 's Peak High School'), '2016-07-14', 'https://video.sibnet.ru/shell.php?videoid=2643661');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6614, 381, 2, CONCAT('My Impurest Heart for You'), '2016-07-21', 'https://streamtape.com/e/7kqR931P7rCAgAj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6615, 381, 3, CONCAT('A Farewell to All Futures'), '2016-07-28', 'https://ebd.cda.pl/800x450/9576624e4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6616, 381, 4, CONCAT('The Melancholy, Surprise, and Disappearance of Nagito Komaeda'), '2016-08-04', 'https://ebd.cda.pl/800x450/957666044');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6617, 381, 5, CONCAT('Beginning of the End'), '2016-08-11', 'https://ebd.cda.pl/800x450/9576642a9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6618, 381, 6, CONCAT('A Despairfully Fateful Encounter'), '2016-08-18', 'https://ebd.cda.pl/800x450/957663039');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6619, 381, 7, CONCAT('The Biggest, Most Atrocious Incident in Hope', CHAR(39), 's Peak High School', CHAR(39), 's History'), '2016-08-25', 'https://ebd.cda.pl/800x450/95766576a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6620, 381, 8, CONCAT('The Worst Reunion by Chance'), '2016-09-01', 'https://ebd.cda.pl/800x450/782915339');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6621, 381, 9, CONCAT('Chisa Yukizome Doesn’t Smile'), '2016-09-08', 'https://streamtape.com/e/A20jQ8YKZ6CXObx/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6622, 381, 10, CONCAT('Smile at Despair in the Name of Hope'), '2016-09-15', 'https://ebd.cda.pl/800x450/95766480f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6623, 381, 11, CONCAT('Goodbye, Hope’s Peak High School'), '2016-09-22', 'https://ebd.cda.pl/800x450/957665408');
