INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (384, CONCAT('Dansai Bunri no Crime Edge'), CONCAT('Kiri Haimura has an obsession with beautiful hair—specifically, cutting it. This bizarre trait is what leads him to seek out a rumored long-haired ghost who lives in an abandoned house on a hill. However, he finds not a ghost, but a beautiful girl with long flowing hair named Iwai Mushanokouji, the "Hair Queen," whose hair cannot be cut due to a family curse.<br>
<br>Iwai explains that there is a death game surrounding her, and that if she is killed by a cursed object, aptly named a "Killing Good," the wielder gets their wish granted. After protecting Iwai from "Authors"—Killing Goods users—he learns there is in fact a Killing Good passed down in his own family: a pair of scissors used by his ancestor to commit murders. Naming the scissors "The Severing Crime Edge," he finds that he is able to cut Iwai', CHAR(39), 's cursed hair with them, setting her free to live a normal life. However, many Authors seek to kill the Hair Queen, and Kiri will have to protect her in this lethal game of fate.<br>
<br>[Written by MAL Rewrite]'), 1, '2013-04-04', '2013-06-27', 'Spring 2013', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/52137.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (174, 384, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (897, 384, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (898, 384, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (899, 384, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (428, 384, 16);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6650, 384, 1, CONCAT('The Sleeping Princess'), '2013-04-04', 'https://ebd.cda.pl/620x395/802101809');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6651, 384, 2, CONCAT('The Portrait of Heresy'), NULL, 'https://drive.google.com/file/d/0B7RcIuOih6LCYlpXYWo1ZENLYTQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6652, 384, 3, CONCAT(' Cross the Thunder Clouds'), NULL, 'https://drive.google.com/file/d/0B7RcIuOih6LCYkpWNXN4VEVvNlk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6653, 384, 4, CONCAT('Where Is the Visitor?'), NULL, 'https://drive.google.com/file/d/0B7RcIuOih6LCWVVpVS1kNjYzaTA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6654, 384, 5, CONCAT('Before the Game'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1130385');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6655, 384, 6, CONCAT('Waltz of Stars'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1141219');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6656, 384, 7, CONCAT('The Silver Coins of Balance'), NULL, 'https://ebd.cda.pl/620x395/802104817');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6657, 384, 8, CONCAT('Party Chopper'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1155876');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6658, 384, 9, CONCAT('Lyrical Night Flight'), NULL, 'https://drive.google.com/file/d/0B7RcIuOih6LCSEc5anpjWERpVWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6659, 384, 10, CONCAT('Standing Babe-ation'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1169717');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6660, 384, 11, CONCAT('Red Rising'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1178979');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6661, 384, 12, CONCAT('Forbidden Game'), NULL, 'https://drive.google.com/file/d/0B7RcIuOih6LCVkZDWVBGeTE5WXM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6662, 384, 13, CONCAT('Grayland is in the House'), NULL, 'https://ebd.cda.pl/620x395/8021039ad');
