INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (405, CONCAT('Deltora Quest'), CONCAT('Long ago, the blacksmith Adin forged a belt of seven powerful gems, one from each of the seven tribes of Deltora. Wielding the belt', CHAR(39), 's unparalleled power, he repelled the Shadow Lord', CHAR(39), 's attempt to overthrow the kingdom. Adin was crowned king of Deltora, but he never forgot that the enemy remained unbeaten. <br>
<br>Centuries later, memory of the Shadow Lord has become faded and almost forgotten, and the people of Deltora see their monarchy as detached and uncaring. Much to their dismay, the Shadow Lord strikes once more, breaking the Belt of Deltora by scattering the seven gems across the continent. Jarred, a close friend of the young king Endon, assists him and his wife in escaping from the castle as the Shadow Lord takes over, and they part ways to go into hiding.<br>
<br>The Shadow Lord now reigns over Deltora and many years pass under his tyrannical rule. However, there is a glimmer of hope in Jarred', CHAR(39), 's son Lief, whom he has lovingly raised and trained to find the scattered gemstones and reassemble the Belt of Deltora. Along with his companions Barda and Jasmine, Lief must face devious enemies and dangerous beasts to oust the Shadow Lord and return peace to Deltora.<br>
<br>[Written by MAL Rewrite]'), 1, '2007-01-06', '2008-03-29', 'Winter 2007', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/88164.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (294, 405, '"HEART☆BEAT"', ' by MARIA ', 'js-theme-songs', 'https://open.spotify.com/track/1sIlrJ5rokYFd4MxbZ5M30');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (295, 405, '"Sakura Uta (桜唄)"', ' by Rythem', 'js-theme-songs', 'https://open.spotify.com/track/0lnnXwqF8UbcODHlZwbBoh');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (181, 405, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (948, 405, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (949, 405, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (455, 405, 3);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6941, 405, 1, CONCAT('The Adventure Begins'), '2007-01-06', 'https://dood.so/e/byrjnhz12mjd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6942, 405, 2, CONCAT('Jasmine, Girl of the Forests'), '2007-01-13', 'https://dood.so/e/8zsqqgu8t16s');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6943, 405, 3, CONCAT('The Golden Knight'), '2007-01-20', 'https://dood.so/e/ma0jfurelsrz');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6944, 405, 4, CONCAT('The Enigmatic Giant'), '2007-01-27', 'https://dood.so/e/e732akeowyti');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6945, 405, 5, CONCAT('Nij and Doj’s Trap'), '2007-02-03', 'https://dood.so/e/2sdsc8fbz36r');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6946, 405, 6, CONCAT('The Monster in the Lake of Tears'), '2007-02-10', 'https://dood.so/e/exzzafkw9877');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6947, 405, 7, CONCAT('Sorceress Thaegan'), '2007-02-17', 'https://dood.so/e/j442h6egw8bd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6948, 405, 8, CONCAT('Tom', CHAR(39), 's Curious Shop'), '2007-02-24', 'https://dood.so/e/afksxtgdgl5h');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6949, 405, 9, CONCAT('Noradz the Clean'), '2007-03-03', 'https://dood.so/e/wi1plnvudj0s');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6950, 405, 10, CONCAT('Escape'), '2007-03-10', 'https://dood.so/e/m4wipovx373v');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6951, 405, 11, CONCAT('Cross the River'), '2007-03-17', 'https://dood.so/e/gtwnd9008qrs');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6952, 405, 12, CONCAT('The King of the Rats'), '2007-03-24', 'https://dood.so/e/qs7dszj845nm');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6953, 405, 13, CONCAT('Endon and Jarred'), '2007-03-31', 'https://dood.so/e/jw1atshs79xp');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6954, 405, 14, CONCAT('The Stolen Gems'), '2007-04-07', 'https://dood.so/e/vkon9eqmuye7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6955, 405, 15, CONCAT('Good Luck! Bad Luck!'), '2007-04-14', 'https://dood.so/e/d63x6ca4b5v9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6956, 405, 16, CONCAT('The Rithmere Games'), '2007-04-21', 'https://dood.so/e/9tvlnn4mcame');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6957, 405, 17, CONCAT('Test of Endurance'), NULL, 'https://dood.so/e/eva6muhnr0ud');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6958, 405, 18, CONCAT('Jasmine vs. Doom'), '2007-05-05', 'https://dood.so/e/ov7a38bxa1n2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6959, 405, 19, CONCAT('The Boy from the Resistance'), '2007-05-12', 'https://dood.so/e/kfhq9d94rtw3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6960, 405, 20, CONCAT('The Shifting Sands'), '2007-05-19', 'https://dood.so/e/re6jh2tnbsej');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6961, 405, 21, CONCAT('The Heavenly Stone'), '2007-05-26', 'https://dood.so/e/mykn73ymilhr');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6962, 405, 22, CONCAT('Thaegan’s Return'), '2007-06-02', 'https://dood.so/e/q322zd7llepj');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6963, 405, 23, CONCAT('Thaegan’s Trap'), '2007-06-09', 'https://dood.so/e/0srdenorhff0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6964, 405, 24, CONCAT('Meeting Prin'), '2007-06-16', 'https://dood.so/e/gzj8tdsnqxqu');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6965, 405, 25, CONCAT('Kin to the Air'), '2007-06-23', 'https://dood.so/e/k5s6vmy36jrp');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6966, 405, 26, CONCAT('Vraal Attack!'), '2007-06-30', 'https://dood.so/e/8v6y16rmpnqu');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6967, 405, 27, CONCAT('Trapped under Dread Mountain'), '2007-07-07', 'https://dood.so/e/5zndh09oj514');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6968, 405, 28, CONCAT('The Great Gellick!'), '2007-07-14', 'https://dood.so/e/ns8e3hxhqiqe');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6969, 405, 29, CONCAT('The End of the Carn Squad?'), '2007-07-21', 'https://dood.so/e/cfati2nhf8ex');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6970, 405, 30, CONCAT('The Mysterious Ols'), '2007-07-28', 'https://dood.so/e/fsl5jlb5u2o7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6971, 405, 31, CONCAT('Goodbye, Jasmine'), '2007-08-04', 'https://dood.so/e/rx1mxqzung2t');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6972, 405, 32, CONCAT('The River Queen'), '2007-08-11', 'https://dood.so/e/lyqshqta6un8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6973, 405, 33, CONCAT('Pirate Attack'), NULL, 'https://dood.so/e/w9x4mqh71zwt');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6974, 405, 34, CONCAT('The Pirates', CHAR(39), ' Feast'), '2007-08-25', 'https://dood.so/e/in1tuw1pikgv');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6975, 405, 35, CONCAT('Maze of the Beast'), '2007-09-01', 'https://dood.so/e/ol9zl1psdn83');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6976, 405, 36, CONCAT('Sorceress Thaegan Is Back!'), '2007-09-08', 'https://dood.so/e/5oa56bq89d6l');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6977, 405, 37, CONCAT('Mirror of Fear'), '2007-09-15', 'https://dood.so/e/kjxgabdp3jn7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6978, 405, 38, CONCAT('Sorcerer Oacus'), '2007-09-22', 'https://dood.so/e/080sf9pqzh0l');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6979, 405, 39, CONCAT('The Vow of the Torans'), '2007-09-29', 'https://dood.so/e/73l3kqduejz4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6980, 405, 40, CONCAT('The Valley of the Lost'), '2007-10-06', 'https://dood.so/e/3vwv0zrtrhr3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6981, 405, 41, CONCAT('The Last Gem'), '2007-10-13', 'https://dood.so/e/to64hzgdwyl3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6982, 405, 42, CONCAT('The Seven Gems United'), '2007-10-20', 'https://dood.so/e/1q43aqhwk5tc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6983, 405, 43, CONCAT('Nevets Goes Wild'), '2007-10-27', 'https://dood.so/e/3cinw8mfzkco');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6984, 405, 44, CONCAT('Battle At Withick Mire'), '2007-11-03', 'https://ebd.cda.pl/800x450/4078423ea');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6985, 405, 45, CONCAT('The Oath'), '2007-11-10', 'https://dood.so/e/zu17pvar77dd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6986, 405, 46, CONCAT('The Last Battle of Fire'), '2007-11-17', 'https://dood.so/e/yj568uyyenup');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6987, 405, 47, CONCAT('The Seven Tribes!'), '2007-11-24', 'https://dood.so/e/627f0pv48eak');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6988, 405, 48, CONCAT('Who Is Dain?'), '2007-12-01', 'https://dood.so/e/r394c2sz7b8h');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6989, 405, 49, CONCAT('A Desperate Rescue'), '2007-12-08', 'https://dood.so/e/tzlsi5fs158f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6990, 405, 50, CONCAT('Who’s the Next King?'), '2007-12-15', 'https://dood.so/e/ngyngg9bbcrm');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6991, 405, 51, CONCAT('Battle of the Ak-Babas'), '2007-12-22', 'https://dood.so/e/0dfdmmoos4j8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6992, 405, 52, CONCAT('When the Seven Gems Shine'), '2007-12-31', 'https://dood.so/e/epct0ppvwcpi');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6993, 405, 53, CONCAT('On an Adventurous Journey Again'), '2008-01-05', 'https://www.youtube.com/embed/iHtCaMPr680');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6994, 405, 54, CONCAT('Jasmine Returns to the Forest'), '2008-01-12', 'https://www.youtube.com/embed/ZFFJ_7dBQbI');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6995, 405, 55, CONCAT('Trap of the Underground Labyrinth'), '2008-01-19', 'https://www.youtube.com/embed/NVE4qDRxzpk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6996, 405, 56, CONCAT('Filli in a Big Pinch?'), '2008-01-26', 'https://www.youtube.com/embed/I7lq47OC5cw');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6997, 405, 57, CONCAT('The Solitary Guards'), '2008-02-02', 'https://www.youtube.com/embed/eYEs7Wpfmts');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6998, 405, 58, CONCAT('House-sitting at Tom', CHAR(39), 's Shop'), '2008-02-09', 'https://www.youtube.com/embed/Y58EWPsmJZ8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (6999, 405, 59, CONCAT('Prin', CHAR(39), 's First Love'), '2008-02-16', 'https://www.youtube.com/embed/HMVhE_-mv28');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7000, 405, 60, CONCAT('The Pirates of the River Tor'), '2008-02-23', 'https://www.youtube.com/embed/qspVHK4d7Z4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7001, 405, 61, CONCAT('The Stolen Belt'), '2008-03-01', 'https://www.youtube.com/embed/UlZLcpT6IrY');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7002, 405, 62, CONCAT('The Promise that Lief Kept'), '2008-03-08', 'https://www.youtube.com/embed/N0B6IUv9xAQ');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7003, 405, 63, CONCAT('Neridah and Jasmine'), '2008-03-15', 'https://www.youtube.com/embed/slUsaYiH1cE');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7004, 405, 64, CONCAT('The House Where Ols Lurk'), '2008-03-22', 'https://www.youtube.com/embed/bOE1a8bkSvg');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7005, 405, 65, CONCAT('Deltora Forever'), '2008-03-29', 'https://www.youtube.com/embed/cMHc5IgaajA');
