INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (438, CONCAT('Dog Days', CHAR(39), '', CHAR(39), ''), CONCAT('Cinque Izumi, Nanami Takatsuki, and Rebecca Anderson must once again embark on a journey to the continent of Flonyard and participate in the friendly war games of the three allied nations: Biscotti Republic, Galette, and Pastilage. Cinque is Biscotti’s hero, who also happens to be the cousin of Galette’s hero Nanami. Rebecca is Pastillage’s hero and a dear friend of Cinque.<br><br>Dog Days', CHAR(39), '', CHAR(39), ' begins in the human world. Rebecca prepares her things for her journey back to Pastilage from Japan. Meanwhile, Cinque and Nanami set out to travel to Biscotti and Galette, respectively, all the way from England, when suddenly, a freakish streak of bad luck—in the form of lightning, of course—sends them off course. They soon find themselves in the great Dragon Forest, protected by a Dragon Priestess named Sharu. The Dragon Priestess informs them that demons threaten to invade the forest, as well as the whole continent of Flonyard!<br>
<br>It looks like a real war is about to begin in Dog Days', CHAR(39), '', CHAR(39), '. Can these three heroes save the whole continent from these evil beings?'), 1, '2015-01-11', '2015-03-29', 'Winter 2015', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/70709.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (311, 438, '"No Limit"', ' by Nana Mizuki', 'js-theme-songs', 'https://open.spotify.com/track/7scWTACvzsB1Q92nERgey4')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1052, 438, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1053, 438, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1054, 438, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (490, 438, 12);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7784, 438, 1, CONCAT('Once Again, The Hero Returns'), NULL, 'https://ebd.cda.pl/620x395/802460021');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7785, 438, 2, CONCAT('The Dragon Priestess'), NULL, 'https://ebd.cda.pl/620x395/802463381');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7786, 438, 3, CONCAT('Decisive Battle! The Dragon', CHAR(39), 's Forest!'), NULL, 'https://ebd.cda.pl/620x395/802459797');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7787, 438, 4, CONCAT('What', CHAR(39), 's Passed On'), NULL, 'https://ebd.cda.pl/620x395/802463972');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7788, 438, 5, CONCAT('Exploration at the Crystal Mines!'), NULL, 'https://ebd.cda.pl/620x395/802459472');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7789, 438, 6, CONCAT('The Lion', CHAR(39), 's Arranged Marriage'), NULL, 'https://ebd.cda.pl/620x395/802463696');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7790, 438, 7, CONCAT('The Little Prince and the Legendary Hero'), NULL, 'https://ebd.cda.pl/620x395/8024609c3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7791, 438, 8, CONCAT('Recollection: The Story of the Hero and the Princess'), NULL, 'https://ebd.cda.pl/620x395/8024612c6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7792, 438, 9, CONCAT('The Star Whale in the Sky Sea'), NULL, 'https://ebd.cda.pl/620x395/80246188d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7793, 438, 10, CONCAT('The Sky Priestess and the Star People'), NULL, 'https://ebd.cda.pl/620x395/80246301a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7794, 438, 11, CONCAT('Song of the Stars'), NULL, 'https://ebd.cda.pl/620x395/8024627c6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7795, 438, 12, CONCAT('Returning Home'), NULL, 'https://ebd.cda.pl/620x395/802461531');
