INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (442, CONCAT('Domestic na Kanojo'), CONCAT('In their teenage years, few things can hurt people more than the heartaches that come with unrequited love. Such is the case for Natsuo Fujii, who has found himself entranced by his school', CHAR(39), 's ever-cheerful teacher Hina. Deflated by this unreachable desire, Natsuo humors his friends and attends a mixer. There he meets Rui, a girl whose lack of excitement rivals that of himself. After bonding over their mutual awkwardness, Rui takes Natsuo to her house and asks him to have sex with her, hoping that the experience will stop her friends from treating her like a clueless child. With his hopeless feelings towards Hina still on his mind, Natsuo hesitantly agrees.<br>
<br>Equally unfulfilled by their "first times," the two decide to part ways as strangers. However, before he even has a chance to process this experience, Natsuo', CHAR(39), 's father drops a major bombshell: he is getting remarried, and his new wife Tsukiko Tachibana is coming over now to meet Natsuo. As if that was not enough of a shock, her daughters—and, in turn, Natsuo', CHAR(39), 's new sisters—are Hina and Rui Tachibana, the woman he', CHAR(39), 's in love with and the girl with whom he shared his first night. Now, Natsuo must come to terms with the feelings he has for his step-siblings as his eyes open to a darker side of love.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-01-12', '2019-03-30', 'Winter 2019', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1021/95670.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (314, 442, '"Kawaki wo Ameku (カワキヲアメク)"', ' by Minami', 'js-theme-songs', 'https://open.spotify.com/track/1gUAX2ImxDsB3YDcyxMXlB')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (202, 442, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1065, 442, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1066, 442, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (494, 442, 30);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (466, 442, 22);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (467, 442, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7832, 442, 1, CONCAT('Will You Do It With Me, Here?'), '2019-01-12', 'https://ebd.cda.pl/620x368/330907916');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7833, 442, 2, CONCAT('By Any Chance, Did We Do It?'), '2019-01-19', 'https://ebd.cda.pl/620x368/330908518');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7834, 442, 3, CONCAT('Is It True, After All?'), '2019-01-26', 'https://ebd.cda.pl/620x368/303589877');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7835, 442, 4, CONCAT('And... What About You?'), '2019-02-02', 'https://ebd.cda.pl/620x368/3309142b3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7836, 442, 5, CONCAT('Is It Okay... If I Fall for Him?'), '2019-02-09', 'https://ebd.cda.pl/620x368/3091476ea');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7837, 442, 6, CONCAT('Right Here and Now, Try to Kiss'), '2019-02-16', 'https://ebd.cda.pl/620x368/330918139');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7838, 442, 7, CONCAT('This Is What It Means To Go Out Together, You Know?'), '2019-02-23', 'https://ebd.cda.pl/800x450/3753559ba');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7839, 442, 8, CONCAT('Then I Don', CHAR(39), 't Have To Be An Adult'), '2019-03-02', 'https://ebd.cda.pl/620x368/33091877c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7840, 442, 9, CONCAT('Don', CHAR(39), 't Say That, Please?'), '2019-03-09', 'https://ebd.cda.pl/620x368/32074311c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7841, 442, 10, CONCAT('Liar…'), '2019-03-16', 'https://ebd.cda.pl/620x368/330919381');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7842, 442, 11, CONCAT('Are You Sure?'), '2019-03-23', 'https://ebd.cda.pl/620x368/3309223d8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7843, 442, 12, CONCAT('I', CHAR(39), 'm Sorry. I Love You.'), '2019-03-30', 'https://ebd.cda.pl/620x368/3323722f0');
