INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (443, CONCAT('Donten ni Warau'), CONCAT('In the 11th year of the Meiji Era, the end of the samurai shogunate and the prohibition of swords has left Japan with lasting scars. Displeased by these recent changes, many former samurai plot against the new government, inciting a wave of bloodshed. To counter this movement, the government constructs a colossal prison in the middle of Lake Biwa. <br>
<br>Unofficially assigned to help the police arrest criminals, Tenka Kumou also serves as a ferryman to the Lake Biwa prison with the help of his two younger siblings: the ambitious Soramaru and the enthusiastic Chuutarou. Together with the former Fuma ninja Shirasu Kinjou, the Kumou brothers live a frugal and joyful life mostly dedicated to studying and training.<br>
<br>However, behind this relatively uneventful daily routine, the specter of the "Orochi" curse is starting to spread its shadow over the city of Oumi. According to legend, every three hundred years, Orochi reincarnates in a human vessel—and it is believed that this is the harbinger of an imminent catastrophe. As various groups clash in search of Orochi', CHAR(39), 's vessel, some aim to seal the curse, while others have darker plans in motion.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2014-10-04', '2014-12-20', 'Fall 2014', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1661/114954.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (203, 443, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1067, 443, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1068, 443, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (495, 443, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7844, 443, 1, CONCAT('Three Brothers, Standing Under the Clouds'), '2014-10-04', 'https://video.sibnet.ru/shell.php?videoid=1593205');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7845, 443, 2, CONCAT('Cutthroat, Sneering at the Clouds'), '2014-10-11', 'https://drive.google.com/file/d/0BzP_5dQGK87PSThidVNlaDFySTg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7846, 443, 3, CONCAT('Second Brother, Undercover in Prison'), NULL, 'https://vk.com/video_ext.php?oid=186749831&id=170198617&hash=910404c0988876e6&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7847, 443, 4, CONCAT('Fuma, Sneaking Through the Prison Gate'), NULL, 'https://vk.com/video_ext.php?oid=274565215&id=170458814&hash=ef7660a53196c011&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7848, 443, 5, CONCAT('Tenka, Shaken by Turmoil'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1597468');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7849, 443, 6, CONCAT('The Sun, Disappearing into the Clouds'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1597471');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7850, 443, 7, CONCAT('Fleeting Laughter'), NULL, 'https://vk.com/video_ext.php?oid=250023721&id=170947716&hash=fd013fe7ae417f24');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7851, 443, 8, CONCAT('Boys, Lamenting in the Rain'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1633183');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7852, 443, 9, CONCAT('Successor, Standing Under the Cloudy Sky'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1633187');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7853, 443, 10, CONCAT('White Darkness, Turning Back'), NULL, 'https://drive.google.com/file/d/0B3OpSwHluIW5V1VxRFdRc0JEN1U/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7854, 443, 11, CONCAT('The Sun, Shining Again in the Clouds'), NULL, 'https://drive.google.com/file/d/0B9SlP9nShNbsSFpJbWhlYVNHdlk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7855, 443, 12, CONCAT('Brothers, Gathering Under the Sun'), NULL, 'https://drive.google.com/file/d/0B3OpSwHluIW5ZmszY2NWNVZ4aEE/preview');
