INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (452, CONCAT('Dr. Stone'), CONCAT('After five years of harboring unspoken feelings, high-schooler Taiju Ooki is finally ready to confess his love to Yuzuriha Ogawa. Just when Taiju begins his confession however, a blinding green light strikes the Earth and petrifies mankind around the world—turning every single human into stone.<br>
<br>Several millennia later, Taiju awakens to find the modern world completely nonexistent, as nature has flourished in the years humanity stood still. Among a stone world of statues, Taiju encounters one other living human: his science-loving friend Senkuu, who has been active for a few months. Taiju learns that Senkuu has developed a grand scheme—to launch the complete revival of civilization with science. Taiju', CHAR(39), 's brawn and Senkuu', CHAR(39), 's brains combine to forge a formidable partnership, and they soon uncover a method to revive those petrified.<br>
<br>However, Senkuu', CHAR(39), 's master plan is threatened when his ideologies are challenged by those who awaken. All the while, the reason for mankind', CHAR(39), 's petrification remains unknown.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-07-05', '2019-12-13', 'Summer 2019', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1613/102576.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (322, 452, '"Good Morning World!"', ' by BURNOUT SYNDROMES', 'js-theme-songs', 'https://open.spotify.com/track/5p0T8499UG6lKHzXjLnckz')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (206, 452, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1097, 452, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1098, 452, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1099, 452, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (505, 452, 23);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (482, 452, 14);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (483, 452, 15);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7944, 452, 1, CONCAT('Stone World'), '2019-07-05', 'https://drive.google.com/file/d/1Suzu5CDWpJ-XIQI3Doefdl34K53CsKHU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7945, 452, 2, CONCAT('King of the Stone World'), '2019-07-12', 'https://drive.google.com/file/d/1jqRY83Vqk-BwaIF8BiOa-fL5CkXzqOSJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7946, 452, 3, CONCAT('Weapons of Science'), '2019-07-19', 'https://drive.google.com/file/d/1CrPaDD2S2IvjEp_yxCFY7XCBbcK9JDC2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7947, 452, 4, CONCAT('Fire the Smoke Signal'), '2019-07-26', 'https://drive.google.com/file/d/1VM3w5b1Kxw_jojA0seFt57MAqp8HiGn4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7948, 452, 5, CONCAT('Stone World The Beginning'), '2019-08-02', 'https://drive.google.com/file/d/1P5YtDiaasZuNjpqRwyNU4vRctGYQEooE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7949, 452, 6, CONCAT('Two Nations of the Stone World'), '2019-08-09', 'https://drive.google.com/file/d/1eJymg9li2omz-UW8nvHIl5LDrNFZhc_B/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7950, 452, 7, CONCAT('Where Two Million Years Have Gone'), '2019-08-16', 'https://drive.google.com/file/d/1CZEjEH_4GwMA45I8Wut9kMVKSdV_VsGJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7951, 452, 8, CONCAT('Stone Road'), '2019-08-23', 'https://drive.google.com/file/d/1Zy3InVIJKkbQJc2n7z7U2bRtLXsVevFD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7952, 452, 9, CONCAT('Let There Be the Light of Science'), '2019-08-30', 'https://drive.google.com/file/d/1jSJsYkfzWBsCkTV97vBy-m7ruO4QgejQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7953, 452, 10, CONCAT('A Flimsy Alliance'), '2019-09-06', 'https://drive.google.com/file/d/1qoo8umH9Rq1D2yG_41MNyKRrGxiWrB9r/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7954, 452, 11, CONCAT('Clear World'), '2019-09-13', 'https://drive.google.com/file/d/1Awg73UMi1y-sjWtUs5nQ124d_Lo9Oz4N/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7955, 452, 12, CONCAT('Buddies Back to Back'), '2019-09-20', 'https://drive.google.com/file/d/1CrPovovjPMoEJ4gBTS6AykgUoJsaZc9-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7956, 452, 13, CONCAT('Masked Warrior'), '2019-09-27', 'https://drive.google.com/file/d/1-l42X3YW3_h3UBhPn43TykyLf8G4tepz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7957, 452, 14, CONCAT('Master of Flame'), '2019-10-04', 'https://drive.google.com/file/d/18h3Pk40Wb5Y4EvTDSNyAhQToUZGdQgE7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7958, 452, 15, CONCAT('The Culmination of Two Million Years'), '2019-10-11', 'https://drive.google.com/file/d/1TLYlHAv4wLw0Dx9TEFlTZzQgevfWd3Fl/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7959, 452, 16, CONCAT('A Tale for the Ages'), '2019-10-18', 'https://drive.google.com/file/d/17Oa3wLj_ajzR3NN3SIKPuF8je96UsUke/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7960, 452, 17, CONCAT('A Hundred Nights and a Thousand Skies'), '2019-10-25', 'https://drive.google.com/file/d/1QO2DZqDtCGbOdbPuBFL-a7xUANKAXKvs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7961, 452, 18, CONCAT('Stone Wars'), '2019-11-01', 'https://drive.google.com/file/d/197FC-MwWqDZnxj9K0r3hCMdoJq-fxAzw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7962, 452, 19, CONCAT('To Modernity'), '2019-11-08', 'https://drive.google.com/file/d/19HKo8-WfKaHm6oMRKcxpPeH7NaP1UcnD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7963, 452, 20, CONCAT('The Age of Energy'), '2019-11-15', 'https://drive.google.com/file/d/1ihWfi-C1TSARpBhgJlTEvNMfEatElt1O/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7964, 452, 21, CONCAT('Spartan Crafts Club'), '2019-11-22', 'https://ebd.cda.pl/620x395/5211786f8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7965, 452, 22, CONCAT('The Treasure'), '2019-11-29', 'https://ebd.cda.pl/620x395/5211789d4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7966, 452, 23, CONCAT('Wave of Science'), '2019-12-06', 'https://drive.google.com/file/d/1Z3uIwtvqOiLiUPusGqhMlJmwh5WD5tPc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7967, 452, 24, CONCAT('Voices Over Infinite Distance'), '2019-12-13', 'https://drive.google.com/file/d/1rNmFKY1t0BvGNOGk6TVj84gdqfTxHjAF/preview');
