INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (464, CONCAT('Dream Festival! R'), CONCAT('No synopsis information has been added to this title. Help improve our database by adding a synopsis here.'), 4, '2017-08-23', '2017-11-08', '', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/86852.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (331, 464, '"Yume no Kodou (ユメノコドウ)"', ' by DearDream', 'js-theme-songs', 'https://open.spotify.com/track/1ICjjhyI3WYkuFHznUKYJK')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (517, 464, 86);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (500, 464, 36);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (501, 464, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8449, 464, 1, CONCAT('True Idols!!!!!'), NULL, 'https://vk.com/video363201967_456239025');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8450, 464, 2, CONCAT('A Song With No Continuation'), NULL, 'https://vk.com/video363201967_456239031');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8451, 464, 3, CONCAT('The Two Standing in the Fog!!'), NULL, 'https://mp4upload.com/embed-7rvowewmw2b7.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8452, 464, 4, CONCAT('Assault! Full Coverage of Sankishi!!!'), NULL, 'https://vk.com/video363201967_456239030');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8453, 464, 5, CONCAT('Away Team Drama'), NULL, 'https://vk.com/video363201967_456239033');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8454, 464, 6, CONCAT('Two of Us Are Rivals!!'), NULL, 'https://www.youtube.com/embed/gx9LvTbq1AM');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8455, 464, 7, CONCAT('My Value as an Idol'), NULL, 'https://www.mp4upload.com/embed-xo6nlqqs1m0u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8456, 464, 8, CONCAT('DearDream Fan Meeting!!!!!'), NULL, 'https://www.mp4upload.com/embed-mbz1zbrqqryj.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8457, 464, 9, CONCAT('Ryo Enters Port!!!'), NULL, 'https://www.mp4upload.com/embed-as5yz5grixfn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8458, 464, 10, CONCAT('Now Is the Moment to Change'), NULL, 'https://www.mp4upload.com/embed-2a48rfgcwkyf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8459, 464, 11, CONCAT('All For Tomorrow!!!!!!!'), NULL, 'https://www.mp4upload.com/embed-tddcznwhj0wy.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8460, 464, 12, CONCAT('DearDream x KUROFUNE La La La Live Special'), NULL, 'https://www.mp4upload.com/embed-5teodeyvg98a.html');
