INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (489, CONCAT('Engage Kiss'), CONCAT('Bayron City, a pioneering metropolis built on a newly discovered energy source, promises every citizen a luxurious and comfortable lifestyle. In reality, young demon exterminator Shuu Ogata', CHAR(39), 's life is far from extravagant. Despite running a private military business, he often struggles to make ends meet due to reckless expenses. Fortunately, Kisara, his demon partner, is more than eager to help Shuu with household matters—albeit a little too forcefully for his comfort.<br>
<br>The two work side by side, taking countermeasures against demon hazards, which stand as the biggest threats to the city. With danger lurking in the shadows, Shuu and Kisara strive to grant the town', CHAR(39), 's safety however, exterminating the possessed comes with a price unbeknownst to others.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-07-03', '2022-09-25', 'Summer 2022', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1549/125495.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1207, 489, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1208, 489, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (544, 489, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8793, 489, 1, CONCAT('A Loser and a Demon and a Man and a Woman'), '2022-07-03', 'https://ebd.cda.pl/620x368/1134842530');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8794, 489, 2, CONCAT('The Island of Desire'), '2022-07-10', 'https://drive.google.com/file/d/1L45x47yliC7u3BLw8LfeCso6JgCrdqub/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8795, 489, 3, CONCAT('The Slightest Terrible Cost'), '2022-07-17', 'https://drive.google.com/file/d/14ygH6hzDj9gl1i7erbAlTXi945YWcbGh/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8796, 489, 4, CONCAT('Unobtainable Lingering'), '2022-07-24', 'https://drive.google.com/file/d/109W1eOGkB97Jv95x_EIFonmQRyn5UZt7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8797, 489, 5, CONCAT('Fleeting Scars'), '2022-07-31', 'https://drive.google.com/file/d/1G-MZFbd9XDfXyUlQCWy3S1Y8XmJOREYN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8798, 489, 6, CONCAT('Third-Party Demon Killer'), '2022-08-07', 'https://drive.google.com/file/d/1DsDIuAqIly1tRdNM0Nypyq1OATiSNOjV/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8799, 489, 7, CONCAT('But It', CHAR(39), 's Okay, That', CHAR(39), 's Enough'), '2022-08-14', 'https://drive.google.com/file/d/1FW0C6xBkb1ashltlAqcfZDF1udSSH1IB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8800, 489, 8, CONCAT('The Unwanted Truth'), '2022-08-21', 'https://drive.google.com/file/d/1XlSO-pRk6Dghf5fCS1Lveeii7nYvDZEw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8801, 489, 9, CONCAT('Without Understanding the Tears Shed'), '2022-08-28', 'https://drive.google.com/file/d/1tT3dMxf1lbEMsAEQ-BN1t4VVY2_dOCjI/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8802, 489, 10, CONCAT('High Hopes for the Worst Case'), '2022-09-04', 'https://drive.google.com/file/d/1I3rlC6mLgrDGxYe2afw0YUH2ZeDYFGXT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8803, 489, 11, CONCAT('Gentle Foolish Lies'), '2022-09-11', 'https://drive.google.com/file/d/1QGVoojwcig8SvZebypFR_Xi1yViS66cQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8804, 489, 12, CONCAT('Believe in Him'), '2022-09-18', 'https://drive.google.com/file/d/14NZephdPrx4yspfhS24V-1FB43tou4IC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8805, 489, 13, CONCAT('Unresolved Grand Finale'), '2022-09-25', 'https://drive.google.com/file/d/1wVqdy4wOvvz68CXKhD6DvecMxo12SS_Q/preview');
