INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (492, CONCAT('Eromanga-sensei'), CONCAT('One year ago, Sagiri Izumi became step-siblings with Masamune Izumi. But the sudden death of their parents tears their new family apart, resulting in Sagiri becoming a shut-in which cut her off from her brother and society.<br>
<br>While caring for what', CHAR(39), 's left of his family, Masamune earns a living as a published light novel author with one small problem: he', CHAR(39), 's never actually met his acclaimed illustrator, Eromanga-sensei, infamous for drawing the most lewd erotica. Through an embarrassing chain of events, he learns that his very own little sister was his partner the whole time!<br>
<br>As new characters and challenges appear, Masamune and Sagiri must now face the light novel industry together. Eromanga-Sensei follows the development of their relationship and their struggle to become successful and as Sagiri slowly grows out of her shell, just how long will she be able to hide her true persona from the rest of the world?<br>
<br>[Written by MAL Rewrite]'), 1, '2017-04-09', '2017-06-25', 'Spring 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/86468.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (355, 492, '"Hitorigoto (ヒトリゴト)"', ' by ClariS', 'js-theme-songs', 'https://open.spotify.com/track/6WMeDp0t2UJmy21PRKAOzx')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1211, 492, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1212, 492, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1213, 492, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1214, 492, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (547, 492, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8853, 492, 1, CONCAT('My Little Sister, and the Sealed Room'), '2017-04-09', 'https://ebd.cda.pl/620x368/443502257');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8854, 492, 2, CONCAT('Class Rep with a Normie Life, and a Fearless Fairy'), '2017-04-16', 'https://ebd.cda.pl/620x368/44606575d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8855, 492, 3, CONCAT('Buck Naked Mansion and the Fallen Master'), '2017-04-23', 'https://ebd.cda.pl/620x368/44974376f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8856, 492, 4, CONCAT('Eromanga-sensei'), '2017-04-30', 'https://ebd.cda.pl/620x368/453872046');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8857, 492, 5, CONCAT('Let', CHAR(39), 's Plan a Light-novel with your Little Sister'), '2017-05-07', 'https://ebd.cda.pl/620x368/4560362ee');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8858, 492, 6, CONCAT('Masamune Izumi and the Nemesis of Ten Million Copies'), '2017-05-14', 'https://ebd.cda.pl/620x368/4621340ff');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8859, 492, 7, CONCAT('Little Sister and the Most Interesting Novel in the World'), '2017-05-21', 'https://ebd.cda.pl/620x368/47720541f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8860, 492, 8, CONCAT('Dreaming Sagiri and Summer Fireworks'), '2017-05-28', 'https://ebd.cda.pl/620x368/4982279ef');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8861, 492, 9, CONCAT('Little Sister and the Fairy Island'), '2017-06-04', 'https://ebd.cda.pl/620x368/510431109');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8862, 492, 10, CONCAT('Masamune Izumi and the Younger Senpai'), '2017-06-11', 'https://ebd.cda.pl/620x368/5288907d5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8863, 492, 11, CONCAT('How the Two Met and Future Siblings'), '2017-06-18', 'https://drive.google.com/file/d/19zvrupoHZwkbm-Dy5l6lgqdoDNfHihZ9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8864, 492, 12, CONCAT('Eromanga Festival'), '2017-06-25', 'https://video.sibnet.ru/shell.php?videoid=4029017');
