INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (495, CONCAT('Estab-Life: Great Escape'), CONCAT('In the distant future, the cities of Japan have been walled off and isolated from one another. Tourism and immigration are heavily controlled—if not impossible. Each region is overseen by an AI moderator that maintains its domain as it sees fit. These clusters are refined into a single ideal, with every citizen fulfilling their role in preserving the moderator', CHAR(39), 's creation. But not everyone is satisfied with the narrowly focused vision of the city they were born in, and thus, they require some under-the-table help in relocating to a more appropriate cluster.<br>
<br>During the day, Equa, Ferres, and Martese are ordinary high school students but at night, they act as Extractors—people who illegally smuggle civilians between the city borders. Transporting those brave enough to leave everything behind, Equa and her friends risk their lives in order to give their clients a second chance. But the dangers of extraction begin to intensify when the cluster moderators become increasingly aware of the group', CHAR(39), 's actions that threaten their perfect utopias.<br>
<br>[Written by MAL Rewrite]'), 2, '2022-04-06', '2022-06-22', 'Spring 2022', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1811/121606.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (357, 495, '"Rana (ラナ)"', ' by Meychan (めいちゃん)', 'js-theme-songs', 'https://open.spotify.com/track/1iXN8j1ThITNhNOr2Tez8A')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1219, 495, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1220, 495, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1221, 495, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (550, 495, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8879, 495, 1, CONCAT('You Can', CHAR(39), 't Run from Schoolwork'), '2022-03-01', 'https://video.sibnet.ru/shell.php?videoid=4671125');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8880, 495, 2, CONCAT('You Can', CHAR(39), 't Run from Memories'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4809908');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8881, 495, 3, CONCAT('You Can', CHAR(39), 't Run from the Aquarium'), NULL, 'https://dood.pm/e/d5jmk44p9trn');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8882, 495, 4, CONCAT('You Can', CHAR(39), 't Run from Democracy'), NULL, 'https://dood.pm/e/4il73w5ased4');
