INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (514, CONCAT('Fate/kaleid liner Prisma☆Illya'), CONCAT('Mage', CHAR(39), 's Association members Rin Toosaka and Luviagelita "Luvia" Edelfelt are tasked with finding and retrieving seven Class Cards, medieval artifacts containing the life essence of legendary Heroic Spirits. To aid them in their mission, they are granted the power of Ruby and Sapphire, two sentient Kaleidosticks that would enable them to transform themselves into magical girls and drastically increase their abilities. However, the two mages are on anything but good terms, prompting the Kaleidosticks to abandon them in search for new masters. They stumble upon two young schoolgirls—Illyasviel von Einzbern and Miyu—and quickly convince them to form a contract. With their new powers and responsibilities, Illya and Miyu set forth to collect all the Class Cards.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2013-07-13', '2013-09-14', 'Summer 2013', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1773/121542.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (373, 514, '"starlog"', ' by ChouCho', 'js-theme-songs', 'https://open.spotify.com/track/6VB3K5u8557Vg4qadMeXiO')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1271, 514, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1272, 514, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1273, 514, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (574, 514, 50);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9487, 514, 1, CONCAT('Birth! A Magical Girl!'), '2013-07-13', 'https://drive.google.com/file/d/18dpFcp1jOalc0VKhK5q3au08XFux-yxR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9488, 514, 2, CONCAT('Who'), '2013-07-20', 'https://ebd.cda.pl/620x395/62968556f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9489, 514, 3, CONCAT('Girl Meets Girl'), '2013-07-27', 'https://drive.google.com/file/d/1p1Kn3DJaMDf6iZ42wTfI0_UmA9D_1dpk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9490, 514, 4, CONCAT('We Lost'), '2013-08-03', 'https://drive.google.com/file/d/1SiaMEPJESBilGs74o9V2dP9TxzJ9XQTm/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9491, 514, 5, CONCAT('There are two options?'), '2013-08-10', 'https://ebd.cda.pl/620x395/62968648d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9492, 514, 6, CONCAT('A Blank, and the End of Night…'), '2013-08-17', 'https://drive.google.com/file/d/14bkdiTYDGUG8JJuKBm_xyKE5WedUhpQw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9493, 514, 7, CONCAT('Victory and Flight'), '2013-08-24', 'https://ebd.cda.pl/620x395/6296870ca');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9494, 514, 8, CONCAT('I', CHAR(39), 'm Going to Be a Normal Girl Again!'), '2013-08-31', 'https://ebd.cda.pl/620x395/6296873a0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9495, 514, 9, CONCAT('I', CHAR(39), 'll End It Here!'), '2013-09-07', 'https://ebd.cda.pl/620x395/629687637');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9496, 514, 10, CONCAT('Kaleidoscope'), '2013-09-14', 'https://ebd.cda.pl/800x450/629687940');
