INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (523, CONCAT('Free!'), CONCAT('Haruka Nanase has a love for water and a passion for swimming. In elementary school, he competed in and won a relay race with his three friends Rin Matsuoka, Nagisa Hazuki, and Makoto Tachibana. After claiming victory at the tournament, the four friends went their separate ways. Years later, they reunite as high school students however, Rin couldn', CHAR(39), 't care less about returning to the way things used to be. Not only does he attend a different school, but the sole thing important to him is proving that he is a better swimmer than Haruka.<br>
<br>After the bitter reunion, Haruka, Nagisa, and Makoto decide to form the Iwatobi High School Swim Club, but they will need a fourth member if they hope to take part in the upcoming tournament. Enter Rei Ryuugazaki, a former member of the track team whom Nagisa recruits. As the time to compete draws near, the four develop a close bond while training intensely to come out on top and settle things between Haruka and Rin once and for all.<br>
<br>[Written by MAL Rewrite]'), 1, '2013-07-04', '2013-09-26', 'Summer 2013', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/51107.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (585, 523, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (586, 523, 15);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9622, 523, 1, CONCAT('Reunion at the Starting Block!'), '2013-07-04', 'https://drive.google.com/file/d/0B139lo1udc_WdVRQMU15STRsQ0E/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9623, 523, 2, CONCAT('Memories in the Distance!'), '2013-07-11', 'https://drive.google.com/file/d/0B1JKi5BjK1pjTE16aFpjN1AwdEk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9624, 523, 3, CONCAT('Theoretical Dolphin Kick!'), '2013-07-18', 'https://drive.google.com/file/d/0B139lo1udc_WdVo3Z1JFQlE2VTg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9625, 523, 4, CONCAT('Captive Butterfly!'), '2013-07-25', 'https://drive.google.com/file/d/0B139lo1udc_WSE9iQ2hyUll1UEU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9626, 523, 5, CONCAT('Trial in Open Water!'), '2013-08-08', 'https://ebd.cda.pl/800x450/2537514ad');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9627, 523, 6, CONCAT('Shocking No Breathing!'), '2013-08-15', 'https://drive.google.com/file/d/0B81hBlvyBDaDUDZORjBFU2JiUGc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9628, 523, 7, CONCAT('One Style Final!'), '2013-08-22', 'https://drive.google.com/file/d/0B139lo1udc_WSWVLRi1GNHhRakk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9629, 523, 8, CONCAT('Revenge in the Medley!'), '2013-08-29', 'https://ebd.cda.pl/620x395/533744796');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9630, 523, 9, CONCAT('Hesitant Loosen Up!'), '2013-09-05', 'https://drive.google.com/file/d/0B139lo1udc_WYjh1X1JqMExlYlE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9631, 523, 10, CONCAT('Irritated Heart Rate!'), '2013-09-12', 'https://drive.google.com/file/d/0B139lo1udc_WUUF6R0tsSHh2RWM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9632, 523, 11, CONCAT('Furious All-out!'), '2013-09-19', 'https://drive.google.com/file/d/0B139lo1udc_WOWtJclVQU2lIakE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9633, 523, 12, CONCAT('Distant Free!'), '2013-09-26', 'https://drive.google.com/file/d/0B81hBlvyBDaDVjY5RVdPTHhVOHc/preview');
