INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (533, CONCAT('Fudanshi Koukou Seikatsu'), CONCAT('Ryou Sakaguchi is a totally normal high school student, aside from his single unusual hobby. Sakaguchi is a fudanshi—a man who loves reading "boys', CHAR(39), ' love" manga, and fantasizing about the gay potential he sees everywhere. He has only one wish before he dies: to find himself some friends that understand his secret passion.<br>
<br>His wish comes true, as Sakaguchi begins to uncover a host of interested parties. There', CHAR(39), 's Rumi Nishihara, a closeted fujoshi who is more than eager to discuss the joys of boys', CHAR(39), ' love with Sakaguchi the flamboyantly gay leader of the school', CHAR(39), 's cooking club, Yuujirou Shiratori, who makes no effort whatsoever to conceal his sexuality Akira Ueda, Shiratori', CHAR(39), 's diligent admirer, who will do anything for the love of his life and even the mischievous Daigo, a fellow fudanshi and popular author of boys', CHAR(39), ' love doujinshi. Standing by their sides throughout all the otaku chaos is Sakaguchi', CHAR(39), 's best friend, Toshiaki Nakamura, who only wishes his classmates would start acting more like normal people.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-07-05', '2016-09-20', 'Summer 2016', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/80966.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (388, 533, '"SEKAI wa Boy Meets Boy (SEKAIはボーイミーツボーイ♂)"', ' by Ryou Sakaguchi (Wataru Hatano)', 'js-theme-songs', '');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (236, 533, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (597, 533, 48);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (540, 533, 18);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (541, 533, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9822, 533, 1, CONCAT('The Daily Life of a Fudanshi High School Student'), '2016-07-05', 'https://ebd.cda.pl/800x450/6232826f1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9823, 533, 2, CONCAT('My Classmate'), '2016-07-12', 'https://ebd.cda.pl/800x450/623280283');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9824, 533, 3, CONCAT('There are Fujoshi Everywhere'), '2016-07-19', 'https://ebd.cda.pl/800x450/6232811e3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9825, 533, 4, CONCAT('My First Otaku Friend'), '2016-07-26', 'https://ebd.cda.pl/800x450/623280810');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9826, 533, 5, CONCAT('Troublesome Kouhai'), '2016-08-02', 'https://ebd.cda.pl/800x450/623280538');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9827, 533, 6, CONCAT('Summer for Otakus'), '2016-08-09', 'https://ebd.cda.pl/800x450/62328141d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9828, 533, 7, CONCAT('Everyone', CHAR(39), 's Fun Times'), NULL, 'https://ebd.cda.pl/800x450/62328202a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9829, 533, 8, CONCAT('The Girl On My Mind'), NULL, 'https://www.mp4upload.com/embed-uyem1gyw1ztg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9830, 533, 9, CONCAT('Transformation Desires'), NULL, 'https://ebd.cda.pl/800x450/62327990c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9831, 533, 10, CONCAT('Worldly Desires of 801 (Yaoi)'), NULL, 'https://ebd.cda.pl/800x450/623282912');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9832, 533, 11, CONCAT('Bittersweet Valentine'), NULL, 'https://ebd.cda.pl/800x450/62328178e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9833, 533, 12, CONCAT('What Moves Me'), NULL, 'https://ebd.cda.pl/800x450/623283230');
