INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (541, CONCAT('Fullmetal Alchemist: Brotherhood Specials'), CONCAT('Amazing secrets and startling facts are exposed for the first time in the Fullmetal Alchemist: Brotherhood OVA Collection, a new assortment of stories set in never-before-seen corners of the FMA universe. Join Ed and Al as they chase rumors of successful human transmutation into a web of shocking family drama and lies. Sneak a glance at hidden sides of Winry and Hawkeye', CHAR(39), 's personalities. Survive the frigid north with a young Izumi Curtis as she fights to gain a deeper understanding of alchemy. Explore the legendary friendship shared by Mustang and Hughes and watch them grow from military school rivals into hardened brothers transformed by the horrors of the Ishvalan War. You thought you knew the whole story. You thought all the tales were told. The Fullmetal Alchemist: Brotherhood OVA Collection offers proof: You were wrong. <br>
<br>(Source: FUNimation)'), 1, '2009-08-26', '2010-08-25', '', '15 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1493/91571.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (240, 541, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1342, 541, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1343, 541, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1344, 541, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1345, 541, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (604, 541, 77);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9973, 541, 1, CONCAT('The Blind Alchemist'), '2009-08-26', 'https://drive.google.com/file/d/1-WmxOBuHDmH-hdjk-FZXqnz9Srvk26be/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9974, 541, 2, CONCAT('Simple People'), '2009-12-23', 'https://drive.google.com/file/d/1cdKSHlM64-sBRSZgFvYswXLPp72juSa9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9975, 541, 3, CONCAT('The Tale of Teacher'), '2010-04-21', 'https://drive.google.com/file/d/1j26dBFhjIyUpoZn7Miru58BckCmw9Tkt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9976, 541, 4, CONCAT('Yet Another Man', CHAR(39), 's Battlefield'), '2010-08-25', 'https://drive.google.com/file/d/18ika3WcERbLGvdSYTUk8UsX_aLOKtKlT/preview');
