INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (582, CONCAT('Gatchaman Crowds: Insight'), CONCAT('One day, a huge UFO spins over Japan and crashes into a rural farmland outside Nagaoka, disrupting Tsubasa Misudachi', CHAR(39), 's ordinary life. As the Gatchaman, the legendary defenders of Tachikawa City, supervise the ordeal, a peaceful alien creature emerges from the spacecraft. In the ensuing chaos, Tsubasa is given a special high-tech notebook, or NOTE, from Gatchaman founder J.J. Robinson, signaling Tsubasa', CHAR(39), 's sudden recruitment into their group. Under the tutelage of fellow hero Hajime Ichinose, Tsubasa slowly begins to adjust to life as a defender of justice.  <br>
<br>Meanwhile, the CROWDS technology, which enables users to manifest their consciousness', CHAR(39), ' into a physical form, is spreading amongst the public, as well as being endorsed by Prime Minister Sugayama. However, a mysterious organization known as VAPE has gained notoriety by using unique red CROWDS to wreak havoc, shifting public opinion against the CROWDS technology. The Gatchaman, along with new recruit Tsubasa, must put a stop to their destructive activities before it', CHAR(39), 's too late.<br>
<br>[Written by MAL Rewrite]'), 1, '2015-07-05', '2015-09-27', 'Summer 2015', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/74978.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (410, 582, '"Insight"', ' by WHITE ASH', 'js-theme-songs', 'https://open.spotify.com/track/1jgVBRISCBt5ThlXBnypmN');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1441, 582, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1442, 582, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (649, 582, 98);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10706, 582, 1, CONCAT('contact point'), '2015-07-05', 'https://video.sibnet.ru/shell.php?videoid=1852283');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10707, 582, 2, CONCAT('penetration'), '2015-07-12', 'https://video.sibnet.ru/shell.php?videoid=1853760');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10708, 582, 3, CONCAT('launch'), '2015-07-19', 'https://video.sibnet.ru/shell.php?videoid=1855201');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10709, 582, 4, CONCAT('2:6:2'), '2015-07-26', 'https://video.sibnet.ru/shell.php?videoid=1864882');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10710, 582, 5, CONCAT('halo effect'), '2015-08-02', 'https://video.sibnet.ru/shell.php?videoid=1974597');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10711, 582, 6, CONCAT('engagement'), '2015-08-09', 'https://video.sibnet.ru/shell.php?videoid=2046839');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10712, 582, 7, CONCAT('outbound'), '2015-08-16', 'https://drive.google.com/file/d/14dlLtzsmfIyWCCGr_1wnjPb6E_D-pJ3e/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10713, 582, 8, CONCAT('cluster'), '2015-08-30', 'https://drive.google.com/file/d/1aWx2Gn19h1k5rJTDVz4awvuXa-g-KWgN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10714, 582, 9, CONCAT('opt-out'), '2015-09-06', 'https://drive.google.com/file/d/144HuQSDOBu1tYQil9i76OcjUkoABojMZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10715, 582, 10, CONCAT('seeds'), '2015-09-13', 'https://drive.google.com/file/d/1XAFxkNIADdpq5avrbvo82fDzhbeReUgv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10716, 582, 11, CONCAT('trade-off'), '2015-09-20', 'https://drive.google.com/file/d/1M65OC5o1nupvHiUg-0CaHl9YvkrAfWEy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10717, 582, 12, CONCAT('insight'), '2015-09-27', 'https://drive.google.com/file/d/1KFJqf3mPrc6WiW7SjHhjffNIkI3oJ6Yn/preview');
