INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (583, CONCAT('Gate: Jieitai Kanochi nite, Kaku Tatakaeri'), CONCAT('Off-duty Japan Self-Defense Forces (JSDF) officer and otaku Youji Itami is on his way to attend a doujin convention in Ginza, Tokyo when a mysterious portal in the shape of a large gate suddenly appears. From this gate, supernatural creatures and warriors clad in medieval armor emerge, charging through the city, killing and destroying everything in their path. With swift actions, Youji saves as many lives as he can while the rest of the JSDF direct their efforts toward stopping the invasion.<br>
<br>Three months after the attack, Youji has been tasked with leading a special recon team, as part of a JSDF task force, that will be sent to the world beyond the gate—now being referred to as the "Special Region." They must travel into this unknown world in order to learn more about what they are dealing with and attempt to befriend the locals in hopes of creating peaceful ties with the ruling empire. But if they fail, they face the consequence of participating in a devastating war that will engulf both sides of the gate.<br>
<br>[Written by MAL Rewrite]'), 1, '2015-07-04', '2015-09-19', 'Summer 2015', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/76222.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1443, 583, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1444, 583, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1445, 583, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (650, 583, 6);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (601, 583, 20);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (602, 583, 25);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10718, 583, 1, CONCAT('The Self-Defense Force Goes to Another World'), '2015-07-04', 'https://drive.google.com/file/d/1vedySbFmFaRD6S4DU02PrE5hsblfP4JQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10719, 583, 2, CONCAT('The Two Armies'), '2015-07-11', 'https://drive.google.com/file/d/11OEFzziKPens0h39uPsD4Jvfrb2Jikm-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10720, 583, 3, CONCAT('Fire Dragon'), '2015-07-18', 'https://drive.google.com/file/d/1QKApVtwgKXsiEIW48nUwtPgJh9uIbWkj/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10721, 583, 4, CONCAT('To Unknown Lands'), '2015-07-25', 'https://drive.google.com/file/d/1Uws2pb5C2GGn3WVmm70uK-BwjlYrekYC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10722, 583, 5, CONCAT('The Battle of Italica'), '2015-08-01', 'https://drive.google.com/file/d/1kSb33l3ir8Dkm2R5so14qwBgrTrIUcf-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10723, 583, 6, CONCAT('Ride of the Valkyries'), '2015-08-08', 'https://drive.google.com/file/d/1j_1_EZhYb7N1Baz9VrErFTRS-L-rfN1F/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10724, 583, 7, CONCAT('The Princess', CHAR(39), 's Decision'), '2015-08-15', 'https://drive.google.com/file/d/1mwFis4nXzoOphZidkNq06PEnBsaVxeVy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10725, 583, 8, CONCAT('Japan, Beyond the Gate'), '2015-08-22', 'https://drive.google.com/file/d/1NH5-dgjyjUaW0k_kMvOzvRmVTXUnuVYK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10726, 583, 9, CONCAT('The Hakone Mountain Night Battle'), '2015-08-29', 'https://drive.google.com/file/d/1C3VN39YdOSsDSr0gjPPDLgT1Ss_sJ1tp/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10727, 583, 10, CONCAT('Despair and Hope'), '2015-09-05', 'https://drive.google.com/file/d/1rSYCoxsBrMFBU-1GI6MAUCL2T_ej_EMc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10728, 583, 11, CONCAT('Visitors'), '2015-09-12', 'https://drive.google.com/file/d/1heZflBtFnIoLW2i_pTYmnqfelhjvMviX/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10729, 583, 12, CONCAT('What Would Itami Do?'), '2015-09-19', 'https://drive.google.com/file/d/1q1xlOyyys_2P2cLn9Wob5Jp3_Eoo6M55/preview');
