INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (584, CONCAT('gdMen'), CONCAT('In the series, Light and Yomi are spending their daily lives happily playing video games. One night when everyone else is asleep, Light receives an invitation from Alpha, a messenger for someone named King. Light and Yomi are then sucked into another world, where they must undertake a quest to rescue Princess Melody from the demon lord. Light thinks this must be his destiny, while Yomi thinks it', CHAR(39), 's kind of annoying. They form a party with Alpha to start their quest. Alpha as it turns out is an AI robot, and he has a program that allows them to raise their levels while slowly continuing their adventure.<br>
<br>(Source: ANN)'), 1, '2018-01-09', '2018-03-27', 'Winter 2018', '8 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/88981.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (412, 584, '"Mousou Teikoku Chikuouki (妄想帝国蓄音機)"', ' by Eri Kitamura', 'js-theme-songs', '')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1446, 584, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1447, 584, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (651, 584, 148);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10730, 584, 1, CONCAT(' Level 01: Reborn in a Game World!?'), NULL, 'https://dood.so/e/eqp2kd20bmrt');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10731, 584, 2, CONCAT('Level 02: What', CHAR(39), 's the Princess Like!?'), NULL, 'https://dood.so/e/37qhzn65spea');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10732, 584, 3, CONCAT('Level 03: The Job Assignment Chamber'), NULL, 'https://streamtape.com/e/AkQ1bOyl6dSXlja/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10733, 584, 4, CONCAT('Level 04: Wait for Us! Holy Jam! (Part 1)'), NULL, 'https://streamtape.com/e/wlZlmz32B1HJzxb/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10734, 584, 5, CONCAT('Level 05: Wait for Us! Holy Jam! (Part 2)'), NULL, 'https://streamtape.com/e/6q0AZ8gjGZF93q4/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10735, 584, 6, CONCAT('Level 06: Weapon Evolution!? Fantasy Sword'), NULL, 'https://streamtape.com/e/XyklbzjrVXs0WP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10736, 584, 7, CONCAT('Level 07: Competition! The Hottie Audition'), NULL, 'https://streamtape.com/e/Le2QWV1GzOFRLvp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10737, 584, 8, CONCAT('In Pursuit of the "Straht', CHAR(39), 'ehgee Gyde"'), NULL, 'https://streamtape.com/e/J3gx1XOyGphjxxr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10738, 584, 9, CONCAT('Level 09: Welcome to Dream Island!'), NULL, 'https://streamtape.com/e/QwgLwGrqVxC0Pr8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10739, 584, 10, CONCAT('The Pre-Eminent Moment: The Dark Lord', CHAR(39), 's Castle'), NULL, 'https://streamtape.com/e/gq8yrlvVVjFqwLl/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10740, 584, 11, CONCAT('Level 11: The Demon Lord', CHAR(39), 's Castle Is Like, Right There'), NULL, 'https://streamtape.com/e/wyX1gVOoVpiJ118/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10741, 584, 12, CONCAT('Level 12: Until We Meet Again'), NULL, 'https://streamtape.com/e/DeYl1daX89cDqV/');
