INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (585, CONCAT('Gegege no Kitarou (2018)'), CONCAT('Nearly twenty years into the 21st century, people have forgotten the existence of youkai. When a number of unexplainable phenomena plague adults of the human world with confusion and chaos, thirteen-year-old Mana writes a letter to the Youkai Post in search of answers, only to be greeted by Gegege no Kitarou...<br>
<br>(Source: Crunchyroll)'), 1, '2018-04-01', '2020-03-29', 'Spring 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1273/93610.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (413, 585, '"Gegege no Kitarou (ゲゲゲの鬼太郎)"', ' by Kiyoshi Hikawa', 'js-theme-songs', 'https://open.spotify.com/track/2YhDpZ2jehDKUNFSN69oOM')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (261, 585, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1448, 585, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1449, 585, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1450, 585, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (652, 585, 1);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10742, 585, 1, CONCAT('The Day Yokai Awoke'), NULL, 'https://streamtape.com/e/JvbZMY3VjYsjqoV/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10743, 585, 2, CONCAT('TERROR! MIAGE-NYUDO'), NULL, 'https://hqq.tv/e/NTVTbGVDL1dIMHIrYWdJNzBiK1IyZz09');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10744, 585, 3, CONCAT('Tantanbo', CHAR(39), 's Yokai Castle'), '2018-04-15', 'https://tune.pk/video/7735615');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10745, 585, 4, CONCAT('The Strange, Forbidden Forest'), '2018-04-22', 'https://tune.pk/video/7742959');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10746, 585, 5, CONCAT('The Disaster of the Electric Yokai'), '2018-04-29', 'https://hqq.tv/e/ajFQZ3FRZm9YRHhCS3l4STErWHZndz09');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10747, 585, 6, CONCAT('The Misfortune of the Sunekosuri'), '2018-05-06', 'https://tune.pk/video/7784740');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10748, 585, 7, CONCAT('GHOST TRAIN'), NULL, 'https://tune.pk/video/7784787');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10749, 585, 8, CONCAT('MENACE! KAGAMI JIJII', CHAR(39), 'S PLOT'), NULL, 'https://tune.pk/video/7804067');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10750, 585, 9, CONCAT('THE KAPPAS', CHAR(39), ' WORK REFORM'), NULL, 'https://rapidvideo.com/e/FRXK1R821Z');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10751, 585, 10, CONCAT('VANISHING! THE SEVEN SCHOOL MYSTERIES'), NULL, 'https://tune.pk/video/7852676');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10752, 585, 11, CONCAT('CONQUER JAPAN! THE 808 TANUKI ARMY'), NULL, 'https://embed.tune.pk/play/7889583');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10753, 585, 12, CONCAT('CAPITAL ANNIHILATED! THE TERRIFYING YOKAI BEAST'), NULL, 'https://rapidvideo.com/e/FXXQ27OJI1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10754, 585, 13, CONCAT('DIAMONDS OF GREED! WANYUDO', CHAR(39), 'S TRAP'), NULL, 'https://rapidvideo.com/e/FXXPZ9EONC');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10755, 585, 14, CONCAT('MAKURA-GAESHI AND THE FANTASTIC DREAM'), NULL, 'https://rapidvideo.com/e/FXXQ0YVX4U');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10756, 585, 15, CONCAT('ZUNBERA SPIRITPLASTY'), NULL, 'https://rapidvideo.com/e/FXYOJCCWJK');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10757, 585, 16, CONCAT('THE MYSTERY OF THE TIDE! UMIZATO'), NULL, 'https://tune.pk/video/7942250');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10758, 585, 17, CONCAT('KANI-BOZU AND THE ANCIENT MYSTERY'), NULL, 'https://tune.pk/video/7942251');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10759, 585, 18, CONCAT('KAWAUSO', CHAR(39), 'S LIE'), NULL, 'https://tune.pk/video/7942252');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10760, 585, 19, CONCAT('YOKAI RESURRECTION?! THE GHOST SCHOOL'), NULL, 'https://cloudvideo.tv/embed-i3mtjwma88ie.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10761, 585, 20, CONCAT('MEMORIES OF THE YOKA'), NULL, 'https://cloudvideo.tv/embed-iwe4jkqvkb51.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10762, 585, 21, CONCAT('FLAME ON! THE SOLITUDE OF THE TAKURO-BI'), NULL, 'https://cloudvideo.tv/embed-s9idjeg2imka.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10763, 585, 22, CONCAT('BERSERK!! THE TERRIFYING YOKAI, GYUKI'), NULL, 'https://cloudvideo.tv/embed-0mbqo2msxzt8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10764, 585, 23, CONCAT('THE YOKAI APARTMENT SECRET STORY'), NULL, 'https://streamtape.com/e/A6arJVmaeOcX7jp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10765, 585, 24, CONCAT('RAT MAN', CHAR(39), 'S DISAPPEARANCE?! SEKIYO', CHAR(39), 'S TRAP'), NULL, 'https://cloudvideo.tv/embed-i2nghsblo8sr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10766, 585, 25, CONCAT('KUBIRE-ONI', CHAR(39), 'S CURSE'), NULL, 'https://streamtape.com/e/m3j08A3GxmfXvw/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10767, 585, 26, CONCAT('INFATUATION THE ALLURING GAHI'), NULL, 'https://streamtape.com/e/eYGdDZQR20HYDPj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10768, 585, 27, CONCAT('INVASION! THE BACKBEARD ARMY'), NULL, 'https://streamtape.com/e/DPz0ryeBwKF6Dj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10769, 585, 28, CONCAT('THE GREAT YOKAI WAR'), NULL, 'https://drive.google.com/file/d/13TG-SH-y-2zKdocBmbFzaou_ItgHsFl4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10770, 585, 29, CONCAT('THE MAD FRANKENSTEIN'), NULL, 'https://streamtape.com/e/LDmDergMpas4vg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10771, 585, 30, CONCAT('THE VAMPIRE', CHAR(39), 'S HALLOWEEN PARTY'), NULL, 'https://streamtape.com/e/Jqx31mLqV3SjvYj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10772, 585, 31, CONCAT('AZUKI-ARAI, AZUKI-HAKARI, AZUKI-BABAA'), NULL, 'https://streamtape.com/e/3r1K9ej0rDFdvor/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10773, 585, 32, CONCAT('DEMON BELIAL THE HUNDRED-YEAR GRUDGE'), NULL, 'https://streamtape.com/e/8B8D1dZwyaCowlw/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10774, 585, 33, CONCAT('THE FOX', CHAR(39), 'S WEDDING AND HAKUSANBO'), NULL, 'https://streamtape.com/e/pVOQwR6vW2urmKM/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10775, 585, 34, CONCAT('EMPEROR BACKBEARD'), NULL, 'https://streamtape.com/e/34gpPypq3lTdvea/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10776, 585, 35, CONCAT('THE WITCHES OF DESTINY'), NULL, 'https://streamtape.com/e/kwxj1l4rxLtOdq6/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10777, 585, 36, CONCAT('THE TRANSFORM ALL JAPANESE YOKAI PROJECT'), NULL, 'https://streamtape.com/e/kvQP9bDlwYCOGlB/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10778, 585, 37, CONCAT('SHOWDOWN!! BACKBEARD'), NULL, 'https://streamtape.com/e/0rYwbOOdpAsb4XL/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10779, 585, 38, CONCAT('NEW YEAR', CHAR(39), 'S MAN-EATING FABLE KASHA'), NULL, 'https://streamtape.com/e/RAe0GAkwgvidw2j/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10780, 585, 39, CONCAT('YUKI-ONNA PURE WHITE LOVE REPORT'), NULL, 'https://streamtape.com/e/AldDkerGARHwAg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10781, 585, 40, CONCAT('THE FINAL BALLAD SARA-KOZO'), NULL, 'https://streamtape.com/e/0pqemwV9RKHbrA3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10782, 585, 41, CONCAT('ENIGMA! THE BAKE-ZORI REBELLION'), NULL, 'https://streamtape.com/e/232vD0kxDacVqr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10783, 585, 42, CONCAT('MOMON-JII', CHAR(39), 'S SCHEME THE GREAT YOKAI TRIAL'), NULL, 'https://www.mp4upload.com/embed-my3bmfa36yhn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10784, 585, 43, CONCAT('ETERNAL LIFE ODORO-ODORO'), NULL, 'https://streamtape.com/e/apAGLoP0GzTlQD/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10785, 585, 44, CONCAT('MASQUERADE NOPPERABO'), NULL, 'https://streamtape.com/e/WXMm77GPkrFbjoX/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10786, 585, 45, CONCAT('THE TRUTH LIES IN THE THICKET OF THE MANNEN-DAKE'), NULL, 'https://streamtape.com/e/XBGbPGOyV9CDRXZ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10787, 585, 46, CONCAT('THE CURSED DOLL FESTIVAL MAYUGE'), NULL, 'https://streamtape.com/e/79KalaZxdViA3qO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10788, 585, 47, CONCAT('THE BABY-STEALING UBUME'), NULL, 'https://streamtape.com/e/96W94daj97fa49x/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10789, 585, 48, CONCAT('THE VOID OF DESPAIR AND DARKNESS'), NULL, 'https://streamtape.com/e/W6AgKY36QxcblJJ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10790, 585, 49, CONCAT('NANASHI AND MANA'), NULL, 'https://streamtape.com/e/bk19yDz3RZfPMw3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10791, 585, 50, CONCAT('MESSENGER FROM THE UNDERWORLD NUE'), NULL, 'https://streamtape.com/e/O7B9rzrLPzUZJ76/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10792, 585, 51, CONCAT('ENMA-DAIO', CHAR(39), 'S SECRET BARGAIN'), NULL, 'https://streamtape.com/e/J9jyqzj7VqHjXXj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10793, 585, 52, CONCAT('RUNAWAY GIRL! THE FOREST OF THE KINOKO'), NULL, 'https://streamtape.com/e/4wgKklkJPqFKlDo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10794, 585, 53, CONCAT('NARCISSISM OVERLOAD! NUKE-KUBI', CHAR(39), 'S CLOSE CALL'), NULL, 'https://streamtape.com/e/3DjmL04Rv9sdw9o/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10795, 585, 54, CONCAT('DOROTABO, LIFE AND EARTH'), NULL, 'https://streamtape.com/e/lAZ3QbA92YT7LvB/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10796, 585, 55, CONCAT('HIHI', CHAR(39), 'S HARASSMENT HELL'), NULL, 'https://streamtape.com/e/8Or8akw3K4c6gM/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10797, 585, 56, CONCAT('THE BEWITCHING MELODY ELITE THE VAMPIRE'), NULL, 'https://streamtape.com/e/01mZqD0V1kCbJgK/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10798, 585, 57, CONCAT('THE BLOODY NOBLE LA SIENE'), NULL, 'https://streamtape.com/e/APggDjb9mvuwqe/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10799, 585, 58, CONCAT('THE HAN-GYOJIN', CHAR(39), 'S STRANGE KAMABOKO TALE'), NULL, 'https://streamtape.com/e/8VjM0z16ROtGgR/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10800, 585, 59, CONCAT('PROMISE TO THE FEMALE YOKAI USHIROGAMI'), NULL, 'https://streamtape.com/e/k08bqe4mqJSOlkP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10801, 585, 60, CONCAT('PITCH-BLACK COLDNESS THE YOKAI BURU-BURU'), NULL, 'https://streamtape.com/e/oGMRXO8VbacJkoo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10802, 585, 61, CONCAT('TOFU-KOZO', CHAR(39), 'S MOLD PANDEMIC'), NULL, 'https://streamtape.com/e/3G7zaRMaLASdQXq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10803, 585, 62, CONCAT('THE FOUR GENERALS OF THE UNDERWORLD KUROBOZU', CHAR(39), 'S TRAP'), NULL, 'https://streamtape.com/e/R99ZxopGlRfJxa/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10804, 585, 63, CONCAT('THE STAR FESTIVAL OF LOVE THE YOKAI FLOWER'), NULL, 'https://streamtape.com/e/3qYGgRPlp7HdPD3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10805, 585, 64, CONCAT('THE HEART', CHAR(39), 'S DARKNESS THE SUIKO REFLECTS'), NULL, 'https://streamtape.com/e/WZ9l3zqgYrFbjdk/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10806, 585, 65, CONCAT('Nation Founding?! Mabyo', CHAR(39), 's Great Tottori Empire'), NULL, 'https://streamtape.com/e/OoBZvK0gqqHZqxp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10807, 585, 66, CONCAT('THE SHINIGAMI AND SAKAIMINATO', CHAR(39), 'S HIDDEN VILLAGE'), NULL, 'https://streamtape.com/e/6oXdyqoeOkFoXd/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10808, 585, 67, CONCAT('THE SOCIAL MEDIA ADDICT VERSUS THE JOMON MAN'), NULL, 'https://streamtape.com/e/LOy9Lpv1yGtawV/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10809, 585, 68, CONCAT('CAPITAL PUNISHMENT! EXILED TO THE UNDERWORLD'), NULL, 'https://streamtape.com/e/BAma7J81zkUyBml/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10810, 585, 69, CONCAT('GENERAL OF THE UNDERWORLD  THE KIDO, IBUKIMARU'), NULL, 'https://streamtape.com/e/LLkjO00llmS4B9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10811, 585, 70, CONCAT('SPIRIT AFFLICTION MYSTERIOUS FOOTPRINTS'), NULL, 'https://streamtape.com/e/drZV1XPvBXU0zq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10812, 585, 71, CONCAT('KARAKASA', CHAR(39), 'S UMBRELLA TROUBLES'), NULL, 'https://streamtape.com/e/OrA4MObl77UZPLQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10813, 585, 72, CONCAT('IYAMI THE YOKAI', CHAR(39), 'S GREAT LOVE PROJECT'), NULL, 'https://streamtape.com/e/Dl6ZqXLqKYFkze3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10814, 585, 73, CONCAT('THE YAMATA-NO-OROCHI OF GREED'), NULL, 'https://streamtape.com/e/k3k4zRz9XBcO2WX/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10815, 585, 74, CONCAT('The Fall of the Underworld?! Tamamo-no-Mae', CHAR(39), 's Trap'), NULL, 'https://streamtape.com/e/7XxAJRvy4WFAlWW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10816, 585, 75, CONCAT('KYUBI NO KITSUNE'), NULL, 'https://streamtape.com/e/lD0kv4aWRKU7kOz/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10817, 585, 76, CONCAT('NURARIHYON', CHAR(39), 'S AMBITION'), NULL, 'https://streamtape.com/e/xmoQkDbkPGUk3d0/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10818, 585, 77, CONCAT('VANISHING HUMANS! NEKO-SENNIN', CHAR(39), 'S REVENGE'), NULL, 'https://streamtape.com/e/BeY1xwAYq6Tyem2/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10819, 585, 78, CONCAT('THE MORYO OF MUKURO VILLAGE'), NULL, 'https://streamtape.com/e/aPoezy0ADJHx4br/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10820, 585, 79, CONCAT('KOMORI-NEKO', CHAR(39), 'S HALLOWEEN PANDEMONIUM'), NULL, 'https://streamtape.com/e/rAyDBZyWwOtbLAr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10821, 585, 80, CONCAT('ONMORAKI', CHAR(39), 'S TRAP'), NULL, 'https://streamtape.com/e/bvQv2bkb1xhPwwO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10822, 585, 81, CONCAT('HOT BLOODED MANGA ARTIST THE YOKAI HIDERIGAMI'), NULL, 'https://streamtape.com/e/4yKBwj22wBfKbgQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10823, 585, 82, CONCAT('GERIATRIC NUPPEPPO'), NULL, 'https://streamtape.com/e/laKbovk9rgu7gqo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10824, 585, 83, CONCAT('CHAIN OF HATRED THE YOKAI HOKO'), NULL, 'https://streamtape.com/e/lW3WAb9YRdC77vd/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10825, 585, 84, CONCAT('CHIN-SAN, THE FOREIGN WORKER'), NULL, 'https://streamtape.com/e/LOMgJALDPPiRGjy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10826, 585, 85, CONCAT('THE GIANT, DAIDARABOTCHI'), NULL, 'https://streamtape.com/e/y2oM910j6mh1Mqy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10827, 585, 86, CONCAT('BLOODY CHRISTMAS'), NULL, 'https://streamtape.com/e/23ybWlkx90tWBW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10828, 585, 87, CONCAT('THE BINBOGAMI AND THE ZASHIKI-WARASHI'), NULL, 'https://streamtape.com/e/rlm0BAAL1JSeBb/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10829, 585, 88, CONCAT('ROLLO CLOTH', CHAR(39), 'S ROMANCE'), NULL, 'https://streamtape.com/e/bkpMG7RrJOHRXZ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10830, 585, 89, CONCAT('THE CURSE OF TE-NO-ME'), NULL, 'https://streamtape.com/e/69yJLB8z1VI9Dxr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10831, 585, 90, CONCAT('IDOL LEGEND SAZAE-ONI'), NULL, 'https://streamtape.com/e/01AJq4zZ4DCbOb6/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10832, 585, 91, CONCAT('THE MISTY NIGHT OF ANGKOR WAT'), NULL, 'https://streamtape.com/e/a7baA3wmB2SxjKj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10833, 585, 92, CONCAT('THE WRITER IS AMA-NO-JAKU'), NULL, 'https://streamtape.com/e/K0qo2YYDJvI0G8X/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10834, 585, 93, CONCAT('The Phantom Train'), '2020-02-16', 'https://streamtape.com/e/JooBOXMz3Lijdl3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10835, 585, 94, CONCAT('The Lazy Fujimi Hot Springs Bus Trip'), '2020-02-23', 'https://streamtape.com/e/rBkxqbYoO8ig9a/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10836, 585, 95, CONCAT('THE GREAT YOKAI ALLIANCE'), NULL, 'https://streamtape.com/e/DPOQg3ae9khkpv3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10837, 585, 96, CONCAT('THE SECOND GREAT YOKAI WAR'), NULL, 'https://streamtape.com/e/4wvjQw493RhKPYx/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10838, 585, 97, CONCAT('THE WORLD YOU SEE ISN', CHAR(39), 'T ALL THERE IS'), NULL, 'https://streamtape.com/e/K7gx33MzbXUa8K/');
