INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (600, CONCAT('Giant Robo the Animation: Chikyuu ga Seishi Suru Hi'), CONCAT('In a future to come humanity enjoys a new age of prosperity thanks to Dr. Shizuma', CHAR(39), 's invention of a revolutionary renewable energy source: the Shizuma Drive. But this peace is threatened by Big Fire, a cabal seeking world domination. Against Big Fire the International Police Organisation dispatches a collection of superpowered warriors and martial artists, together with Daisaku Kusama, inheritor and master of Earth', CHAR(39), 's most powerful robot, Giant Robo. <br>
<br>By capturing an abnormal Shizuma Drive which is essential to Big Fire', CHAR(39), 's plans the IPO ignites a desperate conflict between the two groups. The coming battle will test Daisaku', CHAR(39), 's resolve to the utmost, reveal the ghastly truth behind the creation of the Shizuma Drive, and bring human civilization to its knees!<br>
<br>Giant Robo is a character-driven adventure in a retro-futuristic setting, drawing on influences from opera, kung-fu cinema, wuxia stories and classic mecha anime. It incorporates characters from the works of the manga author Mitsuteru Yokoyama but it is designed to be a stand-alone story.'), 1, '1992-07-23', '1998-01-25', '', '49 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/27657.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1480, 600, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1481, 600, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (667, 600, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11019, 600, 1, CONCAT('The Black Attache Case'), '1992-07-22', 'https://embed.tune.pk/play/7088710');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11020, 600, 2, CONCAT('The Tragedy of Bashtarle'), '1993-02-20', 'https://embed.tune.pk/play/7088733');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11021, 600, 3, CONCAT('The Electromagnetic Net Operation: The Fall At Shanghai...'), '1993-08-20', 'https://embed.tune.pk/play/7088738');
