INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (602, CONCAT('Gifuu Doudou!!: Kanetsugu to Keiji'), CONCAT('The Sengoku era gave birth to many historical legends. One of them is Naoe Kanetsugu, the brilliant military general of the Uesugi family. Together with Maeda Keiji, a legendary warrior on the battlefield, who become lifelong friends with each other, they carve out a piece of history in the most dangerous and volatile time in Japan', CHAR(39), 's history. The two men recall their beginnings and the journey they took to get to the accomplished position they now sit at.'), 1, '2013-07-03', '2013-12-18', 'Summer 2013', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/51427.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (264, 602, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (670, 602, 46);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (614, 602, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (615, 602, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (616, 602, 32);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11034, 602, 1, CONCAT('Kanetsugu and Keiji'), NULL, 'https://streamtape.com/e/eP6Z1GKrGZUYRLP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11035, 602, 2, CONCAT('Kanetsugu', CHAR(39), 's Righteousness'), NULL, 'https://streamtape.com/e/D9LDwxdzJ6sDPl/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11036, 602, 3, CONCAT('Keiji', CHAR(39), 's Righteousness'), NULL, 'https://streamtape.com/e/Gv3r27D7VgF1p7o/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11037, 602, 4, CONCAT('Arrival in Sado'), NULL, 'https://streamtape.com/e/z16G3od2GPFY3BP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11038, 602, 5, CONCAT('Attack on Sado'), NULL, 'https://streamtape.com/e/g0369raP0eFBP3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11039, 602, 6, CONCAT('Uesugi', CHAR(39), 's Righteousness'), NULL, 'https://streamtape.com/e/pYmPVpPLrKsre40/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11040, 602, 7, CONCAT('The Truth Spoken to the Moon'), NULL, 'https://streamtape.com/e/zM9zYJOZzDuobA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11041, 602, 8, CONCAT('The Wind of the Men of War'), NULL, 'https://streamtape.com/e/28vLgRjXogiAOp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11042, 602, 9, CONCAT('The Eccentric, Yoroku'), NULL, 'https://streamtape.com/e/ea323RV1rdFYGGj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11043, 602, 10, CONCAT('Usugumo', CHAR(39), 's Eccentricity'), NULL, 'https://www.mp4upload.com/embed-tbbk8hffxrgy.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11044, 602, 11, CONCAT('Audience with the Ruler'), NULL, 'https://www.mp4upload.com/embed-sma22l5lp7vp.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11045, 602, 12, CONCAT('Follow Your Heart...'), NULL, 'https://streamtape.com/e/3JVzqg7V36udd3X/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11046, 602, 13, CONCAT('The Man of War and the Strategist'), NULL, 'https://www.mp4upload.com/embed-9gppqfe0x7il.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11047, 602, 14, CONCAT('Drinks and Conversations of Men'), NULL, 'https://streamtape.com/e/VXodl7zBgWTKB63/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11048, 602, 15, CONCAT('The Virtue of Otani Yoshitsugu'), NULL, 'https://streamtape.com/e/WoaBoVAbbGHb7Dr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11049, 602, 16, CONCAT('The Flute General'), NULL, 'https://streamtape.com/e/dkgpXJK0mySGy7/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11050, 602, 17, CONCAT('Ii the Red Demon'), NULL, 'https://streamtape.com/e/2BDp2QPgb1SZwd7/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11051, 602, 18, CONCAT('The Death Robe of Date'), NULL, 'https://streamtape.com/e/8ODpwe6mP8UJo3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11052, 602, 19, CONCAT('The Ninjas Take Action'), NULL, 'https://streamtape.com/e/PjmJJ36yWvC0ZGg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11053, 602, 20, CONCAT('Demon'), NULL, 'https://streamtape.com/e/jl70Raz1BJczlGp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11054, 602, 21, CONCAT('Downfall and Tethers'), NULL, 'https://streamtape.com/e/VP18pmdAaWFKmdP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11055, 602, 22, CONCAT('The Whereabouts of the Bodhisattva Statue'), NULL, 'https://streamtape.com/e/GpW0Le9x7AfdW4/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11056, 602, 23, CONCAT('The Warrior', CHAR(39), 's Place of Death'), NULL, 'https://www.mp4upload.com/embed-omvfcrxj4f5f.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11057, 602, 24, CONCAT('To Mount Koya We Go!'), NULL, 'https://streamtape.com/e/MyYZ80orwOCmWj9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11058, 602, 25, CONCAT('The Endless Story Told of Men'), NULL, 'https://streamtape.com/e/eYvrKLZL12T2P6/');
