INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (627, CONCAT('Gochuumon wa Usagi Desu ka?'), CONCAT('Kokoa Hoto is a positive and energetic girl who becomes friends with anyone in just three seconds. After moving in with the Kafuu family in order to attend high school away from home, she immediately befriends the shy and precocious granddaughter of Rabbit House cafe', CHAR(39), 's founder, Chino Kafuu, who is often seen with the talking rabbit, Tippy, on her head.<br>
<br>After beginning to work as a waitress in return for room and board, Kokoa also befriends another part-timer, Rize Tedeza, who has unusual behavior and significant physical capabilities due to her military upbringing Chiya Ujimatsu, a waitress from a rival cafe who does everything at her own pace and Sharo Kirima, another waitress at a different cafe who has the air of a noblewoman despite being impoverished.<br>
<br>With fluffy silliness and caffeinated fun, Gochuumon wa Usagi Desu ka? is a heartwarming comedy about five young waitresses and their amusing adventures in the town they call home.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-04-10', '2014-06-26', 'Spring 2014', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/79600.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (448, 627, '"Daydream café"', ' by Petit Rabbit's (Ayane Sakura, Inori Minase, Risa Taneda, Satomi Sato, Maaya Uchida)', 'js-theme-songs', 'https://open.spotify.com/track/4lFGExZoEArB7jzulnWtfl')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (697, 627, 75);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (698, 627, 38);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (660, 627, 28);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (661, 627, 8);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (662, 627, 17);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11444, 627, 1, CONCAT('I Knew at First Glance That It Was No Ordinary Fluffball'), '2014-04-10', 'https://drive.google.com/file/d/1Eky-jiQ3lbDAMyG6cTo7QShvwkQ6f8Th/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11445, 627, 2, CONCAT('The Girl Who Loved Wheat and the Girl Loved by Azuki Beans.'), '2014-04-17', 'https://drive.google.com/file/d/1FRFv_Dp062bDn1kqrzsMpXiHg-XCfR1w/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11446, 627, 3, CONCAT('Do You Remember the Day You First Got Drunk? You Tried to Light a Campfire in Your Own Home, Didn', CHAR(39), 't You?'), '2014-04-24', 'https://drive.google.com/file/d/1kfqRPXsvbjJDr4d8NIW4i98Gi7--4UDO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11447, 627, 4, CONCAT('Your Lucky Items Are Vegetables, Crime, and Punishment.'), '2014-05-01', 'https://drive.google.com/file/d/1ITet9mpWUFw3m20qDjKO81dABO6M4Vod/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11448, 627, 5, CONCAT('Cocoa and Murderous Intent Without Malice'), '2014-05-08', 'https://drive.google.com/file/d/17Cys5_5pM5tFqEyVeRvQV1F06KyYUJMY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11449, 627, 6, CONCAT('A Story About Telling a Story'), '2014-05-15', 'https://drive.google.com/file/d/1-R0vxP4KvtZMhkunHiWkxWzeqThJnQR9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11450, 627, 7, CONCAT('Call Me Sister'), '2014-05-22', 'https://drive.google.com/file/d/1837ttXaCkgKQsGI7NYTVXTunvs8sWACB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11451, 627, 8, CONCAT('Wet with Pool Water, Wet with Rain, Wet with Tears'), '2014-05-29', 'https://drive.google.com/file/d/1EwCglXDqgw6PcYQM20HG-fSg-iRlicyF/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11452, 627, 9, CONCAT('Aoyama Slump Mountain'), '2014-06-05', 'https://drive.google.com/file/d/142q-u0BzJDKbuxV_sA-1nmJSn5Z5MHaY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11453, 627, 10, CONCAT('The Anti-Sister Battle Corps, Also Known As the Chimame Corps'), '2014-06-12', 'https://drive.google.com/file/d/17hznOouD3iXhlWl9--sMn-I-UYrZWr5U/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11454, 627, 11, CONCAT('The Girl Dons a Red Coat and Drives a Team of Rabbits Across the Christmas Eve Night Sky'), '2014-06-19', 'https://drive.google.com/file/d/1RtPMrhuEUVisthnaAE_jdKijOVRpaZ5_/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11455, 627, 12, CONCAT('For You, I Can Sleep Late'), '2014-06-26', 'https://drive.google.com/file/d/1kZ-8DwNHdKKQq2WcNeJW22NkTwpMG8kN/preview');
