INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (642, CONCAT('Grand Blue'), CONCAT('Iori Kitahara moves to the coastal town of Izu for his freshman year at its university, taking residence above Grand Blue, his uncle', CHAR(39), 's scuba diving shop. Iori has high hopes and dreams about having the ideal college experience, but when he enters the shop he is sucked into the alcoholic activities of the carefree members of the Diving Club who frequent the place. Persuaded by upperclassmen Shinji Tokita and Ryuujirou Kotobuki, Iori reluctantly joins their bizarre party. His cousin Chisa Kotegawa later walks in and catches him in the act, earning Iori her utter disdain.<br>
<br>Based on Kenji Inoue and Kimitake Yoshioka', CHAR(39), 's popular comedy manga, Grand Blue follows Iori', CHAR(39), 's misadventures with his eccentric new friends as he strives to realize his ideal college dream, while also learning how to scuba dive.<br>
<br>[Written by MAL Rewrite]'), 1, '2018-07-14', '2018-09-29', 'Summer 2018', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1302/94882.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (459, 642, '"Kono Yubi Tomare (コノユビトマレ)"', ' by JUNNA', 'js-theme-songs', 'https://open.spotify.com/track/47ltbGJTejvcljxYfzAlUZ')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (290, 642, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (714, 642, 122);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11664, 642, 1, CONCAT('Deep Blue'), '2018-07-14', 'https://drive.google.com/file/d/1Ct6S-YJYvYfyj8IElx2Q3R55F2738qO7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11665, 642, 2, CONCAT('Underwater'), '2018-07-21', 'https://drive.google.com/file/d/1o45EEd4nUDYsnEo_Oxo71Al0u_GQAsmo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11666, 642, 3, CONCAT('A New World'), '2018-07-28', 'https://drive.google.com/file/d/1GgaUbnpqC2d1__RMhnr0O6w7qeg3SyQT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11667, 642, 4, CONCAT('The Male Beauty Pageant'), '2018-08-04', 'https://drive.google.com/file/d/1fx-yJakTqfKZ3p1fw5ou5Mj-03mZJlZ2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11668, 642, 5, CONCAT('Too Late'), '2018-08-11', 'https://drive.google.com/file/d/11TSDSkf5KKPFOS6d4fQqrDTB6C6YPcNy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11669, 642, 6, CONCAT('First Buddy'), '2018-08-18', 'https://drive.google.com/file/d/1KG1yR3fpWGBX2y8hGjbapXScKmy1OLPj/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11670, 642, 7, CONCAT('Doubles'), '2018-08-25', 'https://drive.google.com/file/d/1KOnIgJkpClCNIj-oJtfckSyOOlUokinA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11671, 642, 8, CONCAT('Men', CHAR(39), 's Cocktails'), '2018-09-01', 'https://ebd.cda.pl/800x450/375466014');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11672, 642, 9, CONCAT('Truth or Dare'), '2018-09-08', 'https://drive.google.com/file/d/1t-9h8xVwl6OnkamWbzksflNXisDhQR9-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11673, 642, 10, CONCAT('Arrival in Okinawa'), '2018-09-15', 'https://drive.google.com/file/d/1hkA9nkHEJUhSqW_erztomQwuiLuvp0A5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11674, 642, 11, CONCAT('You Have the Wrong Idea'), '2018-09-22', 'https://drive.google.com/file/d/1MMXl7cMK8U7TfrP2NOkHjr3iYeweY3aq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11675, 642, 12, CONCAT('Otori'), '2018-09-29', 'https://drive.google.com/file/d/1bxaAbIuwVnoZCi7X9Ljvo7W2EqRHZ5vQ/preview');
