INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (651, CONCAT('Grenadier: Hohoemi no Senshi'), CONCAT('Rushuna is a blonde and very beautiful Senshi (gun expert) that travels through the world with one purpose. Which is to make the world a peaceful place by, instead of fighting with weapons, taking away the people', CHAR(39), 's will to fight by giving them a smile. Although she doesn', CHAR(39), 't want to fight, she is forced to, and shows amazing gun skills. In this journey she meets Yajirou, a mercenary that uses a sword to fight and joins her on her journey. <br>
<br>(Source: ANN)'), 1, '2004-10-14', '2005-01-13', 'Fall 2004', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1691/114822.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (296, 651, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1609, 651, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1610, 651, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1611, 651, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1612, 651, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (722, 651, 99);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11864, 651, 1, CONCAT('The Smiling Senshi'), '2004-10-15', 'https://www.mp4upload.com/embed-a316hs2uo16c.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11865, 651, 2, CONCAT('Rushuna under Attack'), '2004-10-22', 'https://www.mp4upload.com/embed-u4wy9mbmkeqi.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11866, 651, 3, CONCAT('Enlightened Evil'), '2004-10-29', 'https://www.mp4upload.com/embed-zeu4cd3ij2va.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11867, 651, 4, CONCAT('The Town that does not Smile'), '2004-11-05', 'https://www.mp4upload.com/embed-xx5lbkjyp0vt.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11868, 651, 5, CONCAT('Explosion! Kensousen, Kurenai Touka'), '2004-11-12', 'https://www.mp4upload.com/embed-qyo25e0tdu6i.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11869, 651, 6, CONCAT('Balloonist, Mikan', CHAR(39), 's Revenge'), '2004-11-19', 'https://www.mp4upload.com/embed-st008bbvz80e.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11870, 651, 7, CONCAT('Destination Tento'), '2004-11-26', 'https://www.mp4upload.com/embed-demz5l8y4lmt.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11871, 651, 8, CONCAT('An Enemy from the Past, Teppa Aizen'), '2004-12-03', 'https://www.mp4upload.com/embed-twf3owd1whtl.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11872, 651, 9, CONCAT('When the Wind Flowers dance'), '2004-12-10', 'https://www.mp4upload.com/embed-9rfosjatapkr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11873, 651, 10, CONCAT('Entering Tento'), '2004-12-17', 'https://www.mp4upload.com/embed-z3e0c7ve826j.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11874, 651, 11, CONCAT('Showdown With Tenshi'), '2005-01-07', 'https://www.mp4upload.com/embed-ffl3r1tpioq6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11875, 651, 12, CONCAT('Things Learned on the Road'), '2005-01-14', 'https://www.mp4upload.com/embed-qkpel3xkg5ux.html');
