INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (665, CONCAT('Gunslinger Girl'), CONCAT('In the heart of Italy, the Social Welfare Agency rescues young girls from hospital beds and gives them a second chance at life using the latest in cybernetic advancements. With their artificially enhanced bodies, the girls are brainwashed and trained as assassins to carry out the dirty work of the Italian Government. Despite all the modifications, they are still just children at heart, struggling for recognition from those they love, even knowing the love they feel is manufactured. This tragic tale unfolds as these girls grapple with their emotions in an agency that treats them as nothing but ruthless killers.<br>
<br>[Written by MAL Rewrite]'), 1, '2003-10-09', '2004-02-19', 'Fall 2003', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/3088.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1641, 665, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1642, 665, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (735, 665, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12114, 665, 1, CONCAT('Fratello (Siblings)'), NULL, 'https://video.sibnet.ru/shell.php?videoid=528137');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12115, 665, 2, CONCAT('Orione (Orion)'), NULL, 'https://myvi.ru/player/embed/html/o9WfneMlDGL5n2qrOAbvbxQKUUXRyJLM89RYeCZXBFpqlLF9lxvIuew2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12116, 665, 3, CONCAT('Ragazzo (Boy)'), NULL, 'https://myvi.ru/player/embed/html/oATApCiFNchjOXHvIugH0J3tDmYKImgpUuqha6J__fGoKNCEiunHdiQ2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12117, 665, 4, CONCAT('Bambola (Doll)'), NULL, 'https://myvi.ru/player/embed/html/otXR5KbSi6BKSoSB21jqHjGSN8jdBt7t9fjJuaikOpNxla9EaXGm-2g2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12118, 665, 5, CONCAT('Promessa (Promise)'), NULL, 'https://myvi.ru/player/embed/html/oEmjlAV2p0fEZuJvQ1va1DpADp_DGzMhbb664BE6QXX3pHb6Okrc5KQ2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12119, 665, 6, CONCAT('Gelato (Frozen)'), NULL, 'https://myvi.ru/player/embed/html/oHeU2iRJi9DMioHBPYnL3Hbc9-FI05o9v_svDxhvMXH29CnXO46lUmQ2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12120, 665, 7, CONCAT('Protezione (Protection)'), NULL, 'https://myvi.ru/player/embed/html/oH9oJcq0CYbZU7dzdbTlsFgWwoGaySMdn6nQuxP_bXlAVYIBzvoKPjg2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12121, 665, 8, CONCAT('Il Principe del regno della pasta (The Prince of the Kingdom of Pasta)'), NULL, 'https://myvi.ru/player/embed/html/ogoRGyjDt0OG3JCeREUav4WZUBNbwwhxzh-d88qnU6HTCgyMjruxMzA2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12122, 665, 9, CONCAT('Lycorsi Radiata Herb (Be Struck Off Herb)'), NULL, 'https://myvi.ru/player/embed/html/oCMMEn0QmXHAohT6rOWb9KgF-lAxXWjCi-xKjvAVCknnnNEAzFLCbRg2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12123, 665, 10, CONCAT('Amare (To Love)'), NULL, 'https://myvi.ru/player/embed/html/ozfNKxjw4cIT2eFgQb_Jq6iRJbzSnG71gYSwzsO7HDilf5c1RiDfFmg2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12124, 665, 11, CONCAT('Febbre Alta (High Fever)'), NULL, 'https://myvi.ru/player/embed/html/oiZP1Tm5iIOgB-09ScmJOjeWPn8p442KLEpiuvjZiYIURvQhFVJoxBQ2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12125, 665, 12, CONCAT('Simbiosi (Symbiosis)'), NULL, 'https://myvi.ru/player/embed/html/oJhic_1PLqRHFb1VRSgx4OT-2lVVw0GS_cVSplGRyMHKpkx8T91QmYA2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12126, 665, 13, CONCAT('Stellacadente (Falling Star)'), NULL, 'https://myvi.ru/player/embed/html/oFKdSNPnaLUZUUk0ALYVAad1J2yrFfTKa3nvCpvy9KHBHTfb18DXy9w2');
