INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (674, CONCAT('Gyakuten Sekai no Denchi Shoujo'), CONCAT('Japan, 2019, just before the dawn of a new era. Suddenly, a rift to another dimension appears in the sky, revealing an alternative world "Shinkoku Nippon," with the sky and the earth upside down. This parallel world keeps their former militarism, with its era being Eternal Showa. The military invades the real Japan with giant humanoid robots called "Garann" and their gas weapons "Genmu", rendering our modern weapons ineffective. "Shinkoku Nippon" instantly seizes the government and achieves de facto conquest of Japan. The new era, "Reiwa," has now arrived for Japan. <br>
<br>(Source: MAL News)'), 1, '2021-10-11', '2021-12-27', 'Fall 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1836/117774.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (477, 674, '"Fever Dreamer"', ' by Mia REGINA', 'js-theme-songs', 'https://open.spotify.com/track/6TBxW0YR9jTQtieh7bgwP3')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1660, 674, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1661, 674, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1662, 674, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (745, 674, 49);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12229, 674, 1, CONCAT('#01: I', CHAR(39), 'd Like to Turn the Tables With You (If Possible)!'), NULL, 'https://ebd.cda.pl/620x368/877502491');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12230, 674, 2, CONCAT('#02: I Want to Believe in You (Somehow)!'), NULL, 'https://ebd.cda.pl/620x368/88446000e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12231, 674, 3, CONCAT('#03: See That? A (Surprisingly) Stunning Comeback!'), NULL, 'https://ebd.cda.pl/620x368/89013905a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12232, 674, 4, CONCAT('#04: No Matter What, I', CHAR(39), 'll be an Idol (The Last in Japan)!'), NULL, 'https://ebd.cda.pl/620x368/8960244a9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12233, 674, 5, CONCAT('#05: I Mean, I', CHAR(39), 'm an Idol (No Matter What Anyone Says)!'), NULL, 'https://ebd.cda.pl/620x368/9021282ba');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12234, 674, 6, CONCAT('#06: The Akiba Apocalypse Revelation (That No One Asked For)!'), NULL, 'https://ebd.cda.pl/620x368/909528967');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12235, 674, 7, CONCAT('#07: (Come out!) The Best Way to Live as a Shut-In!'), NULL, 'https://ebd.cda.pl/620x368/91530064d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12236, 674, 8, CONCAT('#08: (Welcome!) The Best Way to Live as a Shut-In!'), NULL, 'https://ebd.cda.pl/620x368/922383318');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12237, 674, 9, CONCAT('#09: The (Hilarious) Akiba Apocalypse Revelation!'), NULL, 'https://ebd.cda.pl/620x368/927147903');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12238, 674, 10, CONCAT('#10: Look at That! Turning the Tables (of Treachery)!'), NULL, 'https://ebd.cda.pl/620x368/9427353b2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12239, 674, 11, CONCAT('#11: I Want to Believe in You (This Time)!'), NULL, 'https://ebd.cda.pl/620x368/942831048');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12240, 674, 12, CONCAT('#12: I Want to Turn the Tide With You (And Everyone Else)!'), NULL, 'https://ebd.cda.pl/620x368/948043586');
