INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (696, CONCAT('Hakuouki'), CONCAT('In 1864 Japan, a young woman named Chizuru Yukimura is searching for her missing father, Koudou, a doctor by trade whose work often takes him far from home. But with no word from him in months, Chizuru disguises herself as a man and heads to Kyoto in search of him. Attracting the attention of ronin, she tries to hide and ends up witnessing a horrifying sight: the ronin being brutally murdered by crazed white-haired men. In a startling turn of events, members of the Shinsengumi arrive to dispatch the creatures. But Chizuru', CHAR(39), 's safety doesn', CHAR(39), 't last long, as this group of men tie her up and take her back to their headquarters, unsure of whether to let her live or silence her permanently.<br>
<br>However, once she reveals the name of her father, the Shinsengumi decide to keep her safe, as they too have been searching for him. But Koudou is more connected to the Shinsengumi than they let on, and soon Chizuru finds herself embroiled in a conflict between the Shinsengumi and their enemies, as well as political tension in Kyoto.<br>
<br>[Written by MAL Rewrite]'), 1, '2010-04-04', '2010-06-20', 'Spring 2010', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/71800.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (492, 696, '"Izayoi Namida"', ' by Aika Yoshioka', 'js-theme-songs', 'https://open.spotify.com/track/4OKkuBY2AIk16qqIqvbUsu')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (317, 696, 5);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1706, 696, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1707, 696, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1708, 696, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (770, 696, 46);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (734, 696, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (735, 696, 32);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12621, 696, 1, CONCAT('Snowflake Capital'), '2010-04-04', 'https://video.sibnet.ru/shell.php?videoid=3916105-1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12622, 696, 2, CONCAT('Seeds of Discord'), '2010-04-11', 'https://video.sibnet.ru/shell.php?videoid=3916116-2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12623, 696, 3, CONCAT('Twilight Blossom'), '2010-04-18', 'https://video.sibnet.ru/shell.php?videoid=3916125-3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12624, 696, 4, CONCAT('Those Who Come From the Darkness'), '2010-04-25', 'https://video.sibnet.ru/shell.php?videoid=3916137-4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12625, 696, 5, CONCAT('Conflicting Swords'), '2010-05-02', 'https://video.sibnet.ru/shell.php?videoid=3916148-5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12626, 696, 6, CONCAT('The Demon', CHAR(39), 's Lifeline'), '2010-05-09', 'https://video.sibnet.ru/shell.php?videoid=3916161-6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12627, 696, 7, CONCAT('Fate of a Fetter'), '2010-05-16', 'https://video.sibnet.ru/shell.php?videoid=3916172-7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12628, 696, 8, CONCAT('Fleeting Dreams'), '2010-05-23', 'https://video.sibnet.ru/shell.php?videoid=3916182-8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12629, 696, 9, CONCAT('The Trails of Carnage'), '2010-05-30', 'https://video.sibnet.ru/shell.php?videoid=3916193-9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12630, 696, 10, CONCAT('Where the Bonds Lead'), '2010-06-06', 'https://video.sibnet.ru/shell.php?videoid=3916203-10');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12631, 696, 11, CONCAT('Fallen Ones'), '2010-06-13', 'https://video.sibnet.ru/shell.php?videoid=3916211-11');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12632, 696, 12, CONCAT('On Opposite Sides of Arms'), '2010-06-20', 'https://video.sibnet.ru/shell.php?videoid=3916242-12');
