INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (719, CONCAT('Hataage! Kemono Michi'), CONCAT('Professional wrestler Genzou Shibata sports the body of a mountain, but beneath his hulking appearance is a man with an extreme affection for animals. Facing off his opponents in the ring as the legendary "Animal Mask," Genzou wins the hearts of crowds everywhere with his iconic tiger persona.<br>
<br>During the bout for the title of World Champion against his greatest rival, the Macadamian Ogre, Genzou is suddenly summoned to a fantasy world by a princess. With her kingdom being threatened by a monster infestation, she pleads the wrestler for assistance—to which he answers by knocking her out with a German suplex! Escaping the castle and finding himself stranded in a mysterious land, Genzou decides to begin his career as a beast hunter to capture and befriend creatures far and wide. Joined by the wolf-girl Shigure, the dragon-girl Hanako, and the vampire Carmilla Vanstein, the professional wrestler pursues all kinds of dangerous requests for the sake of fulfilling his dream as a pet shop owner.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-10-02', '2019-12-18', 'Fall 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1736/103512.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (513, 719, '"Anegdot (アネクドット)"', ' by Momosu Momosu (ももすももす)', 'js-theme-songs', 'https://open.spotify.com/track/2f95dlsVs75NE7XpZGFjAv');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (329, 719, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1760, 719, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1761, 719, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (792, 719, 168);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12988, 719, 1, CONCAT('Wrestler x Summoning'), NULL, 'https://ebd.cda.pl/620x368/4015480e9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12989, 719, 2, CONCAT('Quest x Demon Beast Killer'), NULL, 'https://ebd.cda.pl/620x368/4018699b3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12990, 719, 3, CONCAT('Runaway Girl x Attacker'), NULL, 'https://ebd.cda.pl/620x368/40470613a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12991, 719, 4, CONCAT('Demon Beast x Part-Time Job'), NULL, 'https://drive.google.com/file/d/1ubw4KyUFl9YIVyrJkRzdjDogVIXz9D9_/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12992, 719, 5, CONCAT('Animal Mask x MAO'), NULL, 'https://ebd.cda.pl/620x368/4090420b2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12993, 719, 6, CONCAT('Loser x Master'), NULL, 'https://ebd.cda.pl/620x368/412345017');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12994, 719, 7, CONCAT('First Student x Pain in the Butt'), NULL, 'https://ebd.cda.pl/620x368/4154269cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12995, 719, 8, CONCAT('Animal x Event'), NULL, 'https://ebd.cda.pl/620x368/418450698');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12996, 719, 9, CONCAT('Princess x Panties'), NULL, 'https://ebd.cda.pl/620x368/42059832a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12997, 719, 10, CONCAT('Money x Bonds'), NULL, 'https://ebd.cda.pl/620x368/422517896');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12998, 719, 11, CONCAT('Pride x Loyalty'), NULL, 'https://ebd.cda.pl/620x368/426000297');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12999, 719, 12, CONCAT('Hero x Demon King'), NULL, 'https://ebd.cda.pl/620x368/429466115');
