INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (726, CONCAT('Hayate no Gotoku! Cuties'), CONCAT('Taking place after the events that occurred in Hayate no Gotoku! Can', CHAR(39), 't Take My Eyes off You. Hayate, Nagi and Maria return to their daily lives at the Sanzenin Mansion and the Violet Mansion.<br><br>(Source: Hayate no Gotoku! Wikia)'), 1, '2013-04-09', '2013-07-02', 'Spring 2013', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/48953.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (521, 726, '"Haru ULALA♥LOVE yo Koi!!! (春ULALA♥LOVEよ来い!!!)"', ' by Hinagiku Katsura (Shizuka Itou)', 'js-theme-songs', 'https://open.spotify.com/track/0OlkKuAZFswd0usVw1w389')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (334, 726, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1777, 726, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1778, 726, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (799, 726, 17);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (764, 726, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (765, 726, 21);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13109, 726, 1, CONCAT('Hayate Asayaki'), '2013-04-09', 'https://drive.google.com/file/d/0B3hUym4Bk3fpY1k1ZFdGdEN6Tlk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13110, 726, 2, CONCAT('Nagi Sanzenin'), '2013-04-16', 'https://drive.google.com/file/d/0B3hUym4Bk3fpODU4VG9wbS1XaVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13111, 726, 3, CONCAT('Athena Tennousu'), '2013-04-23', 'https://myvi.ru/player/embed/html/o-PSOjqNcb5V7wflmsS7sH8xHboXvcOLZN4jgusk_-Jw1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13112, 726, 4, CONCAT('Isumi Saginomiya and Sakuya Aizawa'), '2013-04-30', 'https://video.sibnet.ru/shell.php?videoid=1126834');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13113, 726, 5, CONCAT('Hinagiku Katsura'), '2013-05-07', 'https://drive.google.com/file/d/0B3hUym4Bk3fpc1ZsMzBfNXE2aVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13114, 726, 6, CONCAT('Izumi Segawa and the Other Two'), '2013-05-14', 'https://drive.google.com/file/d/0B3hUym4Bk3fpZTd5bm92X3lCanc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13115, 726, 7, CONCAT('Ruka Suirenji'), '2013-05-28', 'https://drive.google.com/file/d/0B3hUym4Bk3fpS1dpNjZpbGxzOE0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13116, 726, 8, CONCAT('Ayumu Nishizawa'), '2013-06-04', 'https://video.sibnet.ru/shell.php?videoid=1258120');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13117, 726, 9, CONCAT('Chiharu Harukaze and Kayura Tsurugino'), '2013-06-11', 'https://www.mp4upload.com/embed-yw9bzpj29k4r.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13118, 726, 10, CONCAT('Maria'), '2013-06-18', 'https://drive.google.com/file/d/0BxqGsfSsWAG_N0FLcTdsXy1hTGs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13119, 726, 11, CONCAT('Who', CHAR(39), 's Knocking on the Door?'), '2013-06-25', 'https://drive.google.com/file/d/0BxqGsfSsWAG_dnhBWHZ3bURpNGM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13120, 726, 12, CONCAT('I Will Love and Be Loved in My Life'), '2013-07-02', 'https://drive.google.com/file/d/0BxqGsfSsWAG_OHIzNVRGb3lJUWM/preview');
