INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (753, CONCAT('High School DxD Hero'), CONCAT('After rescuing his master, Rias Gremory, from the Dimensional Gap, Red Dragon Emperor and aspiring Harem King Issei Hyoudou can finally return to his high school activities alongside fellow members of the Occult Research Club: Yuuto Kiba, Asia Argento, Xenovia Quarta, and Irina Shidou. The group soon embarks on a school trip to Kyoto. <br>
<br>While peacefully visiting a temple thanks to Rias', CHAR(39), ' spell, an attacking group of local youkai breaks the calm atmosphere. Once the altercation ends, the club learns that the mythical nine-tailed fox that protected the city was abducted and that someone has framed them for the act. Issei and his friends will now have to fight to protect the city and save their school trip from a planned disaster!<br>
<br>In the meantime, Rias, who had to stay in Tokyo with Akeno Himejima and Koneko Toujou, grows increasingly restless to have left the perverted Issei alone with the other girls of the Occult Research Club. Beyond this vague anxiety, what is the exact nature of the feelings Rias has been struggling with for the past few months?<br>
<br>[Written by MAL Rewrite]'), 1, '2018-04-17', '2018-07-03', 'Spring 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1189/93528.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (542, 753, '"SWITCH"', ' by Minami', 'js-theme-songs', 'https://open.spotify.com/track/7eDyDKNZfTrf8lPf6m4ro6');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1844, 753, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1845, 753, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1846, 753, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1847, 753, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (830, 753, 58);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (813, 753, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (814, 753, 11);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (815, 753, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13563, 753, 1, CONCAT('That', CHAR(39), 's Right, Let', CHAR(39), 's go to Kyoto'), '2018-04-17', 'https://drive.google.com/file/d/19xLjO6oi5w00h2P8u71l9kDHcHYziZzs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13564, 753, 2, CONCAT('School Trip, an Abrupt Attack'), '2018-04-24', 'https://drive.google.com/file/d/14VawVf7cWFnLwGw3IZ6uRWCE9etP6w2h/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13565, 753, 3, CONCAT('The Party of Heroes'), '2018-05-01', 'https://drive.google.com/file/d/14myaXoBf3WOs41ANWBcCd9QTrxRbK260/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13566, 753, 4, CONCAT('Showdown! Gremory Family vs. Hero Faction in Kyoto'), '2018-05-08', 'https://drive.google.com/file/d/1ZAWDfIb_ET8H3-MRLo8TKVi974meERNC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13567, 753, 5, CONCAT('My Potential Released!'), '2018-05-15', 'https://ebd.cda.pl/620x368/2283726f1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13568, 753, 6, CONCAT('The School Trip Is in Pandemonium'), '2018-05-22', 'https://drive.google.com/file/d/1b7o9WZMoxUWWU6d5i5a9-T6eR9P7XolN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13569, 753, 7, CONCAT('We Are Preparing for the School Festival!'), '2018-05-29', 'https://drive.google.com/file/d/1_5aamMqCyz9Wl52GZUfk1GU6XdxSb5SM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13570, 753, 8, CONCAT('A Girl', CHAR(39), 's Heart is Complicated'), '2018-06-05', 'https://drive.google.com/file/d/1HaH-2rZytzjErP_nTl3ycMoMSRWT6aF8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13571, 753, 9, CONCAT('The Deciding Battle of the Strongest Youth, Begins!'), '2018-06-12', 'https://drive.google.com/file/d/19c3nokcax8_xYswn_G0XDbbnWqzNE5IV/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13572, 753, 10, CONCAT('As a Family Member of Rias Gremory'), '2018-06-19', 'https://drive.google.com/file/d/18ZLtdntaL2md5_6zKesFqJOTRfKq_vIN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13573, 753, 11, CONCAT('Max vs Max. Power ', CHAR(39), 'Man Versus Man', CHAR(39), ''), '2018-06-26', 'https://drive.google.com/file/d/11OhllFZOnqb-ufDx5TzzYUqXeiFfWH-A/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (13574, 753, 12, CONCAT('Maximum vs Power. Maximum ', CHAR(39), 'Lion Heart of the School Festival', CHAR(39), ''), '2018-07-03', 'https://drive.google.com/file/d/1IsxyEErFJq31sYuolYrH4h053o8vvnNb/preview');
