INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (820, CONCAT('Ichiban Ushiro no Daimaou Specials'), CONCAT('DVD/BD specials of Ichiban Ushiro no Daimaou.'), 1, '2010-06-25', '2010-11-25', '', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/80505.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2012, 820, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2013, 820, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2014, 820, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2015, 820, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (898, 820, 175);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (904, 820, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (905, 820, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14731, 820, 1, CONCAT('Another Extra Daimaou: Thump!? A Swimming Tournament with Girls Everywhere! There', CHAR(39), 's Also an Accident or Two!?'), '2010-06-25', 'https://drive.google.com/file/d/0ByNZKSOHmn2jYWpJUmlITG5HbkE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14732, 820, 2, CONCAT('Another Extra Daimaou: Junko', CHAR(39), 's Exciting Ninja Scroll!?'), '2010-07-23', 'https://drive.google.com/file/d/0ByNZKSOHmn2jUGJESzBOcVdzcXM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14733, 820, 3, CONCAT('Another Extra Daimaou: Keina', CHAR(39), 's Apron of Love!?'), '2010-08-25', 'https://drive.google.com/file/d/0ByNZKSOHmn2jZjNyaEtIUkc2ZkE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14734, 820, 4, CONCAT('Another Extra Daimaou: Disaster Survival!?'), '2010-09-22', 'https://drive.google.com/file/d/0ByNZKSOHmn2jN3hYMXZiOFV0SzA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14735, 820, 5, CONCAT('Another Extra Daimaou: Korone', CHAR(39), 's Report. Or Rather, Sai Akuto', CHAR(39), 's Uneventful, Daily Life.'), '2010-10-22', 'https://drive.google.com/file/d/0ByNZKSOHmn2jdzQ1aHZUb0VDSmc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14736, 820, 6, CONCAT('Another Extra Daimaou: The Student Council', CHAR(39), 's in Ecstasy!?'), '2010-11-25', 'https://drive.google.com/file/d/0ByNZKSOHmn2jYnVSUlhlMTRRc1E/preview');
