INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (828, CONCAT('IDOLiSH7: Third Beat!'), CONCAT('Nearing their first debut anniversary and with their popularity still on the rise, IDOLiSH7 set a date for a live tour to express their gratitude toward their fans. Meanwhile, the Black or White event draws closer—and as the previous year', CHAR(39), 's winners—the group must prepare to take on the challengers. Looking to solidify their reputation in the world of idols, IDOLiSH7 are determined to come out victorious and settle the score once and for all with their rival, TRIGGER.<br>
<br>While working around their packed schedules, IDOLiSH7, TRIGGER, and Re:vale meet powerful figures in the entertainment industry. In the midst of the hectic period, some members catch wind of a scandalous rumor regarding IDOLiSH7. As the members of IDOLiSH7 begin to worry about their image, their bonds are put to the test, all while a spiteful figure begins to carry out a certain plan behind the scenes.<br>
<br>[Written by MAL Rewrite]'), 1, '2021-07-04', '2021-09-26', 'Summer 2021', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1646/115723.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (590, 828, '"THE POLiCY"', ' by IDOLiSH7 [Riku Nanase (CV: Kensho Ono), Iori Izumi (CV: Toshiki Masuda), Yamato Nikaidou (CV: Yuusuke Shirai), Mitsuki Izumi (CV: Tsubasa Yonaga, Tamaki Yotsuba (CV: KENN), Sougo Ousaka (CV: Atsushi Abe), Nagi Rokuya (CV: Takuya Eguchi)]', 'js-theme-songs', 'https://open.spotify.com/track/0XFawxpWbJpymBtIOVhhou')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (908, 828, 45);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (919, 828, 36);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (920, 828, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14846, 828, 1, CONCAT('Clouds Covering the Stars'), NULL, 'https://ebd.cda.pl/620x368/7728076ce');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14847, 828, 2, CONCAT('Unknown Scars'), NULL, 'https://ebd.cda.pl/620x368/79239682e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14848, 828, 3, CONCAT('Rifts'), NULL, 'https://ebd.cda.pl/620x368/797268851');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14849, 828, 4, CONCAT('The Voice Within'), NULL, 'https://ebd.cda.pl/620x368/803197742');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14850, 828, 5, CONCAT('Where We Belong'), NULL, 'https://ebd.cda.pl/620x368/8077373e3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14851, 828, 6, CONCAT('Feelings to Convey'), NULL, 'https://ebd.cda.pl/620x368/813654877');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14852, 828, 7, CONCAT('Contact'), NULL, 'https://ebd.cda.pl/620x368/8160824ab');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14853, 828, 8, CONCAT('Our Incomplete Selves'), NULL, 'https://ebd.cda.pl/620x368/820788541');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14854, 828, 9, CONCAT('Re:vale'), NULL, 'https://ebd.cda.pl/620x368/83112515e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14855, 828, 10, CONCAT('The Training Camp Begins!'), NULL, 'https://ebd.cda.pl/620x368/8311338f4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14856, 828, 11, CONCAT('Meticulous Malice'), NULL, 'https://ebd.cda.pl/620x368/838981513');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14857, 828, 12, CONCAT('Preparing to Take Over'), NULL, 'https://ebd.cda.pl/620x368/845237450');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14858, 828, 13, CONCAT('Tetrarchy of Madness and Destruction'), NULL, 'https://ebd.cda.pl/620x368/852328816');
