INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (848, CONCAT('Inazuma Eleven: Ares no Tenbin'), CONCAT('Taking place in an alternate timeline after Raimon Junior High wins the Football Frontier, a group of boys is playing soccer on a remote island off the coast of Japan. However, one day the students witness the demolition of the only soccer field on the island as they fight desperately to prevent its destruction, to no avail.<br>
<br>The only way to regain their soccer club is to become champions of the Football Frontier. Asuto Inamori and his classmates take up the offer, moving to mainland Japan and attending Raimon Junior High. Leaving behind their families and entering metropolitan Tokyo, they embark on a journey that will test their resolve to be the best in all of Japan.<br><br>Inazuma Eleven: Ares no Tenbin tells the tale of a group of friends whose desire for soccer burns brighter by the day. Through their encounters with several titans of the soccer landscape, including the mysterious coach Zhao Jinyun—they rush headlong into the Football Frontier to face the greatest teams Japan has to offer!<br>
<br>[Written by MAL Rewrite]'), 2, '2018-04-06', '2018-09-28', 'Spring 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1460/96891.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (375, 848, 1);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (929, 848, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (953, 848, 29);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (954, 848, 27);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15041, 848, 1, CONCAT('Setting Sail for Tomorrow'), '2018-04-06', 'https://ebd.cda.pl/800x450/411437834');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15042, 848, 2, CONCAT('The Devil of the Field'), '2018-04-06', 'https://ebd.cda.pl/800x450/227596505');
