INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (851, CONCAT('Infini-T Force'), CONCAT('Emi is a seventeen-year-old girl living in Shibuya. Her father is always away with work and she', CHAR(39), 's grown listless. Suddenly, a twist of fate involving a certain magical item changes everything. A mysterious pencil, of all things, is linked to the appearance of heroes from another world! Could this be the start to the excitement she', CHAR(39), 's so desperately craving, or is there something more?<br>
<br>(Source: VIZ Media)'), 1, '2017-10-03', '2017-12-19', 'Fall 2017', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/88430.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (603, 851, '"To be continued…"', ' by  flumpool', 'js-theme-songs', 'https://open.spotify.com/track/4nVaaVpQtTLMCOY1iTwnIV')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (932, 851, 77);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15096, 851, 1, CONCAT('Isolated Flower'), '2017-10-03', 'https://www.mp4upload.com/embed-ai0oh5qkpr93.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15097, 851, 2, CONCAT('Immediate Family'), '2017-10-10', 'https://www.mp4upload.com/embed-4tlglx830lu2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15098, 851, 3, CONCAT('Intelligent Fury'), '2017-10-17', 'https://www.mp4upload.com/embed-jixfc46vewc5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15099, 851, 4, CONCAT('Imaginary Friend'), '2017-10-24', 'https://www.mp4upload.com/embed-g1r9mgu1sbgh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15100, 851, 5, CONCAT('Invisible Future'), '2017-10-31', 'https://www.mp4upload.com/embed-9owummt6mwv9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15101, 851, 6, CONCAT('Infini-T Force'), '2017-11-07', 'https://www.mp4upload.com/embed-h0pk5f6ot9h6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15102, 851, 7, CONCAT('Insane Father'), '2017-11-14', 'https://www.mp4upload.com/embed-9ewjar8i65s2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15103, 851, 8, CONCAT('Inner Frustration'), '2017-11-21', 'https://www.mp4upload.com/embed-tquofr7r4tjo.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15104, 851, 9, CONCAT('In Flux'), '2017-11-28', 'https://www.mp4upload.com/embed-gqmze4aotz2g.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15105, 851, 10, CONCAT('Ignition Flame'), '2017-12-05', 'https://www.mp4upload.com/embed-bs3lk6cusbwa.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15106, 851, 11, CONCAT('Independent Flower'), '2017-12-19', 'https://www.mp4upload.com/embed-g0318qiizmqm.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15107, 851, 12, CONCAT('I', CHAR(39), 'll Find...'), '2017-12-26', 'https://www.mp4upload.com/embed-r285macjgbih.html');
