INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (887, CONCAT('Ishuzoku Reviewers'), CONCAT('Countless diverse races, from perky fairies to oozing slimes, inhabit the world. Naturally, such a melting pot of creatures has a broad and alluring variety of brothels. With so many options to choose from, it is hard to decide with which succu-girl to have a meaningful, interpersonal experience.<br>
<br>Fortunately, a tight group of brave warriors has come together to enlighten the public. These perverted adventurers take it upon themselves to assess the appeal of all types of succu-girls through hands-on research. Whether it be the scorchingly hot salamanders or the udderly hu-moo-ngous cow-girls, the Yoruno Gloss reviewers leave no species behind.<br>
<br>Directed by the mastermind behind Miru Tights, Ishuzoku Reviewers seeks to answer one of the most pressing questions there is: which species is the sexiest?<br>
<br>[Written by MAL Rewrite]'), 1, '2020-01-11', '2020-03-28', 'Winter 2020', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1870/105970.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2142, 887, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2143, 887, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2144, 887, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (969, 887, 58);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15720, 887, 1, CONCAT('A Hot ', CHAR(39), 'n Heavy Debate About Elf and Human MILFS, An Angel Ascends at Meow Meow Paradise, Can', CHAR(39), 't Get Enough of That Sensitive Birdmaid Cloaca!'), '2020-01-11', 'https://ebd.cda.pl/620x368/439882216');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15721, 887, 2, CONCAT('Fairies Have Limits on What They Can Take, Demons Aren', CHAR(39), 't Very Popular, Minotaur Girls Are Big, Bountiful, and Boobylicious!'), '2020-01-18', 'https://ebd.cda.pl/620x368/443021099');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15722, 887, 3, CONCAT('Gender-Swap Sex Means Less Succu-Girl Choices, and It Kinda Hurts, But You Learn Just What Girls Feel, So You Should Give It a Try!'), '2020-01-25', 'https://ebd.cda.pl/620x395/4474979c9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15723, 887, 4, CONCAT('Savage Succubi Will Squeeze the Life Out of You Even If You Say You Can', CHAR(39), 't Go On. Salamander Girls Have Such Hot Bods, Hearts, Sals, and Manders, that You Can', CHAR(39), 't Help But Get Fired Up About ', CHAR(39), 'Em!'), '2020-02-01', 'https://ebd.cda.pl/620x395/45120410b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15724, 887, 5, CONCAT('I Wanna Drown in a Cyclops Girl', CHAR(39), 's Pretty Eye, But It', CHAR(39), 's Pretty Hard? Speaking of Hard, Let the Pros Pick Out the Perfect Mushroom Girl for a Slimy, Sticky Good Time!'), '2020-02-08', 'https://ebd.cda.pl/620x395/455223214');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15725, 887, 6, CONCAT('You Can Build the Perfect Golem Girl, but Don', CHAR(39), 't Let the Girl You Base Her Off of Find Out. Cum to the Land of Dreams on the Light of the Will o', CHAR(39), ' the Wisps!'), '2020-02-15', 'https://ebd.cda.pl/620x395/4599233c5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15726, 887, 7, CONCAT('The Gang Gets Laid at the Egg-stravagant Egg-Laying Show, Miss Meidri', CHAR(39), 's Deep, Dark Secret Uncovered, and the Succu-Girl Popularity Ranking is Unveiled!'), '2020-02-22', 'https://ebd.cda.pl/620x395/46831762a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15727, 887, 8, CONCAT('Succu-girl Roleplay Will Get You Going All Night, The Angel', CHAR(39), 's Holy Lance is Great at Lancing Holes, The Succubus Tower Lasts Forever, But You (and Your Mayo) Won', CHAR(39), 't!'), '2020-02-29', 'https://ebd.cda.pl/620x395/474149601');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15728, 887, 9, CONCAT('A Deep, Dark Something Lies Between the Living and the Dead, the Darling Angel', CHAR(39), 's Lotion Explosion, and the Uncouth, Unsanctioned Reviewer Rivals Are in Their Scene!'), '2020-03-07', 'https://ebd.cda.pl/620x395/47869220a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15729, 887, 10, CONCAT('Let Your Eyes Behold the Glory and Mystery of the Brothel with a Perfect Score! Take a Newlywed or a Horny Tutor or a Little Piggie as Your Lover! They', CHAR(39), 'll Squeeze, Squeeze, Squeeze It Outta Ya! Infinite Pleasure over a Satisfying Three-Day Excursion! True Happiness Awaits!!!'), '2020-03-14', 'https://ebd.cda.pl/620x395/4838954d0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15730, 887, 11, CONCAT('The Frighteningly Faultless Philanthropist Sexually Satisfies Several Succubi, Drunken Fools and Their Money Are, of Course, Soon Parted, and Mitsue', CHAR(39), 's Room Comes to a Close!'), '2020-03-21', 'https://ebd.cda.pl/620x395/488048662');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15731, 887, 12, CONCAT('Farewell, Beloved Fans of Our Beloved Reviewers... Worry Not As Long as Succu-Girls Keep On Working Hard, So Too Will Our Reviewers. When You Think of Our Heroes, Remember This: When You Help Others (Get Their Fuck On), You', CHAR(39), 're Only Helping Yourself (Get Your Fuck On)...'), '2020-03-28', 'https://ebd.cda.pl/620x395/4961975bf');
