INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (906, CONCAT('Jikan no Shihaisha'), CONCAT('​Like many in her class, Koyuki Honda looks forward to her graduation ceremony. However, while her peers have family to attend, Koyuki has no one, as her only family—her brother—died years ago. While visiting his grave, she meets two brothers named Kiri and Victor Putin chasing a strange creature. They try to assure her that they are just actors shooting a movie Victor, however, piques Koyuki', CHAR(39), 's curiosity about the old legend of the clock tower at the cemetery: if you make a wish under the clock tower at midnight during a full moon, time will turn back, allowing someone to reclaim what they have lost.<br>
<br>Deciding to make her wish, Koyuki learns the horrifying truth: the legend is a ruse for time demons called "Horologues" to steal humans', CHAR(39), ' time. As they are drawn to regrets, Victor uses Koyuki as bait to lure a demon there. Kiri and Victor explain that they are Chronos Rulers, warriors who fight against the Horologues using the "Oath of Time"—an item allowing them to speed up or slow down time.<br>
<br>With the demon destroyed and the crisis averted, Koyuki is able to go on her way free from regrets. However, she is not the only human with sorrows. The two boys must continue to hunt down Horologues in order to keep humanity safe.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-07-08', '2017-09-30', 'Summer 2017', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/86753.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (641, 906, '"Jikan wa Mado no Mukougawa (時間は窓の向こう側)"', ' by Nagi Yanagi', 'js-theme-songs', 'https://open.spotify.com/track/01KQV7K090zaRShY9VPgyI');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (398, 906, 1);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (988, 906, 106);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16047, 906, 1, CONCAT('Being and Nothingness'), '2017-07-08', 'https://ebd.cda.pl/620x368/148264720');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16048, 906, 2, CONCAT('Memory and Reminiscence'), '2017-07-15', 'https://ebd.cda.pl/620x368/148905591');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16049, 906, 3, CONCAT('Twilight of the Idols'), '2017-07-22', 'https://ebd.cda.pl/620x368/1499143cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16050, 906, 4, CONCAT('The Concept of Anxiety'), '2017-07-29', 'https://ebd.cda.pl/620x368/150629803');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16051, 906, 5, CONCAT('Beyond Good and Evil'), '2017-08-05', 'https://ebd.cda.pl/620x368/151663328');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16052, 906, 6, CONCAT('Will and Representation'), '2017-08-12', 'https://ebd.cda.pl/620x368/152283091');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16053, 906, 7, CONCAT('The Poverty of Philosophy'), NULL, 'https://ebd.cda.pl/620x368/152910532');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16054, 906, 8, CONCAT('Fact and Fiction'), NULL, 'https://ebd.cda.pl/620x368/153387316');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16055, 906, 9, CONCAT('Responsibility and Principle'), NULL, 'https://ebd.cda.pl/620x368/1550580f1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16056, 906, 10, CONCAT('Conjectures and Refutations'), NULL, 'https://www.mp4upload.com/embed-9f9g9ervt4i6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16057, 906, 11, CONCAT('The Transcendence of the Ego'), NULL, 'https://ebd.cda.pl/620x368/15788670e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16058, 906, 12, CONCAT('Process and Reality'), NULL, 'https://www.mp4upload.com/embed-s74fymyfc2gr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16059, 906, 13, CONCAT('Fantasy Future'), NULL, 'https://www.mp4upload.com/embed-14dnh8pgze1a.html');
