INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (909, CONCAT('Jormungand'), CONCAT('Brought up in a conflict-ridden environment, child soldier Jonathan "Jonah" Mar hates weapons and those who deal them. But when Koko Hekmatyar, an international arms dealer, takes on Jonah as one of her bodyguards, he has little choice but to take up arms. Along with Koko', CHAR(39), 's other bodyguards, composed mostly of former special-ops soldiers, Jonah is now tasked with protecting Koko and her overly idealistic goal of world peace from the countless dangers that come from her line of work.<br><br>Jormungand follows Koko, Jonah, and the rest of crew as they travel the world selling weapons under the international shipping company HCLI. As Koko', CHAR(39), 's work is illegal under international law, she is forced to constantly sidestep both local and international authorities while doing business with armies, private militaries, and militias. With the CIA always hot on her trail, and assassins around every corner, Jonah and the crew must guard Koko and her dream of world peace with their lives or die trying.<br>
<br>[Written by MAL Rewrite]'), 1, '2012-04-11', '2012-06-27', 'Spring 2012', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/73280.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (644, 909, '"Borderland"', ' by Mami Kawada', 'js-theme-songs', 'https://open.spotify.com/track/3CPGZ2WsYmP4PudCFIeZfI')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (400, 909, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2201, 909, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2202, 909, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (991, 909, 38);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16084, 909, 1, CONCAT('Gunmetal Calico Road'), '2012-04-11', 'https://drive.google.com/file/d/145TbpCKIC_GlhBoWWO9UO40EkgIcsv5u/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16085, 909, 2, CONCAT('Pulsar'), '2012-04-18', 'https://drive.google.com/file/d/1bmyE73j9x6KpBoN7xwLs-53DlKhQxiLN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16086, 909, 3, CONCAT('Musica Ex Machina (Phase 1)'), '2012-04-25', 'https://drive.google.com/file/d/18h_bk-wmMcHqBmKIhQKhJ-7BxXfn40oz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16087, 909, 4, CONCAT('Musica Ex Machina (Phase 2)'), '2012-05-02', 'https://drive.google.com/file/d/1Vp-Umz2vvhtZDckW3kcwWO_6aCwS_2Az/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16088, 909, 5, CONCAT('Vein'), '2012-05-09', 'https://ebd.cda.pl/800x450/180304752');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16089, 909, 6, CONCAT('African Golden Butterflies (Phase 1)'), '2012-05-16', 'https://drive.google.com/file/d/1pd6DICQ4TSDiTsE45I01rUw5540Jxm1n/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16090, 909, 7, CONCAT('African Golden Butterflies (Phase 2)'), '2012-05-23', 'https://drive.google.com/file/d/1dy5V0jHuLiejIWHNWrwYBW1wY4VC2vAa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16091, 909, 8, CONCAT('Mondo Grosso'), '2012-05-30', 'https://drive.google.com/file/d/1q4nE8ZRGfwZawztomfPyyTiTMEqsGLz6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16092, 909, 9, CONCAT('Dragon Shooter (Phase 1)'), '2012-06-06', 'https://drive.google.com/file/d/1yTvPaqJWmPwrl7ZkLAlMivT8_zDbitm-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16093, 909, 10, CONCAT('Dragon Shooter (Phase 2)'), '2012-06-13', 'https://drive.google.com/file/d/1iCd4m3YLKIhNZNGPrwf1A3UqgT2MTlWK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16094, 909, 11, CONCAT('The Hill of Ruin (Phase 1)'), '2012-06-20', 'https://drive.google.com/file/d/1VuEo03bFHRRUNTWQ1QZy282lRi67btxa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16095, 909, 12, CONCAT('The Hill of Ruin (Phase 2)'), '2012-06-27', 'https://drive.google.com/file/d/0BwtVRkMiBtDmTGZjTTVxbmxiMUE/preview');
