INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (925, CONCAT('Juushin Enbu: Hero Tales'), CONCAT('For citizens of the Ken Empire, justice is a myth. Lord Keiro, the deranged Shogun of the Imperial Army, blazes a trail of terror across the countryside in search of the sacred sword that will make him a god. Standing in his way is Taito, an omnipotent star reborn in human form—a young hero who vows to use his celestial strength to avenge those slaughtered by the villainous Shogun.<br>
<br>Taito', CHAR(39), 's mystical powers steer him toward a violent showdown with Keiro, and if used recklessly, his newfound abilities could shred the very fabric of his being. To master the art of control and become a heroic martial artist, Taito must seek the guidance of others like him: the seven star-born warriors with the strength to shatter a corrupt empire.<br>
<br>(Source: RightStuf)'), 1, '2007-10-08', '2008-03-31', 'Fall 2007', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/75193.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (406, 925, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2241, 925, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2242, 925, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1007, 925, 188);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16289, 925, 1, CONCAT('Chapter One: Alkaid Roars'), NULL, 'https://ebd.cda.pl/620x368/330456777');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16290, 925, 2, CONCAT('Chapter Two: The Karma of Mizar'), NULL, 'https://ebd.cda.pl/800x450/33614027b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16291, 925, 3, CONCAT('Chapter Three: The Pledge of Energy...'), NULL, 'https://video.sibnet.ru/shell.php?videoid=3582387');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16292, 925, 4, CONCAT('Chapter Four: Divine Warrior'), NULL, 'https://video.sibnet.ru/shell.php?videoid=3582388');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16293, 925, 5, CONCAT('Chapter Five: Ailing Empire'), NULL, 'https://video.sibnet.ru/shell.php?videoid=3582389');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16294, 925, 6, CONCAT('Chapter Six: The Red Champion'), NULL, 'https://video.sibnet.ru/shell.php?videoid=3582390');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16295, 925, 7, CONCAT('Chapter Seven: Sorrowful Phecda'), NULL, 'https://video.sibnet.ru/shell.php?videoid=3582242');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16296, 925, 8, CONCAT('Chapter Eight: What Echoes in the...'), NULL, 'https://ebd.cda.pl/620x368/330459193');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16297, 925, 9, CONCAT('Chapter Nine: Shadow on the Imperial...'), NULL, 'https://ebd.cda.pl/620x368/33045940c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16298, 925, 10, CONCAT('Chapter Ten: The Lonely Emperor'), NULL, 'https://ebd.cda.pl/620x368/3304600d5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16299, 925, 11, CONCAT('Chapter Eleven: The Tale of the Big...'), NULL, 'https://ebd.cda.pl/620x368/3304606e0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16300, 925, 12, CONCAT('Chapter Twelve: A Glimmer in the...'), NULL, 'https://ebd.cda.pl/620x368/3304609fb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16301, 925, 13, CONCAT('Chapter Thirteen: The Two Celestial...'), NULL, 'https://ebd.cda.pl/620x368/3304612a8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16302, 925, 14, CONCAT('Chapter Fourteen: The Dou Ya Changes...'), NULL, 'https://ebd.cda.pl/620x368/33046154a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16303, 925, 15, CONCAT('Chapter Fifteen: Alkaid', CHAR(39), 's Guidepost'), NULL, 'https://ebd.cda.pl/620x368/3304618c1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16304, 925, 16, CONCAT('Chapter Sixteen: Dubhe, Devourer of...'), NULL, 'https://ebd.cda.pl/620x368/3304621ad');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16305, 925, 17, CONCAT('Chapter Seventeen: The Father-Son...'), NULL, 'https://ebd.cda.pl/620x368/3304624ff');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16306, 925, 18, CONCAT('Chapter Eighteen: Lian Tong Temple...'), NULL, 'https://ebd.cda.pl/620x368/330462796');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16307, 925, 19, CONCAT('Chapter Nineteen: Stars Divided'), NULL, 'https://ebd.cda.pl/620x368/330463021');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16308, 925, 20, CONCAT('Chapter Twenty: The Turmoil Begins'), NULL, 'https://ebd.cda.pl/620x368/330463336');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16309, 925, 21, CONCAT('Chapter Twenty-One: A Commoner Infuriated'), NULL, 'https://ebd.cda.pl/620x368/3304636ce');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16310, 925, 22, CONCAT('Chapter Twenty-Two: Imperial Capital in Confusion'), NULL, 'https://ebd.cda.pl/620x368/3304639ae');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16311, 925, 23, CONCAT('Chapter Twenty-Three: Clash'), NULL, 'https://ebd.cda.pl/620x368/330464526');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16312, 925, 24, CONCAT('Chapter Twenty-Four: Karma Out of Control'), NULL, 'https://ebd.cda.pl/800x450/3361471f8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16313, 925, 25, CONCAT('Chapter Twenty-Five: The Dubhe God'), NULL, 'https://ebd.cda.pl/800x450/336147437');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16314, 925, 26, CONCAT('Final Chapter: The End of the Tale'), NULL, 'https://ebd.cda.pl/800x450/3361477ba');
