INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (927, CONCAT('K-On!'), CONCAT('A fresh high school year always means much to come, and one of those things is joining a club. Being in a dilemma about which club to join, Yui Hirasawa stumbles upon and applies for the Light Music Club, which she misinterprets to be about playing simple instruments, such as castanets. Unable to play an instrument, she decides to visit to apologize and quit.<br>
<br>Meanwhile, the Light Music Club faces disbandment due to a lack of members. This causes the club members to offer anything, from food to slacking off during club time, in order to convince Yui to join. Despite their efforts, Yui insists on leaving due to her lack of musical experience. As a last resort, they play a piece for Yui, which sparks her fiery passion and finally convinces her to join the club.<br>
<br>From then onward, it', CHAR(39), 's just plain messing around with bits and pieces of practice. The members of the Light Music Club are ready to make their time together a delightful one!<br>
<br>[Written by MAL Rewrite]'), 1, '2009-04-03', '2009-06-26', 'Spring 2009', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/76120.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (660, 927, '"Cagayake! GIRLS"', ' by Sakurakou Keion-bu (Aki Toyosaki, Yoko Hisaka, Satomi Satou, Minako Kotobuki)', 'js-theme-songs', 'https://open.spotify.com/track/6dCeYPmR97wXMKgfZxU4wU')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (407, 927, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1010, 927, 21);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1032, 927, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1033, 927, 40);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16322, 927, 1, CONCAT('Disband the Club!'), '2009-04-03', 'https://drive.google.com/file/d/1Qf410lf49L1EGsjZoEibhlOcQueGoXLR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16323, 927, 2, CONCAT('Instruments!'), '2009-04-10', 'https://drive.google.com/file/d/1tiCGKKm4S_Q9aBADkdP9hlbrDY0Ggv__/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16324, 927, 3, CONCAT('Cram Session!'), '2009-04-17', 'https://drive.google.com/file/d/1LYhSHPTWdZpRVzbcZv0uNlohqYfXDrue/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16325, 927, 4, CONCAT('Training Camp!'), '2009-04-24', 'https://drive.google.com/file/d/1w051DyuGOyJe0GXP9L18kTp4wecgj5AJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16326, 927, 5, CONCAT('Advisor!'), '2009-05-01', 'https://drive.google.com/file/d/1-unnVyy3dpd8F4kxPRr0Z-dSRp_vfvrO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16327, 927, 6, CONCAT('School Festival!'), '2009-05-08', 'https://drive.google.com/file/d/1WS5_bK0PDyx1pK69z-zLbf3CsOR2dpe2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16328, 927, 7, CONCAT('Christmas!'), '2009-05-15', 'https://drive.google.com/file/d/1CjKHXCJRH62c69h2_Z6RRE3Q5TSBxN-9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16329, 927, 8, CONCAT('Freshman Reception!'), '2009-05-21', 'https://drive.google.com/file/d/1czTcog4AzFmXOyoytdH2es6RrlHjF-Yk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16330, 927, 9, CONCAT('New Club Member!'), '2009-05-29', 'https://drive.google.com/file/d/1onRC1tSbDP5Qikkh8fe3F6khBrWCKJPZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16331, 927, 10, CONCAT('Another Training Camp!'), '2009-06-05', 'https://drive.google.com/file/d/1IRygeTdTDQgnJx04EdKncCw3GNjDtMZk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16332, 927, 11, CONCAT('Crisis!'), '2009-06-12', 'https://drive.google.com/file/d/1s6rfWlM6dc6WIq6MS5AZgwD8_SnscVb9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16333, 927, 12, CONCAT('Light Music!'), '2009-06-19', 'https://drive.google.com/file/d/1i7ioMxNGJv2t8hHdLYW-ENPeaO4cDQjk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16334, 927, 13, CONCAT('Winter Days!'), '2009-06-26', 'https://drive.google.com/file/d/1BAd2LU1K-6Kget4MFj_uAqvafAp7Gk26/preview');
