INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (935, CONCAT('Kai Byoui Ramune'), CONCAT('At first glance, Ramune may not seem like a professional doctor—he is crass, rude, and often acts halfheartedly. But his true brilliance shines through once his patients pay him a visit: he is able to diagnose and treat all sorts of strange, mysterious diseases that come his way. From a young student whose fingers have turned into chili peppers to a child whose tears are made of condiments, Ramune is able to tap into a kind of innate, otherworldly sensibility that enables him to decipher the roots of their source. But finding the proper cure for these illnesses comes at a valuable price, and money certainly cannot be used to pay it. <br>
<br>[Written by MAL Rewrite]'), 1, '2021-01-10', '2021-03-28', 'Winter 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1443/110157.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (410, 935, 1);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1019, 935, 118);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1041, 935, 34);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1042, 935, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16416, 935, 1, CONCAT('Condiment Tears'), '2021-01-10', 'https://drive.google.com/file/d/1UplqkHphF8FbCAXK0mwPrfzqHeDny04t/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16417, 935, 2, CONCAT('The Chikuwa Penis'), '2021-01-17', 'https://drive.google.com/file/d/1amVucuax8R7H5ZLKV7G8ZEMHBUKxvOJV/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16418, 935, 3, CONCAT('Mysterious Item Shop Akatsuki'), '2021-01-24', 'https://drive.google.com/file/d/1T6hDhw13dONRq5Ph3tdVqHiB70hjV27d/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16419, 935, 4, CONCAT('Chili Pepper Fingertips'), '2021-01-31', 'https://drive.google.com/file/d/1AaTUnVl6cZNsU_OKfx6qRNcO-V48msiO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16420, 935, 5, CONCAT('Pot Sticker Ears (Part One)'), '2021-02-07', 'https://drive.google.com/file/d/1HMsChTp8piblpURbD3b7jBlhsoijDOsO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16421, 935, 6, CONCAT('Pot Sticker Ears (Part Two)'), '2021-02-14', 'https://drive.google.com/file/d/1WqSmqe4BDpcwdVPGzKOeSFEzjyg0Hu2v/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16422, 935, 7, CONCAT('Popcorn Head (Part One)'), '2021-02-21', 'https://drive.google.com/file/d/1JnEEH_yLhcPsjxGaJWdu4veQL2jCIp7D/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16423, 935, 8, CONCAT('Popcorn Head (Part Two)'), '2021-02-28', 'https://drive.google.com/file/d/1DuSAjVrOAxKkJxk2Txc7DsZIZe-u2yV_/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16424, 935, 9, CONCAT('Mysterious Labyrinth'), '2021-03-07', 'https://drive.google.com/file/d/1fYYXWfOlwV4BGh0DVJWvv2_QHFqr3asI/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16425, 935, 10, CONCAT('Toru', CHAR(39), 's Deeply Mysterious Story - Part One'), '2021-03-14', 'https://drive.google.com/file/d/1jiET-H898DZ31FIG4Bxv3rimQWV08apj/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16426, 935, 11, CONCAT('Toru', CHAR(39), 's Deeply Mysterious Story - Part Two'), '2021-03-21', 'https://drive.google.com/file/d/1xyQozoxV39NKhVNiEeHqL1ebGHsknpN7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16427, 935, 12, CONCAT('Dr. Ramune -Mysterious Disease Specialist-'), '2021-03-28', 'https://drive.google.com/file/d/1G0vXd9aA1hYrINI8jE3X0xJPbtzBZidq/preview');
