INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (942, CONCAT('Kaizoku Oujo'), CONCAT('A decade ago, a tragic shipwreck separated Fena Houtman from her childhood friend Yukimaru and took her father', CHAR(39), 's life. Now, at age 23, she is trapped on an island and is doomed to spend the rest of her life selling herself to men. On the night she is to be forcibly wed to a client, Fena hatches a plan to escape from her employers, but two old acquaintances unexpectedly intervene and help her run away. <br>
<br>The three make haste for the open sea and land upon Goblin Island—a mysterious place that a clan of fierce warriors call home. It is there that Fena learns that her father', CHAR(39), 's ill-fated final journey at sea was in search of a place called "Eden," the location of something important that he had to protect. With nothing but a clear crystal as a clue, Fena is tasked with finding this place, as she is the only person who can do so. <br>
<br>While still contemplating the search for what her father left behind, Fena reunites with Yukimaru, who encourages her to take up the quest. Now the captain of a seven-person crew, Fena must navigate the high seas in search of Eden. But as uncanny groups begin to target her, the perilous journey proves to be even more challenging than it previously seemed.<br>
<br>[Written by MAL Rewrite]'), 1, '2021-10-03', '2021-12-19', 'Fall 2021', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1607/117951.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2281, 942, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2282, 942, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2283, 942, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1026, 942, 2);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16504, 942, 1, CONCAT('Memories'), '2021-10-03', 'https://ebd.cda.pl/620x368/817372160');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16505, 942, 2, CONCAT('An Inherited Journey'), NULL, 'https://ebd.cda.pl/620x368/8173724ab');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16506, 942, 3, CONCAT('Bar-Baral'), NULL, 'https://ebd.cda.pl/620x368/82073365f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16507, 942, 4, CONCAT('The Mystery of the Stone'), NULL, 'https://ebd.cda.pl/620x368/8253629d9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16508, 942, 5, CONCAT('Coordinates'), NULL, 'https://ebd.cda.pl/620x368/8310234db');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16509, 942, 6, CONCAT('Mutiny on the Blue Giant'), NULL, 'https://ebd.cda.pl/620x368/839407519');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16510, 942, 7, CONCAT('The Burning Sea'), NULL, 'https://ebd.cda.pl/800x450/84568958a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16511, 942, 8, CONCAT('A Knight', CHAR(39), 's Vow'), NULL, 'https://ebd.cda.pl/620x368/8549682ee');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16512, 942, 9, CONCAT('Vice Versa'), NULL, 'https://ebd.cda.pl/620x368/8699340e0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16513, 942, 10, CONCAT('The Curtain Rises on the Climax'), NULL, 'https://ebd.cda.pl/620x368/8756022b9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16514, 942, 11, CONCAT('At Mission', CHAR(39), 's End'), NULL, 'https://ebd.cda.pl/620x368/88247798b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16515, 942, 12, CONCAT('The Chosen Maiden'), NULL, 'https://ebd.cda.pl/620x368/888612696');
