INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (954, CONCAT('Kamisama Dolls'), CONCAT('Kyouhei, after moving away to Tokyo from his old town to get away from the events that happened, is on a goukon with his friends, including his old neighbor, Shiba. After drinking for a whole night, he and Shiba discover a dead, bloody body in the elevator. He is told by his younger sister, Utao with her Kamisama Doll, that Aki, an old friend, and his Doll are the culprits responsible. '), 1, '2011-07-06', '2011-09-28', 'Summer 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1001/98636.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (419, 954, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2313, 954, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2314, 954, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2315, 954, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1039, 954, 23);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16714, 954, 1, CONCAT('A God Arrives'), NULL, 'https://www.facebook.com/video/embed?video_id=129566330473781');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16715, 954, 2, CONCAT('A God', CHAR(39), 's Training'), NULL, 'https://video.sibnet.ru/shell.php?videoid=511953');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16716, 954, 3, CONCAT('It Attacks...'), NULL, 'https://video.sibnet.ru/shell.php?videoid=511962');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16717, 954, 4, CONCAT('Heruma'), NULL, 'https://www.dailymotion.com/embed/video/k45UFzMjvNtcrK3q5dq?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.p');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16718, 954, 5, CONCAT('To Home...'), NULL, 'https://video.sibnet.ru/shell.php?videoid=726930');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16719, 954, 6, CONCAT('Karakami Village'), NULL, 'https://www.dailymotion.com/embed/video/k7pWR7rM5txfDE3q5gG?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.p');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16720, 954, 7, CONCAT('Portrait of Memories'), NULL, 'https://www.facebook.com/video/embed?video_id=130423733721374');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16721, 954, 8, CONCAT('The Role of a God'), NULL, 'https://www.facebook.com/video/embed?video_id=131161546980926');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16722, 954, 9, CONCAT('Tangled Relations'), NULL, 'https://vidstreaming.io/streaming.php?id=MjU3Nzg');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16723, 954, 10, CONCAT('The Princess Arrives'), NULL, 'https://www.mp4upload.com/embed-5jkza76911r5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16724, 954, 11, CONCAT('Hibino Kidnapped'), NULL, 'https://www.mp4upload.com/embed-gqrh3evji7jf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16725, 954, 12, CONCAT('Out of Control'), NULL, 'https://www.mp4upload.com/embed-ve5iofav851a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16726, 954, 13, CONCAT('Kuga Kyohei, the Seki'), NULL, 'https://www.mp4upload.com/embed-2ijc9r95zryc.html');
