INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (961, CONCAT('Kanojo ga Flag wo Oraretara'), CONCAT('In visual novels, an imaginary flag is defined as an event that serves as a turning point for the whole story. A player triggering the romance flag for a heroine will proceed to her route, or a death flag will signify that a certain character will die afterwards.<br>
<br>High school student Souta Hatate can see these flags above a person', CHAR(39), 's head, and has the ability to bring them down to stop certain events from happening. Using this power, he has prevented other people', CHAR(39), 's deaths. But, after a past accident with him as a sole survivor, he ended up believing that only misfortune will befall those who are near him, and has refrained from making friends or having relationships ever since.<br>
<br>However, everything starts to change after transferring to a new school. After toppling another death flag, his classmate Nanami Knight Bladefield notices his powers and tries to learn more about him, promising that she will remain at his side no matter what may happen. Thus begins Souta', CHAR(39), 's journey as he meets new friends and acquaintances while uncovering the mysteries of his ability... which might run deeper than what anyone expects.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-04-07', '2014-06-30', 'Spring 2014', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/63363.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (680, 961, '"Cupid Review (クピドゥレビュー)"', ' by Aoi Yuuki', 'js-theme-songs', 'https://open.spotify.com/track/7xl3J0lCEuVVQQIpfjSG0i')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2335, 961, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2336, 961, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1046, 961, 8);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1066, 961, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1067, 961, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16801, 961, 1, CONCAT('I', CHAR(39), 'm Going to Marry Her Once I Leave This School'), NULL, 'https://ebd.cda.pl/800x450/6726455c6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16802, 961, 2, CONCAT('Girls are in the Dorm. But I can', CHAR(39), 't say it yet. Wait Until Tomorrow.'), NULL, 'https://ebd.cda.pl/800x450/6726461aa');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16803, 961, 3, CONCAT('Leave it to Me, There is a Chance We', CHAR(39), 're Going to Win This Athletic Meet'), NULL, 'https://drive.google.com/file/d/1N47ARcJqm4-g6PqDPEzvhKdfpulgr9Kj/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16804, 961, 4, CONCAT('We', CHAR(39), 're Almost to the Goal. The Track Meet ', CHAR(39), 'll End Just Fine.'), NULL, 'https://drive.google.com/file/d/0BxHOXujEV4CZejQyc25tSHVBbVE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16805, 961, 5, CONCAT('Believe and Wait for Me. I', CHAR(39), 'm not Going to be Late for My Date With Everyone.'), NULL, 'https://ebd.cda.pl/800x450/6726407d9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16806, 961, 6, CONCAT('Phew. Don', CHAR(39), 't scare me like that. I guess you', CHAR(39), 're just a little sister.'), NULL, 'https://ebd.cda.pl/800x450/672643779');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16807, 961, 7, CONCAT('I Learned Something Amazing. I', CHAR(39), 'll Hide Myself Before I can be Erased'), NULL, 'https://ebd.cda.pl/800x450/672638603');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16808, 961, 8, CONCAT('I', CHAR(39), 'll catch up to you. Have I ever broken a promise to you before?'), NULL, 'https://ebd.cda.pl/800x450/672644928');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16809, 961, 9, CONCAT('Someday, it', CHAR(39), 'd be Nice if We Could all Go to a Festival Together Again'), NULL, 'https://drive.google.com/file/d/0Bx0HQ6Ndm4f5MWpZaFRod0FlTkE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16810, 961, 10, CONCAT('Hold this for Me. The Winner of the Beauty Contest is Written Here.'), NULL, 'https://ebd.cda.pl/800x450/6726452f0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16811, 961, 11, CONCAT('We Don', CHAR(39), 't all Have to Dance. I can Dance by Myself'), NULL, 'https://ebd.cda.pl/800x450/672639286');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16812, 961, 12, CONCAT('It', CHAR(39), 's a Cruel World. I', CHAR(39), 'm Going to Take a Look in the Shadows.'), NULL, 'https://ebd.cda.pl/800x450/6726383be');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16813, 961, 13, CONCAT('If His Flag Breaks'), NULL, 'https://ebd.cda.pl/800x450/6726446dc');
