INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (980, CONCAT('Katsute Kami Datta Kemono-tachi e'), CONCAT('With the initiation of the Patrian civil war came the creation of half-beast, half-human soldiers—a development of the outnumbered Northerners in a desperate attempt to counter the overwhelming Southern forces. Able to quickly dominate battlefields and achieve victory with ease, the soldiers', CHAR(39), ' godlike abilities earned them the name "Incarnates." However, as the war raged on, the Incarnates encountered a problem involving the beasts inside them that they were unable to rectify by ordinary means. <br>
<br>Once the war was over, mysteries and accounts of the Incarnates submitting to the misfortune of their war days surfaced. Aware of the horrors they faced during the war, Special Sergeant Major and former captain of the Incarnates Hank Henriette becomes a Beast Hunter—those who take the lives of Incarnates who have succumbed to the issues they experienced on the battlefields. <br>
<br>After witnessing her father, a former Incarnate soldier, meet his end at the hands of one such Beast Hunter, Nancy Schaal Bancroft resolves to hunt the man who took her father', CHAR(39), 's life. However, Nancy', CHAR(39), 's eye-opening encounter with the Beast Hunter influences her to instead seek the reason behind her father', CHAR(39), 's death and the Incarnates', CHAR(39), ' problematic existence in society.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-07-01', '2019-09-16', 'Summer 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1109/101230.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (692, 980, '"Sacrifice (サクリファイス)"', ' by Mafumafu', 'js-theme-songs', 'https://open.spotify.com/track/45oVY6oQcKsMmRhacvLhsG')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (435, 980, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2372, 980, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2373, 980, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2374, 980, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1066, 980, 73);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17040, 980, 1, CONCAT('To the Abandoned Sacred Beasts'), NULL, 'https://drive.google.com/file/d/1FbgBbb655_qTAzSc5JR1U-zZKYbgEB3o/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17041, 980, 2, CONCAT('The Dragon', CHAR(39), 's Daughter'), NULL, 'https://drive.google.com/file/d/1HjXeFXtZQ9Q4lLj4OqM_LKqMTl-HNRZM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17042, 980, 3, CONCAT('The Minotaur', CHAR(39), 's Fortress'), NULL, 'https://drive.google.com/file/d/1Axy4sQXtCouBwmaQy9k81KQu6bnjU-4R/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17043, 980, 4, CONCAT('March of the Behemoth'), NULL, 'https://drive.google.com/file/d/17sjnZ_K_UXTQ02C3zzuBLlp8bTJzWAPq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17044, 980, 5, CONCAT('Gargoyle', CHAR(39), 's Judgment'), NULL, 'https://drive.google.com/file/d/1utzuTsEa40Zq_ynVdMGuhFrPt3QNcdPv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17045, 980, 6, CONCAT('The King of the Beasts'), NULL, 'https://drive.google.com/file/d/1qOZYoGUlDqQBOQH8Fo_OhFBLRa-933ub/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17046, 980, 7, CONCAT('The Trigger of Memories'), NULL, 'https://drive.google.com/file/d/1bMZzKKlmXlNC5U8r6LxsVbsIp4Xv6-cq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17047, 980, 8, CONCAT('Songstress of Sleep'), NULL, 'https://drive.google.com/file/d/1YEkcIazDPmv31BjBk7kU7ulrt_18CxU4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17048, 980, 9, CONCAT('The Hound of Hell', CHAR(39), 's Gate'), NULL, 'https://drive.google.com/file/d/1PtpXh9jt1H8bwQUJYpvBILEKBxf2Q4od/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17049, 980, 10, CONCAT('Two Oaths'), NULL, 'https://drive.google.com/file/d/1XhbE934wh2g9Q0k-2f6epLjBgGTGPEK4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17050, 980, 11, CONCAT('The Start of Troubles Ahead'), NULL, 'https://drive.google.com/file/d/1Q7xTipJpN4usFxBlTbSCeoqOPyWbwJ6y/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17051, 980, 12, CONCAT('Those Who Seek'), NULL, 'https://drive.google.com/file/d/1tPqXJutUsvF3iuI35ZdN7Q8-S2wf8Mox/preview');
