INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (994, CONCAT('Kemonozume'), CONCAT('Creatures known as Shokujinki have been secretly living alongside humans for hundreds of years. Though they may look like humans, Shokujinki are able to transform into uncontrollable beasts with gigantic claws and consume humans to survive. The equally secretive Kifuuken dojo specializes in killing Shokujinki by cutting off their arms, and is the only force preventing unchecked Shokujinki domination.<br>
<br>Toshihiko Momota, the son of the leader of the Kifuuken, is instantly charmed by a mysterious woman named Yuka Kamitsuki. Their relationship is complicated, however, because unbeknownst to them both, Yuka is a Shokujinki and Toshihiko is sworn to kill her. Meanwhile, the Kifuuken is having a crisis of confidence as Toshihiko', CHAR(39), 's brother Kazuma pushes against tradition and tries to modernize the Kifuuken. As emotions are strained and the secrets of both the past and present are revealed, who will live, and who will be eaten?<br>
<br>[Written by MAL Rewrite]'), 1, '2006-08-06', '2006-11-05', 'Summer 2006', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/86766.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (704, 994, '"Auvers Blue"', ' by Katteni Shiyagare', 'js-theme-songs', 'https://open.spotify.com/track/6QAjUG8sshm4odBANCj2up');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (705, 994, '"Suki"', ' by Santara', 'js-theme-songs', 'https://open.spotify.com/track/1mTRCNgh8U9CFaUS8BBvpy');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (443, 994, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2410, 994, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2411, 994, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2412, 994, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1080, 994, 172);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17263, 994, 1, CONCAT('First Taste'), '2006-08-06', 'https://www.mp4upload.com/embed-6ijrlzoayf17.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17264, 994, 2, CONCAT('Hard Farewells'), '2006-08-13', 'https://www.mp4upload.com/embed-z92zofcvl5l1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17265, 994, 3, CONCAT('Salty New Moon Night'), '2006-08-20', 'https://www.mp4upload.com/embed-iicy58y7n92t.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17266, 994, 4, CONCAT('Bitterness of the Past'), '2006-08-27', 'https://www.mp4upload.com/embed-d4pvocyydazq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17267, 994, 5, CONCAT('Woman', CHAR(39), 's Hidden Flavour'), '2006-09-10', 'https://www.mp4upload.com/embed-q7ku90gbxc44.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17268, 994, 6, CONCAT('Spicy Hot Birthday'), '2006-09-17', 'https://www.mp4upload.com/embed-pf7pksvop268.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17269, 994, 7, CONCAT('The Sweet Fragrance of Rie'), '2006-09-24', 'https://www.mp4upload.com/embed-m1d8bt95qyel.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17270, 994, 8, CONCAT('Detention Tastes Like Iron'), '2006-10-01', 'https://www.mp4upload.com/embed-7va89s7xn0th.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17271, 994, 9, CONCAT('Sweet Dreams'), '2006-10-08', 'https://www.mp4upload.com/embed-1anhyimr7wfw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17272, 994, 10, CONCAT('The Misfortunes of Others Are the Taste of Honey'), '2006-10-15', 'https://www.mp4upload.com/embed-obvecejizoy0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17273, 994, 11, CONCAT('The Rain Was Bitter'), '2006-10-22', 'https://www.mp4upload.com/embed-hw5sdb18bon6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17274, 994, 12, CONCAT('Coffee-Flavoured Millet Dumplings'), '2006-10-29', 'https://www.mp4upload.com/embed-6369x4trt0eq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17275, 994, 13, CONCAT('Taste Has Nothing to Do with It'), '2006-11-05', 'https://www.mp4upload.com/embed-lq0wcrexwj9b.html');
