INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (996, CONCAT('Ken En Ken: Aoki Kagayaki'), CONCAT('Yin and Ning are two sisters who have been wandering the land together ever since their village was destroyed by the villainous Taibai Empire. Their childhood friend, Zhao, has been enslaved by the Taibai himself, and uses his brilliance at tinkering and inventing to get by as a slave to the Empire', CHAR(39), 's whims. One day, Yin accidentally discovers a legendary sword, which grants her fantastic abilities in combat, and allows her to summon a mystical, mechanical fox spirit named Yun, who is sworn to fight by her side. Meanwhile, Zhao is making fast friends with a mysterious young girl who just may hold a great amount of power within the Taibai Empire. As Zhao and the Fu sisters find themselves increasingly caught up in the Empire', CHAR(39), 's battle for supremacy over the land, it will take all of the magic and might that the budding resistance armies can muster to turn the tide of war once and for all.<br>
<br>(Source: ANN)'), 1, '2018-10-02', '2018-12-25', 'Fall 2018', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1339/95573.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (707, 996, '"Nageki no Hana (嘆きの華)"', ' by Nana Mizuki', 'js-theme-songs', 'https://open.spotify.com/track/0sykGYWNmdFkBXJurdnWKo')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2415, 996, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2416, 996, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2417, 996, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1082, 996, 46);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1102, 996, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1103, 996, 11);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17288, 996, 1, CONCAT('The Beginning'), NULL, 'https://ebd.cda.pl/620x368/27681240b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17289, 996, 2, CONCAT('The Work of Memory'), NULL, 'https://ebd.cda.pl/620x368/27682145e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17290, 996, 3, CONCAT('The Sword of Sorrow'), NULL, 'https://ebd.cda.pl/620x368/2768286a1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17291, 996, 4, CONCAT('Fate', CHAR(39), 's Jest'), NULL, 'https://drive.google.com/file/d/1KyAUyEYGMHhBaYnYSihjHuE4gso4Xv_Q/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17292, 996, 5, CONCAT('The Courage to Set Out'), NULL, 'https://ebd.cda.pl/620x368/2772803fd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17293, 996, 6, CONCAT('Their Bond'), NULL, 'https://ebd.cda.pl/620x368/2774804d6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17294, 996, 7, CONCAT('Complicated Feelings'), NULL, 'https://ebd.cda.pl/620x368/2778385e3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17295, 996, 8, CONCAT('The Black Fire Armor'), NULL, 'https://ebd.cda.pl/620x368/279044813');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17296, 996, 9, CONCAT('The Palace of Strategy'), NULL, 'https://ebd.cda.pl/x/281240827');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17297, 996, 10, CONCAT('The Drops of Interrogation'), NULL, 'https://ebd.cda.pl/x/286560778');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17298, 996, 11, CONCAT('The Blade of Love and Hate'), NULL, 'https://ebd.cda.pl/620x368/286560778');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17299, 996, 12, CONCAT('The Guilt of Forgetfulness'), NULL, 'https://ebd.cda.pl/620x368/2893072c3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17300, 996, 13, CONCAT('The Sky Fortress'), NULL, 'https://ebd.cda.pl/620x368/2913369a1');
