INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1025, CONCAT('King of Prism: Shiny Seven Stars'), CONCAT('TV version of the King of Prism: Shiny Seven Stars movies.<br>
<br>After appearing in the Prism King Cup representing Edel Rose, and getting a glimpse of what it was like to a be a future Prism Star, Ichijo Shin entered Kakyoin Academy’s High School division in spring and became a first-year high school student. Koji, Hiro, and Kazuki from Over The Rainbow left Edel Rose and established a new agency. They were all keeping quite busy. Meanwhile, after having the title of Prism King stolen by Hiro, the leader of Schwarz Rose, Norizuki Jin, proposes PRISM.1, which would decide a new king other than Prism King. He then announces that Schwarz Rose and Edel Rose will be competing with each other. While everyone is preparing for PRISM.1, Yukinojo is torn between being in kabuki and the Prism Show. He doesn’t feel like he’s living up to his potential in either and doesn’t know what to do. His father sees him like this and tells him to leave the world of Prism Shows...<br>
<br>(Source: Crunchyroll)<br>'), 2, '2019-04-16', '2019-07-02', 'Spring 2019', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1649/100502.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (729, 1025, '"Shiny Seven Stars!"', ' by Shin Ichijou (Junta Terashima), Yukinojou Tachibana (Souma Saitou), Taiga Kougami (Tasuku Hatanaka), Kakeru Juuouin (Taku Yashiro), Minato Takahashi (Masashi Igarashi), Leo Saionji (Takuma Nagatsuka), Yuu Suzuno (Yuuma Uchida)', 'js-theme-songs', 'https://open.spotify.com/track/2DN5nL5BPfhAaoIJACgHhM')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2490, 1025, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2491, 1025, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2492, 1025, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1114, 1025, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17771, 1025, 1, CONCAT('Hayami Hiro, Mihama Koji, Nishina Kazuki: Beyond The Rainbow'), NULL, 'https://streamtape.com/e/q6wWGARbY2SzX6m/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17772, 1025, 2, CONCAT('Tachibana Yukinojo Has Arrived!'), NULL, 'https://streamtape.com/e/yrkG3O24qmIdwQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17773, 1025, 3, CONCAT('Kogami Taiga: The Festival! Is Inside Me!'), NULL, 'https://streamtape.com/e/ygYbAPg3KMu1pvq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17774, 1025, 4, CONCAT('Juoin Kakeru: Soaring with Love'), NULL, 'https://streamtape.com/e/q84wJzVYJaCRvl/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17775, 1025, 5, CONCAT('The Shuffle: Joji', CHAR(39), 's Song'), NULL, 'https://streamtape.com/e/d3kyJjvJ4bh71m/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17776, 1025, 6, CONCAT('Takahashi Minato: My Heart Is an Ocean'), NULL, 'https://streamtape.com/e/Ba9wQPbjvOu2mD/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17777, 1025, 7, CONCAT('Saionji Leo: Flowers Blooming in Your ♥'), NULL, 'https://streamtape.com/e/2kAZGlgrMocZOZj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17778, 1025, 8, CONCAT('Suzuno Yu: I Am Zeus'), NULL, 'https://streamtape.com/e/vVPpwZJR7gILRv/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17779, 1025, 9, CONCAT('Yamato Alexander: The Charisma of Street'), NULL, 'https://streamtape.com/e/oG4gAwmdWRuJ6jO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17780, 1025, 10, CONCAT('Kisaragi Louis: Prism Emissary'), NULL, 'https://streamtape.com/e/w4ByjO4paxSJJgv/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17781, 1025, 11, CONCAT('Ichijo Shin: SIN'), NULL, 'https://streamtape.com/e/3xxG8MrvR9cdk7Z/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17782, 1025, 12, CONCAT('Shiny Seven Stars Forever!'), NULL, 'https://streamtape.com/e/Ba6l246MzZuyZ6W/');
