INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1039, CONCAT('Kishibe Rohan wa Ugokanai'), CONCAT('Kishibe Rohan wa Ugokanai adapts a handful of one-shots based on the manga series JoJo no Kimyou na Bouken, and follows the bizarre adventures that Rohan Kishibe goes through as he searches for inspiration for his manga.<br><br>Fugou Mura<br>
<br>Rohan accompanies manga editor Kyouka Izumi to a secretive village where she plans on buying a house. Izumi informs Rohan that inhabitants of the village suddenly become rich at the age of 25 after purchasing their homes. Being 25 years old herself, Izumi has high hopes for moving into the village and invites Rohan to gather ideas for his manga. As they enter one of the houses for an interview with the seller, they are greeted by a servant named Ikkyuu, who puts them through a test of etiquette with deadly consequences.<br><br>Mutsukabezaka<br>
<br>Rohan meets with his editor, Minoru Kagamari, to discuss both his manga and the six mountains that the manga author recently bought. He explains that he purchased the mountains in order to search for a legendary spirit known as the Mutsukabezaka. To give his search context, he tells the tale of Naoko Osato, a wealthy heiress who murdered her boyfriend and became cursed by the spirit.<br><br>Zangenshitsu<br>
<br>Rohan decides to vacation in Venice after putting his manga on hiatus. While there, he explores the interior of a church and examines the structure of its confessional. After stepping into the priest', CHAR(39), 's compartment, Rohan hears a man enter the confessional and begin to confess his sins. The man recounts his confrontation with a starving beggar and the haunting events that followed.<br><br>The Run<br>
<br>Youma Hashimoto is a young male model who has quickly risen to success. As his popularity grows, so does his obsession with his appearance and body. One day, he meets Rohan at the gym, and the two quickly form a rivalry which pushes Youma to intensify his training. Soon. Youma', CHAR(39), 's fixation on his physique takes a dark turn as his training takes precedence over his life, and he challenges Rohan to a fatal competition on the treadmills.<br>
<br>[Written by MAL Rewrite]'), 3, '2017-09-20', '2020-03-25', '', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1716/103072.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (741, 1039, '"Theme of Kishibe Rohan wa Ugokanai (岸辺露伴は動かないのテーマ)"', ' by Yugo Kanno', 'js-theme-songs', 'https://open.spotify.com/track/1bRQ2GyRv55vB1Ljylzpb1')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (471, 1039, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2514, 1039, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2515, 1039, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2516, 1039, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1129, 1039, 81);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18104, 1039, 1, CONCAT('Thus Spoke Kishibe Rohan: Millionaire Village'), '2017-09-20', 'https://ebd.cda.pl/620x368/5380728ac');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18105, 1039, 2, CONCAT('Thus Spoke Kishibe Rohan: Mutsu-kabe Hill'), '2018-07-19', 'https://ebd.cda.pl/620x368/381634300');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18106, 1039, 3, CONCAT('Thus Spoke Kishibe Rohan: The Run'), '2020-03-25', 'https://ebd.cda.pl/620x368/5380692c5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18107, 1039, 4, CONCAT('Thus Spoke Kishibe Rohan: At a Confessional'), '2020-03-25', 'https://ebd.cda.pl/620x368/53757751b');
