INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1046, CONCAT('Knights of the Zodiac: Saint Seiya'), CONCAT('Zeus had a daughter named Athena, the goddess of war. A group of youths flocked to Athena fighting to protect her amidst heroic battles as her "Saints". Their proof of being a Saint laid with the battle protector known as Sacred Cloth.<br>
<br>After a virtual eternity, a new struggle is about to unfold now again over the Cloth. A boy named Seiya has crossed way over to Greece to undergo the training to become a Saint and obtained the Cloth, Bronze cloth, the lowest position among Saints. Every Saint takes a constellation as their tutelary god. And Seiya', CHAR(39), 's guardian star is Pegasus. Now, the saints gather together from all over the world to participate in the "Galatic War" - championship of Saints, aiming at the Gold Cloth, the symbol of ruler of the Saints. The curtain for Galatic War has been cut open. During the death battle between the Saints, Phoenix, the Black Saint, suddenly appeared on the scene and runs off with Gold Cloth in front of a full house in his ambition to become ruler of the world. Seiya and his fellow bronze cloth warriors go after Phoenix and his "Shadow Army" to retrieve the lost Gold Cloth...<br>
<br>The battles waged among the saints, the strongest young men on earth, begin now!<br>
<br>(Source: Toei Animation)'), 1, '2019-07-19', '2020-01-23', '', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1091/101664.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (475, 1046, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2526, 1046, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2527, 1046, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2528, 1046, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1136, 1046, 1);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18194, 1046, 1, CONCAT('Seiya'), '2019-07-19', 'https://www.mp4upload.com/embed-f6gijar920hs.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18195, 1046, 2, CONCAT('Burn Your Cosmo'), '2019-07-19', 'https://www.mp4upload.com/embed-0guu1bvpazfy.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18196, 1046, 3, CONCAT('Enter The Dragon'), '2019-07-19', 'https://www.mp4upload.com/embed-tdhxgyrzxc2l.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18197, 1046, 4, CONCAT('Nebula Chain'), '2019-07-19', 'https://www.mp4upload.com/embed-okprw6wq2jz6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18198, 1046, 5, CONCAT('The Black Knights'), '2019-07-19', 'https://www.mp4upload.com/embed-r46a7zq19pg6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18199, 1046, 6, CONCAT('Phoenix Rising'), '2019-07-19', 'https://www.mp4upload.com/embed-bp6nqpo39vqc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18200, 1046, 7, CONCAT('The Silver Knights'), '2020-01-23', 'https://www.mp4upload.com/embed-q68aev76sndm.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18201, 1046, 8, CONCAT('The Rising Tide'), '2020-01-23', 'https://www.mp4upload.com/embed-yjorynmka5wn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18202, 1046, 9, CONCAT('To Fight For Athena'), '2020-01-23', 'https://www.mp4upload.com/embed-y87ywkb3wliu.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18203, 1046, 10, CONCAT('The Challenge'), '2020-01-23', 'https://www.mp4upload.com/embed-ftuvpmqo22di.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18204, 1046, 11, CONCAT('The Prophecy'), '2020-01-23', 'https://www.mp4upload.com/embed-uxg9sasucakn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18205, 1046, 12, CONCAT('One War Ends, Another Begins'), '2020-01-23', 'https://www.mp4upload.com/embed-uju6pasrhn73.html');
