INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1048, CONCAT('Kobayashi-san Chi no Maid Dragon S'), CONCAT('As Tooru continues on her quest to become the greatest maid and Kanna Kamui fully immerses in her life as an elementary school student, there is not a dull day in the Kobayashi household with mischief being a daily staple. On one such day, however, a massive landslide is spotted on the hill where Kobayashi and Tooru first met—a clear display of a dragon', CHAR(39), 's might. When none of the dragons they know claim responsibility, the perpetrator herself descends from the skies: Ilulu, the radical Chaos Dragon with monstrous power rivaling that of Tooru.<br>
<br>Sickened by Tooru', CHAR(39), 's involvement with humans, Ilulu resorts to the typical dragon method of resolving conflict—a battle to the death. Despite such behavior, she becomes intrigued by Kobayashi', CHAR(39), 's ability to befriend dragons and decides instead to observe just what makes Kobayashi so special. With a new troublesome dragon in town, Kobayashi', CHAR(39), 's eccentric life with a dragon maid is only getting merrier.<br>
<br>[Written by MAL Rewrite]'), 1, '2021-07-08', '2021-09-23', 'Summer 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1252/115539.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (749, 1048, '"Ai no Supreme (愛のシュプリーム！)"', ' by fhána', 'js-theme-songs', 'https://open.spotify.com/track/03FUnhSnPO95g1JNsxSraj')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2533, 1048, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2534, 1048, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1138, 1048, 14);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18230, 1048, 1, CONCAT('New Dragon, Ilulu! (Please Be Nice to Her Again)'), '2021-07-08', 'https://drive.google.com/file/d/1fuk-q6YBaBRnBX-xyOl7ocG_S1bnY7d6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18231, 1048, 2, CONCAT('Hot Guy Kobayashi! (In Many Senses)'), '2021-07-15', 'https://drive.google.com/file/d/1wLT8WhxzkYHWl1HKepZtw8epnhuUX5KM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18232, 1048, 3, CONCAT('Extracurricular Activities (Of Course They', CHAR(39), 're Not Normal)'), '2021-07-22', 'https://drive.google.com/file/d/1kslIKNI7zvewMOR7gM_cpboPv9vAd6BP/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18233, 1048, 4, CONCAT('When in Rome, Do as the Romans Do (It', CHAR(39), 's Hard to Match Others)'), '2021-07-29', 'https://ebd.cda.pl/620x395/8064557c6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18234, 1048, 5, CONCAT('Together With You (Well, If We Get Along)'), '2021-08-05', 'https://drive.google.com/file/d/1jy0NoI_X5syl6vg3fteP59NNGPruW760/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18235, 1048, 6, CONCAT('Uncanny Relationships (One Side Is a Dragon)'), '2021-08-12', 'https://drive.google.com/file/d/1GNIugqB_DVFZuYmc7gmA8aOEvzNT2xyA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18236, 1048, 7, CONCAT('Common Sense (It', CHAR(39), 's Different For Everyone)'), '2021-08-19', 'https://ebd.cda.pl/620x395/8195624b6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18237, 1048, 8, CONCAT('The World', CHAR(39), 's Only (Insert Phrase You Like Here)'), '2021-08-26', 'https://ebd.cda.pl/620x395/82463546e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18238, 1048, 9, CONCAT('There Are Various Reasons Behind It (It', CHAR(39), 's Full of Elma)'), '2021-09-02', 'https://ebd.cda.pl/620x395/83339219d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18239, 1048, 10, CONCAT('Kanna', CHAR(39), 's Summer Break (Broadcast In Two Languages!?)'), '2021-09-09', 'https://ebd.cda.pl/620x368/8416659a0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18240, 1048, 11, CONCAT('Premium Seat (No Extra Charge)'), '2021-09-16', 'https://drive.google.com/file/d/18ExMhxvLwMoYNKWHZjdHX8HyZX7lonST/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18241, 1048, 12, CONCAT('Life is Constant Change (But It', CHAR(39), 's Okay To Stop And Appreciate It)'), '2021-09-23', 'https://drive.google.com/file/d/1cCI_gb9SujzqKUkDppmv0cYWiTBBvvgi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18242, 1048, 13, CONCAT('Japanese Hospitality (The Attendant Is a Dragon)'), NULL, 'https://drive.google.com/file/d/1ETSWeeTfTFIRfhyjju7tOqjBbO2F38t3/view');
