INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1056, CONCAT('Koi wa Ameagari no You ni'), CONCAT('Akira Tachibana, a reserved high school student and former track runner, has not been able to race the same as she used to since she experienced a severe foot injury. And although she is regarded as attractive by her classmates, she is not interested in the boys around school.<br>
<br>While working part-time at the Garden Cafe, Akira begins to develop feelings for the manager—a 45-year-old man named Masami Kondou—despite the large age gap. Kondou shows genuine concern and kindness toward the customers of his restaurant, which, while viewed by others as soft or weak, draws Akira to him. Spending time together at the restaurant, they grow closer, which only strengthens her feelings. Weighed down by these uncertain emotions, Akira finally resolves to confess, but what will be the result?<br>
<br>[Written by MAL Rewrite]'), 1, '2018-01-12', '2018-03-30', 'Winter 2018', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1271/90136.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (754, 1056, '"Nostalgic Rainfall (ノスタルジックレインフォール)"', ' by CHiCO with HoneyWorks', 'js-theme-songs', 'https://open.spotify.com/track/5mwLIUyGIg6QioPbyHgt2s')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (476, 1056, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2557, 1056, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2558, 1056, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1146, 1056, 158);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18318, 1056, 1, CONCAT('The Sound of Rain'), '2018-01-12', 'https://drive.google.com/file/d/1YuVyJJV1RowBKiNSVXh1DY8cIKic0FWK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18319, 1056, 2, CONCAT('Rain Drops On Green Leaves'), '2018-01-19', 'https://drive.google.com/file/d/10Z8TDiJajNBN6wpnsXim8IjScxop1ij2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18320, 1056, 3, CONCAT('Raining Tears'), '2018-01-26', 'https://drive.google.com/file/d/1hpyKwF3ECw4pe0JDIDi44kGymOFgKcYh/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18321, 1056, 4, CONCAT('Gentle Rain'), '2018-02-02', 'https://drive.google.com/file/d/1KD4fXq32w50q1QyyF-9NBbnEhZ4KG9FU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18322, 1056, 5, CONCAT('The Scent of Rain'), '2018-02-09', 'https://drive.google.com/file/d/1rptOjbiL4VHZ9MlXIN2BcTc2di106fDo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18323, 1056, 6, CONCAT('Fine Rain'), '2018-02-16', 'https://drive.google.com/file/d/11N3fQjl9H5_07ACofOWehhDpMlBkUQmw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18324, 1056, 7, CONCAT('Heavy Rain'), '2018-02-23', 'https://drive.google.com/file/d/16c4MIoJDDB20e063vPLSteoP3hDu5nW5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18325, 1056, 8, CONCAT('Quiet Rain'), '2018-03-02', 'https://drive.google.com/file/d/1ZgvRNHoTXSri9LCx8a7IEsgfSbxzOcZK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18326, 1056, 9, CONCAT('Rain of Sorrow'), '2018-03-09', 'https://drive.google.com/file/d/1Sa3Ddv3kvYemB71E3ctvgFLoxiEcygv8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18327, 1056, 10, CONCAT('Sudden Shower'), '2018-03-16', 'https://drive.google.com/file/d/13mgFNRQZEbl0ouUZwE8ajYqJl1FjXOSE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18328, 1056, 11, CONCAT('Passing Shower'), '2018-03-23', 'https://drive.google.com/file/d/1cuq6UiGsJC0vLWKf-U4zEyPL7SVcn9kH/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18329, 1056, 12, CONCAT('After the Rain'), '2018-03-30', 'https://drive.google.com/file/d/1uHoyWDHZ_WsCJ3aVRmMTDbI0RzeqqCFe/preview');
