INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1079, CONCAT('Koufuku Graffiti'), CONCAT('The path to becoming a fine wife begins with being an accomplished cook—at least, that is what Ryou Machiko', CHAR(39), 's late grandmother had led her to believe. For a middle schooler, Ryou', CHAR(39), 's cooking skills are incomparable but recently, though Ryou', CHAR(39), 's food looks appetizing and smells inviting, the taste has not been delicious. Just when the dejected art student comes to terms with the possibility that she might continue living alone for the rest of her life, her aunt tells her that Kirin Morino—Ryou', CHAR(39), 's second cousin—will begin staying with her every weekend since the younger girl has joined a cram school in Tokyo and aims to attend the same school as Ryou.<br>
<br>Surprisingly, with her cousin', CHAR(39), 's arrival, Ryou finds that her cooking has vastly improved—apparently, it is not her prowess in the kitchen, but the sharing of the experience with those closest to her that seems to make the flavors shine.<br>
<br>[Written by MAL Rewrite]'), 1, '2015-01-09', '2015-03-27', 'Winter 2015', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/71963.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (485, 1079, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2622, 1079, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2623, 1079, 15);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2624, 1079, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1170, 1079, 7);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18567, 1079, 1, CONCAT('Warm, Juicy.'), '2015-01-09', 'https://video.sibnet.ru/shell.php?videoid=1651669');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18568, 1079, 2, CONCAT('Fluffy, Sizzling.'), '2015-01-16', 'https://drive.google.com/file/d/0B85PwG_7jyJrcGt6dVFSbjZWbEE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18569, 1079, 3, CONCAT('Crispy, Dripping.'), '2015-01-23', 'https://video.sibnet.ru/shell.php?videoid=1700778');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18570, 1079, 4, CONCAT('Slowly, Crumbly.'), '2015-01-30', 'https://video.sibnet.ru/shell.php?videoid=1710089');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18571, 1079, 5, CONCAT('Slurp, Gulp.'), '2015-02-06', 'https://video.sibnet.ru/shell.php?videoid=1722440');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18572, 1079, 6, CONCAT('Hot, Springy'), '2015-02-13', 'https://video.sibnet.ru/shell.php?videoid=1726911');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18573, 1079, 7, CONCAT('Sizzle, Pop.'), '2015-02-20', 'https://video.sibnet.ru/shell.php?videoid=1739315');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18574, 1079, 8, CONCAT('Piping Hot, Chomp.'), '2015-02-27', 'https://drive.google.com/file/d/0B_3kG9ENKEEaSlZRQkpCZkxTT2s/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18575, 1079, 9, CONCAT('Bubbling, Huff-Puff...'), '2015-03-06', 'https://video.sibnet.ru/shell.php?videoid=1747597');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18576, 1079, 10, CONCAT('Chewy, Melty.'), '2015-03-13', 'https://video.sibnet.ru/shell.php?videoid=1759484');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18577, 1079, 11, CONCAT('Searing, Slurping.'), '2015-03-20', 'https://video.sibnet.ru/shell.php?videoid=1758905');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18578, 1079, 12, CONCAT('Soaked Up, Squeeze.'), '2015-03-27', 'https://video.sibnet.ru/shell.php?videoid=1761773');
