INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1108, CONCAT('Kyoukai Senki Part 2'), CONCAT('Second part of Kyoukai Senki.'), 1, '2022-04-12', '2022-06-28', 'Spring 2022', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1968/122304.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (793, 1108, '"Overload"', ' by Yuuna Fukinbara (富金原佑菜)', 'js-theme-songs', 'https://open.spotify.com/track/5V6AiDZLS838X2NceqiPja')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2695, 1108, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2696, 1108, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1202, 1108, 111);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1222, 1108, 20);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1223, 1108, 25);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1224, 1108, 45);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18995, 1108, 1, CONCAT('Eight Months Later'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4799298');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18996, 1108, 2, CONCAT('Reunion'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4799300');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18997, 1108, 3, CONCAT('Fierce Battle'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4799303');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18998, 1108, 4, CONCAT('TRYVECTA'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4799293');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (18999, 1108, 5, CONCAT('The Sanctuary'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4900892');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19000, 1108, 6, CONCAT('Anniversary'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4942386');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19001, 1108, 7, CONCAT('New Japan Cooperation Organization'), NULL, 'https://dood.pm/e/xz9s7wefqj79');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19002, 1108, 8, CONCAT('Signs of Upheaval'), NULL, 'https://dood.pm/e/xql86h6a10d3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19003, 1108, 9, CONCAT('Fugitives'), NULL, 'https://dood.pm/e/l122dlpptugr');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19004, 1108, 10, CONCAT('Outbreak of War'), NULL, 'https://dood.pm/e/6foypjyzayg7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19005, 1108, 11, CONCAT('Hokuriku Frontline (Part 1)'), NULL, 'https://dood.pm/e/x7ofiftshlj5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19006, 1108, 12, CONCAT('Hokuriku Frontline (Part 2)'), NULL, 'https://dood.pm/e/wnik72cdoydw');
