INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1113, CONCAT('Kyuukyoku Shinka shita Full Dive RPG ga Genjitsu yori mo Kusoge Dattara'), CONCAT('Ten years ago, at the peak of the VRMMO development industry, a game titled "Kiwame Quest" entered the scene with potential like no other. Boasting a colossal total of 10 sexdecillion branches of possible story scenarios, this game pursued ultimate realism, ranging from humanlike NPCs to the perfect replication of all senses and physical abilities. But it soon became apparent that the game was too realistic, and the popularity of VRMMOs in general gradually began to plunge.<br>
<br>At present, due to an accident a few years prior, the high school student Hiroshi Yuuki now immerses himself in full-dive RPGs as a form of escapism. After failing to acquire the latest version of his favorite game, Hiroshi stumbles upon a game shop and meets its beautiful clerk Reona Kisaragi who convinces him to buy a copy of Kiwame Quest so that they can play together. <br>
<br>The first time Hiroshi plays the game, he marvels at the realism it offers. However, his astonishment is short-lived as he sets off a series of misfortunes, quickly realizing that the game is even worse than his already stressful life. Nevertheless, Hiroshi still finds himself logging on again despite his growing contempt for the game. With no do-overs in his current disadvantageous situation, Hiroshi only has one goal—clearing the game!<br>
<br>[Written by MAL Rewrite]'), 1, '2021-04-07', '2021-06-23', 'Spring 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1357/113277.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (796, 1113, '"ANSWER"', ' by Mayu Maeshima', 'js-theme-songs', 'https://open.spotify.com/track/7urK9cyTl4Qx1WsRoVXzNG')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2707, 1113, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2708, 1113, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2709, 1113, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1207, 1113, 168);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19081, 1113, 1, CONCAT('VR⨯Reality'), '2021-04-07', 'https://ebd.cda.pl/620x368/7201081ba');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19082, 1113, 2, CONCAT('Living in a Dead Game'), '2021-04-14', 'https://ebd.cda.pl/620x368/725351290');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19083, 1113, 3, CONCAT('Adult Event Time'), '2021-04-21', 'https://ebd.cda.pl/620x368/7308136ff');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19084, 1113, 4, CONCAT('The Only One to Beat the Game'), NULL, 'https://ebd.cda.pl/620x368/736694850');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19085, 1113, 5, CONCAT('The Tribulation of a Killer'), NULL, 'https://ebd.cda.pl/620x368/743041901');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19086, 1113, 6, CONCAT('Knife vs. Saw'), NULL, 'https://ebd.cda.pl/620x368/7476658c9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19087, 1113, 7, CONCAT('Chance of Survival 0.1%'), NULL, 'https://ebd.cda.pl/620x368/751691871');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19088, 1113, 8, CONCAT('Enlistment and Baptism'), NULL, 'https://ebd.cda.pl/620x368/7563337a7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19089, 1113, 9, CONCAT('A Fairy', CHAR(39), 's Power'), NULL, 'https://ebd.cda.pl/620x368/76277432c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19090, 1113, 10, CONCAT('A New Ally'), NULL, 'https://ebd.cda.pl/620x368/769219233');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19091, 1113, 11, CONCAT('City of Dead Ends'), NULL, 'https://ebd.cda.pl/620x368/77404902b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19092, 1113, 12, CONCAT('Reality⨯VR'), NULL, 'https://ebd.cda.pl/620x368/77841095c');
