INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1127, CONCAT('Litchi DE Hikari Club'), CONCAT('Litchi DE Hikari Club takes place in an alternate reality where the Hikari Club does not fall into disarray after the completion of Litchi, the intelligent humanlike robot the club invented to kidnap girls.<br>
<br>The cult-like Hikari Club has had its ups and downs. Led by the enigmatic, beauty-obsessed Hiroyuki "Zera" Tsunekawa, the club has finally succeeded in using their fruit-powered robot, Litchi, to kidnap the beautiful Kanon. After accomplishing their goals, the Hikari Club has little to do other than delight in their newfound lives. From selling the technology that allows Litchi to run on lychee fruit, to modifying the robot to perform different tasks, there', CHAR(39), 's no telling what antics the Hikari Club will get up to next!<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2012-10-02', '2012-11-20', 'Fall 2012', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1083/116746.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (805, 1127, '"Haikyo no Teiou (廃墟の☆帝王)"', ' by Litchi ☆ Hikari Club', 'js-theme-songs', 'https://open.spotify.com/track/6kqiZbPHDGlpiR01Np4VCi');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2738, 1127, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2739, 1127, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2740, 1127, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2741, 1127, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1223, 1127, 201);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19287, 1127, 1, CONCAT('Death Penalty IN the Light Club'), NULL, 'https://video.sibnet.ru/shell.php?videoid=741204');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19288, 1127, 2, CONCAT('Modifications IN the Light Club'), NULL, 'https://video.sibnet.ru/shell.php?videoid=741213');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19289, 1127, 3, CONCAT('Patents IN the Light Club'), NULL, 'https://vk.com/video_ext.php?oid=181137122&id=163452989&hash=3f26d4a085049b02');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19290, 1127, 4, CONCAT('Investigation IN the Light Club'), NULL, 'https://myvi.ru/player/embed/html/oEO16_6NBNBOdNpoPq8Gcyu_5kJKxHxggKBg7gIIqSB8oQPmbWm-hkDYj5eBm54Py0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19291, 1127, 5, CONCAT('Band IN the Light Club'), NULL, 'https://video.sibnet.ru/shell.php?videoid=753155');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19292, 1127, 6, CONCAT('Fuel IN the Light Club'), NULL, 'https://myvi.ru/player/embed/html/o6YQ-mA-yk-6UBc_QYKCtXIZ95SKrE_KW5e4K0k3doaWoyCWXaGyzN7nHyQESlzlP0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19293, 1127, 7, CONCAT('Beach IN the Light Club'), NULL, 'https://myvi.ru/player/embed/html/oUb7eTtPk1me8SmHnV03aHimSYOdM1o_QJx9qcFsmuF6eFjx0PU70AsyOqxvhx5bi0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19294, 1127, 8, CONCAT('Loyalty IN the Light Club'), NULL, 'https://vk.com/video_ext.php?oid=181137122&id=163748329&hash=4fe6e46404774fe4');
