INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1165, CONCAT('Magatsu Wahrheit: Zuerst'), CONCAT('In the technologically and magically advanced Wahrheit Empire, rumors of a returning catastrophe known only as the "light" causes a disturbance amongst the people. Meanwhile, in the capital of the Empire, transporter Innumael Grauer prepares his daily deliveries, struggling to make ends meet for himself and his sister. Leocadio Wöhler, a newly recruited soldier, assists Innumael whilst commuting to work—unknowingly loading a mysterious package containing contraband artillery belonging to a criminal organization.<br>
<br>Innumael is accused of smuggling the package, facing possible execution due to the Empire', CHAR(39), 's strict oversight of weapons in response to the rising disorder. However, unbeknownst to him, the very syndicate that placed him in this unfortunate predicament may save him from this fate, at least temporarily. Elsewhere, Leocadio is assigned his first mission—to apprehend the criminal group known as "Headkeeper," suspected of transporting illegal weaponry.<br><br>Magatsu Wahrheit: Zuerst follows these two young men on a journey encompassing the Wahrheit Empire, triggering a chain of events that will not only change their lives but also alter the course of the Empire as they know it.<br>
<br>[Written by MAL Rewrite]'), 1, '2020-10-13', '2020-12-29', 'Fall 2020', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1109/108983.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (826, 1165, '"Kimi wo Sukueru nara Boku wa Nani ni demo Naru (君を救えるなら僕は何にでもなる)"', ' by Maon Kurosaki', 'js-theme-songs', 'https://open.spotify.com/track/0YqCJMmlkBOpvqoKK8pGaj')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2835, 1165, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2836, 1165, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1262, 1165, 200);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19899, 1165, 1, CONCAT('The Getaway: Part One'), '2020-10-13', 'https://ebd.cda.pl/620x368/5958377f8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19900, 1165, 2, CONCAT('The Getaway: Part Two'), '2020-10-20', 'https://ebd.cda.pl/620x368/5994068e3');
