INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1166, CONCAT('Magi: Sinbad no Bouken'), CONCAT('Not so long ago, mysterious structures called Dungeons began appearing all over the world. No one knows what they are or how they came to be, but adventurers and armies around the world instantly took interest in them. Thousands set out to explore the Dungeons, but so far, not a single person has returned.<br>
<br>In a Parthevian port, a young boy is about to make a name for himself. Sinbad is good-natured, strong, and craving adventure. A kind deed leads to his meeting with Yunan, an enigmatic traveler who is far more powerful than his frivolous personality lets on. Yunan instructs Sinbad to attain the "power of the king" and change the world—by conquering a Dungeon. The eager boy readily accepts, setting out on the grand adventure he so craved.<br>
<br>Taking place 15 years before the events of the original series, Magi: Sinbad no Bouken chronicles Sinbad', CHAR(39), 's youth as a Dungeon conqueror. Along the way, the budding adventurer and merchant will have to face many obstacles, but anything is possible with the power of a king.<br>
<br>[Written by MAL Rewrite]'), 3, '2014-05-14', '2015-07-15', '', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/60471.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (514, 1166, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2837, 1166, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2838, 1166, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2839, 1166, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1263, 1166, 62);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19901, 1166, 1, CONCAT('The Capture of Baal Dungeon, Part 1'), '2014-05-14', 'https://www.mp4upload.com/embed-n55jljv17xzb.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19902, 1166, 2, CONCAT('The Capture of Baal Dungeon, Part 2'), '2014-08-12', 'https://mp4upload.com/embed-1bgquvghp49u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19903, 1166, 3, CONCAT('The Capture of Valefor Dungeon, Part 1'), '2014-12-16', 'https://www.mp4upload.com/embed-nvjkib967pef.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19904, 1166, 4, CONCAT('The Capture of Valefor Dungeon, Part 2'), '2015-04-15', 'https://www.mp4upload.com/embed-59l69d7tv4oh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19905, 1166, 5, CONCAT('The Capture of Valefor Dungeon, Part 3'), '2015-07-15', 'https://mp4upload.com/embed-b1a5whe1198r.html');
