INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1188, CONCAT('Mahoutsukai no Yome: Hoshi Matsu Hito'), CONCAT('After many hardships in her life, Chise Hatori ended up at an auction, where she was purchased and then freed by the renowned Thorn Sorcerer, Elias Ainsworth, only to stay and become his apprentice. Though her life is wonderful now, the arrival of a picture book, "The Lonely Little Star," brings back memories of those trying times and the loneliness she endured.<br>
<br>As a child, Chise experienced a great tragedy: her mother', CHAR(39), 's death. Shunned and unwanted by peers and relatives alike, she has lived a detached and pitiful life. However, the unexpected discovery of a mysterious library in the forest provides her with a temporary place of solace. Through reading countless books and spending time with the kindhearted librarian, Chise slowly begins to feel less alone in the world. But could this peculiar library have a darker side?<br>
<br>[Written by MAL Rewrite]'), 3, '2016-09-10', '2017-09-09', '', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/80587.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (839, 1188, '"CLOCKWORK QUICK AND LIGHTNING SLOW"', ' by Julia Shortreed', 'js-theme-songs', 'https://open.spotify.com/track/1j5z7j0iSfbictHdIcZhQl');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (522, 1188, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2890, 1188, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2891, 1188, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1286, 1188, 158);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20275, 1188, 1, CONCAT('Episode 1'), '2016-09-10', 'https://drive.google.com/file/d/1gVHgv8OCstnd1zi6vq0LfKRGpFGfDuju/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20276, 1188, 2, CONCAT('Episode 2'), '2017-03-10', 'https://ebd.cda.pl/620x395/6423053ff');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20277, 1188, 3, CONCAT('Episode 3'), '2017-09-09', 'https://drive.google.com/file/d/1hG9gzk65wrRLoO92VVWFzk-YPeqHYauM/preview');
