INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1200, CONCAT('Majin Bone'), CONCAT('Anime adaptation of Majin Bone, a digital card game project.<br>
<br>Majin, the creator of the Universe, has been resurrected in the present day. Shougo Ryuujin, an ordinary high school student who transforms into the Bone Fighter Dragonbone with the Bone Card in order to save Earth. Together, with the other White Bone warriors take a stand against the Dark Bone, a foe that has appeared from darkness to devastate Earth. However, "could the true enemy be ourselves?"<br>
<br>(Source: ANN)'), 1, '2014-04-01', '2015-03-31', 'Spring 2014', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1490/90396.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (844, 1200, '"Legend Is Born"', ' by Kazuki Katou (加藤和樹)', 'js-theme-songs', 'https://open.spotify.com/track/58J2ByjmJJ1WZOrkmEBeOV')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (530, 1200, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2925, 1200, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2926, 1200, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2927, 1200, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2928, 1200, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1299, 1200, 171);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20643, 1200, 1, CONCAT('Visitors From the Darkness'), NULL, 'https://vk.com/video_ext.php?oid=201041148&id=168279855&hash=fdcb90954df548e2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20644, 1200, 2, CONCAT('Chosen Warrior'), NULL, 'https://drive.google.com/file/d/0B3g2KqMctI9qR2Rac2dNVmNQeVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20645, 1200, 3, CONCAT('Rejection of Bone'), NULL, 'https://drive.google.com/file/d/0B3g2KqMctI9qMjVBbm9yS1JwSnc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20646, 1200, 4, CONCAT('Warrior', CHAR(39), 's Resolution'), NULL, 'https://drive.google.com/file/d/0B3g2KqMctI9qVXdFMF8tNGNEVUk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20647, 1200, 5, CONCAT('Majin Descends'), NULL, 'https://vk.com/video250056004_168491290');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20648, 1200, 6, CONCAT('Believe in Yourself'), NULL, 'https://drive.google.com/file/d/0B_wqRYJzCdS3eUlndG9WYjZ1REE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20649, 1200, 7, CONCAT('Bone Research Facility'), NULL, 'https://drive.google.com/file/d/0BwJ-0P1ovtKESkNQc2hsUlkzb2c/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20650, 1200, 8, CONCAT('Invaders'), NULL, 'https://mp4upload.com/embed-7tv8opptvx9g.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20651, 1200, 9, CONCAT('Fierce Resonance'), NULL, 'https://drive.google.com/file/d/0B15WO7xgBq0IRUVTZFJXaGRBeTg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20652, 1200, 10, CONCAT('A Daily Life Worth Protecting'), NULL, 'https://video.sibnet.ru/shell.php?videoid=2138095');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20653, 1200, 11, CONCAT('The Primordial Majin'), NULL, 'https://drive.google.com/file/d/0Bx0HQ6Ndm4f5RHRhc1QyMnVZLWM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20654, 1200, 12, CONCAT('Dragon', CHAR(39), 's Rampage'), NULL, 'https://drive.google.com/file/d/0BzvxohbkF3bvZmRMWUl1ajF2NDA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20655, 1200, 13, CONCAT('True Strength'), NULL, 'https://drive.google.com/file/d/0ByRHoFS6b0rRWVJQM213blh2U00/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20656, 1200, 14, CONCAT('Shark', CHAR(39), 's Rampage'), NULL, 'https://drive.google.com/file/d/0ByRHoFS6b0rRWjBidzJEcUpvREU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20657, 1200, 15, CONCAT('Shaken Destiny'), NULL, 'https://drive.google.com/file/d/0B7XlJcBUPJWMOEtpdmR2SlRabjQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20658, 1200, 16, CONCAT('Will of Steel'), NULL, 'https://drive.google.com/file/d/0B9ff_wFjw0T_WnFES0hVWlV2SU0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20659, 1200, 17, CONCAT('Gentle Big Brother'), NULL, 'https://drive.google.com/file/d/0B7XlJcBUPJWMMUJSbXVSZlVJQVE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20660, 1200, 18, CONCAT('Stray Cats and Stray Dogs'), NULL, 'https://drive.google.com/file/d/0B9LAVlU15MBaS2hfMlA1ZDByOVk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20661, 1200, 19, CONCAT('Iron Bone'), NULL, 'https://vk.com/video250056004_169563468');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20662, 1200, 20, CONCAT('The Shadow of the Traitors'), NULL, 'https://vk.com/video250056004_169653357');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20663, 1200, 21, CONCAT('Three of Iron'), NULL, 'https://drive.google.com/file/d/0B_CeHsXvKFXXUVl3Yl8xODhhLWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20664, 1200, 22, CONCAT('Dragon', CHAR(39), 's Awakening'), NULL, 'https://drive.google.com/file/d/0B_CeHsXvKFXXZDZBaWVXdGdVNXc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20665, 1200, 23, CONCAT('Family Portrait'), NULL, 'https://drive.google.com/file/d/0B_CeHsXvKFXXb0h4RXNONExxOG8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20666, 1200, 24, CONCAT('Unstoppable Urge'), NULL, 'https://embed.tune.pk/play/4515165');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20667, 1200, 25, CONCAT('Cerberus'), NULL, 'https://vk.com/video_ext.php?oid=202464706&id=170036460&hash=a4d7ab7bf3461b1a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20668, 1200, 26, CONCAT('The Brothers', CHAR(39), ' Past'), NULL, 'https://drive.google.com/file/d/0B8xJx_BMIvo_Z0JSVUFIdEI4bTQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20669, 1200, 27, CONCAT('Stirring Ambition'), NULL, 'https://drive.google.com/file/d/0B8xJx_BMIvo_cGJicEwtMk1OZmc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20670, 1200, 28, CONCAT('Coup d', CHAR(39), 'Etat'), NULL, 'https://vk.com/video_ext.php?oid=202464706&id=170229059&hash=4fe311f4b92baee5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20671, 1200, 29, CONCAT('To Nepos!'), NULL, 'https://vk.com/video272448577_170311028');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20672, 1200, 30, CONCAT('Wyvern vs. Cerberus'), NULL, 'https://drive.google.com/file/d/0BzP_5dQGK87PcTJ4LTJFZl8tdjQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20673, 1200, 31, CONCAT('Aid from Space'), NULL, 'https://streamtape.com/e/q9mMdAljpAuzbB4/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20674, 1200, 32, CONCAT('The Truth of 12 Years Ago'), NULL, 'https://streamtape.com/e/JbqWma3rvoiJDY/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20675, 1200, 33, CONCAT('Being a Family'), NULL, 'https://streamtape.com/e/BQog3PoZoKCyYOj/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20676, 1200, 34, CONCAT('Ouroboros Descends'), NULL, 'https://streamtape.com/e/ezKqBOPjOyTYBr9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20677, 1200, 35, CONCAT('Pride of the Eques'), NULL, 'https://streamtape.com/e/MPMQeGJegbhmX3R/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20678, 1200, 36, CONCAT('Rare Metal Bone'), NULL, 'https://streamtape.com/e/QWLyDdYj43f0ZJl/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20679, 1200, 37, CONCAT('The Mystery of Rare Metal'), NULL, 'https://streamtape.com/e/0JDrvMer63Te6O/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20680, 1200, 38, CONCAT('As a Warrior of Nepos'), NULL, 'https://streamtape.com/e/mwBbrw9Y4dCVkO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20681, 1200, 39, CONCAT('Cerberus, to Earth!'), NULL, 'https://streamtape.com/e/wOV7jmwRq8spVm/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20682, 1200, 40, CONCAT('Melbourne Assault'), NULL, 'https://streamtape.com/e/oW0q8lVpkkFKVB/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20683, 1200, 41, CONCAT('The Road Taken, the Road You Must Take'), NULL, 'https://streamtape.com/e/8VgaJaYlvDSGrR/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20684, 1200, 42, CONCAT('Calm Fury'), NULL, 'https://streamtape.com/e/qJWjo1doO8SzgZ2/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20685, 1200, 43, CONCAT('Changing Despair into Hope'), NULL, 'https://streamtape.com/e/MkJmmO9OeRSmRA9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20686, 1200, 44, CONCAT('Majin, Once More'), NULL, 'https://streamtape.com/e/m98PO2pjj6TbJb1/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20687, 1200, 45, CONCAT('Wriggling Desires'), NULL, 'https://streamtape.com/e/bG2JQkGWvDIRxl/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20688, 1200, 46, CONCAT('Unchanging Strength'), NULL, 'https://streamtape.com/e/OqeQggD1lXSZO3D/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20689, 1200, 47, CONCAT('Forbidden Memory'), NULL, 'https://streamtape.com/e/yd9azg9DgWc1Vl8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20690, 1200, 48, CONCAT('Roar of Treason'), NULL, 'https://streamtape.com/e/KZkGwb80PVh00rP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20691, 1200, 49, CONCAT('Wolf and Tiger'), NULL, 'https://streamtape.com/e/rejvqQoBYatbJea/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20692, 1200, 50, CONCAT('The Joining of the End'), NULL, 'https://streamtape.com/e/Q3v0ovzogRs00Lo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20693, 1200, 51, CONCAT('The Beginning of the End'), NULL, 'https://streamtape.com/e/YGvBP2Vxk9sODo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20694, 1200, 52, CONCAT('Somewhere to Return'), NULL, 'https://streamtape.com/e/b1Km3RAmr8iPz0Q/');
