INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1211, CONCAT('Makeruna!! Aku no Gundan!'), CONCAT('After coming across an advertisement about how anyone can lead an invasion force, young Don decides to establish a ragtag squad of his own to conquer the cosmos. Working alongside him are the aloof Pepu and the gaming-obsessed Chiku, though the value of their membership remains somewhat questionable. With his two henchmen by his side, the crew', CHAR(39), 's inexperienced leader sets his sights on their first target: Earth.<br>
<br>According to the manuals, Earth should be a simple enough target, but the situation spirals out of control right from the start. As it turns out, convincing over seven billion humans to simply roll over and accept their new overlord is no easy feat. Having been blown off by the entire human species, Don and his squadron touch down on Earth and begin their search for a way to subjugate humanity. However, with their unexpected failure, they face more pressing issues—namely, finding food and paying rent—so their plans for galactic domination will have to be put on hold for a little longer.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-04-05', '2017-06-21', 'Spring 2017', '4 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/84731.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2961, 1211, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2962, 1211, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2963, 1211, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1310, 1211, 23);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20881, 1211, 1, CONCAT('Don', CHAR(39), 't Lose!! Evil Corps!'), NULL, 'https://www.mp4upload.com/embed-0tqbml22g5al.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20882, 1211, 2, CONCAT('It', CHAR(39), 's a Talking Hippo'), NULL, 'https://www.mp4upload.com/embed-fm3z6gclutc1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20883, 1211, 3, CONCAT('Convenience Store'), NULL, 'https://www.mp4upload.com/embed-bvhzo4jpj1sm.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20884, 1211, 4, CONCAT('Boss Chick'), NULL, 'https://www.mp4upload.com/embed-546blwqqvpa1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20885, 1211, 5, CONCAT('It', CHAR(39), 's on Fire...'), NULL, 'https://www.mp4upload.com/embed-76t0o49dcbwg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20886, 1211, 6, CONCAT('Memories'), NULL, 'https://www.mp4upload.com/embed-kvm5jeuri7bz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20887, 1211, 7, CONCAT('We Can Never Go Home'), NULL, 'https://www.mp4upload.com/embed-rfkmy81x96eh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20888, 1211, 8, CONCAT('Fight'), NULL, 'https://www.mp4upload.com/embed-8wx94mk4hbjz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20889, 1211, 9, CONCAT('Alone'), NULL, 'https://www.mp4upload.com/embed-ph94syy20str.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20890, 1211, 10, CONCAT('Reconciliation'), NULL, 'https://www.mp4upload.com/embed-lnoubzn61145.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20891, 1211, 11, CONCAT('Moving In'), NULL, 'https://www.mp4upload.com/embed-r7is001w8k3n.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20892, 1211, 12, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-lf68wzq2t81h.html');
