INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1228, CONCAT('Masamune-kun no Revenge'), CONCAT('When Masamune Makabe was a child, he was rejected by a rich, beautiful girl named Aki Adagaki, who gave him the nickname ', CHAR(39), '', CHAR(39), 'Piggy', CHAR(39), '', CHAR(39), ' for being overweight. Devastated, Masamune put great effort into working out to improve his appearance. Now a handsome yet narcissistic high school student, Masamune is determined to exact revenge—he will have Aki fall madly in love with him and ultimately reject her the next time they meet.<br>
<br>To his surprise, Masamune discovers he has transferred into Aki', CHAR(39), 's school. Setting his plan into motion, Masamune first begins to form a relationship with the ', CHAR(39), '', CHAR(39), 'Brutal Princess', CHAR(39), '', CHAR(39), ' but, despite his efforts, fails miserably at his initial attempts. Shockingly, when Masamune finally progresses towards his vengeance, he receives a mysterious letter addressing him by his old nickname. Unless Masamune discovers the sender', CHAR(39), 's identity, his plan is doomed before it even starts!<br>
<br>[Written by MAL Rewrite]'), 1, '2017-01-05', '2017-03-23', 'Winter 2017', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/83709.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (540, 1228, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3002, 1228, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3003, 1228, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1326, 1228, 50);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1340, 1228, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1341, 1228, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21057, 1228, 1, CONCAT('The Boy Who Was Called Pig', CHAR(39), 's Foot'), '2017-01-05', 'https://drive.google.com/file/d/1sLpf1sYCxKMC4pmALrrD_5IFDdvnpcc-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21058, 1228, 2, CONCAT('Cinderella Doesn', CHAR(39), 't Smile'), '2017-01-12', 'https://drive.google.com/file/d/1pVNd8NFBEHxqhb6ygeeSuJRk1d1SakGZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21059, 1228, 3, CONCAT('Yoshino', CHAR(39), 's Magic Show'), '2017-01-19', 'https://drive.google.com/file/d/0B8r39dmB_1psU2h4cEV3TVJWYWM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21060, 1228, 4, CONCAT('Clear and Present Danger'), '2017-01-26', 'https://drive.google.com/file/d/14hgZJDuz9weEcfRdE_b2-c44cfnGLnEE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21061, 1228, 5, CONCAT('Mysterious Cat'), '2017-02-02', 'https://drive.google.com/file/d/18qMRn4ruw8XJIH3E6mQAGtQnFJiOr8Mc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21062, 1228, 6, CONCAT('Attack! Battle of the Home Visits'), '2017-02-09', 'https://drive.google.com/file/d/1iFPLsJEplscoE89cZYAHdeiCnVB8I0vZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21063, 1228, 7, CONCAT('The Tsunade Island Incident'), '2017-02-16', 'https://drive.google.com/file/d/1imSYHA9oCj8KeyKOSueDooc_1qPypqpB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21064, 1228, 8, CONCAT('It', CHAR(39), 's Not You'), '2017-02-23', 'https://drive.google.com/file/d/1-xsaCO19fQ06eD3s9KsnkQI6nniDZawR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21065, 1228, 9, CONCAT('It', CHAR(39), 's Been Called Love and Affection'), '2017-03-02', 'https://drive.google.com/file/d/1XSoQjYhNSE04q6iwueE-Ku44EKS_NScA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21066, 1228, 10, CONCAT('The New School Term Filled With Doubts'), '2017-03-09', 'https://drive.google.com/file/d/1aL49VeCCHnMoJBH2tD5D4D4R8LQOUwkW/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21067, 1228, 11, CONCAT('Snow White of the Yasaka Festival'), '2017-03-16', 'https://drive.google.com/file/d/1sgc31y4idaAW7s5Mg0K6i01zXGIqWZJx/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21068, 1228, 12, CONCAT('Don', CHAR(39), 't Let Go of the Mic, Even if You Die'), '2017-03-23', 'https://drive.google.com/file/d/1gP1SbAbuzxIoML1wROI3vT3mCpyxtTle/preview');
