INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1229, CONCAT('Mashiro-iro Symphony: The Color of Lovers'), CONCAT('When boys suddenly get into places where they', CHAR(39), 've never been allowed before, some girls tend to get upset. So when the decision is made to merge the elite Yuihime Girls', CHAR(39), ' Private Academy and the coeducational Kagamidai Private Academy, everyone wants to take extra care in avoiding trouble while bringing the two Privates together. Therefore, rather than just bringing the Kagamidai boys into the Yuihime girls', CHAR(39), ' school all at once, a plan is concocted in which a group of test males will be inserted into the Girls', CHAR(39), ' Private Academy first.<br>
<br>Thus, poor young Shingo finds himself being thrown as a sacrificial lamb to the lionesses of Yuihime, who aren', CHAR(39), 't exactly waiting for him with open arms. Will Shingo manage to survive the estrogen soaked death pit that is Yuihime? Can the girls learn to be more receptive to the boys? And just how long until something involving panties will cause emotions to flare, sparks to fly and the battle of the sexes to explode?<br>
<br>(Source: Sentai Filmworks, edited)'), 1, '2011-10-05', '2011-12-21', 'Fall 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/9/39303.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (861, 1229, '"Authentic symphony"', ' by Choucho', 'js-theme-songs', 'https://open.spotify.com/track/5UlCVMGDdHTAcwQFiOBORj')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3004, 1229, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3005, 1229, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1327, 1229, 17);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1342, 1229, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1343, 1229, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21069, 1229, 1, CONCAT('Pure White Encounter'), NULL, 'https://ebd.cda.pl/800x450/5132895df');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21070, 1229, 2, CONCAT('Rejection-Colored Cooking'), NULL, 'https://ebd.cda.pl/800x450/513578108');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21071, 1229, 3, CONCAT('Annoyance-Colored Anxiety'), NULL, 'https://ebd.cda.pl/800x450/513585343');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21072, 1229, 4, CONCAT('Airi-Colored Secret'), NULL, 'https://ebd.cda.pl/800x450/513589249');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21073, 1229, 5, CONCAT('I am a Your-Colored Maid'), NULL, 'https://ebd.cda.pl/800x450/513591982');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21074, 1229, 6, CONCAT('Search-Colored Bath Time'), NULL, 'https://ebd.cda.pl/800x450/5135946aa');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21075, 1229, 7, CONCAT('Twilight-Colored Swing'), NULL, 'https://ebd.cda.pl/800x450/6196619e2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21076, 1229, 8, CONCAT('Kitten-Colored Black and White'), NULL, 'https://ebd.cda.pl/800x450/51359919c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21077, 1229, 9, CONCAT('Same Colored Couple'), NULL, 'https://ebd.cda.pl/800x450/51360069d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21078, 1229, 10, CONCAT('Tear-Colored Shelter'), NULL, 'https://ebd.cda.pl/800x450/51360335e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21079, 1229, 11, CONCAT('Mashiroiro Symphony'), NULL, 'https://ebd.cda.pl/800x450/5136051fb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21080, 1229, 12, CONCAT('Beginning-Colored Season.'), NULL, 'https://ebd.cda.pl/800x450/513606350');
