INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1242, CONCAT('Megami Kouhosei'), CONCAT('In the future humankind has expanded and colonized other planets. Then an alien species, Victim, attacks the human colonies leaving only one planet, Zion. In an effort to stop Victim from destroying the last planet a training school, GOA, is set up to gather boys from the Zion colonies and train them to become pilots of the Ingrids AKA The Goddesses, five fighting robots that protect Zion. The boys must possess a rare blood type, EO, as well as a special ability, or EX. Zero (Candidate 88) has just arrived in GOA when he falls into the cockpit of the Ingrid Eeva-Leena. Since the synch between pilot and Ingrid are very sensitive everyone believes the Goddess will kill Zero in an attempt to synch. Just before Zero passes out he makes a full synch with the Goddess. Before he can find out more about the incident, his pilot training begins.<br>
<br>(Source: ANN)'), 1, '2000-01-20', '2000-03-27', 'Winter 2000', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/75472.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (544, 1242, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3036, 1242, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3037, 1242, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3038, 1242, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1343, 1242, 17);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1356, 1242, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1357, 1242, 18);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21324, 1242, 1, CONCAT('Curriculum 01 In Tune'), NULL, 'https://mp4upload.com/embed-qru7dzl4eox2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21325, 1242, 2, CONCAT('Curriculum 02 EX'), NULL, 'https://mp4upload.com/embed-omb8dr7l1oua.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21326, 1242, 3, CONCAT('Curriculum 03 Self Awareness'), NULL, 'https://yourupload.com/embed/jrMWMb16b7H8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21327, 1242, 4, CONCAT('Curriculum 04 Partner'), NULL, 'https://mp4upload.com/embed-jf4j0pil7fuf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21328, 1242, 5, CONCAT('Curriculum 05 Combination'), NULL, 'https://mp4upload.com/embed-u1jwrukqck0n.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21329, 1242, 6, CONCAT('Curriculum 06 PRO-ING'), NULL, 'https://mp4upload.com/embed-6viayhko4s5m.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21330, 1242, 7, CONCAT('Curriculum 07 Ground Battle'), NULL, 'https://mp4upload.com/embed-9wi7686vc3zb.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21331, 1242, 8, CONCAT('Curriculum 08 Death'), NULL, 'https://mp4upload.com/embed-9m5xcjnfx0uv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21332, 1242, 9, CONCAT('Curriculum 09 Dream'), NULL, 'https://mp4upload.com/embed-1lyygfl3hyig.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21333, 1242, 10, CONCAT('Curriculum 10 Jealousy'), NULL, 'https://mp4upload.com/embed-jlmuid1khggg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21334, 1242, 11, CONCAT('Curriculum 11 Driftage'), NULL, 'https://mp4upload.com/embed-78f3cblzt3os.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21335, 1242, 12, CONCAT('Curriculum 12 Friends'), NULL, 'https://mp4upload.com/embed-rldqg8w6h40z.html');
