INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1257, CONCAT('Mikakunin de Shinkoukei'), CONCAT('Just an ordinary teenager, Kobeni Yonomori receives quite the surprise on her 16th birthday—a fiancé and a sister-in-law she never even knew she had. As a result of an arrangement that her late grandfather made, Hakuya Mitsumine and his younger sister Mashiro have moved from their countryside home to the Yonomori household in order to deepen their relationship with their new family members.<br><br>Mikakunin de Shinkoukei follows Kobeni', CHAR(39), 's "love life" with Hakuya as she tries her best to adjust to the abrupt changes forced upon her. However, as some extraordinary secrets regarding the siblings come to light, Kobeni will find her life changed forever.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-01-09', '2014-03-27', 'Winter 2014', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/75249.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (878, 1257, '"Tomadoi→Recipe (とまどい→レシピ)"', ' by Mikakuning! (みかくにんぐッ!)', 'js-theme-songs', 'https://open.spotify.com/track/0EbUWbDShy8Uw93gPo1WhG')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3083, 1257, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3084, 1257, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1359, 1257, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21521, 1257, 1, CONCAT('It', CHAR(39), 's Important to Start Off on the Right Foot'), '2014-01-09', 'https://drive.google.com/file/d/19Xj2vmHwMj_jmnUWng9ct4oWMCvBXu2v/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21522, 1257, 2, CONCAT('It', CHAR(39), 's Not Bad Having a Loli Sister-in-Law'), '2014-01-16', 'https://drive.google.com/file/d/1XX-15rJUmZs5ZNFW4SfjR1kPMsXRMVB0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21523, 1257, 3, CONCAT('I Can Feel the RomCom Waves'), '2014-01-23', 'https://drive.google.com/file/d/1FP8wVWEZRrUgsozUdizBr13GxTEf_vi5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21524, 1257, 4, CONCAT('She', CHAR(39), 's Just a Pervert'), '2014-01-30', 'https://drive.google.com/file/d/1B562aUxJFJbWVOAwCsikb07KR5NZzF7a/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21525, 1257, 5, CONCAT('This Woman Has Given Birth?'), '2014-02-06', 'https://drive.google.com/file/d/15pL_fnR4NI3dlIMqsPsRSUBFlcw82RRS/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21526, 1257, 6, CONCAT('I Know! I', CHAR(39), 'll Fill It with a Sister-in-law'), '2014-02-13', 'https://drive.google.com/file/d/1dECprXSvJxWuIS0t-RlI5_cTa4oWFUKR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21527, 1257, 7, CONCAT('That', CHAR(39), 's One Thing, This is Another'), '2014-02-20', 'https://drive.google.com/file/d/1A7YfnH534CFEyO8bGY4C6_YGuIc7tPbE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21528, 1257, 8, CONCAT('Only a Little Sister Can Soothe Sadness Over a Little Sister'), '2014-02-27', 'https://drive.google.com/file/d/1NGjR1nzrU59-twQUd4g2Q1HGu3m_oH_I/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21529, 1257, 9, CONCAT('How Humiliating, I', CHAR(39), 'm So Embarrassed'), '2014-03-06', 'https://drive.google.com/file/d/1JBOvkNmd_BoNYx4L-h3Z13byFu8-4QEZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21530, 1257, 10, CONCAT('I Looked Up the Term "Lovey-Dovey Phase"'), '2014-03-13', 'https://drive.google.com/file/d/16KCFenAAM6MDHInJFj7GHAqqKR43xJvx/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21531, 1257, 11, CONCAT('Enjoying the Handkerchief'), '2014-03-20', 'https://drive.google.com/file/d/1z9tTCVCoGyDywwD6mdDKHiiwVUGh6HbT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21532, 1257, 12, CONCAT('Do You Understand? I Understand'), '2014-03-27', 'https://drive.google.com/file/d/1IZf2ZuusBGf-mHcSb7qQYij2n7Knc_uO/preview');
