INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1274, CONCAT('Mobile Suit Gundam 0080: War in the Pocket'), CONCAT('Alfred Izuruha is a 10-year-old who lives in the neutral colony cluster of Side 6 and, like most boys his age, is obsessed with the war between the Earth Federation and the Principality of Zeon. Unbeknownst to him, Al', CHAR(39), 's next-door neighbor, Christina, is the test pilot of a prototype Gundam being developed in secret by the Earth Federation in the colony. A Zeon Special Forces team is assembled and tasked with infiltrating the colony in order to either steal or destroy it.<br>
<br>When a skirmish breaks out between the Federation and infiltrating Zeon forces, the fascinated Alfred stumbles upon a Zaku mobile suit that has been shot down, piloted by Zeon rookie Bernard "Bernie" Wiseman. After this encounter, the two start a mutual friendship, so Alfred can learn more about the war that interests him so much, and Bernie can acquire inside information about the colony to aid his team', CHAR(39), 's mission.<br>
<br>[Written by MAL Rewrite]'), 1, '1989-03-25', '1989-08-25', '', '27 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1/82.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3129, 1274, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3130, 1274, 13);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3131, 1274, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3132, 1274, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3133, 1274, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1378, 1274, 27);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1388, 1274, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1389, 1274, 25);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1390, 1274, 26);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21791, 1274, 1, CONCAT('How Many Miles to the Battlefield?'), '1989-03-25', 'https://www.dailymotion.com/embed/video/x7r4ret?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21792, 1274, 2, CONCAT('Reflections in a Brown Eye'), '1989-04-25', 'https://www.dailymotion.com/embed/video/x7r4rev?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21793, 1274, 3, CONCAT('And at the End of the Rainbow?'), '1989-05-25', 'https://www.dailymotion.com/embed/video/x7r4rex?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21794, 1274, 4, CONCAT('Over the River and Through the Woods'), '1989-06-25', 'https://www.dailymotion.com/embed/video/x7r6g6d?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21795, 1274, 5, CONCAT('Say it Ain', CHAR(39), 't So, Bernie!'), '1989-07-25', 'https://www.dailymotion.com/embed/video/x7r6g6e?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (21796, 1274, 6, CONCAT('War in the Pocket'), '1989-08-25', 'https://www.dailymotion.com/embed/video/x7r4res?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
