INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1282, CONCAT('Mononoke'), CONCAT('The "Medicine Seller" is a deadly and mysterious master of the occult who travels across feudal Japan in search of malevolent spirits called "mononoke" to slay. When he locates one of these spirits, he cannot simply kill it he must first learn its Form, its Truth, and its Reason in order to wield the mighty Exorcism Sword and fight against it. He must begin  his strange exorcisms with intense psychological analysis and careful investigative work—an extremely dangerous step, as he must first confront and learn about the mononoke before he even has the means to defeat it.<br>
<br>The Medicine Seller', CHAR(39), 's journey leads him to an old-fashioned inn where Shino, a pregnant woman, has finally found a place to rest. The owner has reluctantly placed her in the last vacant room however, as she settles in, it quickly becomes clear that the room is infested by a lethal band of mononoke, the Zashiki Warashi. With his hunter', CHAR(39), 's intuition, the Medicine Seller begins his investigation to discover the Form, the Truth, and the Reason before the Zashiki Warashi can kill again.<br>
<br>[Written by MAL Rewrite]'), 2, '2007-07-13', '2007-09-28', 'Summer 2007', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/20713.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (894, 1282, '"Kagen no Tsuki"', ' by Ryouta Komatsu and Charlie Kosei', 'js-theme-songs', 'https://open.spotify.com/track/32LuGyduyuvZTONbOePuUY');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (895, 1282, '"Natsu no Hana"', ' by JUJU', 'js-theme-songs', 'https://open.spotify.com/track/4z0hsmN4NRcffxOmqZcL2J');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3164, 1282, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3165, 1282, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3166, 1282, 13);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3167, 1282, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1386, 1282, 181);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22043, 1282, 1, CONCAT('Zashikiwarashi: Part 1'), '2007-07-13', 'https://drive.google.com/file/d/1HEyBRwidxR-HCoVRB5nJGL_-LXGW6_zo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22044, 1282, 2, CONCAT('Zashikiwarashi: Part 2'), '2007-07-20', 'https://drive.google.com/file/d/1ZqwhEJOCTeGU2Z17ne7zhrIdBqqYJ5SB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22045, 1282, 3, CONCAT('Sea Bishop: Part 1'), '2007-07-27', 'https://drive.google.com/file/d/1mvj2noT8fX7R-wGdgt-KcrzhtWdQTKS2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22046, 1282, 4, CONCAT('Sea Bishop: Part 2'), '2007-08-03', 'https://drive.google.com/file/d/1ce9R1QrUqMhs8Z_lVBtzUOiewtIdbTCP/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22047, 1282, 5, CONCAT('Sea Bishop: Finale'), '2007-08-10', 'https://drive.google.com/file/d/14oFN7oX1hvYUrmYWwKRx262iPi-f0vau/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22048, 1282, 6, CONCAT('Faceless Monster: Part 1'), '2007-08-17', 'https://drive.google.com/file/d/1jt4YSRlboc1EqhhmzMAaHkzJYQx2bqPa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22049, 1282, 7, CONCAT('Faceless Monster: Part 2'), '2007-08-24', 'https://drive.google.com/file/d/1S9OI89wu6C6Y5-_5o36ydKfxjek2abYc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22050, 1282, 8, CONCAT('Japanese Chimera: Part 1'), '2007-08-31', 'https://drive.google.com/file/d/1tSp14YU_ue5wKEFJuBYLHdc2F8cney4D/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22051, 1282, 9, CONCAT('Japanese Chimera: Part 2'), '2007-09-07', 'https://drive.google.com/file/d/1zBRR9ap9zIkJdqRvtBZ3Ou4uSJZzMS6V/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22052, 1282, 10, CONCAT('Goblin Cat: Part 1'), '2007-09-14', 'https://ebd.cda.pl/620x395/56001037b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22053, 1282, 11, CONCAT('Goblin Cat: Part 2'), '2007-09-21', 'https://drive.google.com/file/d/13d_Io7nap1Qr4Dqlfu_T-7XeqyRfjb0z/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22054, 1282, 12, CONCAT('Goblin Cat: Finale'), '2007-09-28', 'https://drive.google.com/file/d/1g6tYCntM3pNEPhWUb05GMZCQqOVoLoJ9/preview');
