INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1291, CONCAT('Motto To LOVE-Ru'), CONCAT('Rito Yuuki never gets a break—he', CHAR(39), 's always finding himself in lewd accidents with girls around him. Although his heart still yearns for Haruna, his childhood love, Rito can', CHAR(39), 't help but question his feelings for Lala, the alien princess who appeared in front of him and declared she would marry him. But now, it', CHAR(39), 's not just Lala he has to deal with: her younger twin sisters, Momo and Nana, have also traveled to Earth, wanting to meet their older sister', CHAR(39), 's fiancé, and just as luck would have it, they end up staying at Rito', CHAR(39), 's home.<br>
<br>Meanwhile, amidst the bustle of his new family members, Yami, the human weapon girl, begins her pursuit for Rito. It', CHAR(39), 's not an easy life for Rito as he deals with uncertain love, punishment for being a pervert, and a girl dead set on murdering him.<br>
<br>[Written by MAL Rewrite]'), 1, '2010-10-06', '2010-12-22', 'Fall 2010', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/59875.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (902, 1291, '"Loop-the-Loop"', ' by KOTOKO', 'js-theme-songs', 'https://open.spotify.com/track/17hIIei4sCrQiWWtzQtKOw')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (557, 1291, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3189, 1291, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3190, 1291, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3191, 1291, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1395, 1291, 96);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1411, 1291, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1412, 1291, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22195, 1291, 1, CONCAT('Once Again from Here / Bathroom War / Tick Tock Tick Tock, the Sound of Love♡'), '2010-10-06', 'https://drive.google.com/file/d/1FTLXzkF9t8c3J_tlze6we9k9ivPkAEE0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22196, 1291, 2, CONCAT('Those Warped into the Midst of Darkness / Welcome to the Yuuki Household! / Sleepover Party'), '2010-10-13', 'https://drive.google.com/file/d/194IcS4xrjV3hI1KHL3suuuiUiagekgp2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22197, 1291, 3, CONCAT('Magic Love Potion♡ / What I See Through the Lens is... / You are the Lovely Cinderella♡'), '2010-10-20', 'https://drive.google.com/file/d/1xjhLrTKQFyEbQhBhuXTgbN-9lam1A3iR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22198, 1291, 4, CONCAT('Yami-Yami Fashion / Wonderful Love♡ / Twins Escape'), '2010-10-27', 'https://drive.google.com/file/d/13oobQ9Vc6Gn5yjECMkEtPWF-2in-bJPe/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22199, 1291, 5, CONCAT('Queen of Love!? / Let', CHAR(39), 's Play ♪ / Sweet Feelings are a Taste of Chocolate'), '2010-11-03', 'https://drive.google.com/file/d/1fw8xI75AYXEL1NeyG59IAGVmXC9LFLO6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22200, 1291, 6, CONCAT('Beach Girls / Night Tutor / Master of Love'), '2010-11-10', 'https://drive.google.com/file/d/1oqPXsavnN78Z6xVCDnD3EVMH9-O2yzPe/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22201, 1291, 7, CONCAT('Yami', CHAR(39), 's Clinic / Hostile Feelings / A Strange Haruna'), '2010-11-17', 'https://drive.google.com/file/d/1MYEx0jVD_gHVVW3-iAR4lbGKGPjIFtCJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22202, 1291, 8, CONCAT('Grow Bigger ♪ / Wan-derful Life / The Trance of Feelings'), '2010-11-24', 'https://drive.google.com/file/d/1F3IPFgZkXq-bWZLaPJZ_dav9Ej97T6XN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22203, 1291, 9, CONCAT('For Whom the Bell Tolls / Troubling Rampage? / Loving Idol'), '2010-12-01', 'https://drive.google.com/file/d/1SPT9hqbQ7pY7ZS5pyQ18PUj-bHQoQP3W/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22204, 1291, 10, CONCAT('Pollen Telepathy / A Girl', CHAR(39), 's Feelings / Heart Throbbing E-Mail'), '2010-12-08', 'https://drive.google.com/file/d/12x5yr-Cq02W5MxO1-pyWDEmPyRxuw22g/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22205, 1291, 11, CONCAT('All Quiet on the "Sister" Front / The False Love? / Romantic Forecast'), '2010-12-15', 'https://drive.google.com/file/d/18kLE7jQDgSqSdoc1TaX2qIGjW4RlzjfD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22206, 1291, 12, CONCAT('I Love You♡ 1 / I Love You♡ 2 / I Love You♡ 3'), '2010-12-22', 'https://drive.google.com/file/d/1LWONjxkex_U8cKJpfkJUeIBTzY-ZUkyR/preview');
