INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1292, CONCAT('Mouretsu Pirates'), CONCAT('Far in the future, where interstellar travel is considered commonplace, high school student Marika Katou balances her duties in the space yacht club and her job as a restaurant waitress. Following a chance encounter with a peculiar pair of customers, Marika meets them again and learns that her absent father has passed away.<br>
<br>During his life, he was known as the legendary pirate "Gonzaemon." He has left behind his infamous ship Bentenmaru and its crew exclusively for Marika to inherit. With one of the few remaining Letters of Marque that permit legal piracy, Marika must choose whether to stay as a regular student or take up a second life as a high-octane space pirate.<br>
<br>As Marika ponders her decision, the delicate situation attracts the eyes of various government agencies and the mysterious transfer student Chiaki Kurihara, all eager to see if the upcoming captain lives up to her father', CHAR(39), 's reputation. If the crew of the Bentenmaru want to maintain their status, they will need to set sail into the vast expanse of space and once again become a name to be feared.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2012-01-08', '2012-07-01', 'Winter 2012', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/36247.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (903, 1292, '"Mouretsu Uchuu Koukyoukyoku: Daishichi Gakushou 'Mugen no Ai' (猛烈宇宙交響曲・第七楽章「無限の愛」)"', ' by Momoiro Clover Z', 'js-theme-songs', 'https://open.spotify.com/track/3MDGJ0pVnyvP2tGYqUirUQ')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1396, 1292, 43);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22207, 1292, 1, CONCAT('Pirates, Coming Through'), '2012-01-08', 'https://drive.google.com/file/d/0B9f0fGhaDBu-TFZqWVdKYVhFOWM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22208, 1292, 2, CONCAT('My Power, The Power of Pirates'), '2012-01-15', 'https://drive.google.com/file/d/0B9f0fGhaDBu-MWpocUg1QjdJcTg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22209, 1292, 3, CONCAT('The Odette II Leaves Port'), '2012-01-22', 'https://vk.com/video_ext.php?oid=205318180&id=165538667&hash=cff3833c8212cba0&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22210, 1292, 4, CONCAT('The Final Battle is at Midnight'), '2012-01-29', 'https://drive.google.com/file/d/0B9f0fGhaDBu-VnlSYXlFNGFaSDg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22211, 1292, 5, CONCAT('Marika Makes a Decision'), '2012-02-05', 'https://drive.google.com/file/d/0B9f0fGhaDBu-MVo4cnlCQUxSSmM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22212, 1292, 6, CONCAT('Marika', CHAR(39), 's First Day at Work'), '2012-02-11', 'https://drive.google.com/file/d/0B9f0fGhaDBu-SENPcFNBZ3lWdHM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22213, 1292, 7, CONCAT('The Peace Does Not Last'), '2012-02-18', 'https://drive.google.com/file/d/0B9f0fGhaDBu-VVVCVWFVMTBXN2M/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22214, 1292, 8, CONCAT('The Princess and The Pirate'), '2012-02-25', 'https://vk.com/video_ext.php?oid=164598341&id=162333002&hash=8b150cbbe6235998&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22215, 1292, 9, CONCAT('A Beautiful Launch'), '2012-03-03', 'https://drive.google.com/file/d/0B9f0fGhaDBu-bldCRVFCVTczaWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22216, 1292, 10, CONCAT('Battle in the Storm'), '2012-03-10', 'https://drive.google.com/file/d/0B9f0fGhaDBu-RVFxT2hNNHBCekU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22217, 1292, 11, CONCAT('Wanderer of Light'), '2012-03-17', 'https://video.sibnet.ru/shell.php?videoid=617465');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22218, 1292, 12, CONCAT('A Return from Eternity'), '2012-03-24', 'https://video.sibnet.ru/shell.php?videoid=617464');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22219, 1292, 13, CONCAT('Marika Sends an Invitation'), '2012-03-31', 'https://drive.google.com/file/d/0B9f0fGhaDBu-NzlzN1kyb2Z4M1k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22220, 1292, 14, CONCAT('Marika Goes Recruiting'), '2012-04-07', 'https://drive.google.com/file/d/0B9f0fGhaDBu-MmMwejY2U0lqUWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22221, 1292, 15, CONCAT('Smuggling, Leaving Port and a Leap'), '2012-04-14', 'https://drive.google.com/file/d/0B9f0fGhaDBu-UnMyT1RBcmpFd0E/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22222, 1292, 16, CONCAT('The Hakuoh Pirates', CHAR(39), ' First Job'), '2012-04-21', 'https://drive.google.com/file/d/0B9f0fGhaDBu-cXBpcjFMTnZRa2M/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22223, 1292, 17, CONCAT('A Surprising Client'), '2012-04-28', 'https://vk.com/video_ext.php?oid=164598341&id=162773315&hash=92701dfac3d6b6d6&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22224, 1292, 18, CONCAT('We', CHAR(39), 'll Have Juice at the After Party'), '2012-05-05', 'https://drive.google.com/file/d/0B9f0fGhaDBu-RUVnVWFtZ2owTXM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22225, 1292, 19, CONCAT('The Bonds Among the Four'), '2012-05-12', 'https://drive.google.com/file/d/0B9f0fGhaDBu-eGk2MldneEpJSUk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22226, 1292, 20, CONCAT('The Captain Rides the Waves'), '2012-05-19', 'https://drive.google.com/file/d/0B9f0fGhaDBu-bVdEWFg0SnozRWM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22227, 1292, 21, CONCAT('The Final Battle at the Nebula Cup'), '2012-05-26', 'https://drive.google.com/file/d/0B9f0fGhaDBu-MF9ZS3lMUTVKVEU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22228, 1292, 22, CONCAT('Pirate Hunting'), '2012-06-02', 'https://drive.google.com/file/d/0B9f0fGhaDBu-cUZHbGVpV3JaczQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22229, 1292, 23, CONCAT('Head for the Pirate', CHAR(39), 's Nest!'), '2012-06-09', 'https://drive.google.com/file/d/0B9f0fGhaDBu-RVctOWZGTlBZTzQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22230, 1292, 24, CONCAT('The Wounded Benten'), '2012-06-16', 'https://drive.google.com/file/d/0B9f0fGhaDBu-TVRLVlBZVGpCMDA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22231, 1292, 25, CONCAT('The Pirate', CHAR(39), 's Council Begins'), '2012-06-23', 'https://drive.google.com/file/d/0B9f0fGhaDBu-aC1QS2hDU1FfcVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22232, 1292, 26, CONCAT('There Go the Pirates'), '2012-06-30', 'https://video.sibnet.ru/shell.php?videoid=641332');
