INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1306, CONCAT('Musashino!'), CONCAT('Sequel series to Urawa no Usagi-chan.'), 1, '2022-07-02', '2022-09-17', 'Summer 2022', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1541/126462.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3226, 1306, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3227, 1306, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1411, 1306, 208);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22376, 1306, 1, CONCAT('Swimming in the Sea'), NULL, 'https://ebd.cda.pl/620x368/1148760773');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22377, 1306, 2, CONCAT('Termination Kerfuffle'), NULL, 'https://dood.pm/e/p7gjdr6zorkr');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22378, 1306, 3, CONCAT('Praying for Victory'), NULL, 'https://dood.pm/e/e2m28frutfvp');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22379, 1306, 4, CONCAT('Memories of Omiya'), NULL, 'https://dood.pm/e/vqwq6grdp2wr');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22380, 1306, 5, CONCAT('A Pep Rally'), NULL, 'https://dood.pm/e/6ln5bb1jwgx4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22381, 1306, 6, CONCAT('Side Story in Space'), NULL, 'https://dood.pm/e/lbcmx1iqmmg5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22382, 1306, 7, CONCAT('The Championship', CHAR(39), 's Decisive Match'), NULL, 'https://dood.pm/e/j5m3ick3zs9d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22383, 1306, 8, CONCAT('The Championship', CHAR(39), 's Decisive Match 2'), NULL, 'https://dood.pm/e/zjgzjbzv6efm');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22384, 1306, 9, CONCAT('The Championship', CHAR(39), 's Decisive Match 3'), NULL, 'https://dood.pm/e/9jngiarij2lj');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22385, 1306, 10, CONCAT('Championship', CHAR(39), 's Decisive Match 4'), NULL, 'https://dood.pm/e/gtu51jwtz42e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22386, 1306, 11, CONCAT('The Championship', CHAR(39), 's Decisive Match 5'), NULL, 'https://dood.pm/e/ujy726d9q7nu');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22387, 1306, 12, CONCAT('The Ending'), NULL, 'https://dood.pm/e/4jvya1yoqixg');
