INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1355, CONCAT('Night Head 2041'), CONCAT('In the year 2041, World War III has wiped out two-thirds of the human population, and in the newfound structure, the belief in any god or beyond-human entity is considered a preposterous notion. In order to prevent citizens from bearing possibly incriminating thoughts, the government has assembled a Special Weapon Enforcement division to capture and rehabilitate such believers.<br>
<br>The Kirihara brothers, Naoya and Naoto—who were hidden away from society by their captors for years to conceal their psychic abilities—were promised freedom once the world was ready to face their existence. Now, wandering in the appalling new societal climate where psychics are not welcome, the brothers find themselves on the run from the Enforcement', CHAR(39), 's devoted operatives, Yuuya and Takuya Kuroki.<br>
<br>[Written by MAL Rewrite]'), 2, '2021-07-15', '2021-09-30', 'Summer 2021', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1819/116662.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (953, 1355, '"Icy Ivy"', ' by Who-ya Extended', 'js-theme-songs', 'https://open.spotify.com/track/2Vd1bDbCfkZgSA9EjeBYgS')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3371, 1355, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3372, 1355, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3373, 1355, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1461, 1355, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23765, 1355, 1, CONCAT('Barrier: Onset'), '2021-07-15', 'https://ebd.cda.pl/620x368/79487006f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23766, 1355, 2, CONCAT('Fake -Deception-'), NULL, 'https://drive.google.com/file/d/1nIvvROTw8g8oZGhcO-DahWu2f0PEBgSl/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23767, 1355, 3, CONCAT('Complication, Trigger -Awakening-'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4373262');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23768, 1355, 4, CONCAT('Inspiration -Resonance-'), NULL, 'https://drive.google.com/file/d/1rsEdTUuVkLZ5WtdT5J3U29ownZQTfuRt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23769, 1355, 5, CONCAT('Shoko Futami -Shoko-'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4388399');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23770, 1355, 6, CONCAT('Ideologies Collide -Showdown-'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4401252');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23771, 1355, 7, CONCAT('Between the Worlds'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4409405');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23772, 1355, 8, CONCAT('Revelation of Destruction -March to Decimation-'), NULL, 'https://ebd.cda.pl/620x368/84147723b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23773, 1355, 9, CONCAT('Paradox'), NULL, 'https://ebd.cda.pl/620x368/841477534');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23774, 1355, 10, CONCAT('Protection and Salvation -Our Destiny-'), NULL, 'https://drive.google.com/file/d/1DaM4-Mt-ssiv_r_n2i02DE8QLyt6Vn-g/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23775, 1355, 11, CONCAT('Dimensional Fusion -Unity-'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4432968');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23776, 1355, 12, CONCAT('Inheritance and Reincarnation -Start Over-'), NULL, 'https://drive.google.com/file/d/10yIbat22qYPslJyNV52UAvPRCJG4akUT/preview');
