INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1391, CONCAT('Nyan Koi!'), CONCAT('Junpei Kousaka is a second-year high school student who has an allergy for cats—a predicament that has made him hate cats and everything related to them. Unfortunately for him, though, he is surrounded by cat lovers: his family, his estranged childhood friend, and even his crush Kaede Mizuno.<br>
<br>One day, while returning home from school, Junpei nonchalantly attempts to kick an empty can into the trash, but miserably misses. Instead of making it to the garbage, the can ends up breaking off the head of a cat deity statue. That fateful day, he is cursed with the ability to understand cat speech. However, he must keep his curse a secret from everyone else, because anyone who finds out will become more accident-prone and share the same fate as him.<br>
<br>With the guidance of his cat Nyamsus and with no other choice left, Junpei now has to do a hundred good deeds for cats to lift the curse. If he is unable to complete this task, he will turn into a cat, and considering his allergy, that would be a death sentence for him!<br>
<br>[Written by MAL Rewrite]'), 1, '2009-10-02', '2009-12-18', 'Fall 2009', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/18299.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (978, 1391, '"Nyanderful!"', ' by Yui Sakakibara', 'js-theme-songs', 'https://open.spotify.com/track/3XHwlbj7VBWHHI9mfyDyBr')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3452, 1391, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3453, 1391, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1498, 1391, 18);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24307, 1391, 1, CONCAT('The Scruffy Cat and the Cursed High Schooler'), NULL, 'https://ebd.cda.pl/800x450/6336284f7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24308, 1391, 2, CONCAT('The Man Is a Manservant?'), NULL, 'https://dood.so/e/4ui8kdsudlju');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24309, 1391, 3, CONCAT('Your Name Is...'), NULL, 'https://dood.so/e/gyycdgy1qw3e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24310, 1391, 4, CONCAT('Beautiful People'), NULL, 'https://ebd.cda.pl/800x450/7253428f5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24311, 1391, 5, CONCAT('Times Square'), NULL, 'https://ebd.cda.pl/800x450/725386061');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24312, 1391, 6, CONCAT('Milk and Bitters and Sugar and Spice'), NULL, 'https://dood.so/e/d43257ny3kys');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24313, 1391, 7, CONCAT('Wait Until Dark'), NULL, 'https://dood.so/e/icsxeodylp2e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24314, 1391, 8, CONCAT('The Passionate Private Running Coach'), NULL, 'https://dood.so/e/enlam72o385x');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24315, 1391, 9, CONCAT('Girls in the Water'), NULL, 'https://dood.so/e/ks6sr7qt2hru9makcnxfppwq6aoffwrw');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24316, 1391, 10, CONCAT('As It Happened One Night'), NULL, 'https://dood.so/e/lurtlcar87qk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24317, 1391, 11, CONCAT('Friends'), NULL, 'https://dood.so/e/oicl5bmswljo');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24318, 1391, 12, CONCAT('Does Heaven Await Me?'), NULL, 'https://dood.so/e/jzp87mfuns4mawv6dympds2lkwaioiee');
