INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1401, CONCAT('Okusama ga Seitokaichou!+!'), CONCAT('The story begins with Izumi Hayato running to be student council president. But when a beautiful girl swings in promising the liberalization of love while flinging condoms into the audience, he ends up losing to her and becoming the vice president. At the student council meeting, the newly-elected president invites herself over to Izumi', CHAR(39), 's house, where she promptly announces she is to become Izumi', CHAR(39), 's wife thanks to an agreement—facilitated by alcohol—made between their parents when they were only 3.<br>
<br>(Source: MAL Scanlations)'), 1, '2016-10-02', '2016-12-18', 'Fall 2016', '8 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/82409.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (604, 1401, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3477, 1401, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3478, 1401, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3479, 1401, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1509, 1401, 55);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24431, 1401, 1, CONCAT('The Playful Student Council President'), '2016-10-02', 'https://drive.google.com/file/d/1oUYXiqR9i1h-f5YOlU0Ze21liuatGQyU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24432, 1401, 2, CONCAT('Late Summer Festival with the Disciplinary Committee Head'), '2016-10-09', 'https://drive.google.com/file/d/1wzDkBZRTCvfQ7T68y5SzG7T49AZ79Q_l/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24433, 1401, 3, CONCAT('The Student Council President and the Photography Club President'), '2016-10-16', 'https://drive.google.com/file/d/1XmUHvzGOIS3DBTnM5H4pMppukYJ3eRfs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24434, 1401, 4, CONCAT('The Disciplinary Committee Head', CHAR(39), 's Awakening'), '2016-10-23', 'https://drive.google.com/file/d/1ekZGiYJaHSRHdgcaIgPB9bW-INIGbGaE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24435, 1401, 5, CONCAT('The Vice President', CHAR(39), 's Long Night'), '2016-10-30', 'https://drive.google.com/file/d/1S37yg7y4Z7tNRcZX8aEcCUdDHTsRQhJk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24436, 1401, 6, CONCAT('A Dangerous Afternoon with Niikura-san'), '2016-11-06', 'https://drive.google.com/file/d/1JPOAEUoMlYN1FAwXsWT1sFhxP7tyWfs7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24437, 1401, 7, CONCAT('The Unrelenting Battle of the President and the Disciplinary Committee Head'), '2016-11-13', 'https://drive.google.com/file/d/1UNxeON-DVhYjooTiJzbXwv11-l_RmNZQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24438, 1401, 8, CONCAT('The President', CHAR(39), 's Efforts and Winter', CHAR(39), 's Temptations'), '2016-11-20', 'https://drive.google.com/file/d/1wFzi4UpPnspsaXZR0Mo_pjTDvDLWNxxT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24439, 1401, 9, CONCAT('The Photography Club President', CHAR(39), 's Hidden Desire'), '2016-11-27', 'https://drive.google.com/file/d/1B5oxgnxoM4Y17Vi9SrtqtS8kqkJ4BPUL/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24440, 1401, 10, CONCAT('The President and Disciplinary Committee Head', CHAR(39), 's Troubles'), '2016-12-04', 'https://drive.google.com/file/d/1yis00y7WfStczQrKAgNIiSiJHoKz1wO3/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24441, 1401, 11, CONCAT('The Vice President and Treasurer Make Some Kind of Progress'), '2016-12-11', 'https://drive.google.com/file/d/1yDo7emaPyk6p9V4HEsH2oDo--ig2msyi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24442, 1401, 12, CONCAT('A Holy Night with the President and All the Rest'), '2016-12-18', 'https://drive.google.com/file/d/100sdDu9H_dFQipWpdLhAqkWdLKsb3LNJ/preview');
