INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1402, CONCAT('Omae wa Mada Gunma wo Shiranai'), CONCAT('Nori Kamitsuki has recently moved to the Gunma prefecture from Chiba, following after Otoya Todoroki, a former friend who moved there in elementary school. While on the way there, he receives an ominous text message from Todoroki telling him to turn back and that once someone enters Gunma, they never return.<br>
<br>Ignoring the message, As Kamitsuki goes about his school life and makes new friends. These people make it their mission to prove any negative stereotypes surrounding Gunma wrong and show Kamitsuki all the ways Gunma is different from the rest of Japan—from its local foods and landmarks, the changes to its daily school life, and even the attitude of the people who live there. Gunma is widely regarded as the least popular prefecture in Japan, but they clearly don', CHAR(39), 't know Gunma yet!<br>
<br>[Written by MAL Rewrite]'), 1, '2018-04-02', '2018-06-18', 'Spring 2018', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1433/90426.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (986, 1402, '"So Happy"', ' by Aya Uchida', 'js-theme-songs', 'https://open.spotify.com/track/23HuoYhyJnYIpc3IabOrEY');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1510, 1402, 121);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24443, 1402, 1, CONCAT('With Gusto in Gunma'), NULL, 'https://vidoza.net/embed-hyfa22i669aa.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24444, 1402, 2, CONCAT('Stand, Attention, Bow'), NULL, 'https://vidoza.net/embed-lqpe91c26ent.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24445, 1402, 3, CONCAT('Gunma is Shaped Like a Crane in Flight'), NULL, 'https://vidoza.net/embed-erh31sd2ilqv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24446, 1402, 4, CONCAT('Grilled Sweet Buns'), NULL, 'https://streamtape.com/e/09dmeLM8aMCb4PM/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24447, 1402, 5, CONCAT('JKJ'), NULL, 'https://streamtape.com/e/gvq4R1bGaPCqRbR/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24448, 1402, 6, CONCAT('The History of Jomo Karuta'), NULL, 'https://vidoza.net/cig3lzdak8z4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24449, 1402, 7, CONCAT('Dry Wind'), NULL, 'https://streamtape.com/e/mr8WP3v47mTBVZ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24450, 1402, 8, CONCAT('Beach'), NULL, 'https://streamtape.com/e/7YlQ81Km88tAOyR/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24451, 1402, 9, CONCAT('Gunma Sports Day (Part 1)'), NULL, 'https://streamtape.com/e/WGROG7DAvLCb8YA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24452, 1402, 10, CONCAT('Gunma Sports Day (Part 2)'), NULL, 'https://streamtape.com/e/j7GjqXJRVZszrjl/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24453, 1402, 11, CONCAT('Vending Machine Shop'), NULL, 'https://streamtape.com/e/aoXMBAz7P2CJrY/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24454, 1402, 12, CONCAT('We Didn', CHAR(39), 't Know GUNMA Yet'), NULL, 'https://streamtape.com/e/9ewx6xq847Sad7x/');
