INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1423, CONCAT('Ore wo Suki nano wa Omae dake ka yo'), CONCAT('Amatsuyu "Jouro" Kisaragi is a completely average second-year high school student who has two dates over one weekend⁠—with the student council president Sakura "Cosmos" Akino on Saturday, then with his childhood friend Aoi "Himawari" Hinata on Sunday. Sadly for Jouro, both girls proclaim their love for his best friend Taiyou "Sun-chan" Ooga, the ace of the baseball team. Accepting each of their requests for advice and guidance, he is now responsible for helping the two girls win the heart of the same guy.<br>
<br>Unbeknownst to his friends, Jouro', CHAR(39), 's friendly and obtuse image is all but a ruse designed to cast himself as the clueless protagonist of a textbook romantic comedy. A schemer under his cheery facade, he makes the best of this unexpected turn of events with a new plan: get Sun-chan to fall for either Cosmos or Himawari and take the other as his own prize. But Jouro', CHAR(39), 's last-ditch effort is threatened by the gloomy, four-eyed Sumireko "Pansy" Sanshokuin, who surprises Jouro with not only her knowledge of his secret personality but also a confession to the true self he hid for all this time.<br>
<br>Stuck in this hilariously messy situation, each of the five students must navigate countless lies, traps, and misunderstandings to come out on top.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-10-03', '2019-12-26', 'Fall 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1348/102797.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3527, 1423, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3528, 1423, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1530, 1423, 51);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1562, 1423, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1563, 1423, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25728, 1423, 1, CONCAT('I', CHAR(39), 'm Really Just an Ordinary High School Student'), '2019-10-03', 'https://ebd.cda.pl/620x395/40873933e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25729, 1423, 2, CONCAT('I', CHAR(39), 'm Attacked by an Impossible Spiral'), '2019-10-10', 'https://ebd.cda.pl/620x395/4087396bf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25730, 1423, 3, CONCAT('I Was Meeting You'), '2019-10-17', 'https://ebd.cda.pl/620x395/4096762f6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25731, 1423, 4, CONCAT('The Results of My Hard Work'), NULL, 'https://ebd.cda.pl/620x395/4132069f0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25732, 1423, 5, CONCAT('I Thought It Was Working Out Too Well For Me'), NULL, 'https://ebd.cda.pl/620x395/418793821');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25733, 1423, 6, CONCAT('When I Need to Say Something, I', CHAR(39), 'll Say It'), NULL, 'https://ebd.cda.pl/620x368/4136806ab');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25734, 1423, 7, CONCAT('I Discover an Unexpected Side'), '2019-11-14', 'https://ebd.cda.pl/620x368/417971825');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25735, 1423, 8, CONCAT('Before I Knew it, My Tragedy Had Already Begun'), NULL, 'https://ebd.cda.pl/620x368/419932074');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25736, 1423, 9, CONCAT('My Conclusion After Much Consideration'), NULL, 'https://ebd.cda.pl/620x368/421030304');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25737, 1423, 10, CONCAT('Even I', CHAR(39), 'm Useful Once in a While'), NULL, 'https://ebd.cda.pl/800x450/523866009');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25738, 1423, 11, CONCAT('I May Not Be Needed'), NULL, 'https://ebd.cda.pl/620x368/43010817c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25739, 1423, 12, CONCAT('The One I Love Is…'), NULL, 'https://ebd.cda.pl/620x368/4334120ab');
