INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1424, CONCAT('Orenchi no Furo Jijou'), CONCAT('On his way home from school, Tatsumi sees a man collapsed near a lake. When he approaches him, Tatsumi notices something strange: the person in need of help is actually a beautiful merman named Wakasa! Because Wakasa', CHAR(39), 's home has become too polluted to live in, Tatsumi graciously offers his bathtub as a refuge.<br>
<br>With a boisterous merman as his new roommate, Tatsumi', CHAR(39), 's normal life won', CHAR(39), 't be returning anytime soon, not to mention Wakasa', CHAR(39), 's aquatic friends—Takasu, Mikuni, and Maki—often show up uninvited, making them all quite a handful for the high school student. As he humors their curiosity for human life, Tatsumi sometimes finds himself enjoying their childish antics, but he will have to keep his cool if he intends to keep up with his daily life and newfound friendship.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-10-06', '2014-12-29', 'Fall 2014', '4 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/67085.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1005, 1424, '"Chimeishou (致命傷)"', ' by Matenrou Opera (摩天楼オペラ)', 'js-theme-songs', 'https://open.spotify.com/track/3YcR95zBTwA4iZKfbGqHIK');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (615, 1424, 5);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3529, 1424, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3530, 1424, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1531, 1424, 121);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25740, 1424, 1, CONCAT('The Special Circumstances of My Bathtub'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1573150');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25741, 1424, 2, CONCAT('The Severe Circumstances of My Household Budget'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1574568');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25742, 1424, 3, CONCAT('The Circumstances of Wakasa', CHAR(39), 's Friends: Takasu Edition'), NULL, 'https://drive.google.com/file/d/0BzP_5dQGK87PeEJZUFV0SXRVOWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25743, 1424, 4, CONCAT('The Circumstances of Wakasa', CHAR(39), 's Friends: Mikuni Edition'), NULL, 'https://drive.google.com/file/d/0BzP_5dQGK87PMW9XWHpKWTVUdnc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25744, 1424, 5, CONCAT('The Halloween Circumstances of My Household'), NULL, 'https://drive.google.com/file/d/0B31lV-ExJ9IBMTBvalFVX1ZLbU0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25745, 1424, 6, CONCAT('The Circumstances of My Bubbles'), NULL, 'https://myvi.ru/player/embed/html/65402859fce84f9283b59c7bfd14fb6c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25746, 1424, 7, CONCAT('My Sibling Circumstances'), NULL, 'https://vk.com/video_ext.php?oid=304788290&id=171160229&hash=27a4db0373eaab16&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25747, 1424, 8, CONCAT('The Trendy Circumstances of Modern Men'), NULL, 'https://myvi.ru/player/embed/html/3ce12b973072412ab059c14f7fceeca3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25748, 1424, 9, CONCAT('The Circumstances of Our Naked Bonding'), '2014-12-01', 'https://myvi.ru/player/embed/html/291f331e241844298f8d5f126f1d264c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25749, 1424, 10, CONCAT('The Circumstances of Wakasa', CHAR(39), 's Friends: Maki Edition'), NULL, 'https://myvi.ru/player/embed/html/d1c7989db38040abadca3e1fd7cb0d30');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25750, 1424, 11, CONCAT('The Seven Transformations of my Bathtub Circumstances'), NULL, 'https://myvi.ru/player/embed/html/fd823d4a43534c6ab227cfac1f78bc04');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25751, 1424, 12, CONCAT('The Circumstances of Wakasa Staying Home Alone'), NULL, 'https://drive.google.com/file/d/0B_h2WUhye35ZYVBXdF9LNFhiS0U/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25752, 1424, 13, CONCAT('The Circumstances of Wakasa', CHAR(39), 's Employment'), NULL, 'https://drive.google.com/file/d/0B31lV-ExJ9IBYk02bGc2YkpmM3M/preview');
