INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1449, CONCAT('Panty & Stocking with Garterbelt'), CONCAT('The "Anarchy Sisters," Panty and Stocking, have been kicked out of Heaven for, to put it mildly, misbehaving. Led by a priest named Garterbelt, these angels must buy their way back by exterminating ghosts in Daten City. But this task requires unconventional weapons for these unorthodox angels—they transform their lingerie into weapons to dispatch the spirits. Unfortunately, neither of them take their duties seriously, as they rather spend their time in pursuit of other "hobbies": Panty prefers to sleep with anything that walks, and Stocking favors stuffing her face with sweets than hunting ghosts.<br>
<br>Follow these two unruly angels as they battle ghosts, an overflow of bodily fluids, and their own tendency to get side-tracked in Panty & Stocking with Garterbelt.<br>
<br>[Written by MAL Rewrite]'), 1, '2010-10-02', '2010-12-25', 'Fall 2010', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/73643.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1026, 1449, '"Theme for Panty & Stocking"', ' by Hoshina Anniversary', 'js-theme-songs', 'https://open.spotify.com/track/1QV930MbloRewXxzICU3v4')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3594, 1449, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3595, 1449, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3596, 1449, 10);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3597, 1449, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1556, 1449, 20);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1599, 1449, 38);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1600, 1449, 21);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26070, 1449, 1, CONCAT('Excretion Without Honor and Humanity / Death Race 2010'), '2010-10-02', 'https://drive.google.com/file/d/0B1WyIQUrSAJQb0ppTHNZanUxQVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26071, 1449, 2, CONCAT('The Turmoil of the Beehive / Sex and the Daten City'), '2010-10-09', 'https://drive.google.com/file/d/1sv5m_sHs8oTGYBS-NA7xtnE0oFG7mYwy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26072, 1449, 3, CONCAT('Catfight Club / Pulp Addiction'), '2010-10-16', 'https://drive.google.com/file/d/0B1WyIQUrSAJQSURFWHJhbXJzWDA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26073, 1449, 4, CONCAT('The Diet Syndrome / High School Nudical'), '2010-10-23', 'https://drive.google.com/file/d/0B1WyIQUrSAJQUWtRUXhqUlhfNzA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26074, 1449, 5, CONCAT('Raiders of the Nasal Dark / Vomiting Point'), '2010-10-30', 'https://drive.google.com/file/d/0B1WyIQUrSAJQMW5MZFVxc1JqZzg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26075, 1449, 6, CONCAT('Les Diaboliques'), '2010-11-06', 'https://drive.google.com/file/d/0B1WyIQUrSAJQRFQ0NnVOSTIyVWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26076, 1449, 7, CONCAT('Trans-homers / The Stripping'), '2010-11-13', 'https://ebd.cda.pl/620x395/6064244d7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26077, 1449, 8, CONCAT('...Of the Dead / One Angry Ghost'), '2010-11-20', 'https://drive.google.com/file/d/0B-zgkElrJfsjNS1ZSWY3MlcwRWc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26078, 1449, 9, CONCAT('If the Angels Wore Swimsuits / Ghost: The Phantom of Daten City'), '2010-11-27', 'https://drive.google.com/file/d/0B1WyIQUrSAJQOVUtbUw3VEdjMkU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26079, 1449, 10, CONCAT('Inner Brief / Chuck to the Future / Help! We Are Angels'), '2010-12-04', 'https://drive.google.com/file/d/0B1WyIQUrSAJQekxfZEhIWUUxMVk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26080, 1449, 11, CONCAT('Once Upon a Time... in Garterbelt / Nothing to Room'), '2010-12-11', 'https://drive.google.com/file/d/1EXsIlCRawM6AhdufUWeqBv9Po12RDkfK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26081, 1449, 12, CONCAT('D.C. Confidential / Panty + Brief'), '2010-12-18', 'https://drive.google.com/file/d/0B1WyIQUrSAJQR1V5dVFDWUViOVU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26082, 1449, 13, CONCAT('Bitch Girls / Bitch Girls: 2 Bitch'), '2010-12-25', 'https://drive.google.com/file/d/0B1WyIQUrSAJQNFJOa0pJYlBpcU0/preview');
