INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1451, CONCAT('Paradise Kiss'), CONCAT('On her way home from school, Yukari Hayasaka is approached by a weird-looking guy who starts looking at her body intently. He', CHAR(39), 's got blond spiky hair, a spiked choker, and multiple piercings on his ears and face. She wants nothing to do with him, and runs away, only to bump into a very tall and beautiful purple-haired woman with a flower pattern around her eye. Yukari faints from shock and wakes up later in a strange place called the Atelier. It turns out that these strangers are fashion designers who attend the most famous art school around, Yazawa Art Academy, and their group wants Yukari to model for their brand in Yazawa Academy', CHAR(39), 's upcoming show.<br>
<br>Yukari turns down their offer and escapes the Atelier, but unknowingly leaves her school ID behind. George Koizumi, the head designer, later sees it and immediately knows she would be the perfect model for them and will not stop until he gets what he wants—and he wants her. Yukari had never considered something as frivolous as modeling before, but could life among these eccentric designers actually prove to be fun? Or will Yukari lose herself in this world of art and passion?<br>
<br>[Written by MAL Rewrite]<br>'), 2, '2005-10-14', '2005-12-30', 'Fall 2005', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/80636.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1028, 1451, '"♥Lonely in Gorgeous♥"', ' by Tommy february6', 'js-theme-songs', 'https://open.spotify.com/track/59e8U3Zr7Eo3KG9pNB4XSk');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1029, 1451, '"Do You Want To"', ' by Franz Ferdinand', 'js-theme-songs', 'https://open.spotify.com/track/6WrnSlcN0dzTO80mVVbBto');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3601, 1451, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3602, 1451, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1558, 1451, 102);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26095, 1451, 1, CONCAT('Studio'), '2005-10-14', 'https://drive.google.com/file/d/1bLti3TifZ8oHSOBLGfABwQQjrbIdhaGp/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26096, 1451, 2, CONCAT('Illumination'), '2005-10-20', 'https://drive.google.com/file/d/1ULaPLFdfsLtWAS4L8tu-4k8nhyxewdw9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26097, 1451, 3, CONCAT('Kiss'), '2005-10-28', 'https://drive.google.com/file/d/1KqioWkbfaH4t3XXN3BiCQGpMW4mM3ZS6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26098, 1451, 4, CONCAT('George'), '2005-11-04', 'https://ebd.cda.pl/620x395/5572011a8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26099, 1451, 5, CONCAT('Mother'), '2005-11-11', 'https://drive.google.com/file/d/17cDaY4LF6ZoJgoQzrk8DSroUpdSutxEq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26100, 1451, 6, CONCAT('New World'), '2005-11-18', 'https://drive.google.com/file/d/1sBhChXzki1VF5GwcuYN-yN-Ks2WMK2z1/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26101, 1451, 7, CONCAT('Butterfly'), '2005-11-25', 'https://drive.google.com/file/d/1a9NbHZVXtYbuxkWNN_AMeYW8xMY95wVw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26102, 1451, 8, CONCAT('Tokumori'), '2005-12-02', 'https://ebd.cda.pl/620x395/55720142b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26103, 1451, 9, CONCAT('Designer'), '2005-12-09', 'https://ebd.cda.pl/620x395/5572020f0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26104, 1451, 10, CONCAT('Rose'), '2005-12-16', 'https://drive.google.com/file/d/1kXagbw-ZpqbZZO40ZDmXcjg_jWtPHMdI/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26105, 1451, 11, CONCAT('Stage'), '2005-12-23', 'https://drive.google.com/file/d/1haNyUa_uIY5NFnroYx8PvQORRSjDsUmQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26106, 1451, 12, CONCAT('Future'), '2005-12-30', 'https://drive.google.com/file/d/1oWXx37Gv_x_WjuZ5vJ-ujkPiYE0XxqCx/preview');
