INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1472, CONCAT('Ping Pong the Animation'), CONCAT('Despite being polar opposites, Makoto "Smile" Tsukimoto and Yutaka "Peco" Hoshino have been best friends since childhood. Although the overly confident Peco strives to be the best ping-pong player in the world, he often skips practice, earning the ire of his fellow teammates on the Katase High School ping-pong team. Meanwhile, Smile—in spite of his innate talent for the sport—cannot help but hold back his full strength when playing against others. Through their mutual love for ping-pong, the two have developed a bond that is seemingly unbreakable.<br>
<br>When Peco hears that an ex-national team player from China is coming to Japan, he drags Smile over to rival Tsujido High School to observe them. The subsequent trip leads to a clash between Peco and Kong Wenge, who overwhelmingly defeats the former in one game. Stunned by such a comprehensive loss, Peco finds himself questioning why he plays to begin with. Seeing his potential as a player, Katase', CHAR(39), 's coach begins to train Smile to overcome his hesitation, but he is reluctant to play if it is not for enjoyment.<br>
<br>As the two struggle to find meaning in the sport, a plethora of stronger players—each with their own internal strifes—await them at the inter-high tournament, where only the very best can persevere. But when these young athletes let their unbridled ambition go unchecked, the hardships they face paint a somber reality as they pursue glory.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2014-04-11', '2014-06-20', 'Spring 2014', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/10/58041.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1042, 1472, '"Tada Hitori (唯一人)"', ' by Bakudan Johnny (爆弾ジョニー)', 'js-theme-songs', 'https://open.spotify.com/track/1dRCFFwXXVXMPmK4eCGsCJ')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3651, 1472, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3652, 1472, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3653, 1472, 10);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3654, 1472, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1578, 1472, 5);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26356, 1472, 1, CONCAT('The Sound of the Wind is in the Way'), '2014-04-11', 'https://ebd.cda.pl/620x395/608020407');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26357, 1472, 2, CONCAT('Smile is a Robot'), '2014-04-18', 'https://ebd.cda.pl/620x395/6080234a9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26358, 1472, 3, CONCAT('Devoting Your Life to Table Tennis is Creepy'), '2014-04-25', 'https://ebd.cda.pl/620x395/6080201d0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26359, 1472, 4, CONCAT('The Only Way to Avoid Losing by Not Fighting'), '2014-05-02', 'https://ebd.cda.pl/620x395/60802104f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26360, 1472, 5, CONCAT('Where Did I Go Wrong?'), '2014-05-09', 'https://ebd.cda.pl/620x395/608021372');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26361, 1472, 6, CONCAT('You Love Table Tennis More Than Anyone Else!!'), '2014-05-16', 'https://ebd.cda.pl/620x395/608021670');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26362, 1472, 7, CONCAT('Yes, My Coach'), '2014-05-23', 'https://ebd.cda.pl/620x395/608022220');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26363, 1472, 8, CONCAT('Enter the Hero'), '2014-05-30', 'https://ebd.cda.pl/620x395/608021944');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26364, 1472, 9, CONCAT('I', CHAR(39), 'm Gonna Go Cry'), '2014-06-06', 'https://ebd.cda.pl/620x395/608022802');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26365, 1472, 10, CONCAT('You', CHAR(39), 're a Hero, Aren', CHAR(39), 't You?!'), '2014-06-13', 'https://ebd.cda.pl/620x395/608022514');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (26366, 1472, 11, CONCAT('Blood Tastes Like Iron'), '2014-06-20', 'https://ebd.cda.pl/620x395/608023103');
