INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1501, CONCAT('Project Scard: Praeter no Kizu'), CONCAT('Under siege by foreign organizations, the Akatsuki Special Ward is a battlefield tainted with greed and violence, abandoning its citizens caught in the crossfire. In the wake of the anarchic turmoil emerges the Scard—vigilantes who wield supernatural abilities gifted to them by divine tattoos. Among them is Eiji Arashiba, the Hero of Akatsuki, who protects the district from tyrant outsiders.<br>
<br>One fateful day, Eiji contends with Dusk—a mafia syndicate—alongside Yamato Kai, a boy he recently met. Amid the chaos, Yamato blocks a sniper bullet heading toward Eiji, but the shot still strikes his tattoo despite Yamato', CHAR(39), 's efforts. To save the injured Yamato, Eiji passes the tattoo onto him, entrusting him with protecting the Akatsuki Special Ward in his sacrifice.<br>
<br>As the ward continues to collapse under conflict, will Yamato be able to use his newfound Scard powers to protect his loved ones, or will he falter trying to become the new Hero of Akatsuki?<br>
<br>[Written by MAL Rewrite]'), 1, '2021-01-09', '2021-04-03', 'Winter 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1239/111647.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1618, 1501, 108);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27727, 1501, 1, CONCAT('The Town Had Its Hero'), '2021-01-09', 'https://drive.google.com/file/d/1MydzXub_56EGCyj4C46VJmVNzbby7zUG/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27728, 1501, 2, CONCAT('Cerberus'), NULL, 'https://drive.google.com/file/d/1afUvwyCCaGd88KlmDgPQyDKWoWeJWuQa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27729, 1501, 3, CONCAT('The Twin Wings of Artemis'), NULL, 'https://ebd.cda.pl/620x368/65525306a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27730, 1501, 4, CONCAT('Public Security Special Service'), NULL, 'https://drive.google.com/file/d/1QXgrRw5PY9cAXThhnqSD0hVDrj4HIA2Z/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27731, 1501, 5, CONCAT('We the Twin Wings Do Solemnly Swear'), NULL, 'https://drive.google.com/file/d/1sTjspqnQVUocjCn3ywkxbDqJ7TvsgUh6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27732, 1501, 6, CONCAT('Justice With Force'), NULL, 'https://drive.google.com/file/d/11LWAh6CNWwoSGYbD3pvSfX247HdUrGM9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27733, 1501, 7, CONCAT('Dusk Arrives'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4250161');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27734, 1501, 8, CONCAT('Dawn'), NULL, 'https://drive.google.com/file/d/12bohHSIDVKX4a3BsudyzVTjp-Lut012d/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27735, 1501, 9, CONCAT('The Warg', CHAR(39), 's Claw Marks'), NULL, 'https://drive.google.com/file/d/125-tNh2mWQT9hOXSQdVL_bsj_-Vl_ZTZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27736, 1501, 10, CONCAT('The Moon and the Sun'), NULL, 'https://drive.google.com/file/d/1hAekowNi1P7Z9Ljy0FL_liPfPwTcrsYR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27737, 1501, 11, CONCAT('Fenrir'), NULL, 'https://drive.google.com/file/d/1Yc5QDvAzEZxShPJc0uG-6kHFum2BeueD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27738, 1501, 12, CONCAT('The Blockade of Akatsuki'), NULL, 'https://drive.google.com/file/d/1rETUp0vUlbWkBNocYh1zIXfbtwuUWfry/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27739, 1501, 13, CONCAT('Hero of Akatsuki'), NULL, 'https://drive.google.com/file/d/1qs1-XLCprMemjCuY3Kd4Hdc_yzhSlzym/preview');
