INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1509, CONCAT('Pupipo!'), CONCAT('Himeji Wakaba is a 5th year elementary school student, and she has the ability to see things that others can', CHAR(39), 't. They are mostly frightening evil spirits, and they tend to do bad things to people who are close to her. As a result, Wakaba has no friends and rarely smiles. On a couple of occasions, she brings home stray animals, but her parents won', CHAR(39), 't let her keep them. However, they', CHAR(39), 're worried about their sad, creepy daughter, so one day they decide that whatever Wakaba brings home next, they', CHAR(39), 'll let her keep.<br>
<br>The next thing she brings home is a pink monster called "Pupipo", but her parents stand by their decision and let her keep it. No one is quite sure what Pupipo is, but it protects Wakaba from the other things she sees. Pupipo also helps Wakaba make friends with an occult-obsessed transfer student and solve problems with bullying. Wakaba', CHAR(39), 's life is a much better place with her pet pink monster!<br>
<br>(Source: MangaHelpers)'), 1, '2013-12-21', '2014-03-29', 'Winter 2014', '4 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/58853.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1073, 1509, '"Shred Gear Rhapsody"', ' by Picasso', 'js-theme-songs', 'https://open.spotify.com/track/3JwUbaYyXP9cxjM56ufKZP');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3761, 1509, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3762, 1509, 8);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3763, 1509, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1626, 1509, 113);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27832, 1509, 1, CONCAT('Wakaba and the Sunset and the Mysterious Creature'), '2013-12-21', 'https://drive.google.com/file/d/0B5-MnnU6QEhhUzVtTjZtc0Vra0E/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27833, 1509, 2, CONCAT('Call Me Az!'), '2013-12-28', 'https://video.sibnet.ru/shell.php?videoid=1357712');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27834, 1509, 3, CONCAT('The Sunset of Youth'), '2014-01-04', 'https://drive.google.com/file/d/1lN_C0c03uIByK7dVdqshnR3xPXu_7hI6/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27835, 1509, 4, CONCAT('Dark Sunday'), '2014-01-11', 'https://drive.google.com/file/d/1-_Qe9ByislR9uNSODo35_qlM_JVKOeO7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27836, 1509, 5, CONCAT('Next Stop, the Afterlife'), '2014-01-18', 'https://drive.google.com/file/d/1PNsGcilRF5ej9X4YaxyAfD_IcymyKQcO/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27837, 1509, 6, CONCAT('Birds of a Feather Flock Apart'), '2014-01-25', 'https://drive.google.com/file/d/0B3g2KqMctI9qVHBxNWFZUFM5YzQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27838, 1509, 7, CONCAT('Unseen Confusion'), '2014-02-01', 'https://drive.google.com/file/d/0B3g2KqMctI9qRnV2TmhLa3dTaHM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27839, 1509, 8, CONCAT('A Light in the Darkness'), '2014-02-08', 'https://drive.google.com/file/d/0B_wqRYJzCdS3NzFDdm9DelBpMkk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27840, 1509, 9, CONCAT('Before Summer'), '2014-02-15', 'https://drive.google.com/file/d/0B_wqRYJzCdS3NnVpbDhlRVJ6dm8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27841, 1509, 10, CONCAT('The End of Oblivion'), '2014-02-22', 'https://drive.google.com/file/d/0B21A248sVfNva2JwSWRxc0pkYm8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27842, 1509, 11, CONCAT('In the Land of Falling Light'), '2014-03-01', 'https://drive.google.com/file/d/0B21A248sVfNvSFgzQTc1b2tOb28/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27843, 1509, 12, CONCAT('Rebirth'), '2014-03-08', 'https://drive.google.com/file/d/0B21A248sVfNvOWFaSzBQclBsbWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27844, 1509, 13, CONCAT('The Spring of Reincarnation'), '2014-03-15', 'https://drive.google.com/file/d/0B21A248sVfNvczB4aTVSU04xVzg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27845, 1509, 14, CONCAT('Collapse'), '2014-03-22', 'https://drive.google.com/file/d/0B21A248sVfNvVnF3NERZUXoxblE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27846, 1509, 15, CONCAT('At Summer', CHAR(39), 's End'), '2014-03-29', 'https://drive.google.com/file/d/0B21A248sVfNvbC00STkydFcyM3M/preview');
