INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1544, CONCAT('ReLIFE: Kanketsu-hen'), CONCAT('After reliving the life of a high school student through the ReLIFE experiment, 27-year-old Arata Kaizaki cannot believe how quickly it has changed him. He has begun to see the world through a different perspective that he had completely forgotten as an adult. He has made friends and formed deep relationships with each one of them. However his support, Ryou Yoake, reminds him that the experiment is all an illusion after his experiment ends, he will be forgotten by all of them.<br>
<br>The experiment of another ReLIFE subject is also coming to an end. After spending two years with ReLIFE, Chizuru Hishiro has developed into a more open, more thoughtful person than she could have ever imagined. She has met people who have changed her life, her perspective, and ultimately her. However, now that their ReLIFE is coming to an end, will they be able to let go of the memories they have made?<br>
<br>[Written by MAL Rewrite]'), 5, '2018-03-21', NULL, '', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1566/91061.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3834, 1544, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3835, 1544, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1662, 1544, 23);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28303, 1544, 1, CONCAT('Seed'), '2018-03-21', 'https://drive.google.com/file/d/12jBaGasrwvSGYKOxnpWtbiyPWK8-Ayx5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28304, 1544, 2, CONCAT('Need'), '2018-03-21', 'https://drive.google.com/file/d/1FM5IuT_LFnFgitZGnYBh0XhetupfzCFw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28305, 1544, 3, CONCAT('Date'), '2018-03-21', 'https://ebd.cda.pl/620x395/6086897fe');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28306, 1544, 4, CONCAT('Life'), '2018-03-21', 'https://ebd.cda.pl/620x368/6086900a4');
