INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1545, CONCAT('Renai Boukun'), CONCAT('When a strange girl named Guri comes knocking at Seiji Aino', CHAR(39), 's door, he quickly finds himself thrust into a world of romantic troubles. Claiming that she will die if he doesn', CHAR(39), 't kiss someone within 24 hours, Guri', CHAR(39), 's pleas of desperation are misunderstood as pleas for love, leading Seiji to kiss the cute stranger that came barging into his house. In actuality, it turns out that this cosplaying cupid is the wielder of a Kiss Note, in which any pairing of names she writes will kiss and become a couple. Guri explains that she misspelt and accidentally wrote Seiji', CHAR(39), 's name while indulging in her yaoi fantasies, but because she had yet to pair him with anyone, their kiss was meaningless. Even worse, Guri reveals that if Seiji is not coupled with anyone soon, not only will she die, but Seiji will remain a virgin for eternity!<br>
<br>Eager to escape his fate, Seiji sets his sights on the beautiful and popular Akane Hiyama. But after Akane hears that he kissed Guri, she reveals the obsessive and psychopathic feelings that she holds for the unfortunate boy and proceeds to viciously attack them. In the ensuing confusion, Guri is able to pair Seiji with Akane in the Kiss Note, temporarily saving Seiji from any further bodily harm. But to complicate matters, Guri', CHAR(39), 's newfound feelings lead her to also pair the two of them with herself. Just when the situation could not get any more convoluted, this new coupling with Guri has turned Seiji and Akane into temporary angels, forcing them into assisting the cupid with her work of pairing humans, lest they be cast into hell. With all semblance of normality snatched from his life, Seiji gets to work at matchmaking with these eccentric girls by his side.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-04-07', '2017-06-23', 'Spring 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/9/84266.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3836, 1545, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3837, 1545, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3838, 1545, 10);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3839, 1545, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1663, 1545, 48);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1676, 1545, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1677, 1545, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28307, 1545, 1, CONCAT('I', CHAR(39), 'm Getting In on This, Too x Whoa! Forbidden Love?!'), '2017-04-07', 'https://ebd.cda.pl/620x395/6774074e9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28308, 1545, 2, CONCAT('Sniff Sniff x The Only One Who May Hurt Seiji-kun... Is Me'), '2017-04-14', 'https://ebd.cda.pl/620x395/677407178');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28309, 1545, 3, CONCAT('I Can Handle This Myself! x Wassup'), '2017-04-21', 'https://ebd.cda.pl/620x395/677411023');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28310, 1545, 4, CONCAT('I', CHAR(39), 'm Not Going to Lose! x Are You Like Me?'), '2017-04-28', 'https://ebd.cda.pl/620x395/677411963');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28311, 1545, 5, CONCAT('What Is Love? x Kami Is Prostrating Himself Now lolol'), '2017-05-05', 'https://ebd.cda.pl/620x395/6774107a9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28312, 1545, 6, CONCAT('Go to the Beach With Me? x It', CHAR(39), 's Not a Matter of Knowing or Not'), '2017-05-12', 'https://ebd.cda.pl/620x395/67741165c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28313, 1545, 7, CONCAT('It', CHAR(39), 's a Festival x How Did It Come to This?!'), '2017-05-19', 'https://ebd.cda.pl/620x395/6774089da');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28314, 1545, 8, CONCAT('Farewell x We', CHAR(39), 're Rivals, Obviously!!'), '2017-05-26', 'https://ebd.cda.pl/620x395/6774092da');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28315, 1545, 9, CONCAT('Absolutely... Nothing... x There', CHAR(39), 's Just Something Wrong With Me...'), '2017-06-02', 'https://ebd.cda.pl/620x395/677409516');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28316, 1545, 10, CONCAT('I', CHAR(39), 'm Here to Stay the Night x I', CHAR(39), 'm... Growing Up, Too'), '2017-06-09', 'https://ebd.cda.pl/620x395/677410122');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28317, 1545, 11, CONCAT('Where Did She Go? x I Apologize for Troubling You Until Now'), '2017-06-16', 'https://ebd.cda.pl/620x395/6774104d5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28318, 1545, 12, CONCAT('Right, Let', CHAR(39), 's All Die! x I Finally Understand'), '2017-06-23', 'https://ebd.cda.pl/620x368/1468359f0');
