INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1559, CONCAT('RobiHachi'), CONCAT('Ever since they encountered aliens on the moon, humanity', CHAR(39), 's technology has developed by leaps and bounds. Half a century later, even though most have it easy, Robby Yaji and Hacchi Kita cannot seem to catch a break in this advanced society. Robby—a man perpetually struck by misfortune—owes large sums of money to debt collectors due to his poor investments in shady get-rich-quick schemes, and Hacchi finds it difficult to get over the boredom of his mundane life.<br>
<br>The two end up on an adventure of a lifetime when loan shark boss Yang sends Hacchi to collect the money Robby owes. Rather than pay up, Robby blasts off into space and heads to Isekandar, a planet that supposedly brings happiness to anyone who visits. Seeing a chance for some much needed excitement, Hacchi tags along with Robby on this journey filled with alien encounters, giant robot battles, and all sorts of troublemaking—all the while avoiding Yang and his cronies who are desperately combing the universe to find them.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-04-08', '2019-06-24', 'Spring 2019', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1555/100447.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1106, 1559, '"Tensai no Playlist (天才のプレイリスト)"', ' by Hatchi feat.Robby (CV: Keisuke Koumoto, Kazuya Nakai)', 'js-theme-songs', 'https://open.spotify.com/track/18mtV5FzPTvFXWSxWQMVSX')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3869, 1559, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3870, 1559, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3871, 1559, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1676, 1559, 132);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28468, 1559, 1, CONCAT('Traveling Companions: Journey to the Star'), '2019-04-08', 'https://ebd.cda.pl/620x368/334882995');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28469, 1559, 2, CONCAT('Truth Found from an Octopus'), '2019-04-15', 'https://ebd.cda.pl/620x368/337756669');
