INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1570, CONCAT('RPG Fudousan'), CONCAT('In a world at peace 15 years after the defeat of the demon lord, a newly graduated mage named Kotone Kazairo moves to Dali—the royal capital of the Kingdom of Actus—to begin a new chapter in her life. To find a place to settle, the 16-year-old goes to a real estate firm called Rent Plan Guide (RPG). There, she meets its employees: the pragmatic priest Rufuria, the tomboyish warrior Rakira, and the adorable demihuman Fa.<br>
<br>Coincidentally, Kotone is also set to work at RPG Real Estate and wastes no time learning about the business from her coworkers. With many housing options available to suit the varied eccentricities of its diverse customer pool, RPG Real Estate strives to deliver perfect matches for clients', CHAR(39), ' specific needs, but it is not always an easy task. Even so, Kotone and her colleagues are determined to bring smiles to the faces of their patrons—one home at a time!<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-04-06', '2022-06-22', 'Spring 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1680/122002.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3903, 1570, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3904, 1570, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1687, 1570, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28604, 1570, 1, CONCAT('Welcome to RPG Real Estate! Room-Searching for the First Time!'), NULL, 'https://ebd.cda.pl/620x368/105557188f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28605, 1570, 2, CONCAT('Troublesome Property! First Business Trip to the Dark Lord', CHAR(39), 's Castle'), NULL, 'https://ebd.cda.pl/620x368/10618985c9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28606, 1570, 3, CONCAT('For Real! Dragon, Ghost, Overwhelming Magic?!'), NULL, 'https://dood.pm/e/d4hoojt5pl2x');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28607, 1570, 4, CONCAT('Always Together! A Property Packed with Pets, Dreams, and Friendship!'), NULL, 'https://dood.pm/e/esxt1rqeowx9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28608, 1570, 5, CONCAT('Summer! We Found a Great House for Wearing Swimsuits!'), NULL, 'https://ebd.cda.pl/800x450/11647748b7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28609, 1570, 6, CONCAT('A Melody for the Grim Reaper!? We', CHAR(39), 're All Friends! Let', CHAR(39), 's Get Along!'), NULL, 'https://dood.pm/e/vfm6u33gpp9v');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28610, 1570, 7, CONCAT('Doors, Doors, Doors! Open the Door to Summer Vacation!'), NULL, 'https://dood.pm/e/9ranlqraenbf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28611, 1570, 8, CONCAT('Wha!? Finding a Dream Home through Fortune Telling!?'), NULL, 'https://dood.pm/e/9eq4umk078oi');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28612, 1570, 9, CONCAT('Nyan! One more deal until we meet our goal! Let', CHAR(39), 's make our wishes come true at the Millennium Star Festival!'), NULL, 'https://dood.pm/e/d4jq33cnenk5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28613, 1570, 10, CONCAT('Woes of Longevity! I Need a Sturdy House That I Can Live in for a Long Time!'), NULL, 'https://dood.pm/e/ybzkrx2if7dz');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28614, 1570, 11, CONCAT('Fa, Let', CHAR(39), 's Go Home Together'), NULL, 'https://dood.pm/e/3ghypp6w0tf0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28615, 1570, 12, CONCAT('Thanks, Everyone! RPG Real Estate', CHAR(39), 's New Journey Begins! '), NULL, 'https://dood.pm/e/ciw2r9s6gb3t');
