INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1620, CONCAT('Scared Rider Xechs'), CONCAT('The Blue World, which symbolizes reason, is under constant attack by the creatures called the Nightfly O', CHAR(39), 'Note originating from the Red World, symbolizing instinct. Akira Asagi, the 17-year-old protagonist who is a researcher at Blue World, is nominated to lead the war at Ryuukyuu LAG, a proud defense facility on the islands of Ishigaki and Iriomote. She meets the sixth combat unit "IS," which was formed four years after a fierce battle that annihilated the fifth unit. Akari must lead these six riders, also called the Scared Rider Xechs, to fight against the other world while at the same time deepening the relationship among them.<br>
<br>(Source: MAL News)'), 1, '2016-07-06', '2016-09-21', 'Summer 2016', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/79983.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1146, 1620, '"Ao to Kurenai no Forzato (青と紅のフォルツァート)"', ' by Yousuke Christoph Komae (Tatsuhisa Suzuki) & Takuto Kirisawa (Mamoru Miyano)', 'js-theme-songs', 'https://open.spotify.com/track/4Tp0pp1FjfdRJ7U4EFqNy7')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4031, 1620, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4032, 1620, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4033, 1620, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1743, 1620, 43);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29584, 1620, 1, CONCAT('RYUKYU Calling'), '2016-07-06', 'https://www.mp4upload.com/embed-2yizelq7f28a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29585, 1620, 2, CONCAT('Combat Rock'), '2016-07-13', 'https://www.mp4upload.com/embed-txcon1rl17kr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29586, 1620, 3, CONCAT('The Right Profile'), '2016-07-20', 'https://www.mp4upload.com/embed-otrzgs0z7pvk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29587, 1620, 4, CONCAT('Episode 4'), '2016-07-27', 'https://www.mp4upload.com/embed-z9nzf3vfduvh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29588, 1620, 5, CONCAT('Plan 6 Channel 5'), NULL, 'https://www.mp4upload.com/embed-ylddqayi0dqq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29589, 1620, 6, CONCAT('My Generation'), NULL, 'https://www.mp4upload.com/embed-lypetubbsmc2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29590, 1620, 7, CONCAT('Quadrophenia'), NULL, 'https://www.mp4upload.com/embed-ex42dzj4cvts.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29591, 1620, 8, CONCAT('To Be Someone'), NULL, 'https://www.mp4upload.com/embed-odg1n8mho60g.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29592, 1620, 9, CONCAT('Away From The Number'), NULL, 'https://www.mp4upload.com/embed-ibiu9gjhi4i4.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29593, 1620, 10, CONCAT('Stay Or Go'), NULL, 'https://www.mp4upload.com/embed-6v3l5yc49a5a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29594, 1620, 11, CONCAT('Not Of This Blue Earth'), NULL, 'https://www.mp4upload.com/embed-yxpanagr96mg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29595, 1620, 12, CONCAT('LAST GIG'), NULL, 'https://www.mp4upload.com/embed-xb7z0znt8bec.html');
