INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1646, CONCAT('Seitokai Yakuindomo*'), CONCAT('They say that the more things change, the more they stay the same, and those words could not be more true for the student council of Ousai Private Academy. Though an entire year has passed—bringing the senior members to their final year of high school—not much has changed. President Shino Amakusa is just as perverted as ever, Secretary Aria Shichijou still refuses to put on a pair of panties, Treasurer Suzu Hagimura has yet to grow an inch, and Vice President Takatoshi Tsuda is still stuck as the straight man to their crazy antics.<br>
<br>Of course, limiting the fun to a four-way might get a little stale although the group still messes around with the Judo Club and the Newspaper Club, more girls have come to get in on the excitement. Takatoshi', CHAR(39), 's sister Kotomi, a new student at Ousai, is as perverse as the president, while Uomi, the aloof student council president of the nearby Eiryou High School, fits right in with the insanity at Ousai. With loads of absurdity and sexual humor that keeps on coming, Takatoshi needs to harden up if he is going to keep up with all the madness around him.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-01-04', '2014-03-30', 'Winter 2014', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/9/56941.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1159, 1646, '"Hanasaku☆Saikyou Legend Days (花咲く☆最強レジェンドDays)"', ' by Triple Booking', 'js-theme-songs', '')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (696, 1646, 1);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1771, 1646, 108);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1809, 1646, 38);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1810, 1646, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30009, 1646, 1, CONCAT('Under the Cherry Blossom Trees, Once Again / The Sleepy Season, Slip / A Wolf Pretends'), '2014-01-04', 'https://drive.google.com/file/d/1lDldhQsCVEldmK7rPYt0H4RaiOpk9Czo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30010, 1646, 2, CONCAT('I Was Watching Over Hagimura Suzu / Ousai & Eiyou Have Another Mixer! / Always Have Tissues Ready for Your Check-up'), '2014-01-11', 'https://drive.google.com/file/d/1UAJwryzwNu_Cg9CJlptdmWoqXKe0q3cb/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30011, 1646, 3, CONCAT('The Three-Day Vice President / Beautiful Lady'), '2014-01-18', 'https://video.sibnet.ru/shell.php?videoid=1001807');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30012, 1646, 4, CONCAT('Emphasis Point Point Point / Moe-tail / Always Peeled Back at Groundbreaking Levels'), '2014-01-25', 'https://drive.google.com/file/d/1eb0mz8LaRrE_t8CAM-kMEYvh45inmNT7/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30013, 1646, 5, CONCAT('Support Style / Pitching a Tent After the Deed / Fighting Girls'), '2014-02-01', 'https://drive.google.com/file/d/1zL4mLAdXwb1OQ7YNhO681ulkw8Drtltk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30014, 1646, 6, CONCAT('Student Council President: The Idol / Attack Item Throb'), '2014-02-08', 'https://drive.google.com/file/d/1VzsLg8Q1K06D4nDyL_UkPS4tU-maa6x2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30015, 1646, 7, CONCAT('I Said Something Good / The Ones Who Make You, You / Yep, It Came Out'), '2014-02-15', 'https://drive.google.com/file/d/1fsxdYPZaajeRl-iZTydSg5bc3388ftAC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30016, 1646, 8, CONCAT('Play with Water and Get Soaked / All-purpose Wing / Summer Night, Summer Morning'), '2014-02-22', 'https://drive.google.com/file/d/14iTHtM1zSQakAfilOlfivGpKdlLKZkV9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30017, 1646, 9, CONCAT('Hata Ranko Does It! / Female Alumni are Super Awesome / Got the Wrong Idea'), '2014-03-01', 'https://drive.google.com/file/d/1kwn4Wgk26xASILD2BwSsR19xzoFEDhip/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30018, 1646, 10, CONCAT('The Tsuda Mushroom was as Expected / Feathers Fly / What it Feels Like to be a Pumpkin'), '2014-03-08', 'https://drive.google.com/file/d/1j8C7aKbBJPW_ZwJXEbgEUxZL80uF0oRX/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30019, 1646, 11, CONCAT('A Pure Reaction to a Double Entendre / That Happens in Some Countries / Play With the Snow, Santa', CHAR(39), 's Heirs!'), '2014-03-15', 'https://drive.google.com/file/d/10KEnI38aeFASOLB4OnaWT0Y8NTO0MClq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30020, 1646, 12, CONCAT('It', CHAR(39), 's Happy New Year / What It Takes to Stand Above Someone / Virgin / I Can', CHAR(39), 't Believe You', CHAR(39), 're Washing That'), '2014-03-22', 'https://drive.google.com/file/d/1Q09aHY80z2AxbBE-JHYe7zm0BXo-SQzu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30021, 1646, 13, CONCAT('How to Talk About Love Properly / Long Range Attack / Hair Showing / Cherry Blossom Sky'), '2014-03-29', 'https://drive.google.com/file/d/1T2Uod2oJHjpZPOnU7N-bt7x018fTjVhT/preview');
