INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1655, CONCAT('Selector Infected WIXOSS'), CONCAT('Things are not always what they seem. This is especially true for Ruuko Kominato, when she receives a deck of cards for the popular card game WIXOSS, only to find a girl trapped inside her LRIG, or avatar card. Upon meeting others in the same situation, Ruuko discovers that she has now become a "Selector," a player in a special version of WIXOSS where girls can battle each other for a chance to have their deepest desires come true. However, there is a catch. In contrast to the glory that awaits them after their victories, there is a cruel fate: if they lose three times, their lives will be destroyed.<br>
<br>In an ominous game filled with lies and deceit, Ruuko and her newfound friends must uncover the secrets behind WIXOSS and realize what is truly most important to them before it is too late.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-04-04', '2014-06-20', 'Spring 2014', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/70147.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1166, 1655, '"killy killy JOKER"', ' by Kanon Wakeshima', 'js-theme-songs', 'https://open.spotify.com/track/2EOuU9Brx1rXuFrBXScYQd')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1781, 1655, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1820, 1655, 37);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1821, 1655, 4);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1822, 1655, 9);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30098, 1655, 1, CONCAT('This Miracle Trembles'), '2014-04-04', 'https://video.sibnet.ru/shell.php?videoid=1444912');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30099, 1655, 2, CONCAT('That Poisonous Meeting'), '2014-04-11', 'https://drive.google.com/file/d/0B3g2KqMctI9qZFpDdnc5UjVzWlE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30100, 1655, 3, CONCAT('This Nonsensical Peace'), '2014-04-18', 'https://drive.google.com/file/d/0BxHOXujEV4CZeWlZLTdGdXUwZnc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30101, 1655, 4, CONCAT('That Wish is Blasphemy'), '2014-04-25', 'https://drive.google.com/file/d/0B_wqRYJzCdS3QWM1VlBKYWxxVGc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30102, 1655, 5, CONCAT('That Invalidated Vow'), '2014-05-02', 'https://vk.com/video212990883_169044229');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30103, 1655, 6, CONCAT('This Pure Heart'), '2014-05-09', 'https://drive.google.com/file/d/0B15WO7xgBq0IY1U1Y29wWVRFOGM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30104, 1655, 7, CONCAT('That Girl', CHAR(39), 's Desire'), '2014-05-16', 'https://video.sibnet.ru/shell.php?videoid=1494115');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30105, 1655, 8, CONCAT('That Fake Vow'), '2014-05-23', 'https://drive.google.com/file/d/0ByRHoFS6b0rRajh2LXkzQUc2YXc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30106, 1655, 9, CONCAT('The Cruel Truth'), '2014-05-30', 'https://video.sibnet.ru/shell.php?videoid=1498858');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30107, 1655, 10, CONCAT('That Stranded Emotion'), '2014-06-06', 'https://video.sibnet.ru/shell.php?videoid=1498859');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30108, 1655, 11, CONCAT('The Summer of Dreams'), '2014-06-13', 'https://video.sibnet.ru/shell.php?videoid=1498861');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30109, 1655, 12, CONCAT('That Choice...'), '2014-06-20', 'https://video.sibnet.ru/shell.php?videoid=1498862');
