INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1658, CONCAT('Sengoku Choujuu Giga: Kou'), CONCAT('The history, either daily life or life stories of Sengoku warriors, is described using animals. We invite popular young actors and unique casts to voice out those Sengoku warriors while joking about them. An anime that teases Japan', CHAR(39), 's history and Sengoku warriors that', CHAR(39), 's "Sengoku Choujuu Giga."<br>
<br>(Source: MAL News)'), 1, '2016-10-09', '2017-01-08', 'Fall 2016', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/82326.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1784, 1658, 2);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1831, 1658, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1832, 1658, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1833, 1658, 32);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1834, 1658, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30134, 1658, 1, CONCAT('Something I Want to Show You'), NULL, 'https://www.mp4upload.com/embed-3e8l2bpuloo7.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30135, 1658, 2, CONCAT('Who is First Spear?'), NULL, 'https://www.mp4upload.com/embed-v0pbfezokyma.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30136, 1658, 3, CONCAT('The Melancholy of Masamune'), NULL, 'https://www.mp4upload.com/embed-qp8geqiw2nw8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30137, 1658, 4, CONCAT('Two Weirdos'), NULL, 'https://www.mp4upload.com/embed-4hinff503urz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30138, 1658, 5, CONCAT('Rokumonsen'), NULL, 'https://www.mp4upload.com/embed-xz51gx23de0w.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30139, 1658, 6, CONCAT('My Fundoshi'), NULL, 'https://www.mp4upload.com/embed-iw02w35iskau.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30140, 1658, 7, CONCAT('The Secret of the Sandals'), NULL, 'https://www.mp4upload.com/embed-3llzih8hgrsk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30141, 1658, 8, CONCAT('Hit and Cover'), NULL, 'https://www.mp4upload.com/embed-s3xbm2t36flb.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30142, 1658, 9, CONCAT('Fuurinkazan'), NULL, 'https://www.mp4upload.com/embed-s8dbdo2k69xd.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30143, 1658, 10, CONCAT('Treasure'), NULL, 'https://www.mp4upload.com/embed-b1zglez47yvc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30144, 1658, 11, CONCAT('Hole'), NULL, 'https://www.mp4upload.com/embed-929ruyg5yoti.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30145, 1658, 12, CONCAT('Water Attack'), NULL, 'https://www.mp4upload.com/embed-d7yhzj6dxjzn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30146, 1658, 13, CONCAT('New Years'), NULL, 'https://www.mp4upload.com/embed-5qqgbz2k5o5p.html');
