INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1659, CONCAT('Sengoku Choujuu Giga: Otsu'), CONCAT('Second season of Sengoku Choujuu Giga.'), 1, '2017-01-15', '2017-04-09', 'Winter 2017', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/83737.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1785, 1659, 221);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1835, 1659, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1836, 1659, 11);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1837, 1659, 32);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30147, 1659, 1, CONCAT('Crane Soup'), NULL, 'https://www.mp4upload.com/embed-jy6eera8usx8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30148, 1659, 2, CONCAT('The Assault on Odawara Castle'), NULL, 'https://www.mp4upload.com/embed-dbr38qv7ewx3.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30149, 1659, 3, CONCAT('Nuppefuhofu'), NULL, 'https://www.mp4upload.com/embed-clns12s7tnfv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30150, 1659, 4, CONCAT('Body Double Audition.'), NULL, 'https://www.mp4upload.com/embed-i9gxpnt8lhy9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30151, 1659, 5, CONCAT('Rear Guard'), NULL, 'https://www.mp4upload.com/embed-itx1n4aebzxw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30152, 1659, 6, CONCAT('My First Banana'), NULL, 'https://www.mp4upload.com/embed-9ovbv8nxaiyv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30153, 1659, 7, CONCAT('Who am I?'), NULL, 'https://www.mp4upload.com/embed-jarvkq7wx1fp.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30154, 1659, 8, CONCAT('The Guy No One Likes'), NULL, 'https://www.mp4upload.com/embed-1iooznim8ns1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30155, 1659, 9, CONCAT('The Five Great Elders'), NULL, 'https://www.mp4upload.com/embed-3gqlw5txs2pp.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30156, 1659, 10, CONCAT('The Four Shimazu Brothers'), NULL, 'https://www.mp4upload.com/embed-2ugt1eck73e5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30157, 1659, 11, CONCAT('Rumors of Kenshin'), NULL, 'https://www.mp4upload.com/embed-j07hjiuv9vf6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30158, 1659, 12, CONCAT('Mistress of the Castle'), NULL, 'https://www.mp4upload.com/embed-vp6i1izwsrva.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30159, 1659, 13, CONCAT('The Honnoji Incident'), NULL, 'https://www.mp4upload.com/embed-cthi3ra9dhp8.html');
