INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1657, CONCAT('Sengoku Basara: Judge End'), CONCAT('Based on CAPCOM', CHAR(39), 's 2010 game Sengoku Basara 3 (Sengoku Basara: Samurai Heroes), Sengoku Basara: Judge End will depict the epic Battle of Sekigahara.<br>
<br>(Source: ANN)'), 5, '2014-07-06', '2014-09-28', 'Summer 2014', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/62511.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1168, 1657, '"Thunderclap"', ' by Fear, and Loathing in Las Vegas', 'js-theme-songs', 'https://open.spotify.com/track/2ftDCZTbtOHAVVdPC2Trjl')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1783, 1657, 2);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1827, 1657, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1828, 1657, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1829, 1657, 32);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1830, 1657, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30122, 1657, 1, CONCAT('Rift'), NULL, 'https://drive.google.com/file/d/0B_wqRYJzCdS3OWdpd1IxZGlVRkk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30123, 1657, 2, CONCAT('Chaos'), NULL, 'https://vk.com/video_ext.php?oid=248590174&id=169211175&hash=590dba899e3cd7a1&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30124, 1657, 3, CONCAT('Alliances'), NULL, 'https://drive.google.com/file/d/0B9LAVlU15MBaZFVkaUtFNGZxZG8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30125, 1657, 4, CONCAT('Astray'), NULL, 'https://drive.google.com/file/d/0B9LAVlU15MBaWVNtOG9RWFpyNUU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30126, 1657, 5, CONCAT('Defeat'), NULL, 'https://www.mp4upload.com/embed-eb0kcn8zhi8q.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30127, 1657, 6, CONCAT('Declarations'), NULL, 'https://www.mp4upload.com/embed-8dgpr897b5kq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30128, 1657, 7, CONCAT('Darkness'), NULL, 'https://www.mp4upload.com/embed-gsrohxnw6ogw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30129, 1657, 8, CONCAT('Promise'), NULL, 'https://www.mp4upload.com/embed-cfjww8ef7q8o.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30130, 1657, 9, CONCAT('Sekigahara'), NULL, 'https://www.mp4upload.com/embed-kspsfhtrmfq2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30131, 1657, 10, CONCAT('Life-and-Death'), NULL, 'https://www.mp4upload.com/embed-f7lrjnjhn544.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30132, 1657, 11, CONCAT('Verdict'), NULL, 'https://www.mp4upload.com/embed-a854u02e50r0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30133, 1657, 12, CONCAT('Guide'), NULL, 'https://www.mp4upload.com/embed-i4c5dr8vxhtq.html');
