INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1660, CONCAT('Sengoku Collection'), CONCAT('Sengoku Collection revolves around many samurai who are accidentally removed from a parallel universe inhabited by well-known historic characters. Unlike the historical war period known to us, all inhabitants in this unique world look like high school girls. Coming from the medieval era and finding themselves totally amazed by everything they encounter in modern day Tokyo, the girls become best friends through their adventures. <br>
<br>(Source: Crunchyroll) '), 1, '2012-04-06', '2012-09-28', 'Spring 2012', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/35329.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1169, 1660, '"Me wo Tojite Gyuttoshiyo (目をとじてギュッしよ)"', ' by ABCHO', 'js-theme-songs', 'https://open.spotify.com/track/7Aa0zODCvo3SvZ5UVcUtvV')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1786, 1660, 35);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1838, 1660, 21);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1839, 1660, 32);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30160, 1660, 1, CONCAT('Sweet Little Devil'), NULL, 'https://vk.com/video_ext.php?oid=172657569&id=162653932&hash=fac6099d6abea103&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30161, 1660, 2, CONCAT('Peaceful Empress'), NULL, 'https://vk.com/video_ext.php?oid=172657569&id=162658614&hash=70ad001085950332&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30162, 1660, 3, CONCAT('Pure Angel'), NULL, 'https://dood.so/e/7o6r472xyxbk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30163, 1660, 4, CONCAT('One-eyed Dragon'), NULL, 'https://dood.so/e/lslfvootbpxj');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30164, 1660, 5, CONCAT('Sword Maiden'), NULL, 'https://dood.so/e/lsdr46q5w6d1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30165, 1660, 6, CONCAT('Knowledge Masters'), NULL, 'https://dood.so/e/f9y6yurdf7ki');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30166, 1660, 7, CONCAT('Refined Bard'), NULL, 'https://dood.so/e/5ai1pojfh9sq');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30167, 1660, 8, CONCAT('Regent Girl'), NULL, 'https://www.mp4upload.com/embed-7079fe0e8nus.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30168, 1660, 9, CONCAT('Ambitious Princess-I'), NULL, 'https://dood.so/e/sh65ha1qwiue');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30169, 1660, 10, CONCAT('Ambitious Princess-II'), NULL, 'https://dood.so/e/lpg0hykb9t0b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30170, 1660, 11, CONCAT('Brutal Maiden'), NULL, 'https://dood.so/e/aig1ek6dpcgz');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30171, 1660, 12, CONCAT('Dancing Blossom'), NULL, 'https://dood.so/e/ycyc8pfzpzpk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30172, 1660, 13, CONCAT('Silver Hornet'), NULL, 'https://dood.so/e/kdq642kn50h8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30173, 1660, 14, CONCAT('Novel Deciders'), NULL, 'https://dood.so/e/ox8orq0v3ysk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30174, 1660, 15, CONCAT('Annihilate Princess'), NULL, 'https://dood.so/e/82dx63kvhl0u');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30175, 1660, 16, CONCAT('Blade Adept'), NULL, 'https://dood.so/e/9po0zbfj18a8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30176, 1660, 17, CONCAT('Sunshine Ruler'), NULL, 'https://dood.so/e/kfor2k6ux8yw');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30177, 1660, 18, CONCAT('Four Leaves'), NULL, 'https://dood.so/e/6z77l83tondm');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30178, 1660, 19, CONCAT('Vengeful Fang-IS'), NULL, 'https://dood.so/e/go0swuhauruy');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30179, 1660, 20, CONCAT('Vengeful Fang-OS'), NULL, 'https://www.mp4upload.com/embed-v1mu98egijhq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30180, 1660, 21, CONCAT('Cavalary Queen'), NULL, 'https://dood.so/e/1nb7ejeo8scp');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30181, 1660, 22, CONCAT('The Splendor'), NULL, 'https://dood.so/e/syq8vv70u3bf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30182, 1660, 23, CONCAT('The Dune'), NULL, 'https://dood.so/e/9xhqz390b661');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30183, 1660, 24, CONCAT('Peaceful Empress-EX'), NULL, 'https://dood.so/e/0ia879o70sr5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30184, 1660, 25, CONCAT('Marshal Princess'), NULL, 'https://dood.so/e/huzpsbz9vjsv');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30185, 1660, 26, CONCAT('Sengoku Collection'), NULL, 'https://dood.so/e/pxmi13fh14hy');
