INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1665, CONCAT('Senki Zesshou Symphogear AXZ'), CONCAT('Hibiki Tachibana has defeated many powerful enemies, saved countless innocent lives, and escaped from numerous desperate situations, but she is currently finding herself unable to escape from her most desperate situation yet—summer homework!  Although her high school life is relatively unremarkable, her career as a member of the military organization S.O.N.G. is anything but. Using powerful, ancient armor known as Symphogear, Hibiki and her teammates work with the United Nations to deal with international disputes and disasters.  <br>
<br>During a mission briefing at headquarters, Hibiki is made aware of a mysterious organization known as the Bavarian Illuminati, who has been responsible for several major disasters in the past and currently operate in the war-torn country Val Verde. Together, Hibiki and her team infiltrate one of the Bavarian Illuminati', CHAR(39), 's manufacturing plants and free hundreds of slaves. Exposed, alchemists Saint-Germain, Cagliostro, and Prelati reveal themselves as the organization', CHAR(39), 's top brass, and—using alchemical powers—declare a global revolution while sacrificing thousands of lives. Faced with yet another threat to the world', CHAR(39), 's survival, Hibiki and her allies must confront the Bavarian Illuminati in their most difficult and destructive battle yet.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-07-02', '2017-10-01', 'Summer 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/86584.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1173, 1665, '"TESTAMENT"', ' by Nana Mizuki', 'js-theme-songs', 'https://open.spotify.com/track/2QSZ2xvqALjTBqZfKxsMeI')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4123, 1665, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4124, 1665, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1791, 1665, 43);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1792, 1665, 114);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1853, 1665, 5);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1854, 1665, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30249, 1665, 1, CONCAT('Hell at Valverde'), NULL, 'https://ebd.cda.pl/620x368/1474842f9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30250, 1665, 2, CONCAT('Last Resort'), NULL, 'https://ebd.cda.pl/620x368/14828063b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30251, 1665, 3, CONCAT('A Horoscope Drawn By Gears'), NULL, 'https://ebd.cda.pl/620x368/1499770b0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30252, 1665, 4, CONCAT('Golden Transmutation'), NULL, 'https://ebd.cda.pl/620x368/1502627cf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30253, 1665, 5, CONCAT('Risking Your Life In A Fictional Warzone'), NULL, 'https://ebd.cda.pl/620x368/1507740d3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30254, 1665, 6, CONCAT('Surfacing From the Suicide Zone'), NULL, 'https://ebd.cda.pl/620x368/152750124');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30255, 1665, 7, CONCAT('ARCANA No. 00'), NULL, 'https://ebd.cda.pl/x/15305869d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30256, 1665, 8, CONCAT('In The Gap Between Past and Future'), NULL, 'https://ebd.cda.pl/800x450/40556293f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30257, 1665, 9, CONCAT('Blue Bunny'), NULL, 'https://ebd.cda.pl/800x450/405562672');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30258, 1665, 10, CONCAT('An Tiki Thera'), NULL, 'https://ebd.cda.pl/800x450/4055643cb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30259, 1665, 11, CONCAT('Ultimate Apotheosis'), NULL, 'https://ebd.cda.pl/800x450/4056028a9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30260, 1665, 12, CONCAT('AXZ'), NULL, 'https://ebd.cda.pl/800x450/40557401e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30261, 1665, 13, CONCAT('The Reality Proved When Each Tear Falls On The Next'), NULL, 'https://ebd.cda.pl/800x450/405569267');
