INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1673, CONCAT('Senyoku no Sigrdrifa'), CONCAT('When humanity is driven to the brink of despair by an alien threat called Pillars, a self-proclaimed god named Odin appears and bestows upon the people the power of "Valkyries"—battle maidens who pilot vintage aircraft called Hero Wings.<br>
<br>Claudia "Schwertleite" Bruford is the ace of the European Valkyrie Wing. When Japan', CHAR(39), 's S-class Valkyrie passes away in battle, Claudia is relocated to Japan as a replacement. However, with a dark record of being the sole survivor in every mission that results in being nicknamed "Grim Reaper," she suspects she already knows why she was chosen.<br>
<br>Prepared to be shunned yet again, she arrives at the Tateyama Valkyrie Wing. Little does she know, her new comrades are a bunch of oddballs who have zero intention of accepting her dreadful nickname!<br>
<br>[Written by MAL Rewrite]'), 1, '2020-10-03', '2020-12-26', 'Fall 2020', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1576/109007.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1803, 1673, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30349, 1673, 1, CONCAT('Welcome to Tateyama Base!'), NULL, 'https://ebd.cda.pl/620x368/589326863');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30350, 1673, 2, CONCAT('Umihotaru Sea Assault!'), NULL, 'https://ebd.cda.pl/620x368/593217246');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30351, 1673, 3, CONCAT('Disaster Recovery Assessment!'), NULL, 'https://ebd.cda.pl/620x368/597098088');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30352, 1673, 4, CONCAT('Tateyama Castle Swimsuit Skirmish!'), NULL, 'https://ebd.cda.pl/620x368/6008723e0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30353, 1673, 5, CONCAT('Tateyama Joint Forces!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4126455');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30354, 1673, 6, CONCAT('Fuji Pillar Assault!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4149670');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30355, 1673, 7, CONCAT('Fuji Pillar Retreat!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4150396');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30356, 1673, 8, CONCAT('Exploring a Mythical World!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4151470');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30357, 1673, 9, CONCAT('Retaking Tateyama Air Base!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4171327');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30358, 1673, 10, CONCAT('The Eve Before the Battle of Tateyama Bay!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4197668');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30359, 1673, 11, CONCAT('Reattacking Fuji Pillar!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4197669');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30360, 1673, 12, CONCAT('Welcome to Tateyama Base!!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4197677');
