INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1698, CONCAT('Shikkakumon no Saikyou Kenja'), CONCAT('At birth, mages randomly acquire one of the four "crests" that represents the extent of their magical capability. Equipped with a crest specializing in creation, a man named Gaius reached the ceiling of his potential, becoming known as the world', CHAR(39), 's strongest sage. Despite his overwhelming power, he is unsatisfied with his abilities and desires to possess the mark suitable for close combat. Knowing that a person', CHAR(39), 's crest is unchangeable, Gaius decides to reincarnate far into the future, hoping to alter his fate.<br>
<br>Thousands of years later, Gaius is reborn as Mathias Hildesheimer, successfully obtaining his long-coveted crest. However, he is surprised to learn that in these times, magic has vastly waned, and the techniques that were once widely used are now nothing more than just a speck of legend. Moreover, the crest that he painstakingly strived to attain is now considered the weakest—merely dubbed the "Crest of Failure."<br>
<br>Nevertheless, Mathias naturally exceeds all expectations. He enrolls into the royal capital', CHAR(39), 's Second Academy, acing every trial that comes his way. But soon after, Mathias discovers the dark truth behind humanity', CHAR(39), 's downfall into magical mediocrity—demons—and endeavors to remedy the consequence of his millennia-long absence once and for all.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-01-08', '2022-03-26', 'Winter 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1132/120388.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4215, 1698, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4216, 1698, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4217, 1698, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1832, 1698, 31);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30754, 1698, 1, CONCAT('The Strongest Sage Appears'), NULL, 'https://ebd.cda.pl/620x368/96156063d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30755, 1698, 2, CONCAT('The Strongest Sage Enters the Dungeon'), NULL, 'https://ebd.cda.pl/620x368/9707907a7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30756, 1698, 3, CONCAT('The Strongest Sage Meets a Dragon'), NULL, 'https://ebd.cda.pl/620x368/979697481');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30757, 1698, 4, CONCAT('The Strongest Sage Infiltrates'), NULL, 'https://ebd.cda.pl/620x368/989675411');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30758, 1698, 5, CONCAT('The Strongest Sage Makes Allies'), NULL, 'https://ebd.cda.pl/620x368/1001406067');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30759, 1698, 6, CONCAT('The Strongest Sage Leaves the School'), NULL, 'https://ebd.cda.pl/620x368/100849953d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30760, 1698, 7, CONCAT('The Strongest Sage Goes on a Journey'), NULL, 'https://ebd.cda.pl/620x368/1014845398');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30761, 1698, 8, CONCAT('The Strongest Sage Saves the City'), NULL, 'https://ebd.cda.pl/620x368/10214609c3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30762, 1698, 9, CONCAT('The Strongest Sage Duels'), NULL, 'https://ebd.cda.pl/620x368/1025933061');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30763, 1698, 10, CONCAT('The Strongest Sage Works With a Team'), NULL, 'https://ebd.cda.pl/620x368/1032713083');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30764, 1698, 11, CONCAT('The Strongest Sage Faces a Powerful Enemy'), NULL, 'https://ebd.cda.pl/620x368/1038209313');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30765, 1698, 12, CONCAT('The Strongest Sage Goes on a Journey Again.'), NULL, 'https://ebd.cda.pl/620x368/104440826f');
