INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1709, CONCAT('Shingeki no Kyojin Season 3 Part 2'), CONCAT('Seeking to restore humanity', CHAR(39), 's diminishing hope, the Survey Corps embark on a mission to retake Wall Maria, where the battle against the merciless "Titans" takes the stage once again.<br>
<br>Returning to the tattered Shiganshina District that was once his home, Eren Yeager and the Corps find the town oddly unoccupied by Titans. Even after the outer gate is plugged, they strangely encounter no opposition. The mission progresses smoothly until Armin Arlert, highly suspicious of the enemy', CHAR(39), 's absence, discovers distressing signs of a potential scheme against them. <br><br>Shingeki no Kyojin Season 3 Part 2 follows Eren as he vows to take back everything that was once his. Alongside him, the Survey Corps strive—through countless sacrifices—to carve a path towards victory and uncover the secrets locked away in the Yeager family', CHAR(39), 's basement.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-04-29', '2019-07-01', 'Spring 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1517/100633.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1209, 1709, '"Shoukei to Shikabane no Michi (憧憬と屍の道)"', ' by Linked Horizon', 'js-theme-songs', 'https://open.spotify.com/track/1rxLfrpsIR0x2wqI6vFNdP')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (717, 1709, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4240, 1709, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4241, 1709, 6);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1845, 1709, 158);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1907, 1709, 10);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1908, 1709, 25);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1909, 1709, 14);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30859, 1709, 1, CONCAT('The Town Where Everything Began'), '2019-04-29', 'https://drive.google.com/file/d/10XEdCtymxalVr-1vFNqaPhleuzibqRjZ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30860, 1709, 2, CONCAT('Thunder Spears'), '2019-05-06', 'https://drive.google.com/file/d/11CCRLx8dL0vck1WpQXnff59Op7Z578KF/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30861, 1709, 3, CONCAT('Descent'), '2019-05-13', 'https://drive.google.com/file/d/1xuao__SNjXZISZgbS9AuegEIC_Nh-Jnb/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30862, 1709, 4, CONCAT('Perfect Game'), '2019-05-20', 'https://drive.google.com/file/d/1z0zLeSU_J_WpQ-rFSLCyQGLdMuFmO80Q/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30863, 1709, 5, CONCAT('Hero'), '2019-05-27', 'https://drive.google.com/file/d/1bWIYipgsbnv0m5s3Ug_7206DboJVQEA4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30864, 1709, 6, CONCAT('Midnight Sun'), '2019-06-03', 'https://drive.google.com/file/d/1PSBp5jbZORoVZ46qGt8RxIUFMo_7YFXv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30865, 1709, 7, CONCAT('The Basement'), '2019-06-10', 'https://drive.google.com/file/d/1Kb64GrO20ztxrjQxrS0LtDsXpKUroK6j/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30866, 1709, 8, CONCAT('That Day'), '2019-06-17', 'https://drive.google.com/file/d/1rl6VsJLRV8FEHz8SlxsZrYDvAMIdfSDG/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30867, 1709, 9, CONCAT('Attack Titan'), '2019-06-24', 'https://drive.google.com/file/d/1IdlprI9xPhMlEqGwitlXWd1a32LPEki1/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30868, 1709, 10, CONCAT('The Other Side of the Wall'), '2019-07-01', 'https://drive.google.com/file/d/1gw__TdJlFci5xF_hG9-msjmzo5JPsek3/preview');
