INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1726, CONCAT('Shirobako Specials'), CONCAT('Shirobako Specials is an OVA adaptation of the first episodes of the two fictional television anime produced by Musashino Animation in the Shirobako television anime.<br><br>Exodus!: Shutsu Tokyo
<br>Akane, Aya, and Alpine are the three members of the struggling idol group Tracy, which has yet to make a name for themselves. After their performance at a supermarket attracts a dismal audience, the trio', CHAR(39), 's leader Akane decides to turn their fortune around by confronting their disinterested manager Taguchi. But the girls are in for a surprise when they stumble across Taguchi', CHAR(39), 's corpse in a storage room, and become the prime suspects in his murder—all the while rising to the widespread fame they so desperately wanted.<br><br>Daisan Hikou Shoujotai: FALLING ANGEL
<br>The 307 Aerial Squad, also known as "Hell Alice," is part of a global military resistance against the enigmatic Builders, who have covered a third of Earth', CHAR(39), 's surface with mysterious structures known as Pillars. With all aircraft built after the 1970s disabled by the Pillars, Hell Alice must pilot their outdated equipment against the advanced technology stolen by the Builders. Among their ranks is the talented, school-aged Japanese girl Aria Hitotose, the so-called "Ice Doll" who never hesitates in even the most dire of situations. When an operation to rescue survivors from a destroyed base goes awry, it is up to Aria and her trusty allies to save the day.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2015-02-25', '2015-07-29', '', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/72234.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4292, 1726, 13);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4293, 1726, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4294, 1726, 6);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1865, 1726, 52);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1921, 1726, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1922, 1726, 18);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1923, 1726, 17);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31071, 1726, 1, CONCAT('"Exodus!" Episode 1: Exit Tokyo'), '2015-02-25', 'https://ebd.cda.pl/800x450/190724074');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31072, 1726, 2, CONCAT('"Third Aerial Girls Squad" File:01: Falling Angel'), '2015-07-29', 'https://ebd.cda.pl/800x450/1907471d7');
