INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1735, CONCAT('Shokugeki no Souma: Ni no Sara OVA'), CONCAT('Having completed their Stagiaire assignments, the residents of Polar Star Dormitory and their friends visit a hot springs inn. Though they planned on relaxing, these young chefs step up to the plate when the inn', CHAR(39), 's entire kitchen staff suffer accidents. Unbeknownst to them, they will not be cooking for any ordinary patrons.<br>
<br>Sometime after this trip, Souma Yukihira', CHAR(39), 's desire for worthy opponents is stoked when he, Megumi Tadokoro, and the other Autumn Election quarter-finalists are invited to the annual Autumn Leaves Viewing event. The eight Tootsuki freshmen have a special opportunity to enjoy tea with the Elite Ten Council—including the Tenth Seat Erina Nakiri, who participates alongside her first-year classmates. Though it is framed as a friendly introduction between nine promising underclassmen and nine prestigious upperclassmen, Director Senzaemon Nakiri sees this meeting for what it is: a first encounter between the current reigning elite and their eventual usurpers. <br>
<br>[Written by MAL Rewrite]'), 1, '2017-05-01', '2017-07-04', '', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1032/96640.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1228, 1735, '"ROUGH DIAMONDS"', ' by SCREEN mode', 'js-theme-songs', 'https://open.spotify.com/track/2t9txwVeiYmbMXsb6q8YPS')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (723, 1735, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4311, 1735, 15);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4312, 1735, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1874, 1735, 31);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31244, 1735, 1, CONCAT('Episode 1'), '2017-05-01', 'https://ebd.cda.pl/800x450/434115842');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31245, 1735, 2, CONCAT('Episode 2'), '2017-07-04', 'https://ebd.cda.pl/800x450/4346582a6');
