INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1744, CONCAT('Shouwa Genroku Rakugo Shinjuu'), CONCAT('Yotarou is a former yakuza member fresh out of prison and fixated on just one thing: rather than return to a life of crime, the young man aspires to take to the stage of rakugo, a traditional Japanese form of comedic storytelling. Inspired during his incarceration by the performance of distinguished practitioner Yakumo Yuurakutei, he sets his mind on meeting the man who changed his life. After hearing Yotarou', CHAR(39), 's desperate appeal for his mentorship, Yakumo is left with no choice but to accept his very first apprentice.<br>
<br>As he eagerly begins his training, Yotarou meets Konatsu, an abrasive young woman who has been under Yakumo', CHAR(39), 's care ever since her beloved father Sukeroku Yuurakutei, another prolific rakugo performer, passed away. Through her hidden passion, Yotarou is drawn to Sukeroku', CHAR(39), 's unique style of rakugo despite learning under contrasting techniques. Upon seeing this, old memories and feelings return to Yakumo who reminisces about a much earlier time when he made a promise with his greatest rival.<br><br>Shouwa Genroku Rakugo Shinjuu is a story set in both the past and present, depicting the art of rakugo, the relationships it creates, and the lives and hearts of those dedicated to keeping the unique form of storytelling alive.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-01-09', '2016-04-02', 'Winter 2016', '26 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1354/124768.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1234, 1744, '"Usurahi Shinjuu (薄ら氷心中)"', ' by Megumi Hayashibara', 'js-theme-songs', 'https://open.spotify.com/track/4QYzCp1ADvsI0Qdv2q6DiI')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (727, 1744, 5);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1883, 1744, 46);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1941, 1744, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1942, 1744, 22);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1943, 1744, 41);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31370, 1744, 1, CONCAT('Episode 1'), '2016-01-09', 'https://myvi.ru/player/embed/html/oan5BMf8nv9HhMBAG3YlRyWvzloRTwtJ6DcowhEudU4UkaXWsnOODZJqn7veJppVV0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31371, 1744, 2, CONCAT('Episode 2'), '2016-01-16', 'https://www.mp4upload.com/embed-2kso1spqudxb.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31372, 1744, 3, CONCAT('Episode 3'), '2016-01-23', 'https://www.mp4upload.com/embed-sryp9cbzvoso.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31373, 1744, 4, CONCAT('Episode 4'), '2016-01-30', 'https://www.mp4upload.com/embed-jucvrtgqt0i1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31374, 1744, 5, CONCAT('Episode 5'), '2016-02-06', 'https://www.mp4upload.com/embed-282lmje6h9ej.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31375, 1744, 6, CONCAT('Episode 6'), '2016-02-13', 'https://www.mp4upload.com/embed-5h7v249rlmc5.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31376, 1744, 7, CONCAT('Episode 7'), '2016-02-20', 'https://mp4upload.com/embed-1oq94ibox69m.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31377, 1744, 8, CONCAT('Episode 8'), '2016-02-27', 'https://video.sibnet.ru/shell.php?videoid=2531816');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31378, 1744, 9, CONCAT('Episode 9'), '2016-03-05', 'https://www.mp4upload.com/embed-867wp0ru52z0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31379, 1744, 10, CONCAT('Episode 10'), '2016-03-12', 'https://video.sibnet.ru/shell.php?videoid=2537183');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31380, 1744, 11, CONCAT('Episode 11'), '2016-03-19', 'https://mp4upload.com/embed-8il1ox2pylv9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31381, 1744, 12, CONCAT('Episode 12'), '2016-03-26', 'https://mp4upload.com/embed-xoyp7it0gjbn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31382, 1744, 13, CONCAT('Episode 13'), '2016-04-02', 'https://video.sibnet.ru/shell.php?videoid=2547383');
