INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1753, CONCAT('Shuumatsu Nani Shitemasu ka? Isogashii Desu ka? Sukutte Moratte Ii Desu ka?'), CONCAT('Putting his life on the line, Willem Kmetsch leaves his loved ones behind and sets out to battle a mysterious monster, and even though he is victorious, he is rendered frozen in ice. It is during his icy slumber that terrifying creatures known as "Beasts" emerge on the Earth', CHAR(39), 's surface and threaten humanity', CHAR(39), 's existence. Willem awakens 500 years later, only to find himself the sole survivor of his race as mankind is wiped out.<br>
<br>Together with the other surviving races, Willem takes refuge on the floating islands in the sky, living in fear of the Beasts below. He lives a life of loneliness and only does odd jobs to get by. One day, he is tasked with being a weapon storehouse caretaker. Thinking nothing of it, Willem accepts, but he soon realizes that these weapons are actually a group of young Leprechauns. Though they bear every resemblance to humans, they have no regard for their own lives, identifying themselves as mere weapons of war. Among them is Chtholly Nota Seniorious, who is more than willing to sacrifice herself if it means defeating the Beasts and ensuring peace.<br>
<br>Willem becomes something of a father figure for the young Leprechauns, watching over them fondly and supporting them in any way he can. He, who once fought so bravely on the frontlines, can now only hope that the ones being sent to battle return safely from the monsters that destroyed his kind.<br>
<br>[Written by MAL Rewrite] '), 1, '2017-04-11', '2017-06-27', 'Spring 2017', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/85260.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1241, 1753, '"DEAREST DROP"', ' by Tamaru Yamada', 'js-theme-songs', '')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4342, 1753, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4343, 1753, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4344, 1753, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4345, 1753, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1893, 1753, 43);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1894, 1753, 167);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31504, 1753, 1, CONCAT('In This World With Tilted Sun - Broken Chronograph'), '2017-04-11', 'https://ebd.cda.pl/620x395/67711641e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31505, 1753, 2, CONCAT('Inside a Forest in the Sky - Late Autumn Night', CHAR(39), 's Dream'), '2017-04-18', 'https://ebd.cda.pl/620x395/67711673c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31506, 1753, 3, CONCAT('When This Battle Have Ended - Starry Road to Tomorrow'), '2017-04-25', 'https://ebd.cda.pl/620x395/6771176ba');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31507, 1753, 4, CONCAT('Person Who Have Not Come Back and Persons Who Have Waited - Dice in Pot'), '2017-05-02', 'https://ebd.cda.pl/620x395/67711708f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31508, 1753, 5, CONCAT('Everyone, in the Name of Justice - From Dawn Till Dusk'), '2017-05-09', 'https://ebd.cda.pl/620x395/677117357');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31509, 1753, 6, CONCAT('Unerasable Past, Disappearing Future - No News Was Good News'), '2017-05-16', 'https://ebd.cda.pl/620x395/677117929');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31510, 1753, 7, CONCAT('I', CHAR(39), 'm Home - Home, Sweet Home'), '2017-05-23', 'https://ebd.cda.pl/620x395/677118206');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31511, 1753, 8, CONCAT('Even If Eventually That Sun Will Fall - Slight Light, Slight Hope'), '2017-05-30', 'https://ebd.cda.pl/620x395/6771188d6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31512, 1753, 9, CONCAT('No Matter If Future Is Nowhere to Be Seen - Moonlit Sorcery'), '2017-06-06', 'https://ebd.cda.pl/620x395/67711945c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31513, 1753, 10, CONCAT('Brightness at This Moment - My Happiness'), '2017-06-13', 'https://ebd.cda.pl/620x395/677118589');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31514, 1753, 11, CONCAT('Please, Do Not Forget - Evidence of Existance'), '2017-06-20', 'https://ebd.cda.pl/620x395/67712001a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31515, 1753, 12, CONCAT('The Happiest Girl in the World - Chtholly'), '2017-06-27', 'https://ebd.cda.pl/620x368/1472004ba');
