INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1759, CONCAT('Sin: Nanatsu no Taizai'), CONCAT('Lucifer, an Archangel and former head of the Seven Heavenly Virtues, is banished from Heaven after revolting against the Lord', CHAR(39), 's will.. While plummeting from the skies, she is halted halfway between Heaven and Hell after crashing through the roof of a high school church. Though she is witnessed by Maria Totsuka, a soft-spoken student at the academy, Lucifer swiftly continues her descent into the depths of Hell.<br>
<br>Soon after her arrival, Lucifer is found by aspiring Demon Lord and fangirl Leviathan. The two decide to overthrow the Seven Sins, the authorities of Hell under the leadership of Belial. But with their combined powers, the Seven Sins are able to repel Lucifer and contain her divine powers by placing a Garb of Punishment over her body, transforming Lucifer into a Demon Lord. <br>
<br>Longing for revenge and accompanied by Leviathan, Lucifer makes her way back to Earth, where she forces Maria to become her immortal slave. Together with her new accomplices, Lucifer sets out on a mission to subdue the Seven Sins so she may be free of the curse brought upon by her Garb.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-04-15', '2017-07-29', 'Spring 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/86621.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1246, 1759, '"My Sweet Maiden"', ' by Mia REGINA', 'js-theme-songs', 'https://open.spotify.com/track/5UrFlWFW76LUlmjWgPuwGC')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4358, 1759, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4359, 1759, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1901, 1759, 175);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1902, 1759, 128);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31589, 1759, 1, CONCAT('The Proud Fallen Angel'), '2017-04-15', 'https://streamtape.com/e/jOMbPOqq04SgR9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31590, 1759, 2, CONCAT('Driven Wild by Envy'), '2017-04-22', 'https://streamtape.com/e/Y174JJOVmvToKy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31591, 1759, 3, CONCAT('Beach of Lust'), '2017-04-29', 'https://streamtape.com/e/WyKQLL1llaibwyR/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31592, 1759, 4, CONCAT('The Town of Fog Where Greed Brews'), '2017-05-06', 'https://streamtape.com/e/0207peJ00lfA90/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31593, 1759, 5, CONCAT('The Languid Diva'), '2017-05-20', 'https://streamtape.com/e/Q1LAdX1X3ZIRZQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31594, 1759, 6, CONCAT('Sloth Online'), '2017-05-27', 'https://streamtape.com/e/RkQm2LkvlJtdAx8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31595, 1759, 7, CONCAT('Guiltless Gluttony'), '2017-06-03', 'https://drive.google.com/file/d/0B3FQEG0g6x4hcUpoc1E3U3RZM2s/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31596, 1759, 8, CONCAT('Unleashed Wrath'), '2017-06-10', 'https://drive.google.com/file/d/0BzPe0Wj3xolQLXNYX3VEUDBzcEk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31597, 1759, 9, CONCAT('Ye Abandon All Hope'), '2017-06-17', 'https://drive.google.com/file/d/0B3FQEG0g6x4hdmZ2aC1zWDJlc2s/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31598, 1759, 10, CONCAT('Love Your Enemies and Pray for Those Who Persecute You'), '2017-06-24', 'https://streamtape.com/e/bvKxQ7Wvw1TPYv0/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31599, 1759, 11, CONCAT('Ask, and It Shall Be Given to You'), '2017-07-08', 'https://streamtape.com/e/rg98d30r4LUbJlA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (31600, 1759, 12, CONCAT('Gods In His Heaven, All', CHAR(39), 's Right with The World'), '2017-07-29', 'https://streamtape.com/e/aGDR02mxdPsxRj9/');
