INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1784, CONCAT('Sora wo Miageru Shoujo no Hitomi ni Utsuru Sekai'), CONCAT('To save both the Magical Kingdom and the Heavens and restore the flow of akuto, the flow of energy of everything, the Magical King Munto must follow a vision and find the girl Yumemi in the normal world. Yumemi herself is just a normal girl except that she is the only one who can see the islands of the Heavens floating above. When Munto appears before her she starts thinking about hers and others responsibility to the world.<br>
<br>(Source: ANN)'), 1, '2009-01-14', '2009-03-11', 'Winter 2009', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1221/118907.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1264, 1784, '"Anemoi (アネモイ)"', ' by eufonius', 'js-theme-songs', 'https://open.spotify.com/track/67mdoooIA1vY06nVtDaWqm');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4432, 1784, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4433, 1784, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4434, 1784, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1928, 1784, 14);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32111, 1784, 1, CONCAT('Knowing'), '2009-01-14', 'https://myvi.ru/player/embed/html/o9JsWNTqhaX9LYuf4icS45S7bdwGX3JOrDt9PjiSwxj-3hmi3t3H1dQGqxm_U8Xmi0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32112, 1784, 2, CONCAT('Fleeing'), '2009-01-21', 'https://drive.google.com/file/d/1AW0-FjAsV1JZlDc0Ug8hlS8xiXxmE5LD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32113, 1784, 3, CONCAT('Confronting'), '2009-01-28', 'https://drive.google.com/file/d/1vNFGIyPdrgfh3eUwapsdDan1K_2BeL4-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32114, 1784, 4, CONCAT('Yearning'), '2009-02-04', 'https://drive.google.com/file/d/1M4QhVqmvwWo5y2agH1HApxqIbx3nUthB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32115, 1784, 5, CONCAT('Confusing'), '2009-02-11', 'https://drive.google.com/file/d/1Z3_DvmDzmWTsVuzclm-kPLgQl7EyFNGD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32116, 1784, 6, CONCAT('Believing'), '2009-02-18', 'https://drive.google.com/file/d/10jSVBuWhNTU3tGGky-TdGO0RWPrKXsXK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32117, 1784, 7, CONCAT('Forgiving'), '2009-02-25', 'https://drive.google.com/file/d/1ipQp9jhN6peMmtsZFnouzYmTWc2Qlil9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32118, 1784, 8, CONCAT('Unyielding'), '2009-03-04', 'https://drive.google.com/file/d/1WMO57pNa6FNsHhVOKibXlE-uUfmxFM6c/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32119, 1784, 9, CONCAT('Loving'), '2009-03-11', 'https://drive.google.com/file/d/1LEe_zQ6QZsbgxTlRiPtVCEhHUyvVi6Nn/preview');
