INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1792, CONCAT('Soukyuu no Fafner: Dead Aggressor - Exodus'), CONCAT('2150 AD. The battle against the silicon-based Festums from outer space reaches a new phase. Fragments of the North Pole Mir were scattered throughout the world. Eventually, they began to act on their own as independent Mirs. Most hated humanity and attacked them, but some chose to coexist with mankind. Some with the same way of thinking existed within the human race, as well: those who were both human and Festum. They added to the chaos of the battle and brought about even more hatred. <br>
<br>(Source: Crunchyroll)'), 1, '2015-01-09', '2015-04-03', 'Winter 2015', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/68565.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4447, 1792, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4448, 1792, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4449, 1792, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1936, 1792, 96);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1937, 1792, 230);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1987, 1792, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1988, 1792, 25);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32206, 1792, 1, CONCAT('Visitor'), NULL, 'https://ok.ru/videoembed/3003636779594');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32207, 1792, 2, CONCAT('The Name of Hope'), NULL, 'https://drive.google.com/file/d/0B6CzYyD7en76dko2V0xQc3RoVEU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32208, 1792, 3, CONCAT('The Price of a Conversation'), NULL, 'https://ok.ru/videoembed/3003636714058');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32209, 1792, 4, CONCAT('The Successors'), NULL, 'https://ok.ru/videoembed/3003637238346');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32210, 1792, 5, CONCAT('To a New World'), NULL, 'https://ok.ru/videoembed/3003637303882');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32211, 1792, 6, CONCAT('Blessed Time'), NULL, 'https://drive.google.com/file/d/0B6CzYyD7en76WDRYNFdubFBpNUU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32212, 1792, 7, CONCAT('Battle in a New Dimension'), NULL, 'https://drive.google.com/file/d/0B6CzYyD7en76X2prZWpiLW13SEU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32213, 1792, 8, CONCAT('Dreaming of Peace'), NULL, 'https://drive.google.com/file/d/0BxxdINykTAqWeWpQWTZjMlRVWkU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32214, 1792, 9, CONCAT('The Two Heroes'), NULL, 'https://drive.google.com/file/d/0BySeIZmAjB9Hc25WbVJXUVVtb2s/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32215, 1792, 10, CONCAT('To the Land of Hope'), NULL, 'https://ok.ru/videoembed/3003637172810');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32216, 1792, 11, CONCAT('Transformation'), NULL, 'https://ok.ru/videoembed/3003637041738');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32217, 1792, 12, CONCAT('Children of the Battlefield'), NULL, 'https://drive.google.com/file/d/0B0GZ07xOdkUWVmlCQmlXcU1RRHM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32218, 1792, 13, CONCAT('A Future Within the Darkness'), NULL, 'https://tune.pk/video/6000869');
