INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1797, CONCAT('Soushin Shoujo Matoi'), CONCAT('Matoi Sumeragi wishes for nothing more than to lead a normal life away from the spotlight. She is quite satisfied alternating between school and her part-time job at her best friend Yuma Kusanagi', CHAR(39), 's family shrine. But this routine life is permanently disturbed when a Night—an evil extra-dimensional entity—attacks the shrine. Matoi is able to drive it off after unwittingly calling upon the powers of a god, the natural enemies of the Nights.<br>
<br>Matoi and Yuma are soon joined by Claris Tonitolus, an experienced exorcist from the Vatican, and agent Haruka Luciela, who works for the secretive Night defense organization IATO. Despite not knowing the perpetrator behind these attacks nor their motive, Matoi must come to master this newfound power in order to protect both the people around her and the once normal life she holds so dear.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-10-04', '2016-12-20', 'Fall 2016', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/83224.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1276, 1797, '"Chou Musubi Amulet (蝶結びアミュレット)"', ' by Mia REGINA', 'js-theme-songs', 'https://open.spotify.com/track/2xGvcB1ECBajYMRcfPED7K')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1942, 1797, 38);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32305, 1797, 1, CONCAT('I', CHAR(39), 'm Possessed!'), '2016-10-04', 'https://streamtape.com/e/LDDJ3YzROBFRrJK/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32306, 1797, 2, CONCAT('I Clad Myself In A God!'), '2016-10-11', 'https://thevideo.me/embed-p77523x561sz-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32307, 1797, 3, CONCAT('God', CHAR(39), 's Playing Dumb'), '2016-10-18', 'https://thevideo.me/embed-gom0eib6zk3s-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32308, 1797, 4, CONCAT('Her Resolution and My Reason'), '2016-10-25', 'https://thevideo.me/embed-86pmvb9861h9-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32309, 1797, 5, CONCAT('A Special Kind of Ordinary'), '2016-11-01', 'https://thevideo.me/embed-ne5upsfoj8d0-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32310, 1797, 6, CONCAT('I', CHAR(39), 'm Sorry'), '2016-11-08', 'https://thevideo.me/embed-o8z3h9qtpp03-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32311, 1797, 7, CONCAT('The Sea, Hot Springs, and Sometimes Evil Spirits'), '2016-11-15', 'https://thevideo.me/embed-yupno6096hea-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32312, 1797, 8, CONCAT('A Small Wish'), '2016-11-22', 'https://thevideo.me/embed-ntibil6za0ow-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32313, 1797, 9, CONCAT('Thank You'), '2016-11-29', 'https://thevideo.me/embed-s6j6e6ccrj2k-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32314, 1797, 10, CONCAT('The Open Gate'), '2016-12-06', 'https://thevideo.me/embed-qqq1o69z44jy-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32315, 1797, 11, CONCAT('I', CHAR(39), 'm Headed Out'), '2016-12-13', 'https://www.bitporno.com/embed/Kp1fMwhi');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32316, 1797, 12, CONCAT('Ordinary is #1'), '2016-12-20', 'https://www.bitporno.com/embed/pKqogIPT');
