INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1807, CONCAT('Spy x Family Part 2'), CONCAT('With Anya Forger successfully enrolled at the renowned Eden Academy, Operation Strix advances to its second phase. To investigate Ostanian politician Donovan Desmond, Anya must either befriend his son Damian or collect eight Stella Stars to become an Imperial Scholar. Fortunately, Anya has already acquired her first star. In celebration, her adoptive father, Loid, decides to fulfill her wish to adopt a dog.<br>
<br>During their canine search, Loid receives new orders from his superiors, who have found that a band of Berlint University students is plotting to assassinate Westalis', CHAR(39), ' Minister Brantz using bombs worn by trained dogs. While Loid tries to stop their plans, Anya stumbles upon the terrorists', CHAR(39), ' base of operations. There, she befriends a kindhearted, clairvoyant dog who the family later names Bond.<br>
<br>Although the Forgers continue to lead their individual lives in secrecy, the family—with a new fluffy addition—remains united through all of the unusual obstacles thrown their way.<br>
<br>[Written by MAL Rewrite]'), 4, '2022-10-01', NULL, 'Fall 2022', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1111/127508.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4482, 1807, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4483, 1807, 15);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4484, 1807, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1951, 1807, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32494, 1807, 1, CONCAT('Project Apple'), '2022-10-01', 'https://drive.google.com/file/d/146BAnuJK53pgwhr4XU7y9jPmLvVs_EGw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32495, 1807, 2, CONCAT('Disarm the Time Bomb'), '2022-10-08', 'https://ebd.cda.pl/800x450/12174090ec');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32496, 1807, 3, CONCAT('A New Family Member'), '2022-10-15', 'https://drive.google.com/file/d/1P1mZpCoZiNrewxfUtekhIGsvrPw_xo6V/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32497, 1807, 4, CONCAT('Yors Kitchen / The Informants Great Romance Plan'), '2022-10-22', 'https://drive.google.com/file/d/1isHy5btQePQF0ic4fIfHQDN0LQEPNqqB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32498, 1807, 5, CONCAT('Carry Out the Griffin Plan / Fullmetal Lady / Omelet Rice ♡'), '2022-10-29', 'https://video.sibnet.ru/shell.php?videoid=4934369');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32499, 1807, 6, CONCAT('Uncle the Private Tutor / Daybreak'), '2022-11-05', 'https://video.sibnet.ru/shell.php?videoid=4942724');
