INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1882, CONCAT('Tensei shitara Ken Deshita'), CONCAT('A nameless sword wakes up to discover he has been reincarnated from his former life as a human. With his power of telekinesis, he moves around this new world, acquiring several skills and abilities. When the sword comes upon a forest filled with monsters, he meets a young girl fleeing from a beast. Grabbing the sword, the girl easily defeats the monster. After introducing herself as Fran, she names the sword "Shishou" and officially becomes his wielder.<br>
<br>The two set out to become adventurers, but unfortunately for Fran, she is a member of the Black Cat Tribe—a Beastkin group with a bad reputation. No member of this tribe has ever evolved into a mightier beast, but Fran plans to be the first and achieve her parents', CHAR(39), ' dream. As Shishou promises to remain her sword until she attains her goal, they form an unstoppable partnership of impressive strength.<br>
<br>[Written by MAL Rewrite]'), 1, '2022-10-05', NULL, 'Fall 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1191/127909.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4662, 1882, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4663, 1882, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2037, 1882, 89);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33555, 1882, 1, CONCAT('The Cat Girl Met A Sword'), '2022-09-28', 'https://drive.google.com/file/d/1m8Jq8YVDJgbMeoYh7OJceZrftMrMJ5XQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33556, 1882, 2, CONCAT('The Hellish Trial at the Adventurer', CHAR(39), 's Guild'), '2022-10-05', 'https://drive.google.com/file/d/1DTAu50wZG0JKSvl5I6RrkZLNKGF4y9up/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33557, 1882, 3, CONCAT('The Arcane Blacksmith is Suspicious'), '2022-10-12', 'https://drive.google.com/file/d/13nBR4rIqXI7E1HZhaV1jfPAbGvhyijB8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33558, 1882, 4, CONCAT('A Goblin Stampede Is an Emergency'), '2022-10-19', 'https://video.sibnet.ru/shell.php?videoid=4925009');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33559, 1882, 5, CONCAT('A Perfect Dungeon Debut'), '2022-10-26', 'https://video.sibnet.ru/shell.php?videoid=4931547');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33560, 1882, 6, CONCAT('The Greater Demon Was a Cheater'), '2022-11-02', 'https://mega.nz/file/QhlmBZCD#RfnJH593TWlm_KKpAmzbaXkBfkEFB5jE25u3jsPT--c');
