INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1899, CONCAT('Tiger Mask W'), CONCAT('Two young wrestlers face each other in a recently revived underground wrestling organization, the Tiger', CHAR(39), 's Lair, which destroyed the wrestling dojo they grew up in. One took over the training facilities of Naoto Date at the foot of Mount Fuji, as well as the mask he left behind. The other dared to enter the Tiger', CHAR(39), 's Lair and won a fierce competition, receiving a jet-black tiger mask. One tiger walks the path of light, while the other walks the path of shadows. Neither one knows the other', CHAR(39), 's face. On the ring, they are natural enemies, but they have the same purpose—destroy the Tiger', CHAR(39), 's Lair!<br>
<br>(Source: MAL News)'), 2, '2016-10-02', '2017-07-02', 'Fall 2016', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/81903.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1352, 1899, '"KING OF THE WILD"', ' by Shounan no Kaze', 'js-theme-songs', 'https://open.spotify.com/track/2qxeR46foPkavUMhfNhjtH');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4708, 1899, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4709, 1899, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2054, 1899, 77);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33799, 1899, 1, CONCAT('The Two Tigers'), NULL, 'https://www.bitporno.com/embed/0rI5Rau7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33800, 1899, 2, CONCAT('Tiger and Lion'), NULL, 'https://www.bitporno.com/embed/h3ixUtqJ');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33801, 1899, 3, CONCAT('The Tiger', CHAR(39), 's Legacy'), NULL, 'https://www.bitporno.com/embed/AV77IKnt');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33802, 1899, 4, CONCAT('The Mask of Red Death'), NULL, 'https://thevideo.me/embed-flbrrro7gwfy-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33803, 1899, 5, CONCAT('The Mystery of Fukuwara Mask'), NULL, 'https://www.bitporno.com/embed/QifvUaA4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33804, 1899, 6, CONCAT('Idol vs. Heel'), NULL, 'https://thevideo.me/embed-wiiyrfpg0oon-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33805, 1899, 7, CONCAT('Naoto and Naoto'), NULL, 'https://www.bitporno.com/embed/02613LYF');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33806, 1899, 8, CONCAT('Tiger', CHAR(39), 's Den Bares Fangs'), NULL, 'https://www.bitporno.com/embed/w1Ryy3Eo');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33807, 1899, 9, CONCAT('The Stormy Opening Match'), NULL, 'https://thevideo.me/embed-91dbggi1r6ah-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33808, 1899, 10, CONCAT('The Mysterious Mister Question'), NULL, 'https://www.bitporno.com/embed/4kclTIr2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33809, 1899, 11, CONCAT('The Tiger', CHAR(39), 's Killer Move'), NULL, 'https://thevideo.me/embed-92nl11ag895l-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33810, 1899, 12, CONCAT('Tiger vs. Tiger'), NULL, 'https://thevideo.me/embed-53ombduev3uw-843x475.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33811, 1899, 13, CONCAT('A False Victory'), NULL, 'https://thevideo.me/z0sww6umhzyc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33812, 1899, 14, CONCAT('Crossroads'), NULL, 'https://streamtape.com/e/Zq8L3AZQVoUq6wk/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33813, 1899, 15, CONCAT('Fierce Fight - Bigfoot Match'), NULL, 'https://streamtape.com/e/VOPGZg1xxAUKl2k/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33814, 1899, 16, CONCAT('A Capable Promoter'), NULL, 'https://streamtape.com/e/a0qaxwwPMyfxrXb/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33815, 1899, 17, CONCAT('Don', CHAR(39), 't Be A Softy'), NULL, 'https://streamtape.com/e/dVrWvkbmPyckxK9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33816, 1899, 18, CONCAT('Spring Tiger is Born'), NULL, 'https://streamtape.com/e/zGQe66gxDaHQmB/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33817, 1899, 19, CONCAT('The Escape from Hell'), NULL, 'https://streamtape.com/e/2PpBxadvmLIPAO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33818, 1899, 20, CONCAT('The Gatekeeper of Hell'), NULL, 'https://streamtape.com/e/bkvll8Agw1sPbel/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33819, 1899, 21, CONCAT('Reunion'), NULL, 'https://streamtape.com/e/pbGKMYRj78CrYkP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33820, 1899, 22, CONCAT('Fukuwara Mask', CHAR(39), 's Ambition'), NULL, 'https://streamtape.com/e/mv1XwzLpMRUbg0m/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33821, 1899, 23, CONCAT('War Games Open'), NULL, 'https://streamtape.com/e/LQXRz6WJ4mTRB1V/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33822, 1899, 24, CONCAT('The Fierce Tigers Clash Again'), NULL, 'https://streamtape.com/e/41OWWqmmZYFKvmo/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33823, 1899, 25, CONCAT('The Tiger', CHAR(39), 's Identity{'), NULL, 'https://streamtape.com/e/Akj3jvR4pZiwAd/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33824, 1899, 26, CONCAT('The Mysterious Miracle 1'), NULL, 'https://streamtape.com/e/R4oey2kZOdhdM3L/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33825, 1899, 27, CONCAT('A Deadly Match against King Tiger'), NULL, 'https://streamtape.com/e/WP98BgOv82ubjK6/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33826, 1899, 28, CONCAT('The Yellow Demon'), NULL, 'https://streamtape.com/e/ybM60GOvO3f1pr8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33827, 1899, 29, CONCAT('The Solitary Tiger'), NULL, 'https://streamtape.com/e/w4w4YwyO3kuJO3J/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33828, 1899, 30, CONCAT('The Tiger', CHAR(39), 's Sanction'), NULL, 'https://streamtape.com/e/4RB6vppX8GUdoK/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33829, 1899, 31, CONCAT('Showdown with The Arashi Juken Style'), NULL, 'https://streamtape.com/e/yVbpOa1Ly8H1Z0M/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33830, 1899, 32, CONCAT('Lumberjack'), NULL, 'https://streamtape.com/e/KP194DAdmDh0rep/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33831, 1899, 33, CONCAT('Assassin from The Past'), NULL, 'https://streamtape.com/e/PG4DXJXAeQH07BY/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33832, 1899, 34, CONCAT('Grand Melee'), NULL, 'https://streamtape.com/e/Gp6OKqm0zbuokX/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33833, 1899, 35, CONCAT('Tiger Fangs Strike'), NULL, 'https://streamtape.com/e/6bYObBBy09C4Qg/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33834, 1899, 36, CONCAT('Four Tigers '), NULL, 'https://streamtape.com/e/B4yXxL9G4xhykDY/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33835, 1899, 37, CONCAT('Farewell Tiger'), NULL, 'https://streamtape.com/e/YGVdl3Q1LQivYZO/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (33836, 1899, 38, CONCAT('Masked Tiger Springer'), NULL, 'https://streamtape.com/e/PjQA2wmYjqC0Xq4/');
