INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1959, CONCAT('Tsukiuta. The Animation'), CONCAT('Tsukino Talent Productions is home to two up-and-coming idol units named Six Gravity and Procellarum. The units all live together in the same dormitory and try to juggle their budding careers and daily lives. At their joint handshake event, unit leaders Hajime Mutsuki and Shun Shimotsuki announce the "Full Moon Festival"—a collaboration concert in a few months. Excited about the upcoming event, these 12 male idols must learn to collaborate with each other in order to pull it off successfully.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2016-07-06', '2016-09-28', 'Summer 2016', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/80936.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4887, 1959, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4888, 1959, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4889, 1959, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4890, 1959, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2125, 1959, 55);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2177, 1959, 10);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2178, 1959, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34685, 1959, 1, CONCAT('Betting on the Handshake Event!'), '2016-07-06', 'https://dood.to/e/oiiln6tip8sk');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34686, 1959, 2, CONCAT('Glasswork Heart'), '2016-07-13', 'https://dood.to/e/lw9poz0obr3b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34687, 1959, 3, CONCAT('Going Far Beyond'), '2016-07-20', 'https://dood.to/e/8muljth6op6l');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34688, 1959, 4, CONCAT('On a New Path'), '2016-07-27', 'https://dood.to/e/do5cr53wjqad');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34689, 1959, 5, CONCAT('A Chance Encounter with the Past'), '2016-08-03', 'https://dood.to/e/wiijvhg68nzt');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34690, 1959, 6, CONCAT('A Smart Detective!?'), '2016-08-10', 'https://dood.to/e/mgfjbnirw26e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34691, 1959, 7, CONCAT('The Mutsuki Hajime Expedition'), '2016-08-17', 'https://dood.to/e/yn0r7nnbq6di');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34692, 1959, 8, CONCAT('Round Moon'), '2016-08-24', 'https://dood.to/e/pjts97m3dhpc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34693, 1959, 9, CONCAT('Night of Overlapping Patterns'), '2016-08-31', 'https://streamsb.net/embed-gyaje1mjjylo.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34694, 1959, 10, CONCAT('Blue Flames'), '2016-09-07', 'https://www.mp4upload.com/embed-4dn7eesm2s2i.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34695, 1959, 11, CONCAT('Moment of Indecision'), '2016-09-14', 'https://www.mp4upload.com/embed-y56n3pm2o8e8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34696, 1959, 12, CONCAT('Full Moon Festival'), '2016-09-21', 'https://www.mp4upload.com/embed-mqnwlhn0phw1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34697, 1959, 13, CONCAT('Song of the Moon'), '2016-09-28', 'https://www.mp4upload.com/embed-fvvcv8nqeizi.html');
