INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1963, CONCAT('Tsuritama'), CONCAT('Saving the world... by fishing?<br>
<br>Yuki Sanada has always felt like a fish out of water. Socially awkward and anxious, he struggles to fit in with his surroundings and moves from town to town with his grandma. As he and his grandma settle into the charming seaside town of Enoshima, Yuki hopes for a fresh start. However, his reputation at school is jeopardized by the arrival of fellow transfer student Haru. The eccentric Haru immediately makes a splash, wildly claiming to be an alien and declaring that Yuki is his friend. Pairing the reluctant Yuki with their classmate and fishing talent, Natsuki Usami, he tasks both of them with the absurd mission of saving the world from a mysterious threat in the ocean. Mischief and hijinks ensue, as these three embark on a whimsical adventure filled with laughs, heart, and self-discovery!<br>
<br>[Written by MAL Rewrite]'), 1, '2012-04-13', '2012-06-29', 'Spring 2012', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/69909.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4899, 1963, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4900, 1963, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4901, 1963, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2129, 1963, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34747, 1963, 1, CONCAT('Panicked Fishing'), '2012-04-13', 'https://ebd.cda.pl/620x395/5795621be');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34748, 1963, 2, CONCAT('The Frustrating Uni Knot'), '2012-04-20', 'https://ebd.cda.pl/620x395/579565784');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34749, 1963, 3, CONCAT('Lonely Casting'), '2012-04-27', 'https://drive.google.com/file/d/1fTtOZ6OSkfb-7lyb_xHIeT3NH9b1Yq6n/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34750, 1963, 4, CONCAT('Angry Landing'), '2012-05-04', 'https://drive.google.com/file/d/1NdIyRy0aGQq3iGmo0zP9_Wdp5QKC8Cpx/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34751, 1963, 5, CONCAT('Discouraged Jerking'), '2012-05-11', 'https://ebd.cda.pl/620x395/5795633be');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34752, 1963, 6, CONCAT('Horrified Splash'), '2012-05-18', 'https://drive.google.com/file/d/17JO8-fsXI5l1nsDpv9U38RMiW3tgVHOJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34753, 1963, 7, CONCAT('Painful Countdown'), '2012-05-25', 'https://drive.google.com/file/d/1JiDVIznTrRIrQOhiy0E0KZAqgO6Se2Wg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34754, 1963, 8, CONCAT('Joyous Fighting'), '2012-06-01', 'https://drive.google.com/file/d/1oq6NGu_nrcBO3iY_0dyVmaQ7rE2h4Lcg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34755, 1963, 9, CONCAT('Striking Underwater'), '2012-06-08', 'https://drive.google.com/file/d/1OqF-5_AtoZBigips2-M_cGBgWbb9Bwfh/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34756, 1963, 10, CONCAT('Our Tackle'), '2012-06-15', 'https://ebd.cda.pl/620x395/57956549f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34757, 1963, 11, CONCAT('Legend of the Big Fish'), '2012-06-22', 'https://drive.google.com/file/d/1Vrsc0SrXeqXmMUdMypvk3KJxNlGNDJPo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34758, 1963, 12, CONCAT('Goodbye Fishing'), '2012-06-28', 'https://drive.google.com/file/d/144Uj_u6_Uizao_hAY2RA2RzfaJHAStY2/preview');
