INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1969, CONCAT('Uchi no Maid ga Uzasugiru!'), CONCAT('Having lost her mother at a young age, Misha Takanashi, a second grader who is Russian now lives with her Japanese step-father. Tsubame Kamoi, formerly a Japan Air Self-Defense Force, JASDF officer, comes to the Takanashi household as a housekeeper. This is a home comedy where Kamoi, a hardcore lolicon, attempts to get near Misha as she tries to fight against her.<br>'), 1, '2018-10-05', '2018-12-21', 'Fall 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1786/95330.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4910, 1969, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4911, 1969, 16);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4912, 1969, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2135, 1969, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34814, 1969, 1, CONCAT('Our Maid Is Too Annoying!'), NULL, 'https://www.yourupload.com/watch/60Qsfl73BR50');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34815, 1969, 2, CONCAT('My Maid Kidnapped Me'), NULL, 'https://vidoza.net/ho5eadic8qvl');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34816, 1969, 3, CONCAT('My Maid Is Sneaking Up On Me'), NULL, 'https://www.yourupload.com/watch/enYnS5N03g3S');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34817, 1969, 4, CONCAT('My Maid Reveres Young Girls'), NULL, 'https://www.mp4upload.com/embed-oyajuzfy2hod.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34818, 1969, 5, CONCAT('My Maid Is Everywhere'), NULL, 'https://www.yourupload.com/watch/7rRADp4ldYxt');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34819, 1969, 6, CONCAT('Our Maid', CHAR(39), 's Girl From The Past?'), NULL, 'https://www.mp4upload.com/embed-833o6pnb4qvh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34820, 1969, 7, CONCAT('My Maid Doesn’t Come Anymore'), NULL, 'https://www.mp4upload.com/embed-j3wnfi6931h2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34821, 1969, 8, CONCAT('My Former Maid Is From A Good Family'), NULL, 'https://www.mp4upload.com/embed-x4rvmdfpurdq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34822, 1969, 9, CONCAT('My Maid And The Day We Met'), NULL, 'https://www.mp4upload.com/embed-yuafx4bfshob.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34823, 1969, 10, CONCAT('My Maid And Yasuhiro'), NULL, 'https://www.mp4upload.com/embed-mhphyues4wdf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34824, 1969, 11, CONCAT('My Maid And The Forbidden Room'), NULL, 'https://www.mp4upload.com/embed-jv8wrazl29xf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34825, 1969, 12, CONCAT('My Maid Now and Forever'), '2018-12-21', 'https://www.mp4upload.com/embed-9abuls4td6gb.html');
