INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1971, CONCAT('Uchi Tama?! Uchi no Tama Shirimasen ka?'), CONCAT('The animals of Third Street are seen getting into many misadventures. Tama Okamoto, the curious feline, often goes missing from his home, causing his owner to have posters up looking for him. However, Tama', CHAR(39), 's absence is his opportunity to visit all of his wandering furry friends around the neighborhood. From Tama', CHAR(39), 's best friend Pochi Yamada to the stray alley cat Nora, these animals take human form to hang out, to cause various mischief, but most of all, to have fun!<br>
<br>[Written by MAL Rewrite]'), 1, '2020-01-10', '2020-03-20', 'Winter 2020', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1624/103162.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1409, 1971, '"Friends (フレンズ)"', ' by wacci', 'js-theme-songs', 'https://open.spotify.com/track/2yw4gK5iALigexA3jUiX3g');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2137, 1971, 73);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2138, 1971, 130);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2181, 1971, 8);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2182, 1971, 48);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34832, 1971, 1, CONCAT('Have You Seen My Tama? / Dog Meeting / Our Waiha'), NULL, 'https://drive.google.com/file/d/1A3J_K8zsXAXq-nWaUp1QsPGKN3Dudd1d/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34833, 1971, 2, CONCAT('My Name is Bull / Peace / Going to the Beach'), NULL, 'https://ebd.cda.pl/620x368/466927199');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34834, 1971, 3, CONCAT('The Strongest Guy on Third Street / The Weakest Guy on Third Street'), NULL, 'https://ebd.cda.pl/620x368/468455009');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34835, 1971, 4, CONCAT('Tama', CHAR(39), 's Job / My Name is Gon / Dog Police / Dog Police 2'), NULL, 'https://ebd.cda.pl/620x368/482229848');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34836, 1971, 5, CONCAT('Tora', CHAR(39), 's First Love / Let', CHAR(39), 's Take a Bath / Dog Police Continued'), NULL, 'https://ebd.cda.pl/620x368/4930819cc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34837, 1971, 6, CONCAT('Battle of Dogs and Cats, Part One / Battle of Dogs and Cats, Part Two / Night Picnic'), NULL, 'https://ebd.cda.pl/620x368/4931425f7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34838, 1971, 7, CONCAT('Tama Gets Kidnapped / Surprise Furball / Cat Café Violet'), NULL, 'https://ebd.cda.pl/620x368/493162930');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34839, 1971, 8, CONCAT('Festival Music'), NULL, 'https://ebd.cda.pl/620x368/493553205');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34840, 1971, 9, CONCAT('He', CHAR(39), 's in Town / Nora and the Kitten'), NULL, 'https://ebd.cda.pl/620x368/49374314b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34841, 1971, 10, CONCAT('Don', CHAR(39), 't Fall Asleep / Third Street Quiz / Beh and Bull are BFFs'), NULL, 'https://ebd.cda.pl/620x368/4952540cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34842, 1971, 11, CONCAT('Tama', CHAR(39), 's True Identity / Cat Meeting / My Treasure'), NULL, 'https://drive.google.com/file/d/144WTLOqetFa5ZSt_xgMKSJZ1F8agLmsx/preview');
