INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1968, CONCAT('Uchi no Ko no Tame naraba, Ore wa Moshikashitara Maou mo Taoseru kamo Shirenai.'), CONCAT('Eighteen-year-old Dale Reki is a skilled, kind, and respected traveler, acknowledged as one of the leading adventurers in the city of Kreuz. One day while on the hunt for magical beasts, he comes across a sweet devil girl named Latina. She is alone, dressed in rags, and bears the devils', CHAR(39), ' symbol of a criminal: a broken horn. Concerned for her wellbeing, Dale decides to ensure Latina', CHAR(39), 's safety by bringing her to his home, eventually leading to him adopting her.<br>
<br>Latina is sweet, innocent and compassionate, charming Dale beyond his expectations. He begins to enjoy the life of parenthood— experiencing the trials that come with raising a child and coping with the heartache he feels whenever his busy lifestyle as an adventurer parts him from her.<br>
<br>Although work and life as a new parent become reassuring constants for Dale, the mysteries surrounding the girl remain. Why was Latina alone in the forest, and why does she harbor the symbol of a criminal? At the same time, Latina also begins to learn about the world and herself as she adjusts to her new life with Dale.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-07-04', '2019-09-19', 'Summer 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1568/101203.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1408, 1968, '"I'm with you"', ' by Latina (Kanon Takao)', 'js-theme-songs', 'https://open.spotify.com/track/6aupfGxUobFklJoqjpxH4f')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4908, 1968, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4909, 1968, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2134, 1968, 193);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34802, 1968, 1, CONCAT('The Young Man and the Little Girl Meet.'), '2019-07-04', 'https://ebd.cda.pl/620x368/36801522b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34803, 1968, 2, CONCAT('The Little Girl Begins Her New Life'), NULL, 'https://ebd.cda.pl/620x368/368096291');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34804, 1968, 3, CONCAT('The Young Man Heads Out'), NULL, 'https://ebd.cda.pl/620x368/3698446b5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34805, 1968, 4, CONCAT('The Little Girl and the "Incident."'), NULL, 'https://ebd.cda.pl/620x368/37204874c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34806, 1968, 5, CONCAT('The Little Girl Is Fascinated by the Snow.'), NULL, 'https://ebd.cda.pl/620x368/3747100c9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34807, 1968, 6, CONCAT('The Young Girl Leaves on a Journey.'), NULL, 'https://ebd.cda.pl/620x368/3771793e9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34808, 1968, 7, CONCAT('The Young Girl Visits a Port Town.'), NULL, 'https://ebd.cda.pl/620x368/37985656e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34809, 1968, 8, CONCAT('The Young Man Arrives at His Home Village.'), NULL, 'https://ebd.cda.pl/620x368/38197574c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34810, 1968, 9, CONCAT('The Young Man Attends His Brother', CHAR(39), 's Wedding with the Young Girl.'), NULL, 'https://ebd.cda.pl/620x368/385256897');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34811, 1968, 10, CONCAT('Young Girl Returns to Kreuz'), NULL, 'https://ebd.cda.pl/620x368/39002233c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34812, 1968, 11, CONCAT('The Young Girl and the Kitty Paradise'), NULL, 'https://ebd.cda.pl/620x368/3927256d9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34813, 1968, 12, CONCAT('The Young Girl', CHAR(39), 's Wish'), NULL, 'https://ebd.cda.pl/620x368/3948337be');
