INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1988, CONCAT('Upotte!!'), CONCAT('Kiss kiss, bang bang! The arms race takes on a startling new development when the arms come with heads, legs and very feminine bodies attached!<br>
<br>Yes, at Seishou Academy every girl is literally a lethal weapon, and they', CHAR(39), 're all gunning for the top shot at getting their own personal serviceman! Needless to say, it', CHAR(39), 's going to be difficult for newly recruited human instructor Genkoku to adjust to working with a living arsenal of high caliber cuties with tricky names like FNC (Funko) M 16A4 (Ichiroku) L85A1 (Eru) and SG 550 (Shigu). Especially since many have hair triggers and there', CHAR(39), 's no bulletproof vest that can stop a really determined coed! He', CHAR(39), 'll have to rewrite the operator', CHAR(39), 's manual on student/teacher relationships, and pray that his job description won', CHAR(39), 't include having to field strip and reassemble one of his cadets in the dark. But unfortunately (for him) FNC', CHAR(39), 's already thinking about becoming HIS personal weapon, and she usually gets what she aims for!<br>
<br>(Source: Sentai Filmworks)'), 4, '2012-04-07', '2012-06-09', '', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/35121.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (826, 1988, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4958, 1988, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4959, 1988, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4960, 1988, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2157, 1988, 96);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35152, 1988, 1, CONCAT('Grip and hold!'), NULL, 'https://ebd.cda.pl/800x450/818102680');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35153, 1988, 2, CONCAT('Go for it! Pass it!'), NULL, 'https://ebd.cda.pl/800x450/8181029cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35154, 1988, 3, CONCAT('Wash and Scrub!'), NULL, 'https://ebd.cda.pl/800x450/8181023fc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35155, 1988, 4, CONCAT('Sing! Compete!'), NULL, 'https://ebd.cda.pl/800x450/818969058');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35156, 1988, 5, CONCAT('Graze It! Beat It!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1342966');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35157, 1988, 6, CONCAT('Take it! Hurry!'), NULL, 'https://ebd.cda.pl/800x450/818584415');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35158, 1988, 7, CONCAT('Be Afraid! Visit!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1343049');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35159, 1988, 8, CONCAT('Take a Look! Scold Someone!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1073910');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35160, 1988, 9, CONCAT('Burn Up! Get Mad!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1074278');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35161, 1988, 10, CONCAT('And Then, Upotte!!'), NULL, 'https://video.sibnet.ru/shell.php?videoid=760225');
