INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2009, CONCAT('Vampire Holmes'), CONCAT('The great detective Holmes does not solve mysteries or use deductive reasoning. He does, however, hunt vampires. Using three-minute episodes, Vampire Holmes retells the story of the great Holmes and his assistant. What begins as an ordinary detective agency takes a turn for the occult when the Metropolitan Police of London secretly hire Holmes and Hudson to investigate vampires.<br>
<br>Or at least that', CHAR(39), 's what Holmes would tell anyone who asks. In reality, he and Hudson spend most of their time sitting around arguing, and failing to solve any cases. Joined by the not-so-black, demon cat Kira, and their terrifying rent-hungry landlady, this is the story of the man who was most definitely not London', CHAR(39), 's greatest detective.'), 1, '2015-04-04', '2015-06-20', 'Spring 2015', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/74765.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1437, 2009, '"Everlasting Love"', ' by Nami Tamaki', 'js-theme-songs', '')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (838, 2009, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5008, 2009, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5009, 2009, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5010, 2009, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5011, 2009, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2181, 2009, 5);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2232, 2009, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2233, 2009, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2234, 2009, 19);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35413, 2009, 1, CONCAT('Great Detective!? His Name is…'), '2015-04-04', 'https://drive.google.com/file/d/0B9SlP9nShNbsUkVicDF6YmRuUnc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35414, 2009, 2, CONCAT('Unknown Difficult Case'), '2015-04-11', 'https://video.sibnet.ru/shell.php?videoid=1764849');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35415, 2009, 3, CONCAT('Holmes Ecology'), '2015-04-18', 'https://video.sibnet.ru/shell.php?videoid=1769719');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35416, 2009, 4, CONCAT('Noh Hawk, Somehow'), '2015-04-25', 'https://ebd.cda.pl/800x450/418755487');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35417, 2009, 5, CONCAT('For My Walk...'), '2015-05-02', 'https://mp4upload.com/embed-g7s93tuvxxng.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35418, 2009, 6, CONCAT('Tracking Difficult Cases!?'), '2015-05-09', 'https://mp4upload.com/embed-2f3blvpz7lux.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35419, 2009, 7, CONCAT('Holmes, Stand'), '2015-05-16', 'https://mp4upload.com/embed-fb5j9teieyq4.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35420, 2009, 8, CONCAT('Black Cat Kira'), '2015-05-23', 'https://mp4upload.com/embed-4j35pzb0iyra.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35421, 2009, 9, CONCAT('Things That are Distorted'), '2015-05-30', 'https://mp4upload.com/embed-5h24errw79zk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35422, 2009, 10, CONCAT('Long Walk'), '2015-06-06', 'https://mp4upload.com/embed-grajdpbnqqef.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35423, 2009, 11, CONCAT('Even One Person'), '2015-06-13', 'https://mp4upload.com/embed-t31jqt1kvbv3.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35424, 2009, 12, CONCAT('Holmes is a Great Detective!?'), '2015-06-20', 'https://mp4upload.com/embed-uan49y6aos34.html');
