INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2019, CONCAT('Vividred Operation'), CONCAT('Situated on Blue Island, the Manifestation Engine has been the answer to the world', CHAR(39), 's energy problem for five years. On the neighboring island of Izu Ooshima reside the cheerful Akane Isshiki, her dependable little sister Momo, and her grandfather Kenjirou, one of the inventors of the Manifestation Engine.<br>
<br>As they live peacefully alongside the powerful creation, it all seems like a dream until mysterious entities known as the "Alone" appear seeking to destroy it. With military forces failing to repel the invaders, Kenjirou grants Akane a special key containing the "Vivid System"—empowering her to fight the Alone.<br>
<br>Joined by Aoi Futaba, Wakaba Saegusa, and Himawari Shinomiya, Akane and her friends stand together in the battle against the unforeseen enemy as the last hope for humanity.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2013-01-11', '2013-03-29', 'Winter 2013', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/45935.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1444, 2019, '"ENERGY"', ' by earthmind', 'js-theme-songs', 'https://open.spotify.com/track/4yXpOw1DDfXooIdy6w4w9t')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5032, 2019, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5033, 2019, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5034, 2019, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2191, 2019, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35522, 2019, 1, CONCAT('First Operation'), '2013-01-11', 'https://video.sibnet.ru/shell.php?videoid=994360');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35523, 2019, 2, CONCAT('When Two Become One'), '2013-01-18', 'https://drive.google.com/file/d/0Bza-C6AOOThSSHVLV2I2WnFtTGc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35524, 2019, 3, CONCAT('True Strength'), '2013-01-25', 'https://video.sibnet.ru/shell.php?videoid=1056221');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35525, 2019, 4, CONCAT('Promise'), '2013-02-01', 'https://myvi.ru/player/embed/html/oeC7Z-0eNMyDO9WKJPdwGs7pATnYm6zNm5S23-1VnSfaUK9XnB6sVAOay-Bw2OXWkDyUcV91uQKw1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35526, 2019, 5, CONCAT('Another Key'), '2013-02-08', 'https://video.sibnet.ru/shell.php?videoid=1056254');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35527, 2019, 6, CONCAT('In Which Kenjirou Tries to Strengthen the Friendship Power of Akane and the Other Girls, But Things Get Out of Hand'), '2013-02-15', 'https://video.sibnet.ru/shell.php?videoid=1047273');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35528, 2019, 7, CONCAT('A Dream I Won', CHAR(39), 't Give Up On'), '2013-02-22', 'https://myvi.ru/player/embed/html/oK0XDcJ0ik0uwHsBza2ZGG9ZFJIBO6HIRL_7FvUvZ8atJTE3um0kBHhQbSAWaJqiikCh33dr_KU41');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35529, 2019, 8, CONCAT('Even More Brilliantly Than Today'), '2013-03-01', 'https://video.sibnet.ru/shell.php?videoid=1056261');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35530, 2019, 9, CONCAT('Clear, With Occasional Frivolity'), '2013-03-08', 'https://video.sibnet.ru/shell.php?videoid=1063570');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35531, 2019, 10, CONCAT('Light and Shadow'), '2013-03-15', 'https://myvi.ru/player/embed/html/oW9kxrVvMgjtNUc0n_hgmEsZRlA_mpDRMDS02ldPd5jc1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35532, 2019, 11, CONCAT('I Want You to Know How I Feel'), '2013-03-22', 'https://myvi.ru/player/embed/html/oxW4NAm2nE5ZT-Fiatr-_1MsNhkazKnVYi8qje8Rm_VE1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35533, 2019, 12, CONCAT('Vividred Operation'), '2013-03-29', 'https://video.sibnet.ru/shell.php?videoid=1084320');
