INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2032, CONCAT('Watashi, Nouryoku wa Heikinchi de tte Itta yo ne!'), CONCAT('Having stood out from others most of her life due to her exceptional character, Misato Kurihara has lived without neither the joy of having close friends nor the experience of having a regular life. However, after a sudden death, she was transported to a divine realm to be reincarnated—and granted one wish to top it off. Thinking about the ordinary life that she had always wanted, she wished to be born as a normal person, with abilities that are average for the world she will resurrect in.<br>
<br>Reborn as Adele von Ascham—the daughter of a noble—she possesses magic powers completely exceeding what one would label average. Still desiring to carry out the life she wanted, she leaves her home and enrolls at a hunter school in a faraway kingdom using "Mile" as an alias. However, try as she might to hide her overpowering potential, attaining her goal will be difficult—especially when facing against the crazy situations that ensue!<br>
<br>[Written by MAL Rewrite]'), 1, '2019-10-07', '2019-12-23', 'Fall 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1205/111403.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5060, 2032, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5061, 2032, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2204, 2032, 106);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2254, 2032, 20);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2255, 2032, 45);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35705, 2032, 1, CONCAT('You Said I', CHAR(39), 'd Get a Do-Over in a New World!'), NULL, 'https://ebd.cda.pl/620x368/4013038b5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35706, 2032, 2, CONCAT('Didn', CHAR(39), 't I Say the Four of Us Would Be a Party?!'), NULL, 'https://ebd.cda.pl/620x368/4035778d0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35707, 2032, 3, CONCAT('Didn', CHAR(39), 't I Say to Make My Graduation Plain and Simple?!'), NULL, 'https://ebd.cda.pl/620x368/406137163');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35708, 2032, 4, CONCAT('Didn', CHAR(39), 't I Say This Was the Crimson Vow', CHAR(39), 's First Step?!'), NULL, 'https://ebd.cda.pl/620x368/408294789');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35709, 2032, 5, CONCAT('Didn', CHAR(39), 't I Say That We', CHAR(39), 're Doing Everyone', CHAR(39), 's Backstories?!'), NULL, 'https://ebd.cda.pl/620x368/4115287de');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35710, 2032, 6, CONCAT('Didn', CHAR(39), 't I Say I', CHAR(39), 'm Not Going Into the Forest Anymore?!'), NULL, 'https://ebd.cda.pl/620x368/414115693');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35711, 2032, 7, CONCAT('Didn', CHAR(39), 't I Say We Should Take Breaks Sometimes?!'), NULL, 'https://ebd.cda.pl/620x368/4177483b3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35712, 2032, 8, CONCAT('No One Mentioned That Pauline', CHAR(39), 's Getting Married, Did They?!'), NULL, 'https://ebd.cda.pl/620x368/42004213c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35713, 2032, 9, CONCAT('Didn', CHAR(39), 't I Say Wyvern Hunting?!'), NULL, 'https://ebd.cda.pl/620x368/42202343f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35714, 2032, 10, CONCAT('Didn', CHAR(39), 't I Say Surprises Should Be Kept Secret?!'), NULL, 'https://ebd.cda.pl/620x368/424069133');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35715, 2032, 11, CONCAT('Didn', CHAR(39), 't I Say Arrogance Leads to Trouble?!'), NULL, 'https://ebd.cda.pl/620x368/42860514f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35716, 2032, 12, CONCAT('Didn', CHAR(39), 't I Say The Crimson Vow Would Never Be Destroyed?!'), '2019-12-23', 'https://ebd.cda.pl/620x368/4316816bb');
