INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2033, CONCAT('Wave!! Surfing Yappe!! (TV)'), CONCAT('Energetic and cheerful, 14-year-old Masaki Hinaoka takes his pet corgi on morning runs along the beach bathed in the rising sun. Suddenly, Masaki', CHAR(39), 's eyes sparkle in awe: a blond boy surfs, delicate and breathtaking, with a slight smile gracing his kind face. Before long, Masaki encounters him again as a new classmate named Shou Akitsuki.<br>
<br>Shou is a skilled surfer and has been immersed in the sport since childhood. Even though surfing is the hobby of choice for Masaki', CHAR(39), 's best friend, easygoing half-Hawaiian Nalu Tanaka, Masaki has never shown interest in trying it himself. But his admiration for Shou', CHAR(39), 's surfing style finally inspires him to try the waves for the first time—despite not knowing how to swim.<br>
<br>On the surfboard, Masaki shows surprising potential and talent for balance. He learns quickly and eventually enters a local competition, all with Shou and Tanaka by his side. However, behind Shou', CHAR(39), 's gentle smile lurks a darker shadow, threatening to overwhelm his friends. Nonetheless, Masaki fearlessly steps into the fun world of surfing, stopping at nothing to be the very best.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2021-01-12', '2021-03-30', 'Winter 2021', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1807/113870.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1456, 2033, '"Shigeki Surfer Boy! (刺激サーファーボーイ！)"', ' by Naminori Boys (波乗りボーイズ) [Masaki Hinaoka (Tomoaki Maeno), Shou Akitsuki (Jin Ogasawara), Nalu Tanaka (Yoshiki Nakajima), Kousuke Iwana (Takuya Satou), Yuuta Matsukaze (Yuusuke Shira', 'js-theme-songs', 'https://open.spotify.com/track/6m5MDSO3qOY8utulFIi2F1')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5062, 2033, 8);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5063, 2033, 19);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2205, 2033, 121);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35717, 2033, 1, CONCAT('Let', CHAR(39), 's Go Surfing!!'), '2021-01-12', 'https://ebd.cda.pl/620x368/663066858');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35718, 2033, 2, CONCAT('The Ocean Will Tell You'), '2021-01-19', 'https://ebd.cda.pl/620x368/663919719');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35719, 2033, 3, CONCAT('First Competition'), '2021-01-26', 'https://ebd.cda.pl/620x368/664255401');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35720, 2033, 4, CONCAT('The Endless Summer'), '2021-02-02', 'https://ebd.cda.pl/620x368/6649331f6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35721, 2033, 5, CONCAT('Beyond That Wave'), '2021-02-09', 'https://ebd.cda.pl/620x368/66907310f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35722, 2033, 6, CONCAT('Shonan Magic!'), '2021-02-16', 'https://ebd.cda.pl/620x368/676148301');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35723, 2033, 7, CONCAT('A Heart Adrift Between the Waves'), '2021-02-23', 'https://ebd.cda.pl/800x450/6835097bf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35724, 2033, 8, CONCAT('My Guardian Spirit'), '2021-03-02', 'https://ebd.cda.pl/800x450/68876235b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35725, 2033, 9, CONCAT('Forest Cup in Tsurigasaki'), '2021-03-09', 'https://ebd.cda.pl/800x450/6953434f1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35726, 2033, 10, CONCAT('No Rain, No Rainbow'), '2021-03-16', 'https://mixdrop.co/e/qlg09ppntxx0wrq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35727, 2033, 11, CONCAT('Show Must Go On!!'), '2021-03-23', 'https://vidstreaming.io/streaming.php?id=MTU1NDUz');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35728, 2033, 12, CONCAT('Big WAVEs!!'), '2021-03-30', 'https://vidstreaming.io/streaming.php?id=MTU2MzY0');
