INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2064, CONCAT('Yama no Susume'), CONCAT('As a child, Aoi Yukimura adored mountains and was passionate about climbing. However, a playground accident has since left her afraid of heights, turning her toward indoor hobbies. Unfortunately, now a shy and timid first-year high school student, Aoi has become so absorbed in these pastimes that she can barely socialise with others, leaving her practically friendless. It’s only when she runs into the lively Hinata Kuraue, an old friend from her climbing days, that things start to change. <br>
<br>Impulsive and high-spirited, Hinata insists on having Aoi join her in all sorts of climbing activities. Though reluctant at first, Aoi quickly finds that her time with Hinata brings back fond memories of their childhood and soon decides to start climbing again. As the return to her past hobby starts to bring her out of her shell, Aoi finds herself gaining close friends, taking on new challenges, and continuing to find her own encouragement to climb.<br>
<br>[Written by MAL Rewrite]'), 1, '2013-01-03', '2013-03-21', 'Winter 2013', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/75525.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1477, 2064, '"Staccato Days (スタッカート・デイズ)"', ' by Aoi (Yuka Iguchi) and Hinata (Kana Asumi)', 'js-theme-songs', 'https://open.spotify.com/track/1CSKwk3qNy5bVfzIlPLoFK');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5128, 2064, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5129, 2064, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5130, 2064, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2236, 2064, 90);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2294, 2064, 28);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2295, 2064, 8);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36181, 2064, 1, CONCAT('Anything but Mountains!'), '2013-01-03', 'https://video.sibnet.ru/shell.php?videoid=986737');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36182, 2064, 2, CONCAT('Let', CHAR(39), 's Go Together!'), '2013-01-10', 'https://video.sibnet.ru/shell.php?videoid=991418');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36183, 2064, 3, CONCAT('Mountain Climbing Is Dangerous!?'), '2013-01-17', 'https://video.sibnet.ru/shell.php?videoid=998042');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36184, 2064, 4, CONCAT('Showdown! Mountain Cooking!?'), '2013-01-24', 'https://vk.com/video_ext.php?oid=186749831&id=164078550&hash=f35742c765cc483f&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36185, 2064, 5, CONCAT('What', CHAR(39), 's a Schlafsack?'), '2013-01-31', 'https://vk.com/video_ext.php?oid=186749831&id=164135191&hash=90b8f5afcf55086a&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36186, 2064, 6, CONCAT('I', CHAR(39), 'm The One Deciding!?'), '2013-02-07', 'https://video.sibnet.ru/shell.php?videoid=1034074');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36187, 2064, 7, CONCAT('Which Daypack Do You Want?'), '2013-02-14', 'https://drive.google.com/file/d/0B5-MnnU6QEhhMUNsSkx4MGwzN28/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36188, 2064, 8, CONCAT('Let', CHAR(39), 's Climb Mount Takao!'), '2013-02-21', 'https://drive.google.com/file/d/0B5-MnnU6QEhhbDNzb0tvYURzeFk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36189, 2064, 9, CONCAT('A Forest Girl in the Forest!?'), '2013-02-28', 'https://vidspace.io/embed-6pxzycmvg9ni.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36190, 2064, 10, CONCAT('The Climb Isn', CHAR(39), 't Over Until You Descend!?'), '2013-03-07', 'https://drive.google.com/file/d/0BxjakHSDvXtQQWpzdzFlVWYxd28/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36191, 2064, 11, CONCAT('Tomorrow Is Outdoors!'), '2013-03-14', 'https://vidspace.io/embed-15s3z89a8hok.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36192, 2064, 12, CONCAT('To the Next Landscape'), '2013-03-21', 'https://vk.com/video_ext.php?oid=186749831&id=169007350&hash=91af3e04982ee56c&hd=2');
