INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2078, CONCAT('Yoru no Kuni'), CONCAT('22-ji no Annaibito (The 22 O', CHAR(39), 'Clock Guide)
<br>Refusing to accept the death of her beloved dog, Choco, a young girl named Chiyo falls asleep, only to wake up in the Night World. She is greeted by Yoru, an entity that guides her through the realm of the darkest, most beautiful time of day. As Chiyo learns to cope with the loss in her heart, the starless world around her begins to light up.<br><br>26-ji no Sagashimono (The 26 O', CHAR(39), 'Clock Search)
<br>Since childhood, best friends Hina and Tsumugi have used an exchange diary as a token of their friendship. Angered that Hina wants to open up the diary to include a new girl she has befriended, the jealous Tsumugi throws it away. Upon falling asleep, she wakes up in front of a labyrinth within the Night World. Initially refusing to take Yoru', CHAR(39), 's help, Tsumugi searches for an answer to her predicament, but she is confronted by her feelings of loneliness instead. <br><br>4-ji no Tegami (The 4 O', CHAR(39), 'Clock Letter)
<br>Another morning is approaching, and the thought fills Akatsuki with dread. Dejected from her inability to build a career, she begins to throw away her art pieces, stumbling upon an old sketchbook in the process. Within the book is a letter from a former friend who, a long time ago, had given her hope. As she continues going through her belongings, Akatsuki starts to remember the friend', CHAR(39), 's identity—and she might even discover her fading passion for painting.<br>
<br>[Written by MAL Rewrite]'), 2, '2021-04-16', '2021-09-12', '', '8 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1674/114425.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1485, 2078, '"Trill (トリル)"', ' by Aimer', 'js-theme-songs', '');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (860, 2078, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5161, 2078, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5162, 2078, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5163, 2078, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2251, 2078, 42);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36383, 2078, 1, CONCAT('The 22 O', CHAR(39), 'clock Guide'), '2021-04-16', 'https://ebd.cda.pl/620x368/7731718b7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36384, 2078, 2, CONCAT('The 26 O', CHAR(39), 'clock Search'), '2021-06-04', 'https://ebd.cda.pl/620x368/773172453');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36385, 2078, 3, CONCAT('The 4 O', CHAR(39), 'clock Letter'), '2021-09-12', 'https://ebd.cda.pl/620x368/837369946');
