INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2086, CONCAT('Yumekui Merry'), CONCAT('High school student Yumeji Fujiwara has the ability to see people', CHAR(39), 's dreams. Despite the visions never appearing clear or concrete, he is able to predict them by sensing the person', CHAR(39), 's "aura." Normally, this skill is a fun trick to play on his classmates, but Yumeji only ever sees himself having the same nightmare every night.<br>
<br>To his surprise, the nightmare continues in the middle of the day even before Yumeji has fallen asleep. The unexpected event was triggered by a dream demon—an inhabitant of the world of dreams who wants to use Yumeji', CHAR(39), 's body as a vessel to fully enter the real world. However, Yumeji is saved by the timely arrival of Merry Nightmare, another dream demon who can somehow physically manifest without a host and is instead trying to return to her own realm.<br>
<br>As more dream demons continue to push into reality, it is up to Yumeji and Merry to fight back against the invasion before everyone', CHAR(39), 's nightmares materialize.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2011-01-07', '2011-04-08', 'Winter 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/30869.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1492, 2086, '"Daydream Syndrome"', ' by Marina Fujiwara (藤原鞠菜)', 'js-theme-songs', 'https://open.spotify.com/track/00ANxMHjANZ0GMeoKcNKVp')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5180, 2086, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5181, 2086, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2259, 2086, 31);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36486, 2086, 1, CONCAT('Dream and Reality'), '2011-01-07', 'https://drive.google.com/file/d/1hl0fJ0U__ideexVikddFo_ebGRAXTO-E/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36487, 2086, 2, CONCAT('Dream and Hope'), '2011-01-14', 'https://drive.google.com/file/d/1yqfmb90WOmuWMDpNeZAe5s_1qXrlHBHQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36488, 2086, 3, CONCAT('From Beyond the Dream'), '2011-01-21', 'https://drive.google.com/file/d/13Ng8CtTFA71nBrCIGuRTj0Yzue1aaYcM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36489, 2086, 4, CONCAT('Dream Eater Merry'), '2011-01-28', 'https://drive.google.com/file/d/1WPlo74seD6axvE8pqI2nIBzkg_Ipr3Ul/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36490, 2086, 5, CONCAT('Bewildered by Dreams'), '2011-02-04', 'https://drive.google.com/file/d/1iqgyKDiM7pNEkmwhXpD82-BPlkAqT6K1/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36491, 2086, 6, CONCAT('Encounter With Dreams'), '2011-02-11', 'https://drive.google.com/file/d/1pkKg_Jd5l_67K_QYMm3anpDpRsaqYwFc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36492, 2086, 7, CONCAT('Dreams, Swimsuits and the Color of the Ocean'), '2011-02-18', 'https://drive.google.com/file/d/1-ApMwUZgn1_qYEf25YytPFfcYJ_Ia6SJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36493, 2086, 8, CONCAT('Dream Gallery'), '2011-02-25', 'https://drive.google.com/file/d/1d_NWAVPprHFyhKKvC9LTKjx66vHqrWU5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36494, 2086, 9, CONCAT('Disturbed Dream'), '2011-03-04', 'https://drive.google.com/file/d/16DnKQovAtb8_wiLRGWeN2Ad205WySLkp/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36495, 2086, 10, CONCAT('Without Waking Up from the Dream'), '2011-03-11', 'https://video.sibnet.ru/shell.php?videoid=539445');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36496, 2086, 11, CONCAT('Guardian of the Dream'), '2011-03-25', 'https://video.sibnet.ru/shell.php?videoid=539640');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36497, 2086, 12, CONCAT('Bad Dream'), '2011-04-01', 'https://drive.google.com/file/d/11UWUeq3Ic6_YO1GavlmgJLcJl1c0Tedz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36498, 2086, 13, CONCAT('Dream Again'), '2011-04-08', 'https://drive.google.com/file/d/1E2_aDn-fDHuuC2V6sGNGGZc377MOnFyQ/preview');
