INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2092, CONCAT('Yuru Yuri♪♪'), CONCAT('The girls of the Amusement Club return in Yuru Yuri♪♪, finding new ways to make passing time even more enjoyable. Their members consist of the always energetic Kyouko Toshinou calm and sensible Yui Funami polite but often overlooked Akari Akaza and Chinatsu Yoshikawa, who stumbled upon the others while looking for the Tea Ceremony Club. Together they are the Amusement Club, which has the deceptively simple task of keeping its members entertained.<br>
<br>Along with the Student Council and the odd family member, they strive to enjoy their youth to the fullest. Whether it', CHAR(39), 's a trip to a hot spring or finishing overdue homework, their lives are never dull, and they will always find an excuse to spend time together.<br>
<br>[Written by MAL Rewrite]'), 1, '2012-07-03', '2012-09-18', 'Summer 2012', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/75174.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1497, 2092, '"Yes! Yuyuyu☆Yuru Yuri♪♪ (いぇす! ゆゆゆ☆ゆるゆり♪♪)"', ' by Nanamori Chu☆Goraku Bu (七森中☆ごらく部)', 'js-theme-songs', 'https://open.spotify.com/track/237dREjci0EY0iMcU6W02j')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5193, 2092, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5194, 2092, 16);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2265, 2092, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2312, 2092, 28);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2313, 2092, 38);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2314, 2092, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36550, 2092, 1, CONCAT('The Protagonist Returns'), '2012-07-03', 'https://drive.google.com/file/d/1Rpnu28HMfTDPodN9q10fH0Q1kRFWgci3/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36551, 2092, 2, CONCAT('Yuru Yuri Everyday'), '2012-07-10', 'https://drive.google.com/file/d/19kGNnODDlg9bQ0eiClxrx7J22ybJYLRq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36552, 2092, 3, CONCAT('Chocolate and Tears and Girls and Girls and Isobe Fries'), '2012-07-17', 'https://drive.google.com/file/d/1IaLUWUDRSt-3Jr7ooWDMno6o11G5Ip6X/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36553, 2092, 4, CONCAT('Achoo'), '2012-07-24', 'https://drive.google.com/file/d/1uF9idQyvWVkvssk4LVl9aXkn1f3CcwBJ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36554, 2092, 5, CONCAT('Lazy, Japanese Summer'), '2012-07-31', 'https://drive.google.com/file/d/1UAmSvkQG0k1UYh0O6DzIXQiy2BG3wOvv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36555, 2092, 6, CONCAT('[Breaking News] Yuru Yuri Sold Out'), '2012-08-07', 'https://drive.google.com/file/d/1gSZzvH6x-a-iJBuH1yvv3AkbWomc9Uwo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36556, 2092, 7, CONCAT('Sisterly Relations and Such'), '2012-08-14', 'https://drive.google.com/file/d/177SIIOhxzWA3Ht6UrsS7H_r1A12oR462/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36557, 2092, 8, CONCAT('Chinatsu Unrivaled'), '2012-08-21', 'https://drive.google.com/file/d/1-imzq6asKdmF7kDUK__qsZhDhOJvjJ4k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36558, 2092, 9, CONCAT('A Day Something May or May Not Happen'), '2012-08-28', 'https://drive.google.com/file/d/1eQ8MoHYSw8xCkLKALTGVprBN_9Fkjh-H/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36559, 2092, 10, CONCAT('School Trip R'), '2012-09-04', 'https://drive.google.com/file/d/1ISWDBypE9fbqzY3KjL1lVjnWSE65cMe-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36560, 2092, 11, CONCAT('The Akari Who Leapt Through Time'), '2012-09-11', 'https://drive.google.com/file/d/123capW0uXoc0lxC7F8fFOo6_YEDrVZ84/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36561, 2092, 12, CONCAT('Good Bye Protagonist, Until We Meet Again'), '2012-09-18', 'https://drive.google.com/file/d/1E9eduKotQz7WdX21saB77fgHg1RU_Q_f/preview');
