INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2090, CONCAT('Yuru Camp△'), CONCAT('While the perfect getaway for most girls her age might be a fancy vacation with their loved ones, Rin Shima', CHAR(39), 's ideal way of spending her days off is camping alone at the base of Mount Fuji. From pitching her tent to gathering firewood, she has always done everything by herself, and has no plans of leaving her little solitary world.<br>
<br>However, what starts off as one of Rin', CHAR(39), 's usual camping sessions somehow ends up as a surprise get-together for two when the lost Nadeshiko Kagamihara is forced to take refuge at her campsite. Originally intending to see the picturesque view of Mount Fuji for herself, Nadeshiko', CHAR(39), 's plans are disrupted when she ends up falling asleep partway to her destination. Alone and with no other choice, she seeks help from the only other person nearby. Despite their hasty introductions, the two girls nevertheless enjoy the chilly night together, eating ramen and conversing while the campfire keeps them warm. And even after Nadeshiko', CHAR(39), 's sister finally picks her up later that night, both girls silently ponder the possibility of another camping trip together.<br>
<br>[Written by MAL Rewrite]'), 1, '2018-01-04', '2018-03-22', 'Winter 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/89877.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1496, 2090, '"SHINY DAYS"', ' by Asaka', 'js-theme-songs', 'https://open.spotify.com/track/3V7mWY7bwabSRPOOuJ7rcN')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2263, 2090, 165);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2308, 2090, 28);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2309, 2090, 8);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36535, 2090, 1, CONCAT('Mount Fuji and Curry Noodles'), '2018-01-04', 'https://drive.google.com/file/d/1fuhekHgV61kB-uZ-BTzzJwMOIo0JYBWd/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36536, 2090, 2, CONCAT('Welcome to the Outdoor Activities Club'), '2018-01-11', 'https://drive.google.com/file/d/1D74xniBp9G68YnLozWtoUn6kgwab5bPg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36537, 2090, 3, CONCAT('Mount Fuji and Relaxed Hot Pot Camp'), '2018-01-18', 'https://drive.google.com/file/d/1ylpIftII8DAA4Xnv-6RfZPrypqCcgRoa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36538, 2090, 4, CONCAT('The Outdoor Activities Club and the Solo Camping Girl'), '2018-01-25', 'https://drive.google.com/file/d/1954lIxsi4mZeqDvaBWntsWcSxwbGfa46/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36539, 2090, 5, CONCAT('Two Camps, Two Campers', CHAR(39), ' Views'), '2018-02-01', 'https://drive.google.com/file/d/1HjTw-HQfsEVxvFayKapn1h-M4YL_mRYM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36540, 2090, 6, CONCAT('Meat and Fall Colors and the Mystery Lake'), '2018-02-08', 'https://drive.google.com/file/d/1WCLguf--Ba8qcBQrmoriuUamJSEYi3XD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36541, 2090, 7, CONCAT('A Night on the Lake Shore and Campers'), '2018-02-15', 'https://drive.google.com/file/d/1bdBeRHeKHLRrsoobIXVCZp-pjCjMc9wM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36542, 2090, 8, CONCAT('Exams, Caribou, Steamed Buns, Yum!'), '2018-02-22', 'https://drive.google.com/file/d/16ktjRK60TUIPWC1vB9vRAnZ5yOFHC8Cn/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36543, 2090, 9, CONCAT('A Night of Navigator Nadeshiko and Hot Spring Steam'), '2018-03-01', 'https://drive.google.com/file/d/1ine92wUYePpFMvhNnOhgLZ5Rj_43DYDk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36544, 2090, 10, CONCAT('Clumsy Travelers and Camp Meetings'), '2018-03-08', 'https://drive.google.com/file/d/1tm6oSDxYqtsXxDgN8RGs95huJMm-Xblf/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36545, 2090, 11, CONCAT('Christmas Camp!'), '2018-03-15', 'https://drive.google.com/file/d/1r-p79VPdie7lF81fnAsgIbRLtseh1ukb/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36546, 2090, 12, CONCAT('Mount Fuji and the Laid-Back Camp Girls'), '2018-03-22', 'https://drive.google.com/file/d/1ldLQrFPYW2jSUvpne29uiPU4YMLiYXbj/preview');
