INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2097, CONCAT('Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou'), CONCAT('Having fulfilled their destiny during the events of  Yuuki Yuuna wa Yuusha de Aru, Sanshu Middle School', CHAR(39), 's Hero Club—consisting of Yuuna Yuuki, Karin Miyoshi, and siblings Fuu and Itsuki Inubouzaki—is back in full swing, helping out those in need wherever they can. They have also gained a new member, a hero from the past named Sonoko Nogi. But eventually they notice that someone who should be among them, Mimori Tougou, is missing any trace of her existence is completely gone, save for the girls', CHAR(39), ' memories.<br>
<br>With no leads on Tougou', CHAR(39), 's whereabouts, the girls regain the ability to transform and begin the desperate search for their lost friend. But what they find is more shocking than any of them could ever have imagined, and the consequences of their actions begin to change life as they know it.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-11-25', '2018-01-06', 'Fall 2017', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/83013.jpg');
INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl) VALUES (1500, 2097, '"Hanakotoba (ハナコトバ)"', ' by Sanshuu Chuugaku Yuusha-bu (讃州中学勇者部) (Haruka Terui, Suzuko Mimori, Yumi Uchida, Tomoyo Kurosawa, Juri Nagatsuma, Kana Hanazawa)', 'js-theme-songs', 'https://open.spotify.com/track/3b4JTfTOXCPvq92qTM61FU')INSERT INTO Songs(SongID, AnimeID, Title, Artist, Type, SpotifyUrl);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5206, 2097, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5207, 2097, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5208, 2097, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2270, 2097, 16);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2319, 2097, 30);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2320, 2097, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36705, 2097, 1, CONCAT('Spectacular Days'), '2017-11-25', 'https://tune.pk/video/7573715');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36706, 2097, 2, CONCAT('Important Memories'), '2017-12-02', 'https://ebd.cda.pl/800x450/4005121f6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36707, 2097, 3, CONCAT('My Heart Hurts When I Think of You'), '2017-12-09', 'https://www.mp4upload.com/embed-d3i4rpe7obab.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36708, 2097, 4, CONCAT('Unspoken Intentions'), '2017-12-16', 'https://www.mp4upload.com/embed-d04cd4pz0pk8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36709, 2097, 5, CONCAT('Incorruptible Heart'), '2017-12-23', 'https://www.dailymotion.com/embed/video/x6e2nqf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36710, 2097, 6, CONCAT('Only You Can Make Me Happy'), '2018-01-06', 'https://tune.pk/video/7600469');
