INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (12, CONCAT('3x3 Eyes: Seima Densetsu'), CONCAT('Yakumo has trained and searched for 4 years, following Pai', CHAR(39), 's mysterious disappearance. However, when he finally finds her, not all is well as her memory seems to be gone. They attempt to return her memory by going to the Holy Land, birthplace of the immortal race of Sanjiyans.'), 3, '1995-07-25', '1996-06-25', '', '48 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1288/120666.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (25, 12, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (26, 12, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (27, 12, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (28, 12, 11);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (29, 12, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (12, 12, 9);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (12, 12, 10);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (13, 12, 11);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (149, 12, 1, CONCAT('Descent'), '1995-07-25', 'https://ebd.cda.pl/800x450/639707046');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (150, 12, 2, CONCAT('The Key'), '1995-12-18', 'https://ebd.cda.pl/620x395/6397076d7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (151, 12, 3, CONCAT('The Return'), '1996-06-25', 'https://ebd.cda.pl/620x395/63970733e');
