INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (103, CONCAT('Ao no Exorcist: Kyoto Fujouou-hen'), CONCAT('The ExWire of True Cross Academy are beset with shock and fear in the aftermath of discovering that one of their own classmates, Rin Okumura, is the son of Satan. But for the moment, they have more pressing concerns than that of Rin', CHAR(39), 's parentage: the left eye of the Impure King, a powerful demon, has been stolen from the academy', CHAR(39), 's Deep Keep. After an attempt is made to steal the right eye in Kyoto as well, Rin and the other ExWires are sent to investigate the mystery behind the Impure King and the ultimate goal of the thief.<br>
<br>While this mission has them cooperating for the time being, Rin has never felt more distant from his fellow exorcists. In his attempt to reconcile with them, he undergoes specialized training to control his dark power. However, when the right eye is stolen not long after their arrival, the unthinkable threat of a traitor amongst them leaves them in need of all the power they can get.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-01-07', '2017-03-25', 'Winter 2017', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/85201.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (49, 103, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (235, 103, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (236, 103, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (117, 103, 6);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (104, 103, 11);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (105, 103, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1539, 103, 1, CONCAT('Small Beginnings'), '2017-01-07', 'https://video.sibnet.ru/shell.php?videoid=2803853');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1540, 103, 2, CONCAT('Strange Bedfellows'), '2017-01-14', 'https://drive.google.com/file/d/1q--4wZCSulmiIrAN2YM4v3dgk0Hu4ILu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1541, 103, 3, CONCAT('Suspicion Will Raise Bogies'), '2017-01-21', 'https://video.sibnet.ru/shell.php?videoid=2818005');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1542, 103, 4, CONCAT('Act of Treachery'), '2017-01-28', 'https://ebd.cda.pl/620x395/53972258c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1543, 103, 5, CONCAT('Mysterious Connections'), '2017-02-04', 'https://drive.google.com/file/d/15-7xz9-roXwJiR25gp4yirkK_wf0aKMm/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1544, 103, 6, CONCAT('A Wolf in Sheep', CHAR(39), 's Clothing'), '2017-02-11', 'https://drive.google.com/file/d/1vvBc-fh1tiyma-9PJb-RMRzZjNep38d1/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1545, 103, 7, CONCAT('Like a Fire Burning Bright'), '2017-02-18', 'https://drive.google.com/file/d/1NANh6SNzgLAlMZ9uhQ_6Hyo3nyhFigKd/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1546, 103, 8, CONCAT('From Father to Son'), '2017-02-25', 'https://drive.google.com/file/d/1BTL4C0gQ3h2XySp45ivGvQFGSrMpjNTv/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1547, 103, 9, CONCAT('Through Thick and Thin'), '2017-03-04', 'https://drive.google.com/file/d/1WeX7jhbGjb-IN2we6qPPUty18gR3UJJE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1548, 103, 10, CONCAT('Unbowed and Unbroken'), '2017-03-11', 'https://drive.google.com/file/d/1c8Y1IAVeQJKP6avcu0ugeZMgzwPyMvtr/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1549, 103, 11, CONCAT('Shine Bright as the Sun'), '2017-03-18', 'https://drive.google.com/file/d/1fg5OPMyF1K1--74ByokK4rChtRfvcL9r/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1550, 103, 12, CONCAT('Candid and Open'), '2017-03-25', 'https://drive.google.com/file/d/1oX7hMu5HVolXdeUs-X1CHr67YWGAnHDY/preview');
