INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (113, CONCAT('Aquarion Evol'), CONCAT('12,000 years after the events in Genesis Aquarion, humans live on the star Vega under constant threat of trans-dimensional beings called Abductors. These enemies originate from Vega’s sister star Altair and raid Vega for human life. As a countermeasure, an organization known as Neo-DEAVA formed to combat the Abductors. They pilot advanced mecha suits called Aquaria and are strictly separated by gender. Boys and girls are not allowed contact they are even restrained from fighting on the same battlefield. However, events take a shocking turn when an advanced Abductor mecha suit joins the fray. Two teenagers, Mikono and Amata, are dragged into the conflict. Unknowingly, Amata performs a taboo when he summons an Aquaria and initializes what is called the Forbidden Union between male and female Aquaria. Neo-DEAVA is shocked, and the repercussions of Amata’s actions are much farther reaching than he realizes. How was he able to summon an Aquaria? Where did he learn to form a Forbidden Union? And why was Mikono also able to pilot the mecha suit?'), 1, '2012-01-09', '2012-06-25', 'Winter 2012', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/72743.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (256, 113, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (257, 113, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (258, 113, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (259, 113, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (127, 113, 43);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (114, 113, 3);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (115, 113, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1633, 113, 1, CONCAT('A Myth That Holds An End'), NULL, 'https://video.sibnet.ru/shell.php?videoid=534216');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1634, 113, 2, CONCAT('Forbidden Gattai'), NULL, 'https://streamtape.com/e/adpOZ979MXf0Po/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1635, 113, 3, CONCAT('Love Index Skyrockets'), NULL, 'https://ebd.cda.pl/800x450/71237535');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1636, 113, 4, CONCAT('The Wall - Conquer Oneself -'), NULL, 'https://ebd.cda.pl/800x450/71242662');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1637, 113, 5, CONCAT('Romance Prohibition Order'), NULL, 'https://ebd.cda.pl/800x450/7124989e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1638, 113, 6, CONCAT('Agitato of Life'), NULL, 'https://ebd.cda.pl/800x450/7128227b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1639, 113, 7, CONCAT('Midnight Girl'), NULL, 'https://ebd.cda.pl/800x450/712861eb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1640, 113, 8, CONCAT('Expose'), NULL, 'https://ebd.cda.pl/800x450/712942c9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1641, 113, 9, CONCAT('Anagram of Man and Woman'), NULL, 'https://ebd.cda.pl/800x450/712966d0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1642, 113, 10, CONCAT('One-Eyed Transfer Student'), NULL, 'https://ebd.cda.pl/800x450/712984d6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1643, 113, 11, CONCAT('Calling of the Wild'), NULL, 'https://ebd.cda.pl/800x450/71743933');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1644, 113, 12, CONCAT('The Skies Aquaria Flies'), NULL, 'https://ebd.cda.pl/800x450/7152134b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1645, 113, 13, CONCAT('Fallen Giant'), NULL, 'https://ebd.cda.pl/800x450/7207484e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1646, 113, 14, CONCAT('Beyond an Individual'), NULL, 'https://ebd.cda.pl/800x450/7191641c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1647, 113, 15, CONCAT('Love Beasts'), NULL, 'https://ebd.cda.pl/800x450/720214ad');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1648, 113, 16, CONCAT('Soul', CHAR(39), 's Confession'), NULL, 'https://ebd.cda.pl/800x450/720814fd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1649, 113, 17, CONCAT('Well up, Life!'), NULL, 'https://ebd.cda.pl/800x450/7221124a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1650, 113, 18, CONCAT('Rare Igura'), NULL, 'https://ebd.cda.pl/800x450/7226463a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1651, 113, 19, CONCAT('First Reunion'), NULL, 'https://ebd.cda.pl/800x450/72269133');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1652, 113, 20, CONCAT('MI⋅XY'), NULL, 'https://video.sibnet.ru/shell.php?videoid=731289');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1653, 113, 21, CONCAT('Kiss'), NULL, 'https://vk.com/video163477115_163599269');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1654, 113, 22, CONCAT('Wing of Revival'), NULL, 'https://ebd.cda.pl/800x450/760768c7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1655, 113, 23, CONCAT('Melody of Myth'), NULL, 'https://ebd.cda.pl/800x450/76088242');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1656, 113, 24, CONCAT('ephemera'), NULL, 'https://ebd.cda.pl/800x450/762802ae');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1657, 113, 25, CONCAT('Fragment of Adam'), NULL, 'https://ebd.cda.pl/800x450/763036e0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1658, 113, 26, CONCAT('LOVE'), NULL, 'https://video.sibnet.ru/shell.php?videoid=733137');
