INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (122, CONCAT('Argonavis from BanG Dream!'), CONCAT('Ren Nanahoshi has been chasing a certain thrill he once experienced at a live festival when he was a child. Now, as a first-year university student, he avoids making friends and practices singing by himself, hoping to find that adrenaline once more. A fateful encounter at a karaoke bar allows Nanahoshi to meet Yuuto Goryou and Wataru Matoba—both of whom are impressed by his voice. The two have been searching for band members, and they want Nanahoshi to be their vocalist.  <br>
<br>Nanahoshi initially rejects their constant pestering but relents after attending their live show and performing alongside them. Joined by the carefree Rio Kikyou and passionate Banri Shiroishi, the five boys form "Argonavis" and set their sights on headlining the Destiny Rock Festival. As they begin to work together as a band, they come across the trials and tribulations that come with pursuing stardom.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2020-04-11', '2020-07-04', 'Spring 2020', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1484/109428.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (136, 122, 60);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1784, 122, 1, CONCAT('To place where there is light'), '2020-04-11', 'https://feurl.com/v/5dr6xfdw1kg5el2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1785, 122, 2, CONCAT('Genius and Enthusiasm'), '2020-04-18', 'https://vidstreaming.io/streaming.php?id=MTM4ODY4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1786, 122, 3, CONCAT('Our Departure'), '2020-04-25', 'https://vidstreaming.io/streaming.php?id=MTM4OTU4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1787, 122, 4, CONCAT('Between Dream and Reality'), '2020-05-02', 'https://gounlimited.to/embed-7ndxcem7mz9z.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1788, 122, 5, CONCAT('Farewell to the Past'), '2020-05-09', 'https://vidstreaming.io/streaming.php?id=MTM5NDQx');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1789, 122, 6, CONCAT('Meteor Shower'), '2020-05-16', 'https://vidstreaming.io/streaming.php?id=MTM5NzIx');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1790, 122, 7, CONCAT('Across the waves'), '2020-05-23', 'https://vidstreaming.io/streaming.php?id=MTQwMTE4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1791, 122, 8, CONCAT('Resonance'), '2020-05-30', 'https://vidstreaming.io/streaming.php?id=MTQwMzUw');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1792, 122, 9, CONCAT('Challenge to the Unknown'), '2020-06-06', 'https://mixdrop.co/e/xol86w8vhmj0e1/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1793, 122, 10, CONCAT('Break the limit!'), '2020-06-13', 'https://feurl.com/v/054eqcllp2n36-6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1794, 122, 11, CONCAT('To the place of destiny'), '2020-06-20', 'https://feurl.com/v/my5-ph55d2xrzlz');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1795, 122, 12, CONCAT('Goal Line'), '2020-06-27', 'https://feurl.com/v/7r3dgbgnme04g1x');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (1796, 122, 13, CONCAT('Pray'), '2020-07-04', 'https://feurl.com/v/054eqcl8ymw2kel');
