INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (306, CONCAT('Charlotte'), CONCAT('If not for his ability to take over people', CHAR(39), 's mind and body, Yuu Otosaka would be an ordinary high school student. Though it only lasts for five seconds at a time, Yuu', CHAR(39), 's mysterious power allowed him to cheat his way to the top of his class and  enter a prestigious high school, where he continues his dishonest acts.<br>
<br>His shenanigans are eventually stopped by Nao Tomori—the headstrong student council president from Hoshinoumi Academy—who sees through his deceit. Through coercion, Nao convinces Yuu to transfer to Hoshinoumi and join the student council. Hoshinoumi Academy is secretly an institution created for adolescents who possess supernatural abilities—with the student council serving as a means of locating those who abuse their powers.<br>
<br>With Yuu begrudgingly assisting in council affairs, the group sets out to find and protect new ability users from harm. However, as they further investigate the abilities, their findings entangle them in far more complicated matters than they could ever imagine.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2015-07-05', '2015-09-27', 'Summer 2015', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/74683.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (344, 306, 52);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (325, 306, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (326, 306, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5263, 306, 1, CONCAT('I Think About Others'), '2015-07-05', 'https://ebd.cda.pl/620x368/1301234ce');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5264, 306, 2, CONCAT('Melody of Despair'), '2015-07-12', 'https://drive.google.com/file/d/1WppQD8qoLZipr0WF9yIwehQiYP9r2_Fg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5265, 306, 3, CONCAT('Love and Flame'), '2015-07-19', 'https://drive.google.com/file/d/1fJSCTd5Z3Zau8Xzwe8QTJkpjR5zOZuZd/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5266, 306, 4, CONCAT('Moment of Earnest'), '2015-07-26', 'https://ebd.cda.pl/620x395/594338068');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5267, 306, 5, CONCAT('The Sound You Heard Sometime'), '2015-08-02', 'https://ebd.cda.pl/620x395/56735366f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5268, 306, 6, CONCAT('Happy You Did Not Notice'), '2015-08-09', 'https://ebd.cda.pl/620x395/567350095');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5269, 306, 7, CONCAT('The End of the Exodus'), '2015-08-16', 'https://drive.google.com/file/d/1B7KSU2qg-V8ehgINVzROsxuKt2m7G6Yt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5270, 306, 8, CONCAT('Encounter'), '2015-08-23', 'https://drive.google.com/file/d/1B1bo71LRChIr1fLE0a5HUbbBYCB_MTt-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5271, 306, 9, CONCAT('The World is Not in Here'), '2015-08-30', 'https://drive.google.com/file/d/17yZvP9y_hKXsjG_4bN2JHvSPwGRqaQJl/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5272, 306, 10, CONCAT('Looting'), '2015-09-06', 'https://drive.google.com/file/d/1dIx7ijlJwowqvX473MRIpTNMG6uuUhvM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5273, 306, 11, CONCAT('Charlotte'), '2015-09-13', 'https://drive.google.com/file/d/1R9siB6CYQuDyUTCsbCpVKz0vE9a0RbL9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5274, 306, 12, CONCAT('Promise'), '2015-09-20', 'https://drive.google.com/file/d/19Vk_GKXHcetqNlcVOhPI1zTQmZsoJO7l/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5275, 306, 13, CONCAT('Memories to Come'), '2015-09-27', 'https://ebd.cda.pl/620x395/56735185d');
