INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (324, CONCAT('Choujin Koukousei-tachi wa Isekai demo Yoyuu de Ikinuku you desu!'), CONCAT('Seven Japanese high school students enjoy international renown for their remarkable talents. One day, these friends survive a plane crash only to find themselves in the medieval fantasy world of Freyjagard, where two human races live side by side in a feudal society: the byuma, who have animal features and formidable strength, and the hyuma, who have a small chance of magical aptitude. After being rescued by the byuma Winona and her adopted elven daughter Lyrule, the group pledges to use their advanced skills and knowledge to pay back the people of Elm Village for their hospitality and find a way to return back home.<br>
<br>Tsukasa Mikogami, the prime minister of Japan, acts as the leader of these young geniuses and organizes their efforts to intervene in Freyjagard and gather the information and resources necessary for achieving their goals. Believing that there is a connection between their current situation and an ancient legend about seven heroes from another world who defeated an evil dragon, Tsukasa directs the others to learn about the culture around them and search for any clues leading them back to Earth. But he also gives another instruction: to take it nice and easy, lest they ruin this world by giving it their all.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-10-03', '2019-12-19', 'Fall 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1132/111619.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (362, 324, 106);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5629, 324, 1, CONCAT('High School Prodigies Have Arrived in Another World!'), '2019-10-03', 'https://ebd.cda.pl/620x368/401979100');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5630, 324, 2, CONCAT('Masato Is Serious About Making Money!'), '2019-10-10', 'https://ebd.cda.pl/620x368/4026160ce');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5631, 324, 3, CONCAT('It Seems Roo Can Decide Her Own Worth!'), '2019-10-17', 'https://ebd.cda.pl/620x368/405036701');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5632, 324, 4, CONCAT('It Seems Tsukasa has Resolved to Change the World!'), '2019-10-24', 'https://ebd.cda.pl/620x368/406852009');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5633, 324, 5, CONCAT('It Seems Akatsuki', CHAR(39), 's Becoming God Akatsuki!'), '2019-10-31', 'https://ebd.cda.pl/620x368/410780558');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5634, 324, 6, CONCAT('It Seems Lyrule', CHAR(39), 's Growing Closer to Him!'), '2019-11-07', 'https://ebd.cda.pl/620x368/412701426');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5635, 324, 7, CONCAT('It Seems Shinobu Has a Shinobi', CHAR(39), 's Intuition!'), '2019-11-14', 'https://ebd.cda.pl/620x368/415746726');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5636, 324, 8, CONCAT('It Seems Aoi', CHAR(39), 's Specs Are Greater Than Imagined!'), '2019-11-21', 'https://ebd.cda.pl/620x368/41883977a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5637, 324, 9, CONCAT('It Seems Tsukasa Has Seen Through Everything!'), '2019-11-28', 'https://ebd.cda.pl/620x368/420891720');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5638, 324, 10, CONCAT('It Seems Ringo', CHAR(39), 's Worked Up the Courage to Become a Hunter!'), '2019-12-05', 'https://ebd.cda.pl/620x368/422916244');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5639, 324, 11, CONCAT('It Seems Keine Can', CHAR(39), 't Stand Naughty Boys!'), '2019-12-12', 'https://ebd.cda.pl/620x368/427430644');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5640, 324, 12, CONCAT('It Seems High School Prodigies Have It Easy Even In Another World!'), '2019-12-19', 'https://ebd.cda.pl/620x368/42982132c');
