INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (329, CONCAT('Chuukan Kanriroku Tonegawa'), CONCAT('Chuukan Kanriroku Tonegawa is a spin-off of the Kaiji series, which follows Tonegawa, the right hand man of Kazutaka Hyoudou, the president of the Teiai Corporation and owner of numerous gambling tournaments. After Hyoudou is getting bored with his life, he orders Tonegawa to organize a so called "game of death" as it is his and his subordinate', CHAR(39), 's job to keep the president in a good mood. Tonegawa must cooperate with his subordinates in order to make the president happy and what follows is a humorous story of his interactions with his subordinates and other characters of the Kaiji series.<br>
<br>(Source: MAL News)'), 1, '2018-07-04', '2018-12-26', 'Summer 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1072/93145.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (159, 329, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (752, 329, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (753, 329, 6);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (367, 329, 21);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (345, 329, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (346, 329, 21);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (347, 329, 4);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5681, 329, 1, CONCAT('Initiative'), NULL, 'https://ebd.cda.pl/800x450/631333755');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5682, 329, 2, CONCAT('Conjecture'), NULL, 'https://ebd.cda.pl/620x395/634638550');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5683, 329, 3, CONCAT('Surefire'), NULL, 'https://ebd.cda.pl/620x395/65269675a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5684, 329, 4, CONCAT('Adult'), NULL, 'https://ebd.cda.pl/620x395/7733047e3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5685, 329, 5, CONCAT('Soul-Searching'), NULL, 'https://ebd.cda.pl/620x395/99270901f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5686, 329, 6, CONCAT('Self-Destruct'), NULL, 'https://ebd.cda.pl/620x395/9927084fb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5687, 329, 7, CONCAT('Proliferation'), NULL, 'https://streamtape.com/e/9v47a0G6BmFaaVA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5688, 329, 8, CONCAT('Shrimp'), NULL, 'https://streamtape.com/e/gqOAB3YawaCqW1p/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5689, 329, 9, CONCAT('Cutlets'), NULL, 'https://streamtape.com/e/G9jvaZkbOGH1xWM/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5690, 329, 10, CONCAT('Rehearsal'), NULL, 'https://streamtape.com/e/JwGPw8yxg0uj0q8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5691, 329, 11, CONCAT('Business Trip'), NULL, 'https://streamtape.com/e/OJp9RL6kRLsZMwd/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5692, 329, 12, CONCAT('Fake'), NULL, 'https://streamtape.com/e/7XDoRKYlY8hAk0V/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5693, 329, 13, CONCAT('Setting Sail'), NULL, 'https://streamtape.com/e/mL8yVXkL3Yhbx62/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5694, 329, 14, CONCAT('Excursion'), NULL, 'https://streamtape.com/e/17lLmzdmryUeoJv/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5695, 329, 15, CONCAT('Playing Hard'), NULL, 'https://streamtape.com/e/j4e63B9LrOFzllx/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5696, 329, 16, CONCAT('Natural Enemies'), NULL, 'https://streamtape.com/e/DP9jQgjKA1SAmy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5697, 329, 17, CONCAT('Unofficial Announcement'), NULL, 'https://streamtape.com/e/Bke360p2XXiyBqL/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5698, 329, 18, CONCAT('Alignment'), NULL, 'https://streamtape.com/e/ZXgRDd1ylRcPvG/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5699, 329, 19, CONCAT('Newcomers'), NULL, 'https://streamtape.com/e/4qQBq0mG9RTZPv/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5700, 329, 20, CONCAT('Entertaining'), NULL, 'https://streamtape.com/e/Qrv6jA9mDPf0ZRV/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5701, 329, 21, CONCAT('Defamation'), NULL, 'https://ebd.cda.pl/620x368/12404190d4');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5702, 329, 22, CONCAT('Conclusions'), NULL, 'https://streamtape.com/e/6e00aJkebOT9MxM/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5703, 329, 23, CONCAT('Premonition'), NULL, 'https://streamtape.com/e/X2voMaVwBqTDjaA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (5704, 329, 24, CONCAT('End of the Line'), NULL, 'https://streamtape.com/e/DMJbeWeQg3ikeQM/');
