INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (420, CONCAT('Diabolik Lovers'), CONCAT('At the behest of her father, Yui Komori goes to live in a secluded mansion, home to the six Sakamaki brothers—Shuu, Reiji, Ayato, Kanato, Laito, and Subaru—a family of vampires. Though at first the siblings are confused as to why the girl has arrived, they soon realize that she is to be their new "sacrificial bride," not to mention their other, more carnal intentions for her. After meeting the brothers, Yui quickly begins to question why her father would have sent her here and why she feels a strange, new pain in her chest. With each brother more sadistic than the last, Yui', CHAR(39), 's life as a captive takes a harrowing turn in her new home. As her days turn into endless nights, and each brother vows to make her his own, Yui falls deeper and deeper into madness and ecstasy.<br>
<br>[Written by MAL Rewrite]'), 1, '2013-09-16', '2013-12-09', 'Fall 2013', '15 min. per ep.', 'https://cdn.myanimelist.net/images/anime/9/51989.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (189, 420, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (470, 420, 44);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (450, 420, 47);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (451, 420, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (452, 420, 19);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7188, 420, 1, CONCAT('Untitled'), '2013-09-16', 'https://drive.google.com/file/d/0B9G2uaQXeK9ibm9sV0J5M1R4cjA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7189, 420, 2, CONCAT('Untitled'), '2013-09-23', 'https://vidoza.net/embed-3ii2gpql6n1s.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7190, 420, 3, CONCAT('Untitled'), '2013-09-30', 'https://drive.google.com/file/d/0B9G2uaQXeK9iNTUzbTFBUDlhVnM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7191, 420, 4, CONCAT('Untitled'), '2013-10-07', 'https://vk.com/video_ext.php?oid=217443577&id=166276419&hash=228f6a2a011c0bfd&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7192, 420, 5, CONCAT('Untitled'), '2013-10-14', 'https://video.sibnet.ru/shell.php?videoid=1291936');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7193, 420, 6, CONCAT('Untitled'), '2013-10-21', 'https://drive.google.com/file/d/0B8dxS7-Bdpk8VUxrNXU1azdPdGc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7194, 420, 7, CONCAT('Untitled'), '2013-11-04', 'https://vk.com/video_ext.php?oid=187929867&id=166906466&hash=dd4f15e8f79f2119&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7195, 420, 8, CONCAT('Untitled'), '2013-11-11', 'https://drive.google.com/file/d/0B04CCAR9rGZ2dXpsOVlqVHdqZHM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7196, 420, 9, CONCAT('Untitled'), '2013-11-18', 'https://drive.google.com/file/d/0B2Ems2SRGYoaT0tBT1BLcGhkTFU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7197, 420, 10, CONCAT('Untitled'), '2013-11-25', 'https://mp4upload.com/embed-cqbkj0m6b8vb.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7198, 420, 11, CONCAT('Untitled'), '2013-12-02', 'https://drive.google.com/file/d/0B2Ems2SRGYoaU3cwVUxYcE9weUU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7199, 420, 12, CONCAT('Untitled'), '2013-12-09', 'https://mp4upload.com/embed-7aqyscndao8r.html');
