INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (423, CONCAT('Dies Irae: To the Ring Reincarnation'), CONCAT('Episodes 12–17 of Dies Irae released exclusively on the web.'), 1, '2018-07-01', NULL, '', '28 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1244/93395.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (995, 423, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (996, 423, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (997, 423, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (475, 423, 119);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (457, 423, 20);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (458, 423, 45);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7327, 423, 1, CONCAT('Emanation Level'), NULL, 'https://ebd.cda.pl/800x450/5072285d2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7328, 423, 2, CONCAT('Gladsheim'), NULL, 'https://ebd.cda.pl/800x450/507266944');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7329, 423, 3, CONCAT('Golden Alchemy'), NULL, 'https://ebd.cda.pl/800x450/5072807d6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7330, 423, 4, CONCAT('Valhalla Emanation'), NULL, 'https://drive.google.com/file/d/1Oi13Ot8KDm2m-S4dbH-FoswYCZOtJ3ut/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7331, 423, 5, CONCAT('Verweile Doch'), NULL, 'https://drive.google.com/file/d/1-75-BRANO8MFq9j8s-zakAmmmNmeYhSB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7332, 423, 6, CONCAT('To the New World'), NULL, 'https://ebd.cda.pl/800x450/50733775a');
