INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (437, CONCAT('Do It Yourself!!'), CONCAT('The Fourth Industrial Revolution has led to the development of cutting-edge technologies that have rapidly evolved the world. As a result, schools have begun incorporating these technologies into their curriculum, leaving behind the ways of the old. One such institution is the elite Yuyu Girls', CHAR(39), ' Vocational High School, where both Serufu Yua and her childhood friend, Miku "Purin" Suride, have applied. Although the tech-savvy Purin is accepted to Yuyu High, the accident-prone Serufu is rejected and enters the traditional Gatagata Girls', CHAR(39), ' High School instead, driving a wedge into their friendship.<br>
<br>On her way to class one day, Serufu gets into a bike accident, and Rei Yasaku, a passerby, fixes her damaged bicycle. Serufu later finds out that Rei has a passion for old-fashioned crafts and is the head of the school', CHAR(39), 's Do-It-Yourself (DIY) Club—which is in danger of closing due to a lack of members.<br>
<br>Realizing that this may be her chance to repair her relationship with Purin, Serufu joins the club in hopes of creating projects that could bring them together once more. As the DIY Club welcomes new faces, Serufu learns to build not only handicrafts but also new friendships along the way!<br>
<br>[Written by MAL Rewrite]'), 1, '2022-10-06', NULL, 'Fall 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1408/127129.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1050, 437, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1051, 437, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (489, 437, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7779, 437, 1, CONCAT('What is DIY?'), '2022-10-06', 'https://drive.google.com/file/d/1ZQ_S_UuzewoTuO8ZU8YXRcDEkSnyh0fs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7780, 437, 2, CONCAT('Does "DIY" Mean Doing Stuff With Somebody?'), '2022-10-13', 'https://video.sibnet.ru/shell.php?videoid=4919888');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7781, 437, 3, CONCAT('Does "DIY" Mean Why Did You Suddenly Show Up?'), '2022-10-20', 'https://drive.google.com/file/d/1ww1LtbR6shw3y2WTfyGhtmGElo_U_NZ2/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7782, 437, 4, CONCAT('"DIY" Means You', CHAR(39), 'll Find It Possible to Feel Comfortable Anywhere'), '2022-10-27', 'https://drive.google.com/file/d/1QZyKW3AZgFDXftFFk_-kLc0TTpG9hSZb/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (7783, 437, 5, CONCAT('"DIY" Means Finding a Place to Belong... Finally'), '2022-11-03', 'https://ebd.cda.pl/620x368/12385869ce');
