INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (458, CONCAT('Dragon Drive'), CONCAT('If there', CHAR(39), 's one word to describe Reiji Ozora, it would be "quitter." He can never find the motivation to finish anything, and loses interest at the drop of a hat. This all changes when his best friend Maiko introduces him to the new game "Dragon Drive."<br>
<br>In this virtual reality game, each player is assigned a dragon tailored to match their personality and strength. Reiji hopes for a big, strong, scary beast, but instead, he is stuck with Chibi, a cute, friendly-looking dragon smaller than he is. How disappointing—except it turns out that Chibi is the rarest dragon of them all!<br>
<br>Reiji finally discovers something he can remain interested in, and works hard to train both himself and his newfound friend. Soon this training will be put to use to save the world, for there are people who have dark aspirations for Dragon Drive!'), 1, '2002-07-04', '2003-03-27', 'Summer 2002', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1/2214.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (211, 458, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1119, 458, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1120, 458, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1121, 458, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1122, 458, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (511, 458, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (492, 458, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (493, 458, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8256, 458, 1, CONCAT('The Sleeping Dragon'), '2002-07-04', 'https://www.mp4upload.com/embed-7959d0phdj64.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8257, 458, 2, CONCAT('Dive of Promise'), '2002-07-11', 'https://www.mp4upload.com/embed-0calv89n2jtl.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8258, 458, 3, CONCAT('Revenge'), '2002-07-18', 'https://www.mp4upload.com/embed-qo4pg3mrsyy9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8259, 458, 4, CONCAT('An Awakening from the Impact'), '2002-07-25', 'https://www.mp4upload.com/embed-qluvtfp9qxt6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8260, 458, 5, CONCAT('Inside out Sphere'), '2002-08-01', 'https://www.mp4upload.com/embed-rwjbljsultey.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8261, 458, 6, CONCAT('The Successor'), '2002-08-08', 'https://www.mp4upload.com/embed-vxkgc66dmp6l.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8262, 458, 7, CONCAT('Dragonic Heaven'), '2002-08-15', 'https://www.mp4upload.com/embed-xioeujclg2sd.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8263, 458, 8, CONCAT('The Beginning of a Battle'), '2002-08-22', 'https://www.mp4upload.com/embed-3ejh8v2eirte.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8264, 458, 9, CONCAT('The Place of Anger'), '2002-08-29', 'https://www.mp4upload.com/embed-kjxdzsz9pvwi.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8265, 458, 10, CONCAT('Proof of Trust'), '2002-09-05', 'https://www.mp4upload.com/embed-4x05mpp55am8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8266, 458, 11, CONCAT('Like Yourself'), '2002-09-12', 'https://www.mp4upload.com/embed-f8664i6zdmyg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8267, 458, 12, CONCAT('Gathering'), '2002-09-19', 'https://www.mp4upload.com/embed-v2rro5d8l33w.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8268, 458, 13, CONCAT('The Mission'), '2002-09-26', 'https://www.mp4upload.com/embed-oz6dj9ds5ira.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8269, 458, 14, CONCAT('A Winner and a Loser'), '2002-10-03', 'https://www.mp4upload.com/embed-t28tjwqugpsr.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8270, 458, 15, CONCAT('Last Night'), '2002-10-10', 'https://www.mp4upload.com/embed-p8w99ahdlrjz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8271, 458, 16, CONCAT('Robbery'), '2002-10-17', 'https://www.mp4upload.com/embed-3cplqywx5uhh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8272, 458, 17, CONCAT('The Extremity of Revenge'), '2002-10-24', 'https://www.mp4upload.com/embed-ccfqr71fu8ru.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8273, 458, 18, CONCAT('Journey'), '2002-10-31', 'https://www.mp4upload.com/embed-izpjj44ycllj.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8274, 458, 19, CONCAT('Rebirth'), '2002-11-07', 'https://www.mp4upload.com/embed-lauf4hr4159a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8275, 458, 20, CONCAT('Travel of Ordeals'), '2002-11-14', 'https://www.mp4upload.com/embed-g64fzlpaas1k.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8276, 458, 21, CONCAT('To The Legendary Mountain'), '2002-11-21', 'https://www.mp4upload.com/embed-qemr0hrybags.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8277, 458, 22, CONCAT('Berserk'), '2002-11-28', 'https://www.mp4upload.com/embed-7uau1vo4tgc2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8278, 458, 23, CONCAT('Shinseiber'), '2002-12-05', 'https://www.mp4upload.com/embed-v9r88mxiwmhs.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8279, 458, 24, CONCAT('In Return for the Power'), '2002-12-12', 'https://www.mp4upload.com/embed-9d3ccvwc92dp.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8280, 458, 25, CONCAT('Mysterious Warrior'), '2002-12-19', 'https://www.mp4upload.com/embed-fxghw01vj61v.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8281, 458, 26, CONCAT('A Friends Shadow'), '2002-12-26', 'https://www.mp4upload.com/embed-ht3qavka6t75.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8282, 458, 27, CONCAT('Eternal Life'), '2003-01-09', 'https://www.mp4upload.com/embed-xjr9y0k5xx6w.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8283, 458, 28, CONCAT('Memory'), '2003-01-16', 'https://www.mp4upload.com/embed-4pe1euflrkit.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8284, 458, 29, CONCAT('Young Boy'), '2003-01-23', 'https://www.mp4upload.com/embed-yjkh72ubtzb2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8285, 458, 30, CONCAT('Betrayal'), '2003-01-30', 'https://www.mp4upload.com/embed-4afum2kecl43.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8286, 458, 31, CONCAT('The Four Sacred Dragons'), '2003-02-06', 'https://www.mp4upload.com/embed-d74wycfr2n6n.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8287, 458, 32, CONCAT('Rival'), '2003-02-13', 'https://www.mp4upload.com/embed-0eproipdq6cw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8288, 458, 33, CONCAT('Dark Labyrinth'), '2003-02-20', 'https://www.mp4upload.com/embed-dlqfech95ssw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8289, 458, 34, CONCAT('Truth'), '2003-02-27', 'https://www.mp4upload.com/embed-w0j3so5na1jd.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8290, 458, 35, CONCAT('D Zone'), '2003-03-06', 'https://www.mp4upload.com/embed-nu9lsqied6i8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8291, 458, 36, CONCAT('Return'), '2003-03-13', 'https://www.mp4upload.com/embed-k91bz23tnw4g.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8292, 458, 37, CONCAT('Shinryuu'), '2003-03-20', 'https://www.mp4upload.com/embed-263lpvs338m2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (8293, 458, 38, CONCAT('D-Break!'), '2003-03-27', 'https://www.mp4upload.com/embed-298m3y7kgfna.html');
