INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (510, CONCAT('Fantasy Bishoujo Juniku Ojisan to'), CONCAT('Since their days as students, Tsukasa Jinguuji has had incredible luck with women due to his good looks Hinata Tachibana has had almost none, overshadowed by Jinguuji', CHAR(39), 's brilliance. However, while Jinguuji has never shown interest in the opposite sex, Tachibana is always desperate for a girlfriend. Despite their polar differences, they continue to be best friends even in their thirties as salarymen. <br>
<br>One night, the two are returning home from a mixer where Jinguuji was the center of attention as usual. In his drunken rambles, a frustrated Tachibana inadvertently wishes to become a beautiful girl with irresistible charm. As if the heavens were listening, a goddess suddenly shows herself before Jinguuji and Tachibana, transporting them to another world to defeat the Demon Lord and simultaneously granting Tachibana', CHAR(39), 's desire.<br>
<br>Tachibana—now in the body of an impossibly perfect woman—has become so attractive that even Jinguuji is captivated. Moreover, Tachibana grows aware of Jinguuji', CHAR(39), 's stunning appearance, finally understanding his popularity. Before they fall in love with each other, the duo must complete their mission or risk remaining prisoners to their infatuations forever.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-01-12', '2022-03-30', 'Winter 2022', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1430/120065.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1260, 510, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1261, 510, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (570, 510, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9421, 510, 1, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and Another Guy'), '2022-01-12', 'https://drive.google.com/file/d/1moVWHNO5t2bww-d1nws2VdWjUlAej4Zq/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9422, 510, 2, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and Unparalleled Beauty'), '2022-01-19', 'https://drive.google.com/file/d/13PEIrf2zHfmtpAYWYhwE2ZqdWJ-fFMAa/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9423, 510, 3, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and an Angry Elf'), '2022-01-26', 'https://drive.google.com/file/d/1x_uBiOER10Zl7aspVNji5pjxRD8_qvNN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9424, 510, 4, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Dark Swordsman'), '2022-02-02', 'https://drive.google.com/file/d/1-aUJASpOVVxTj4xVbBupwd_0xqoO5Q96/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9425, 510, 5, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and Armor that Moves'), '2022-02-09', 'https://drive.google.com/file/d/1vt17fayQLtG9UmFOWIiEh1bYh6zmjU-k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9426, 510, 6, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Free Spirit'), '2022-02-16', 'https://video.sibnet.ru/shell.php?videoid=4606169');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9427, 510, 7, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Squid Fire'), '2022-02-23', 'https://video.sibnet.ru/shell.php?videoid=4615855');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9428, 510, 8, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Choice'), '2022-03-02', 'https://video.sibnet.ru/shell.php?videoid=4623261');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9429, 510, 9, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Beautiful Girl'), '2022-03-09', 'https://video.sibnet.ru/shell.php?videoid=4630071');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9430, 510, 10, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Rebel Army'), '2022-03-16', 'https://video.sibnet.ru/shell.php?videoid=4637887');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9431, 510, 11, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and a Weapon for the Final Battle'), '2022-03-23', 'https://mixdrop.co/e/84xpgr41s74nxx');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (9432, 510, 12, CONCAT('A Guy Who Reincarnated as a Fantasy Knockout and'), '2022-03-30', 'https://dood.ws/e/46sdamhg0e69udqgkvsbszxwovttsubb');
