INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (577, CONCAT('Garo: Guren no Tsuki'), CONCAT('Monsters known as "Horrors" have invaded the world, entering through gates from the Makai Realm of Darkness. These corrupt, demonic creatures have the ability to seize human bodies and feed on their souls. Citizens who are out past sunset will likely never see the sun rise again, but those who live in the capital city have no need to worry—they are protected by a spiritual force field created by the sorcerer group Onmyouji.<br>
<br>In possession of legendary armor, the Golden Knight Raikou proclaims that he will protect everyone from the Horrors. Accompanied by his attendant Kintoki and the mysterious Makai Alchemist Seimei, he strives to become a formidable Makai Knight, but Raikou is ill-prepared to handle the side effects of the armor. Disappointed by his own shortcomings, he sets out on a journey of self-discovery to master his weaknesses and prove his worth.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2015-10-10', '2016-04-02', 'Fall 2015', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/76029.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (644, 577, 63);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10598, 577, 1, CONCAT('ONMYOU'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1944787');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10599, 577, 2, CONCAT('TIED SWORD'), NULL, 'https://video.sibnet.ru/shell.php?videoid=2052289');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10600, 577, 3, CONCAT('CURSE'), NULL, 'https://embed.tune.pk/play/6423663');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10601, 577, 4, CONCAT('KAGUYA'), NULL, 'https://embed.tune.pk/play/6431568');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10602, 577, 5, CONCAT('HAKAMADARE'), NULL, 'https://mp4upload.com/embed-ylc26mj7pkh8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10603, 577, 6, CONCAT('LURKING DEMON'), NULL, 'https://www.kreskoweczki.pl/kreskowka/90800/garo-guren-no-tsuki_odcinek-6/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10604, 577, 7, CONCAT('MOTHER DAUGHTER'), NULL, 'https://www.kreskoweczki.pl/kreskowka/90801/garo-guren-no-tsuki_odcinek-7/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10605, 577, 8, CONCAT('BROTHERS'), NULL, 'https://www.kreskoweczki.pl/kreskowka/90802/garo-guren-no-tsuki_odcinek-8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10606, 577, 9, CONCAT('SHINE AND RUIN'), NULL, 'https://www.kreskoweczki.pl/kreskowka/90803/garo-guren-no-tsuki_odcinek-9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10607, 577, 10, CONCAT('1/10TH'), NULL, 'https://www.kreskoweczki.pl/kreskowka/90804/garo-guren-no-tsuki_odcinek-10/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10608, 577, 11, CONCAT('ZANGA'), NULL, 'https://embed.tune.pk/play/6508760');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10609, 577, 12, CONCAT('CONFLICT'), NULL, 'https://www.bitporno.com/embed/ddoEmmju');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10610, 577, 13, CONCAT('SEIMEI'), NULL, 'https://www.mp4upload.com/embed-lphx7na6z9nf.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10611, 577, 14, CONCAT('SOUL MOON'), NULL, 'https://vk.com/video_ext.php?oid=250023721&id=456239068&hash=d90b505d2406a3f6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10612, 577, 15, CONCAT('WORST'), NULL, 'https://vk.com/video_ext.php?oid=172567157&id=456239455&hash=9e538eef4d4e8ce2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10613, 577, 16, CONCAT('SINISTER EVIL'), NULL, 'https://vk.com/video_ext.php?oid=172567157&id=456239456&hash=f4906ea5ea53ecf2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10614, 577, 17, CONCAT('EXTINGUISHED STAR'), NULL, 'https://tune.pk/video/6582200');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10615, 577, 18, CONCAT('FRENZY'), NULL, 'https://vk.com/video_ext.php?oid=315864967&id=456239075&hash=659c17b0c0c80080');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10616, 577, 19, CONCAT('VESSEL'), NULL, 'https://myvi.ru/player/embed/html/ojvB7tjN_ytzo0_uitMq-qk2B6ICAykdfqy-RP6nnreBEJxOO9-aUbnz46m0H7Sis0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10617, 577, 20, CONCAT('DUEL'), NULL, 'https://myvi.ru/player/embed/html/oGfowPtg3FJ3MwAlqOpdE7lNNCd2dDMxcE-hKTS-gvOryXKYBlW9o_jBqIcLRZk2v0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10618, 577, 21, CONCAT('RESONANCE'), NULL, 'https://tune.pk/video/6632376');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10619, 577, 22, CONCAT('RUDRA'), NULL, 'https://embed.tune.pk/play/6662468');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (10620, 577, 23, CONCAT('ASSAULT MOON'), NULL, 'https://embed.tune.pk/play/7417951');
