INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (639, CONCAT('Gosick'), CONCAT('Kazuya Kujou is a foreign student at Saint Marguerite Academy, a luxurious boarding school in the Southern European country of Sauville. Originally from Japan, his jet-black hair and dark brown eyes cause his peers to shun him and give him the nickname "Black Reaper," based on a popular urban legend about the traveler who brings death in the spring.<br>
<br>On a day like any other, Kujou visits the school', CHAR(39), 's extravagant library in search of ghost stories. However, his focus soon changes as he becomes curious about a golden strand of hair on the stairs. The steps lead him to a large garden and a beautiful doll-like girl known as Victorique de Blois, whose complex and imaginative foresight allows her to predict their futures, now intertwined.<br>
<br>With more mysteries quickly developing—including the appearance of a ghost ship and an alchemist with the power of transmutation—Victorique and Kujou, bound by fate and their unique skills, have no choice but to rely on each other.<br>
<br>[Written by MAL Rewrite]'), 1, '2011-01-08', '2011-07-02', 'Winter 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/27906.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1581, 639, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1582, 639, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1583, 639, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (711, 639, 77);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11603, 639, 1, CONCAT('The Dark Reaper Finds the Golden Fairy'), '2011-01-08', 'https://drive.google.com/file/d/0B6BWr4iAdBLkWUFuMUNSR2NzOU0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11604, 639, 2, CONCAT('The Souls of the Dead Raise a Shipwreck'), '2011-01-15', 'https://drive.google.com/file/d/0B6BWr4iAdBLka25vSktadl9uOWM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11605, 639, 3, CONCAT('The Hares Break a Promise Under the Morning Sun'), '2011-01-22', 'https://drive.google.com/file/d/0B6BWr4iAdBLkX2VBaVRibVBzUEE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11606, 639, 4, CONCAT('The Golden Thread Cuts Through a Passing Moment'), '2011-01-29', 'https://drive.google.com/file/d/0B6BWr4iAdBLkS1ZrVXowcW1XeFE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11607, 639, 5, CONCAT('There', CHAR(39), 's a Mysterious Ghost in the Abandoned Storehouse'), '2011-02-05', 'https://drive.google.com/file/d/0B6BWr4iAdBLkSjFOb1hrSHlqZms/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11608, 639, 6, CONCAT('The Gray Wolves Summon Their Brethren'), '2011-02-12', 'https://drive.google.com/file/d/0B6BWr4iAdBLkQVd4ODVRNGJ6MFE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11609, 639, 7, CONCAT('A Divine Revelation is Given at the Summer Solstice Festival'), '2011-02-19', 'https://drive.google.com/file/d/0B6BWr4iAdBLkOVRGU3dhdV9pM3M/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11610, 639, 8, CONCAT('Howling Echoes from the Kingdom of the Past'), '2011-02-26', 'https://drive.google.com/file/d/0B6BWr4iAdBLkRGJWbHRFRDJxWFU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11611, 639, 9, CONCAT('Blue Roses Bloom in the Cannibal Department Store'), '2011-03-05', 'https://drive.google.com/file/d/0B6BWr4iAdBLkS3dIX3M0enRpQTA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11612, 639, 10, CONCAT('Girl with a Cold Dreams of Her Stubborn Friend'), '2011-03-12', 'https://drive.google.com/file/d/0B6BWr4iAdBLkOTd5c3liX0E1S2M/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11613, 639, 11, CONCAT('That Drill Eloquently Speaks of Love'), '2011-04-02', 'https://drive.google.com/file/d/0B6BWr4iAdBLkN0U4NlY1ejhTQ2s/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11614, 639, 12, CONCAT('The Cicadas are Heard on Summer Afternoons'), '2011-04-09', 'https://drive.google.com/file/d/0B6BWr4iAdBLkUmpvcVJEQXNWUFE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11615, 639, 13, CONCAT('A Fool Designates His Own Spokesperson'), '2011-04-16', 'https://drive.google.com/file/d/0B6BWr4iAdBLkLVVFelpITUR5OFE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11616, 639, 14, CONCAT('A Malicious Frill Denounces a Farting Newt'), '2011-04-23', 'https://drive.google.com/file/d/0B6BWr4iAdBLkUE9fVmFZLXo2LTQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11617, 639, 15, CONCAT('Two Monsters Know Each Others', CHAR(39), ' Hearts'), '2011-04-30', 'https://drive.google.com/file/d/0B6BWr4iAdBLkbEtsbUJMS1hOT0U/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11618, 639, 16, CONCAT('The Felling Maria Has the Head of a Fly'), '2011-05-07', 'https://drive.google.com/file/d/0B6BWr4iAdBLkc3Z6QWFQTGZYeUU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11619, 639, 17, CONCAT('The Box Lies in the Spiral Labyrinth'), '2011-05-14', 'https://drive.google.com/file/d/0B6BWr4iAdBLkUnE0SXoxRVZBbWc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11620, 639, 18, CONCAT('The Jet-Black Train Carries Several Lies'), '2011-05-21', 'https://drive.google.com/file/d/0B6BWr4iAdBLkY1JLUW9XNkU0WkE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11621, 639, 19, CONCAT('The Rosy Life is Buried Under a New Snow'), '2011-05-28', 'https://drive.google.com/file/d/0B6BWr4iAdBLkaEFmS19WREZ6clk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11622, 639, 20, CONCAT('Guided by the Phantom of the Phantom'), '2011-06-04', 'https://drive.google.com/file/d/0B6BWr4iAdBLkRVRXTlptRjVZLXc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11623, 639, 21, CONCAT('The Holy Night Bell Drives the Hour Onward'), '2011-06-11', 'https://drive.google.com/file/d/0B6BWr4iAdBLkZVFJNGFPck1HRWs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11624, 639, 22, CONCAT('A Christmas Carol Hangs Happiness by the Window'), '2011-06-18', 'https://drive.google.com/file/d/0B6BWr4iAdBLkT2lTS2tZNFl0S28/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11625, 639, 23, CONCAT('Checkmate is Called on a Gray Chess Board'), '2011-06-25', 'https://drive.google.com/file/d/0B6BWr4iAdBLkaVFvNm1pcE9CRzg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (11626, 639, 24, CONCAT('Eternity is Seen Over the Reaper', CHAR(39), 's Shoulder'), '2011-07-02', 'https://drive.google.com/file/d/0B6BWr4iAdBLkQk5CZFMwSG9ObFk/preview');
