INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (700, CONCAT('Hakyuu Houshin Engi'), CONCAT('When his clan is wiped out by a beautiful demon, young Taikobo finds himself in charge of the mysterious Houshin Project. Its mission: find all immortals living in the human world and seal them away forever. But who do you trust—and whose side are you really on—when you', CHAR(39), 've been trained to hunt demons by a demon?<br>
<br>(Source: VIZ Media)'), 1, '2018-01-12', '2018-06-29', 'Winter 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/11/88796.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (321, 700, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1718, 700, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1719, 700, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1720, 700, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (774, 700, 165);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12661, 700, 1, CONCAT('The Hoshin List'), NULL, 'https://vidoza.net/qvtag8i3k6kn');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12662, 700, 2, CONCAT('Nataku'), NULL, 'https://vidoza.net/embed-gcj97fq7vfkb.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12663, 700, 3, CONCAT('Yozen'), NULL, 'https://vidoza.net/embed-fbriz0cgiv3q.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12664, 700, 4, CONCAT('The Buseioh', CHAR(39), 's Rebellion'), NULL, 'https://rapidvideo.com/e/FXAD8CNBU1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12665, 700, 5, CONCAT('Two Paths'), NULL, 'https://www.mp4upload.com/embed-aszkm0op9f18.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12666, 700, 6, CONCAT('The Curtain Falls on the Aging Wise Man'), NULL, 'https://www.mp4upload.com/embed-n9md88bsmr9s.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12667, 700, 7, CONCAT('The Great Sennin World War Begins!!'), NULL, 'https://www.mp4upload.com/embed-dk44m2isnkzz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12668, 700, 8, CONCAT('The Juzetsujin Battle'), NULL, 'https://rapidvideo.com/e/FXII1FLLW7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12669, 700, 9, CONCAT('Concentration'), NULL, 'https://rapidvideo.com/e/FXKHZ4PVFW');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12670, 700, 10, CONCAT('Rain of Blood'), NULL, 'https://tune.pk/video/8120622');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12671, 700, 11, CONCAT('Insect'), NULL, 'https://tune.pk/video/8120707');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12672, 700, 12, CONCAT('New Romantic'), NULL, 'https://rapidvideo.com/e/FXPIGSLRGI');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12673, 700, 13, CONCAT('Mirror'), NULL, 'https://rapidvideo.com/e/FXUDL7XVVW');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12674, 700, 14, CONCAT('Parasite'), NULL, 'https://tune.pk/video/8129186');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12675, 700, 15, CONCAT('Shadow / Light'), NULL, 'https://vidoza.net/1j1c8xwzbizd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12676, 700, 16, CONCAT('Tsuten Kyoshu'), NULL, 'https://vidoza.net/embed-jnon0g9usoo3.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12677, 700, 17, CONCAT('Fugen Shinjin'), NULL, 'https://vidoza.net/embed-ksdd5syka910.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12678, 700, 18, CONCAT('Battle to the Death'), NULL, 'https://tune.pk/video/8138190');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12679, 700, 19, CONCAT('Bunchu'), NULL, 'https://www.mp4upload.com/embed-n13e2uzr439v.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12680, 700, 20, CONCAT('When the Stars Rain Down'), NULL, 'https://www.mp4upload.com/embed-6ezohbwxnm8o.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12681, 700, 21, CONCAT('Blinding Light, Deafening Silence, and Then...'), NULL, 'https://vidoza.net/embed-n2k1njb0me0u.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12682, 700, 22, CONCAT('The Brave Warrior', CHAR(39), 's Soul Is Released'), NULL, 'https://vidoza.net/embed-nwuonha1eifx.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (12683, 700, 23, CONCAT('Aged Symbols and Diverging Winds'), NULL, 'https://vidoza.net/embed-i7lylwsxrdjg.html');
