INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (781, CONCAT('Hitsugi no Chaika'), CONCAT('For 500 years, the Taboo Emperor, Arthur Gaz, ruled the Gaz Empire with an iron fist and conducted inhumane experiments on his own people. But his reign came to an end five years ago, when mighty warriors—later known as the Eight Heroes—defeated him in a battle for the capital. His death ended the 300-yearlong war between the Gaz Empire and the alliance of six nations.<br>
<br>In the present day, Tooru Acura is a former saboteur from the war who has difficulty settling into the peaceful world, as he cannot find a job where he can put his fighting skills to use. An opportunity appears before him, however, when he meets a white-haired Wizard named Chaika Trabant. With a coffin on her back, she is searching for the scattered remains of her father in order to give him a proper burial, and she hires Tooru and his adoptive sister Akari to help her. However, the six nations alliance, which have now formed the Council of Six Nations, dispatches Albéric Gillette and his men from the Kleeman Agency to pursue and apprehend the late Emperor Gaz', CHAR(39), 's daughter—Chaika.<br>
<br>With the shocking revelation of Chaika', CHAR(39), 's identity, the Acura siblings must choose between helping her gather the remains of the tyrannical emperor and upholding the peace the continent strives to maintain.<br>
<br>[Written by MAL Rewrite]'), 1, '2014-04-10', '2014-06-26', 'Spring 2014', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/61781.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1922, 781, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1923, 781, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1924, 781, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1925, 781, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1926, 781, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (857, 781, 77);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14018, 781, 1, CONCAT('The Girl who Bears the Coffin'), '2014-04-10', 'https://drive.google.com/file/d/1YGkCemjE7nGKlrb-MoCkFe0ouuWZj1R-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14019, 781, 2, CONCAT('The Lazy Man', CHAR(39), 's Choice'), '2014-04-17', 'https://drive.google.com/file/d/1UvJ91D83fowsYxOZCftk3oAfYkHOvQUt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14020, 781, 3, CONCAT('The Forest Where the Hero Lives'), '2014-04-24', 'https://drive.google.com/file/d/17DpJLtnbIhhjhIHf4g_w6h32NrklIzYh/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14021, 781, 4, CONCAT('The Dragoon', CHAR(39), 's Wish'), '2014-05-01', 'https://drive.google.com/file/d/1irPip9pvuSqMdDoPEC3NzAIDinOCHyDE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14022, 781, 5, CONCAT('The Pursuer and the Pursued'), '2014-05-08', 'https://drive.google.com/file/d/1QhbRlwoStIAGK91mMHJNEr26sWXcexYi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14023, 781, 6, CONCAT('Red and White'), '2014-05-15', 'https://drive.google.com/file/d/1RhL9UQ-nxT7Q5hBKB2FkbTQpA6ukpYPK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14024, 781, 7, CONCAT('The Valley of No Return'), '2014-05-22', 'https://drive.google.com/file/d/0ByRHoFS6b0rRWWJfY0h1Y1FCRVE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14025, 781, 8, CONCAT('Empire of Consolation'), '2014-05-29', 'https://drive.google.com/file/d/1NVuKVDYH22lha8CQTkEs9x525x4L1Pwr/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14026, 781, 9, CONCAT('The Value of Memories'), '2014-06-05', 'https://drive.google.com/file/d/1XJ61HahZAdVxffvrxB_H5yRKZvWA1GCg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14027, 781, 10, CONCAT('Fortress in the Sky'), '2014-06-12', 'https://drive.google.com/file/d/1LJcEyobnzxScfzu_nY9H9Q0pvLlGJxoD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14028, 781, 11, CONCAT('The False Princess'), '2014-06-19', 'https://drive.google.com/file/d/1G3rEVycR9inDbWBJn-grYYyMo-Wqh1Bd/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14029, 781, 12, CONCAT('Those Left Behind'), '2014-06-26', 'https://drive.google.com/file/d/1opF39LQp0CVkdLZD7yB57D7JGsXdloMA/preview');
