INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (789, CONCAT('Hoozuki no Reitetsu'), CONCAT('Hell is a bureaucracy, and business is running smoother than ever thanks to the demonic efficiency of Hoozuki, chief deputy to Lord Enma, the King of Hell. Whether offering counsel to the Momotarou of Japanese folklore or receiving diplomatic missions from the Judeo-Christian Hell, the demon who runs the show from behind the king', CHAR(39), 's imposing shadow is ready to beat down any challenges coming his way into a bloody pulp. Metaphorically, of course...<br>
<br>The poster boy for micromanagement and armed with negotiation skills worthy of Wall Street, Hoozuki no Reitetsu follows the sadistic and level-headed Hoozuki as he spends his days troubleshooting hell. With an abundance of familiar faces from popular Japanese legends and East Asian mythology working middle management positions, this referential and anachronistic dark comedy brings new meaning to the phrase "employer liability." Just how hard could it be to manage employees from hell, anyway?<br>
<br>[Written by MAL Rewrite]'), 1, '2014-01-10', '2014-04-04', 'Winter 2014', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/87177.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (357, 789, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1936, 789, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1937, 789, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (1938, 789, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (866, 789, 158);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14131, 789, 1, CONCAT('"Making or Breaking Hell" and "The Discovery of Hell', CHAR(39), 's Mysteries"'), NULL, 'https://drive.google.com/file/d/0B5-MnnU6QEhhNk00cUJqUTJwZzQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14132, 789, 2, CONCAT('"Demons and Underwear and Crabs" and "The State of Hell, and This and That"'), NULL, 'https://drive.google.com/file/d/0B5-MnnU6QEhhYXhaVVA0QVJFUnM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14133, 789, 3, CONCAT('"Hakutaku" and "How their discord came to be"'), NULL, 'https://drive.google.com/file/d/0BxjakHSDvXtQSVpJdEdrX3VvVzg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14134, 789, 4, CONCAT('"Pretty boys need love too" and "Kajika Hell"'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1387241');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14135, 789, 5, CONCAT('"The Instrumental Duo of the Mighty Rivals" and "Mental Sports Day"'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1380373');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14136, 789, 6, CONCAT('"Hell Idol: Peach Make" and "The Right Arm Blues"'), NULL, 'https://drive.google.com/file/d/0B9qUInowzwm9VllFZUxSRVpfYjQ/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14137, 789, 7, CONCAT('"Man and Woman and Mortal Hell" \ "Hell-Style Acupunture and Moxibustion Techniques" \ "How-to use the Johari Mirror"'), NULL, 'https://ebd.cda.pl/800x450/5647901dc');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14138, 789, 8, CONCAT('"The Vulgar Battle" and "The 36 Views of Hell"'), NULL, 'https://vk.com/video_ext.php?oid=239953690&id=167711935&hash=cfe99ea971e5195a&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14139, 789, 9, CONCAT('"The Ultimate Example of Ruin Through Wine and Women" and "Awash with Drunks"'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1414366');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14140, 789, 10, CONCAT('"Dinner of the Ten Kings of the Afterlife" and "Diets are Hell"'), NULL, 'https://vk.com/video_ext.php?oid=239953690&id=167796761&hash=41ff68f805d74120&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14141, 789, 11, CONCAT('"The Samurai Who was Inch High" and "Marsh Sisters on the Mountain"'), NULL, 'https://drive.google.com/file/d/0B7AYcYZOOfI6T1dtRHpiRnduTmc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14142, 789, 12, CONCAT('"Lady Lilith and her Husband" and "Why Monsters are so Widely Spread Throughout the Mundane World of China"'), NULL, 'https://drive.google.com/file/d/0B7AYcYZOOfI6TDcwRE1ITFVDMzA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14143, 789, 13, CONCAT('"Hell', CHAR(39), 's Bon Festival of Lights" and "Idle Chat with the Great King Enma"'), NULL, 'https://drive.google.com/file/d/0B3g2KqMctI9qb05JQ3lWTXZoWTA/preview');
