INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (836, CONCAT('Ikkitousen: Dragon Destiny'), CONCAT('The fierce confrontation among the Kanto high schools reaches new heights with the awakening of dragons in the Kyousho and Seito Academy', CHAR(39), 's leaders, Moutoku Sousou and Gentoku Ryuubi. However, the power balance between these two institutions and their main opponent, Nanyo Academy, is jeopardized when Shimei Ryomou seizes a mysterious dragon orb in China. It is said that the orb grants its strength to a dragon wielder, and Shimei hopes to save Nanyo Academy', CHAR(39), 's leader Hakufu Sonsaku from the adverse effects of her unstable gift.<br>
<br>Meanwhile, Moutoku', CHAR(39), 's powers completely consume him, and he loses control over his own body to the Demon King', CHAR(39), 's soul, whose unlimited ambitions endanger the stability of the region and the safety of his allies. In the face of growing tensions to claim the dragon orb, Hakufu and Gentoku will have to put aside their differences and work together to thwart Moutoku', CHAR(39), 's demonic plans.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2007-02-26', '2007-05-14', 'Winter 2007', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/85202.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2023, 836, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2024, 836, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (917, 836, 129);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (930, 836, 24);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (931, 836, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (932, 836, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14950, 836, 1, CONCAT('Signs of the Dragon Spirit'), '2007-02-26', 'https://myvi.ru/player/embed/html/omKLZqRUEevRD_1r4yhjXwvBDZtUSesKLhIUmR3dPsJY1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14951, 836, 2, CONCAT('The Evil Lord Awakens'), '2007-03-05', 'https://video.sibnet.ru/shell.php?videoid=1247575');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14952, 836, 3, CONCAT('Bloodshed and Tears'), '2007-03-12', 'https://myvi.ru/player/embed/html/olAgFabOBUsV8olzCu10nmH3s5svsSU2h_Ruk3WKiU7fBWtMEVElE1I2szxRj1qLMdOAYGSbtb8c1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14953, 836, 4, CONCAT('Chance Meeting of the Two Dragons'), '2007-03-19', 'https://myvi.ru/player/embed/html/o46ltLSadcXbn9d6sIx6VQ92ENNe8S2digNTpXBQm4841');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14954, 836, 5, CONCAT('Ruthless Fighters'), '2007-03-26', 'https://video.sibnet.ru/shell.php?videoid=1255935');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14955, 836, 6, CONCAT('Encounter with the Crouching Dragon'), '2007-04-02', 'https://vk.com/video297844655_171337317');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14956, 836, 7, CONCAT('Kanu Surrenders'), '2007-04-09', 'https://video.sibnet.ru/shell.php?videoid=1255906');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14957, 836, 8, CONCAT('The Little Conqueror', CHAR(39), 's Heroic Death'), '2007-04-16', 'https://video.sibnet.ru/shell.php?videoid=1255909');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14958, 836, 9, CONCAT('Friendships in Chaos'), '2007-04-23', 'https://myvi.ru/player/embed/html/oNcaJZKo7p39AnUTuDL7sgh-VJQgpBV5GfybWQY7JffU1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14959, 836, 10, CONCAT('The Wandering Koukin'), '2007-04-30', 'https://myvi.ru/player/embed/html/oVSfLCKlm82z-dAosEqQ8WY5E8JfZ7Qpiy_7um8bWL_k1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14960, 836, 11, CONCAT('Fighter Melee'), '2007-05-07', 'https://myvi.ru/player/embed/html/otItzxdne_U9zWjIM5i0p-o0k3f-lvzeSa0UPF_ycFMo1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (14961, 836, 12, CONCAT('Red Cliffs in Flames'), '2007-05-14', 'https://video.sibnet.ru/shell.php?videoid=1255922');
