INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (853, CONCAT('Ingress the Animation'), CONCAT('A project was launched where scientists discovered a mysterious substance that can interface directly with the human brain. This substance, called "Exotic Matter (XM)," has existed since ancient times, influencing human minds and the progress of humanity. In the wake of this discovery, a battle of powerful nations and corporate giants has been unleashed. Organizations across the globe have embarked on a secret race to exploit XM. It represents both an opportunity and a threat to humanity. Two Factions seeks to control the XM. The Enlightened view XM', CHAR(39), 's power as a gift that enhances human experience and discovery. The Resistance sees XM as a hostile takeover of the human mind, choosing technology as humanity', CHAR(39), 's best path forward. XM, and the mystery behind it lie at the center of this battle for the fate of humanity.<br>
<br>2018—Now, a new struggle is about to unfold in Tokyo and across the globe. Dangerous and powerful forces seeking to exploit the potential of XM will collide. This groundbreaking project will mark the beginning of an epic augmented-reality experience combining the three elements of animation, location-based gaming, and the real world.<br>
<br>(Source: MAL News)'), 1, '2018-10-18', '2018-12-27', 'Fall 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1944/93421.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2046, 853, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2047, 853, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2048, 853, 10);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2049, 853, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (934, 853, 5);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15121, 853, 1, CONCAT('Begin – Danger – Message'), '2018-10-18', 'https://ebd.cda.pl/800x450/296774421');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15122, 853, 2, CONCAT('Escape – Past – Destiny'), '2018-10-25', 'https://www.mp4upload.com/embed-bzl4rlw31lnh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15123, 853, 3, CONCAT('Advance – Discover – Conflict'), '2018-11-01', 'https://ebd.cda.pl/800x450/2967756e2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15124, 853, 4, CONCAT('Separate – Together – Pursue'), '2018-11-08', 'https://www.mp4upload.com/embed-y2m28di9b7dd.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15125, 853, 5, CONCAT('Journey – Portal – Potential'), '2018-11-15', 'https://www.mp4upload.com/embed-6nkgecn5ubdv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15126, 853, 6, CONCAT('Enlightenment – Resistance – Chaos'), '2018-11-22', 'https://www.mp4upload.com/embed-80oiaj7g3vk0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15127, 853, 7, CONCAT('Nature – Civilization – Soul'), '2018-11-29', 'https://www.mp4upload.com/embed-9nnh5qmdow7m.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15128, 853, 8, CONCAT('Forget – Information – Rebel'), '2018-12-06', 'https://www.mp4upload.com/embed-euzvn31cf50m.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15129, 853, 9, CONCAT('Live – Die – Truth'), '2018-12-13', 'https://www.mp4upload.com/embed-etxqeosqvfi8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15130, 853, 10, CONCAT('Destroy – Create – Answer'), '2018-12-20', 'https://www.mp4upload.com/embed-yji1wvsq429y.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15131, 853, 11, CONCAT('Us – Them – All'), '2018-12-27', 'https://www.mp4upload.com/embed-jex9hb2hwkh2.html');
