INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (880, CONCAT('Isekai Ojisan'), CONCAT('After a fatal encounter with a truck, Takafumi Takaoka', CHAR(39), 's uncle, Yousuke "Ojisan" Shibazaki, lies comatose for 17 years. When he finally regains consciousness, Ojisan begins to ramble in a foreign tongue and reveals that he had been transported to a magical world called Gran Bahamal. Takafumi dismisses his uncle', CHAR(39), 's claims as nonsense until an incantation makes a cup of water hover in the air. In a flash of brilliance, the pair creates a YouTube channel to showcase Ojisan', CHAR(39), 's magical abilities.<br>
<br>The responsibility now falls on Takafumi', CHAR(39), 's shoulders to acquaint Ojisan with everything that has transpired during his absence, including getting him up to speed with the internet, new technology, and surprisingly, the outcome of the ', CHAR(39), '90s console war—the result of which was especially distressing for a hardcore SEGA fan. With Ojisan', CHAR(39), 's wisdom from his other world experiences, they grow their YouTube channel and tackle online comments and trolls. The journey of this uncle-nephew duo promises to be anything but conventional.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-07-06', NULL, 'Summer 2022', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1743/125204.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2126, 880, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2127, 880, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (962, 880, 82);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (986, 880, 16);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (987, 880, 17);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15642, 880, 1, CONCAT('I', CHAR(39), 'm Finally Back From the Fantasy World Of Granbahamal After 17 Long Years!'), '2022-07-06', 'https://ebd.cda.pl/620x368/11386415ab');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15643, 880, 2, CONCAT('"Guardian Heroes" Shoulda Been Number One!'), '2022-07-13', 'https://ebd.cda.pl/620x368/11437447ba');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15644, 880, 3, CONCAT('I', CHAR(39), 'm Your Un―...Aunt, Dear'), '2022-07-20', 'https://ebd.cda.pl/620x368/1149296272');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15645, 880, 4, CONCAT('You Helped Me Through Tough Times'), '2022-07-27', 'https://ebd.cda.pl/620x368/11585780fe');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15646, 880, 5, CONCAT('That Reminds Me, I Almost Got Assassinated Once'), '2022-08-17', 'https://ebd.cda.pl/620x368/11763926bf');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15647, 880, 6, CONCAT('So They Threw Me into the Basement of a freak show…'), '2022-08-24', 'https://ebd.cda.pl/620x368/1184193834');
