INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (891, CONCAT('Itsudatte Bokura no Koi wa 10 cm Datta.'), CONCAT('Miou Aida and Haruki Serizawa might seem like polar opposites to those around them, but as the two third-years prepare to end their high school experience, they couldn', CHAR(39), 't have been closer. While Miou is a shy and reserved member of the school art club that prefers to stay out of the limelight, Haruki is the boisterous and confident ace of the movie club, already winning awards for his directing prowess. However, after a previous chance encounter during their school entrance ceremony, they quickly become friends despite their stark differences in personality. But although their closeness might be growing, they', CHAR(39), 've never become anything more than just that, much to the bewilderment of their friends.<br>
<br>As their time in high school draws to a close, Miou and Haruki, along with their friends in the art and movie clubs, have just one year left to face their hidden feelings and the daunting task of deciding their future careers. The two might always be only an arm', CHAR(39), 's reach away, but as Haruki chases his dream of becoming a professional movie director and Miou struggles with choosing a path for herself, they', CHAR(39), 'll learn just how hard it is to get past those last 10 centimeters.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-11-25', '2017-12-30', 'Fall 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1015/123541.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2162, 891, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2163, 891, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2164, 891, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (973, 891, 62);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1005, 891, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1006, 891, 42);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15766, 891, 1, CONCAT('Spring, First Love, Color of Cherry Blossoms'), '2017-11-25', 'https://www.dailymotion.com/embed/video/x6bobux');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15767, 891, 2, CONCAT('Summer, Fireworks, Color of Love'), '2017-12-02', 'https://www.mp4upload.com/embed-pyujqyl5d6nk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15768, 891, 3, CONCAT('Secret, Solitude, Color of Twilight'), '2017-12-09', 'https://www.dailymotion.com/embed/video/x6dszl9');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15769, 891, 4, CONCAT('Study Abroad, Map of the Future, Color of the Heart'), '2017-12-16', 'https://www.mp4upload.com/embed-2bohucm2h019.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15770, 891, 5, CONCAT('First Snow, Dreams, Color of Tears'), '2017-12-23', 'https://www.mp4upload.com/embed-l2gihs6rnanz.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (15771, 891, 6, CONCAT('Graduation, Adventures, Color of the Future'), '2017-12-30', 'https://www.mp4upload.com/embed-aihgjcd05frw.html');
