INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (931, CONCAT('Kageki Shoujo!!'), CONCAT('After being forced to graduate from JPX48 following a controversial incident with a male fan, Ai Narata swears to never interact with another man ever again. Using her talents and strong desire to get away from men, Ai auditions for the exclusive all-female Kouka School of Musical and Theatrical Arts. The school is renowned for producing the best actresses that go on to perform in the famous all-female Kouka Theatre Troupe. Coming from the idol industry, Ai is the perfect candidate for the school', CHAR(39), 's hundredth generation class, but her aloof demeanor alienates her from her classmates.<br>
<br>The eccentric Sarasa Watanabe is the only person who wishes to become Ai', CHAR(39), 's friend. She enters Kouka with the goal of becoming a top "otokoyaku" performer—an actress that plays traditionally male roles. After seeing a Kouka performance of The Rose of Versailles when she was younger, Sarasa dreams of performing as Lady Oscar one day. Unfortunately, Sarasa', CHAR(39), 's inability to read a room causes friction between her and her classmates, including Ai, who reluctantly becomes her roommate and partner in many of their classes. <br>
<br>Succeeding at Kouka will involve more than just raw talent for these young girls as jealousy, deceit, and the harsh realities of show business put their mental fortitude to the test. Will Sarasa and Ai be able to rise to the top and stand on the silver bridge?<br>
<br>[Written by MAL Rewrite]'), 1, '2021-07-04', '2021-09-26', 'Summer 2021', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1944/114427.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (408, 931, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2256, 931, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2257, 931, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1015, 931, 61);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16366, 931, 1, CONCAT('Beneath the Cherry Tree, in a Rain of Petals'), '2021-07-04', 'https://drive.google.com/file/d/1WjvLM6XV9r-0tEJqa53LjKoUl5Pe6joU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16367, 931, 2, CONCAT('Those Who Long to Cross the Silver Bridge'), '2021-07-11', 'https://drive.google.com/file/d/1ER56KfMDI-kKwvsaGbCjbexJIxgv1aG4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16368, 931, 3, CONCAT('The Teddy Bear'), '2021-07-18', 'https://drive.google.com/file/d/1ntwQyacl2jssmhahfDIwP7gvau169B4T/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16369, 931, 4, CONCAT('Tears Overwritten'), '2021-07-25', 'https://drive.google.com/file/d/1iR3MIJdDTP_eW_Uf5GpwyIeAP0jj0-Km/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16370, 931, 5, CONCAT('The Chosen Maidens'), '2021-08-01', 'https://drive.google.com/file/d/1TiDOxOX9F-KOjofn3kI94jK7yeZtQzEE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16371, 931, 6, CONCAT('A Glimpse of Stardom'), '2021-08-08', 'https://drive.google.com/file/d/10yMV435aHdGpn5EN4DPrD1ReQll6AzjC/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16372, 931, 7, CONCAT('The Hanamichi and the Silver Bridge'), '2021-08-15', 'https://drive.google.com/file/d/1TuKLXiOCpkKU0h7kf6hrdLoneaymn8Gy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16373, 931, 8, CONCAT('Kaoru', CHAR(39), 's Summer'), '2021-08-22', 'https://video.sibnet.ru/shell.php?videoid=4406302');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16374, 931, 9, CONCAT('The Two Juliets'), '2021-08-29', 'https://video.sibnet.ru/shell.php?videoid=4414699');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16375, 931, 10, CONCAT('A Once-in-a-Century Autumn'), '2021-09-05', 'https://video.sibnet.ru/shell.php?videoid=4415123');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16376, 931, 11, CONCAT('4/40'), '2021-09-12', 'https://video.sibnet.ru/shell.php?videoid=4415135');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16377, 931, 12, CONCAT('Surely Someone'), '2021-09-19', 'https://drive.google.com/file/d/1cN9nPLFUTpyHwHIkfi7mneco79Sffq3N/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16378, 931, 13, CONCAT('Kageki Shojo!!'), '2021-09-26', 'https://video.sibnet.ru/shell.php?videoid=4448115');
