INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (939, CONCAT('Kaijuu Girls: Ultra Kaijuu Gijinka Keikaku'), CONCAT('Very rarely is a girl born with two distinct souls: one of a human and the other of a kaiju. These extraordinary individuals, dubbed "Kaiju Girls," possess the form of a normal person and the supernatural abilities of a giant monster. The International Kaiju Rescue and Mentoring Organization, also known as GIRLS, was created to help these Kaiju Girls adjust to their powers and find a place in society. <br>
<br>Recently, three young girls have awakened their kaiju halves. The introverted Aki Miyashita obtains the soul of Agira, the serious Reika Shiragane inherits Windom, and the energetic Miku Ushimaru receives Miclas. Together they join the organization GIRLS, where the three each learn how to use their powers and control their monstrous instincts. Through the support of those around them, Agira, Windom, and Miclas each discover what it truly means to be a Kaiju Girl.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2016-09-27', '2016-12-13', '', '5 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/82138.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2274, 939, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2275, 939, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1023, 939, 184);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16467, 939, 1, CONCAT('We', CHAR(39), 're Kaiju Girls?!'), '2016-09-27', 'https://www.mp4upload.com/embed-s6eqiqyvtrhk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16468, 939, 2, CONCAT('Transform? Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-o21jzwgovmhn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16469, 939, 3, CONCAT('Transform! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-qh2w5qjugrg2.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16470, 939, 4, CONCAT('Hand Them Out! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-7hvyozww6qvc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16471, 939, 5, CONCAT('Senpai! Kaiju Girl!?'), NULL, 'https://www.mp4upload.com/embed-azxmu21gorzx.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16472, 939, 6, CONCAT('Worry! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-v60ggo7tos6a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16473, 939, 7, CONCAT('Fight! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-n5c40ajppjou.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16474, 939, 8, CONCAT('Joke! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-7wrswoe63o7a.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16475, 939, 9, CONCAT('Going Berserk? Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-qr0wc6y47l03.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16476, 939, 10, CONCAT('Jump! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-iimuhq2uuk30.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16477, 939, 11, CONCAT('Exam! Kaiju Girls!?'), NULL, 'https://www.mp4upload.com/embed-0fmhq9me4rh0.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16478, 939, 12, CONCAT('We are Kaiju! Girls!!'), NULL, 'https://www.mp4upload.com/embed-q7ovjs6mjh2a.html');
