INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (955, CONCAT('Kamisama Hajimemashita'), CONCAT('High schooler Nanami Momozono has quite a few problems of late, beginning with her absentee father being in such extreme debt that they lose everything. Downtrodden and homeless, she runs into a man being harassed by a dog. After helping him, she explains her situation, and to her surprise, he offers her his home in gratitude. But when she discovers that said home is a rundown shrine, she tries to leave however, she is caught by two shrine spirits and a fox familiar named Tomoe. They mistake her for the man Nanami rescued—the land god of the shrine, Mikage. Realizing that Mikage must have sent her there as a replacement god, Tomoe leaves abruptly, refusing to serve a human.<br>
<br>Rather than going back to being homeless, Nanami immerses herself in her divine duties. But if she must keep things running smoothly, she will need the help of a certain hot-headed fox. In her fumbling attempt to seek out Tomoe, she lands in trouble and ends up sealing a contract with him. Now the two must traverse the path of godhood together as god and familiar but it will not be easy, for new threats arise in the form of a youkai who wants to devour the girl, a snake that wants to marry her, and Nanami', CHAR(39), 's own unexpected feelings for her new familiar.<br>
<br>[Written by MAL Rewrite]'), 1, '2012-10-02', '2012-12-25', 'Fall 2012', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/3/85429.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (420, 955, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2316, 955, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2317, 955, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2318, 955, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1040, 955, 23);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16727, 955, 1, CONCAT('Nanami Becomes a God'), '2012-10-02', 'https://drive.google.com/file/d/1r5STHoYkLkCJcda_cd-al3sjx27inmCy/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16728, 955, 2, CONCAT('The God Becomes a Target'), '2012-10-09', 'https://drive.google.com/file/d/0B8qEs6bZsy4aZnREN2FuSDNuLXc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16729, 955, 3, CONCAT('The God Makes a Match'), '2012-10-16', 'https://drive.google.com/file/d/0B8qEs6bZsy4aZVZfSklBUEdQTUU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16730, 955, 4, CONCAT('The God Is Kidnapped'), '2012-10-23', 'https://drive.google.com/file/d/1HfIMJRDrjPVIS8AafUKZFdlZfH1z-OEw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16731, 955, 5, CONCAT('The God Loses Her House'), '2012-10-30', 'https://video.sibnet.ru/shell.php?videoid=1726081');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16732, 955, 6, CONCAT('The God Catches a Cold'), '2012-11-06', 'https://drive.google.com/file/d/1fnyyuCffn3thJZElaTmxekCSLcPS1Axt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16733, 955, 7, CONCAT('The God Asks a Boy Out On a Date'), '2012-11-13', 'https://drive.google.com/file/d/1lF6hhQu-OLgPmUcPAQgH5_be6mfd5t6A/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16734, 955, 8, CONCAT('The God Goes to the Beach'), '2012-11-20', 'https://drive.google.com/file/d/1GYJ4MDt78XsMXljtVkUcySAPjEbeKNt4/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16735, 955, 9, CONCAT('The God Goes to the Dragon King', CHAR(39), 's Palace'), '2012-11-27', 'https://drive.google.com/file/d/11MvpblQPO1avqsFqs6d578fyVe8QeaBk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16736, 955, 10, CONCAT('Tomoe Becomes a Familiar / The God Goes to a Mixer'), '2012-12-04', 'https://drive.google.com/file/d/10OTZeo_bWEhm8L275oNCvi_LACZEWMG5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16737, 955, 11, CONCAT('The Familiar Goes Into Town'), '2012-12-11', 'https://drive.google.com/file/d/1bhVzaKDNjoEdY3QrW_ejW8sy6d-WK5zT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16738, 955, 12, CONCAT('Nanami Quits Being a God'), '2012-12-18', 'https://drive.google.com/file/d/1ufrHheGGwvSeXIXOjA3KE1TtvXpo8J7w/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (16739, 955, 13, CONCAT('I', CHAR(39), 've Started the "Being a God" Thing'), '2012-12-25', 'https://drive.google.com/file/d/1lXaqQ2JdIaCGfoG0oYKYhhxevPh4FzO5/preview');
