INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (987, CONCAT('Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana'), CONCAT('In Tokyo, there exists a peaceful cohabitation between supernatural creatures—elves, dwarves, vampires, and more—and humans. However, contrary to history, powerful dragons once ruled over this world of creatures and humans but have since disappeared. Consequently, a diabolical group under the alias "Nine," who seek the miracles of the once godlike dragons, stirs up trouble in the streets of Tokyo, commiting mass murder and causing destruction. To combat the dangerous group of Nine, the police organize the Special 7—a group of highly skilled professionals whose abilities exceed those of ordinary humans. <br>
<br>Caught up in a bank robbery turned hostage crisis, Seiji Nanatsuki, having recently become a detective, has a chance encounter with Shiori Ichinose, a member of Special 7. Assisting with the resolution of the robbery, Seiji is recognized for his clear sense of justice and refreshing character, suddenly earning him a spot on the elite unit. <br>
<br>As he takes on new missions, Seiji finds that being a detective as part of Special 7 isn', CHAR(39), 't the police work he expected, where working alongside a team of different species with special abilities and vibrant personalities brings unpredictability to his daily life and police work. While the everyday crime in Tokyo continues, Seiji and the Special 7 will fight not only to resolve special cases, but also obstruct the ill-intentioned plans of the merciless group of Nine.<br>
<br>[Written by MAL Rewrite]'), 1, '2019-10-06', '2019-12-29', 'Fall 2019', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1556/111623.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2389, 987, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2390, 987, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1073, 987, 19);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1098, 987, 2);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1099, 987, 19);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17148, 987, 1, CONCAT('One Brings Bad Omens, Seven Brings Good Luck'), NULL, 'https://ebd.cda.pl/620x368/40101616a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17149, 987, 2, CONCAT('The Two Investigate'), NULL, 'https://ebd.cda.pl/620x368/404293311');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17150, 987, 3, CONCAT('The Threefold Trap'), NULL, 'https://ebd.cda.pl/620x368/405901058');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17151, 987, 4, CONCAT('Family of Four'), NULL, 'https://ebd.cda.pl/620x368/408287541');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17152, 987, 5, CONCAT('The Fifth Seal'), NULL, 'https://ebd.cda.pl/620x368/41123683e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17153, 987, 6, CONCAT('The Six-Minute Battle to the Death'), NULL, 'https://ebd.cda.pl/620x368/413712106');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17154, 987, 7, CONCAT('The Seventh Day is for Idleness'), NULL, 'https://ebd.cda.pl/620x368/4190347cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17155, 987, 8, CONCAT('The Eight-Foot Escape Route'), NULL, 'https://ebd.cda.pl/620x368/420518855');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17156, 987, 9, CONCAT('Nine Years', CHAR(39), ' Rage'), NULL, 'https://ebd.cda.pl/620x368/427112683');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17157, 987, 10, CONCAT('The Tenth Dragon'), NULL, 'https://ebd.cda.pl/620x368/43267825e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17158, 987, 11, CONCAT('The Eleven O', CHAR(39), 'clock War'), NULL, 'https://ebd.cda.pl/620x368/43310871b');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17159, 987, 12, CONCAT('From Zero to Seven'), NULL, 'https://ebd.cda.pl/620x368/434764821');
