INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1012, CONCAT('Kill Me Baby'), CONCAT('Kill Me Baby is the touching story of Yasuna, a normal (?) high school girl, and Sonya, her best friend who happens to be an assassin. Unfortunately, little Sonya', CHAR(39), 's trained assassin instincts often work against her and others in her daily high school life, as Yasuna', CHAR(39), 's often-broken wrist can attest to. She just wanted a hug, but she ended up with a broken neck. Isn', CHAR(39), 't it sad? No, it', CHAR(39), 's hilarious.<br>
<br>Not even Yasuna', CHAR(39), 's intense ninja training can prepare her for the exciting adventures in this explosive 4-panel manga adaptation.'), 1, '2012-01-06', '2012-03-30', 'Winter 2012', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/9/87197.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2457, 1012, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2458, 1012, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2459, 1012, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1101, 1012, 64);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1123, 1012, 13);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1124, 1012, 29);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17554, 1012, 1, CONCAT('Sneaking Dog, Blossoming Cherry'), NULL, 'https://www.dailymotion.com/embed/video/xnou4o?hideInfos=1&forcedQuality=hd720&logo=1&animatedTitle=Dla%20Shinden.pl%7C%7C');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17555, 1012, 2, CONCAT('Nunchaku Skills Bear Balloon'), NULL, 'https://www.dailymotion.com/embed/video/xnrkki');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17556, 1012, 3, CONCAT('Cursed Psychic Rain Wrestling'), NULL, 'https://myvi.ru/player/embed/html/o5Lhs0Pa9SjqV-5pSPKlaYN6HovjzkK7QNijVcDyCfGatE4kwGMtN6f_9lEWAklD50');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17557, 1012, 4, CONCAT('Ice Cream Scream Watermelon'), NULL, 'https://myvi.ru/player/embed/html/oRDDnjgBJR2MrnsWWd_hWY62YlfDetxlDyxDGabCmxcJegTzIwxGSUaVupF65UFdM0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17558, 1012, 5, CONCAT('Buggy Festival Sea Dolls'), NULL, 'https://www.mp4upload.com/embed-5rdfx7fthwsc.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17559, 1012, 6, CONCAT('Navel Mechanism Paper Doll Ice'), NULL, 'https://www.mp4upload.com/embed-wgmcoqcf5byg.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17560, 1012, 7, CONCAT('Culture Beanbag Jousting Duel'), NULL, 'https://streamtape.com/e/6WDZoGVKvvt9Ab4/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17561, 1012, 8, CONCAT('Sticking, Strumming, Stabbing'), NULL, 'https://streamtape.com/e/6Pw82XveWrI9rv8/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17562, 1012, 9, CONCAT('Fishing Hammer', CHAR(39), 's Spawn Branch Forgotten'), NULL, 'https://streamtape.com/e/0JbRWXedVLhbObL/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17563, 1012, 10, CONCAT('Santa Icicle Snow Mantra'), NULL, 'https://streamtape.com/e/6wjlZBo96QI9mDW/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17564, 1012, 11, CONCAT('Bath Kite Rice Cake New Year', CHAR(39), 's First Dream'), NULL, 'https://streamtape.com/e/m9Zr0K6lKxCbJ7l/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17565, 1012, 12, CONCAT('Drowsy Chocolate Injury Compress'), NULL, 'https://streamtape.com/e/gg32YAqJdXtxyy/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (17566, 1012, 13, CONCAT('Make the Kill Me and Make Me Your Baby'), NULL, 'https://streamtape.com/e/LpzMmkdpwlTRkPD/');
