INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1116, CONCAT('Lance N', CHAR(39), ' Masques'), CONCAT('Eight words describe the feelings of Youtarou Hanabusa: "I just want to live a normal life." Unfortunately for him, as a member of the Knights of the World, his training in this ancient and international order has left him with a condition he calls "White Knight Syndrome." This condition causes Youtarou to instinctively act heroically and chivalrously whenever he encounters someone in danger.<br>
<br>To protect his identity in such embarrassing moments, he carries a mask with him at all times. Then one day, he saves the life of Makio Kidouin, the young daughter of an elite and affluent family. Little does he know that this singular act of heroism will change his life forever. Soon, he is simultaneously blessed with a life in the lap of luxury and cursed with one of abnormality, for his new friend Makio lives a life far removed from the everyday.<br>
<br>Between coping with the hijinks of six-year-old Makio, and dealing with a cast of odd friends and scheming enemies, Youtarou must protect his new friend while keeping his identity hidden as the masked hero Knight Lancer.<br>
<br>[Written by MAL Rewrite]'), 1, '2015-10-02', '2015-12-18', 'Fall 2015', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/13/76576.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1210, 1116, 16);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19106, 1116, 1, CONCAT('He', CHAR(39), 's a Real Hero'), '2015-10-02', 'https://video.sibnet.ru/shell.php?videoid=1931083');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19107, 1116, 2, CONCAT('Are You Prepared?'), '2015-10-09', 'https://video.sibnet.ru/shell.php?videoid=1939018');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19108, 1116, 3, CONCAT('I Am Here Now, My Lady'), '2015-10-16', 'https://video.sibnet.ru/shell.php?videoid=1950194');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19109, 1116, 4, CONCAT('Daddy'), '2015-10-23', 'https://video.sibnet.ru/shell.php?videoid=1959974');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19110, 1116, 5, CONCAT('From Now On, We', CHAR(39), 're Family'), '2015-10-30', 'https://drive.google.com/file/d/0B0S-wPUxu1SXVUV3cTF3anVDNVE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19111, 1116, 6, CONCAT('Just This Once'), '2015-11-06', 'https://www.mp4upload.com/embed-rvylnu4udlm1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19112, 1116, 7, CONCAT('Be Mine'), '2015-11-13', 'https://video.sibnet.ru/shell.php?videoid=1980200');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19113, 1116, 8, CONCAT('Give Me Courage'), '2015-11-20', 'https://drive.google.com/file/d/0B5GFq1B573dxcEJsbnFuaktJS1k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19114, 1116, 9, CONCAT('Charge'), NULL, 'https://video.sibnet.ru/shell.php?videoid=2000901');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19115, 1116, 10, CONCAT('Be Who You Want to Be'), NULL, 'https://drive.google.com/file/d/0B9bR-1lhpaf5Q1dNcVlObU0wMFE/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19116, 1116, 11, CONCAT('Knighthood'), NULL, 'https://video.sibnet.ru/shell.php?videoid=2021804');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19117, 1116, 12, CONCAT('That', CHAR(39), 's Why I am a Knight'), NULL, 'https://www.mp4upload.com/embed-4ddfjpwtltyd.html');
