INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1141, CONCAT('Love Kome: We Love Rice'), CONCAT('The project anthropomorphizes rice (kome in Japanese) into schoolboys. At the Kokuritsu Inaho Academy ("Rice Ear Academy," a wordplay on national schools)', CHAR(39), 'kome', CHAR(39), 'dy with laughs and passion" promises to let audiences rediscover the virtues of rice ("Japan', CHAR(39), 's soul food").<br>
<br>(Source: ANN)'), 4, '2017-04-05', '2017-06-21', 'Spring 2017', '4 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/84377.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (506, 1141, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2780, 1141, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2781, 1141, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2782, 1141, 3);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2783, 1141, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1238, 1141, 96);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1252, 1141, 12);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1253, 1141, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19490, 1141, 1, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-pth5bziinz0y.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19491, 1141, 2, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-3ylgdu85od29.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19492, 1141, 3, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-l6i4np1yrij7.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19493, 1141, 4, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-s7byz2zwvbk7.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19494, 1141, 5, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-ryvxjetywzq1.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19495, 1141, 6, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-e22740vx814z.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19496, 1141, 7, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-s103eg1puaq7.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19497, 1141, 8, CONCAT('Untitled'), NULL, 'https://drive.google.com/file/d/0B6BWr4iAdBLkMFU5Y2RXLWVyZXc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19498, 1141, 9, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-gqdp3dviud3y.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19499, 1141, 10, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-kxd8bsyan3su.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19500, 1141, 11, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-gxm180pua387.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19501, 1141, 12, CONCAT('Untitled'), NULL, 'https://www.mp4upload.com/embed-etbxfrc158vu.html');
