INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1151, CONCAT('Luck & Logic'), CONCAT('"Logic" is the concept that governs emotions, abilities, ideals, memories, and all other abstract properties that make up life in various worlds. With its power, however, alien "Foreigners" are able to pass through portals imbued with their respective world', CHAR(39), 's Logic and pose a threat to other worlds. To counter this problem, the Another Logic Counter Agency (ALCA) from the human world of Septpia employs "Logicalists," people with the power to form bonds with the Foreigners who seek peace and share their Logic, tasked with dealing with all possible dangers.<br>
<br>After overloading his powers two years prior, Yoshichika Tsurugi has lost the ability to use Logic in combat, making him no different from a regular citizen. However, his life soon returns to the battlefield when he meets Athena, a Foreigner goddess from the world of Tetra-Heaven. She brings Yoshichika his missing Logic Card, allowing him to become a Logicalist once again. Soon after, Yoshichika forms a contract with Athena and joins ALCA. There, he meets other Logicalists, and only by working with them can he hope to bring an end to the threats once and for all.<br>
<br>[Written by MAL Rewrite]'), 1, '2016-01-09', '2016-03-26', 'Winter 2016', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/77134.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2798, 1151, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2799, 1151, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2800, 1151, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1248, 1151, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19626, 1151, 1, CONCAT('Hero or Mob'), '2016-01-09', 'https://video.sibnet.ru/shell.php?videoid=2049346');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19627, 1151, 2, CONCAT('Genius or Fool'), '2016-01-16', 'https://vk.com/video_ext.php?oid=172567157&id=171715142&hash=e03b82541ad188d5&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19628, 1151, 3, CONCAT('Dream or Reality'), '2016-01-23', 'https://vidcloud.co/v/5c9c4e1420649');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19629, 1151, 4, CONCAT('Freedom or Restraint'), '2016-01-30', 'https://www.mp4upload.com/embed-x5yevmpv95nw.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19630, 1151, 5, CONCAT('Yesterday or Tomorrow'), '2016-02-06', 'https://dood.so/e/0ruom3neo1qjkyb6bdyqyriaw9iuiekb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19631, 1151, 6, CONCAT('Battle or Surrender'), '2016-02-13', 'https://www.mp4upload.com/embed-atb62moqs87n.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19632, 1151, 7, CONCAT('Human or God'), '2016-02-20', 'https://streamtape.com/e/xy0dO3QZroCkapA/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19633, 1151, 8, CONCAT('Guilt or Innocence'), '2016-02-27', 'https://vk.com/video323839172_456239019');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19634, 1151, 9, CONCAT('Enemy or Friend'), '2016-03-05', 'https://www.mp4upload.com/embed-egjwu5y1wtu9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19635, 1151, 10, CONCAT('Heaven or Hell'), '2016-03-12', 'https://www.mp4upload.com/embed-o6ztnbqsee6z.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19636, 1151, 11, CONCAT('Despair or Destruction'), '2016-03-19', 'https://streamtape.com/e/9oYdJ62V86SZq6/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (19637, 1151, 12, CONCAT('Luck and Logic'), '2016-03-26', 'https://streamtape.com/e/dpJPDYXbRoTkkm1/');
