INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1219, CONCAT('Maoyuu Maou Yuusha'), CONCAT('Fifteen years have passed since the war between humans and demons began. Dissatisfied with their slow advance into the Demon Realm, the Hero abandons his companions to quickly forge ahead towards the Demon Queen', CHAR(39), 's castle. Upon his arrival at the royal abode, the Hero makes a startling discovery: not only is the Demon Queen a woman of unparalleled beauty, but she also seeks the Hero', CHAR(39), 's help. Confused by this unexpected turn of events, the Hero refuses to ally himself with his enemy, claiming that the war the demons have waged is tearing the Southern Nations apart.<br>
<br>However, the Demon Queen rebuts, arguing that the war has not only united humanity but has also brought them wealth and prosperity, providing evidence to support her claims. Furthermore, she explains that if the war were to end, the supplies sent by the Central Nations in aid to the Southern Nations would cease, leaving hundreds of thousands to starve. Fortunately, she offers the Hero a way to end the war while bringing hope not only to the Southern Nations, but also to the rest of the world, though she will need his assistance to make this a reality.<br>
<br>Finally convinced, the Hero agrees to join his now former enemy in her quest. Vowing to stay together through sickness and health, they set off for the human world.<br>
<br>[Written by MAL Rewrite]'), 1, '2013-01-05', '2013-03-30', 'Winter 2013', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/4/46041.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2980, 1219, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2981, 1219, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2982, 1219, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1317, 1219, 129);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20973, 1219, 1, CONCAT('— You will be mine, Hero. — I refuse!'), NULL, 'https://ebd.cda.pl/620x395/626076872');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20974, 1219, 2, CONCAT('Please Make Us Human.'), NULL, 'https://ebd.cda.pl/620x395/626073808');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20975, 1219, 3, CONCAT(' Where have you been?'), NULL, 'https://ebd.cda.pl/620x395/626074192');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20976, 1219, 4, CONCAT('If That Happens, I', CHAR(39), 'll Take a Bite Out of the Hero!'), NULL, 'https://ebd.cda.pl/620x395/62607657c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20977, 1219, 5, CONCAT('You smell good, Demon King. And I feel safe in your arms, Hero.'), NULL, 'https://ebd.cda.pl/620x395/626074406');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20978, 1219, 6, CONCAT('—Welcome back, Hero! —Yeah, Old Man. I', CHAR(39), 'm back!'), NULL, 'https://ebd.cda.pl/620x395/626073278');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20979, 1219, 7, CONCAT(' —I', CHAR(39), 'll be back soon, we', CHAR(39), 'll see each other soon.'), NULL, 'https://ebd.cda.pl/620x395/626075355');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20980, 1219, 8, CONCAT('Take this sword, my lord'), NULL, 'https://ebd.cda.pl/620x395/6260747e2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20981, 1219, 9, CONCAT('I Am Human'), NULL, 'https://ebd.cda.pl/620x395/6260750e6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20982, 1219, 10, CONCAT('So now their plans are finally coming to fruition?'), NULL, 'https://ebd.cda.pl/620x395/62607562a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20983, 1219, 11, CONCAT('I just destroy and kill, without creating anything'), NULL, 'https://ebd.cda.pl/620x395/6260759cd');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20984, 1219, 12, CONCAT('—I', CHAR(39), 'm back, my Hero. —You sleep too much, my Demon King.'), NULL, 'https://ebd.cda.pl/620x395/626076249');
