INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1221, CONCAT('Maria†Holic'), CONCAT('In search of true love, Kanako Miyamae transfers to Ame no Kisaki Catholic school, inspired by how her parents fell in love with each other there. There is just one difference, though: because men make Kanako break into hives, she has actually come to the all-girls school to find a partner of the same sex.<br>
<br>When she meets the beautiful Mariya Shidou, Kanako believes she has found that special someone however, there', CHAR(39), 's more to Mariya than meets the eye—it turns out that Kanako', CHAR(39), 's first love is actually a cross-dressing boy. Mariya threatens to expose Kanako', CHAR(39), 's impure intentions unless she keeps his real gender a secret, and to make things worse, he also replaces her original roommate so that he can now keep a close eye on her.<br><br>Maria†Holic follows Kanako as she looks for love in all the wrong places and searches for the girl of her dreams—that is, if she can survive being Mariya', CHAR(39), 's roommate!<br>
<br>[Written by MAL Rewrite]'), 1, '2009-01-04', '2009-03-22', 'Winter 2009', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1240/111304.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2987, 1221, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (2988, 1221, 16);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1319, 1221, 7);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1333, 1221, 43);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1334, 1221, 21);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1335, 1221, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20987, 1221, 1, CONCAT('The Flirtatious Kiss'), NULL, 'https://drive.google.com/file/d/1Eu3egAfyDgwBeBZpCP8SAQs8h5FZLAmu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20988, 1221, 2, CONCAT('A Sweet Tinge'), NULL, 'https://drive.google.com/file/d/14UqiHdLhf64Vnp47jYDLNNLzhmOguO0j/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20989, 1221, 3, CONCAT('Masochistic Young Buds'), NULL, 'https://drive.google.com/file/d/11AaQUnKkAEhNegI_tyuNdPOIyjYyL-c_/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20990, 1221, 4, CONCAT('The Cost of Pleasure'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4090399');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20991, 1221, 5, CONCAT('Forbidden Smell'), NULL, 'https://drive.google.com/file/d/1T4_SyDqDaR-I6HVS5hTtYkF4E9I0zLpG/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20992, 1221, 6, CONCAT('Infirmary of Perversion'), NULL, 'https://drive.google.com/file/d/1fy9b0ComZt-mErm2fbm551sJ08viYmct/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20993, 1221, 7, CONCAT('The Suspicious Black Underwear'), NULL, 'https://drive.google.com/file/d/1yNPD2uHPef51DZhwGui0YXDbwy7xqT4v/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20994, 1221, 8, CONCAT('The Tainted Holy Mother, Part 1'), NULL, 'https://drive.google.com/file/d/1OLzGw63YUzlrv87hpY_YD3HET53DNH49/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20995, 1221, 9, CONCAT('The Tainted Holy Mother, Part 2'), NULL, 'https://drive.google.com/file/d/1MHOfvpw0UfWZ4NJXglL6zhB1Vmw088TV/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20996, 1221, 10, CONCAT('A Flat Chested Error'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4090456');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20997, 1221, 11, CONCAT('An Offering to God'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4090460');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (20998, 1221, 12, CONCAT('A Swimming Competition Full of Pretty Girls'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4090467');
