INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1301, CONCAT('Mujaki no Rakuen'), CONCAT('Shouta Handa is a jobless 25 year old who is sick and tired of his boring life. One evening, at the class reunion, he gets to meet all of the cute girls that used to be his classmates. He soon discovers that they are all successful with interesting careers, and even more importantly—really beautiful now, with bigger curves. Unfortunately, it seems that they are all aware of his boring, unsuccessful life, so they mock him and call him a loser, just like in the old days.<br>
<br>Everything changes when Shouta goes for a walk to have a smoke and accidentally falls into the school swimming pool. This triggers a supernatural phenomenon that takes him back ten years into the past. He finds himself in the same swimming pool during swimming class, surrounded by his female classmates in bikinis. How is Shouta going to deal with their cuteness and closeness now that he is a grown man in a boy', CHAR(39), 's body?'), 3, '2014-08-29', '2016-08-29', '', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/74733.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (561, 1301, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3214, 1301, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3215, 1301, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3216, 1301, 14);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1406, 1301, 206);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22341, 1301, 1, CONCAT('Paradise of Miracles / Captured in Paradise / Insect-Luring Paradise'), '2014-08-29', 'https://drive.google.com/file/d/1wWUJN2GH00cn1Zce9EOq8XmOc049HJHK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22342, 1301, 2, CONCAT('Episode 2'), '2015-08-28', 'https://video.sibnet.ru/shell.php?videoid=3916117-2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (22343, 1301, 3, CONCAT('Episode 3'), '2016-08-29', 'https://video.sibnet.ru/shell.php?videoid=3916122-3');
