INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1369, CONCAT('Nobunaga no Shinobi: Anegawa Ishiyama-hen'), CONCAT('Third season of the Nobunaga no Shinobi series.'), 1, '2018-04-07', '2018-09-29', 'Spring 2018', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1651/91110.jpg');
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1475, 1369, 23);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23990, 1369, 1, CONCAT('The Silent Odani Castle'), NULL, 'https://streamtape.com/e/g1ZqwQ0g1XCq60o/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23991, 1369, 2, CONCAT('Isono Takes Off!'), NULL, 'https://streamtape.com/e/2oKKbQDP9AHZdGY/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23992, 1369, 3, CONCAT('Chidori Dances'), NULL, 'https://streamtape.com/e/3AyllW6QgGUD9G/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23993, 1369, 4, CONCAT('The Dangerous Two'), NULL, 'https://streamtape.com/e/0Jpx9VGBd7hbyD3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23994, 1369, 5, CONCAT('A Warrior', CHAR(39), 's Duty'), NULL, 'https://streamtape.com/e/Be1v1q6Vz8sy0g3/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23995, 1369, 6, CONCAT('The One-on-One Bastard Endo-san'), NULL, 'https://streamtape.com/e/0BLaKppQ7KfK8v/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23996, 1369, 7, CONCAT('Walk Over My Corpse'), NULL, 'https://streamtape.com/e/8XrYJbzPVZfXwP/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23997, 1369, 8, CONCAT('Everyone', CHAR(39), 's Own Anegawa'), NULL, 'https://streamtape.com/e/A2gVOPr0DQtX3A9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23998, 1369, 9, CONCAT('True Resolve'), NULL, 'https://streamtape.com/e/erv9GqzPJ1fY14G/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (23999, 1369, 10, CONCAT('Just a Little Trip to the Mori Clan'), NULL, 'https://streamtape.com/e/4WA6qw2RLQtp0W/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24000, 1369, 11, CONCAT('Let Sleeping Buddhas Lie'), NULL, 'https://streamtape.com/e/dqZBlwJOA0ubvQ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24001, 1369, 12, CONCAT('Towards the Light'), NULL, 'https://streamtape.com/e/D9Dy8JgmYeSkpdz/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24002, 1369, 13, CONCAT('Tatsuoki Always Appears Right Around the Time You Forget About Him'), NULL, 'https://streamtape.com/e/09bj9Bmjz2Hbx69/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24003, 1369, 14, CONCAT('The Opportunities Lie in Noda and Fukushima'), NULL, 'https://streamtape.com/e/aVq6D7xZ3Psxy1Z/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24004, 1369, 15, CONCAT('Bring Guns, Not Bows and Arrows'), NULL, 'https://streamtape.com/e/beMZPx9Gb2tPy9B/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24005, 1369, 16, CONCAT('The March of the True Believers'), NULL, 'https://streamtape.com/e/6PaD23r8dBhZ3B/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24006, 1369, 17, CONCAT('The Counterstrike General'), NULL, 'https://streamtape.com/e/B4g99Gz8D3fmRp/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24007, 1369, 18, CONCAT('Territory Defended to the Last'), NULL, 'https://streamtape.com/e/kwjL7kJxQBHPe9/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24008, 1369, 19, CONCAT('Resolve Complete'), NULL, 'https://streamtape.com/e/g280XBLpBQuqDPq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24009, 1369, 20, CONCAT('The Successors'), NULL, 'https://streamtape.com/e/7DVyWwVya4fR2X/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24010, 1369, 21, CONCAT('The Blessing of the Demon'), NULL, 'https://streamtape.com/e/0Zgl3DXgmqfbRLr/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24011, 1369, 22, CONCAT('There Are No Sanctuaries in These Troubled Times'), NULL, 'https://streamtape.com/e/LeQPrj60jeHRGL1/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24012, 1369, 23, CONCAT('The Nightmarish Shiga Encampment'), NULL, 'https://streamtape.com/e/M7j74y8O1zum3MJ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24013, 1369, 24, CONCAT('The Humiliation at Mount Hiei'), NULL, 'https://streamtape.com/e/6b90zG14ggF9yJG/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24014, 1369, 25, CONCAT('The End of Misfortune'), NULL, 'https://streamtape.com/e/J9KX9BRK03cJwq/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (24015, 1369, 26, CONCAT('The Headband and the Fresh Start'), NULL, 'https://streamtape.com/e/7XQLxVbG14iA7Wb/');
