INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1418, CONCAT('Ore ga Suki nano wa Imouto dakedo Imouto ja Nai'), CONCAT('Aspiring light novel author Yuu Nagami regularly enters writing competitions but has yet to win a single one. Despite his recurring failures, he remains steadfast in his resolve to become a better writer.<br>
<br>When he takes a look at the list of winning authors in the latest contest he joined, he notices that someone named Chikai Towano dominated the competition. He soon discovers that behind the pen name is his sister Suzuka—the last person he can imagine being an author. Suzuka cannot reveal to anyone that she is Chikai Towano and requests her brother to take her place.<br>
<br>Yuu agrees with one condition: he will continue posing as Chikai Towano for his sister until he publishes his own book. Until that happens, Yuu uses his new identity as an opportunity to improve his writing skills and meet fellow authors and new acquaintances along the way.<br>
<br>[Written by MAL Rewrite]'), 2, '2018-10-10', '2018-12-19', 'Fall 2018', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1359/96152.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (614, 1418, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3512, 1418, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3513, 1418, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3514, 1418, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1525, 1418, 42);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25659, 1418, 1, CONCAT('How my Sister and I Became Light Novel Authors'), NULL, 'https://ebd.cda.pl/620x368/267344188');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25660, 1418, 2, CONCAT('My Little Sister Aims for the Greatest Heights'), NULL, 'https://drive.google.com/file/d/1PCfHx3BDeuXc1Ia9NABYs29pnWRoF2Xu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25661, 1418, 3, CONCAT('My Little Sister and I are Light Novel Authors Together'), NULL, 'https://drive.google.com/file/d/1y2KMk_u3A6VcLAWGSPg6_3LUHcRQvzXI/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25662, 1418, 4, CONCAT('I Just Wanted to Catch Up to My Little Sister, That', CHAR(39), 's All'), NULL, 'https://drive.google.com/file/d/15uYyHhZUFMd0U74HHTV_hLaekMVoIne9/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25663, 1418, 5, CONCAT('I Love My Little Sister More Than Anything in the World'), NULL, 'https://drive.google.com/file/d/1o2irj_RMdqd2NKd0ZgzTyIMPS1xZwrZ5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25664, 1418, 6, CONCAT('Our Hakuou Girl', CHAR(39), 's School Culture Festival'), NULL, 'https://drive.google.com/file/d/1_CB3dNTsjBUM1f62Q19yGTLVYdy6b_Ei/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25665, 1418, 7, CONCAT('My Sister and I Face a Doujinshi Contest We Can', CHAR(39), 't Lose'), NULL, 'https://drive.google.com/file/d/1bTbIafPKpfEKTkAuC5ABhMpBmjw_mbHU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25666, 1418, 8, CONCAT('About The Time I Got a New Little Sister'), NULL, 'https://ebd.cda.pl/800x450/3810142a3');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25667, 1418, 9, CONCAT('Our Special Training at the Theme Park'), NULL, 'https://ebd.cda.pl/800x450/3806446af');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (25668, 1418, 10, CONCAT('It', CHAR(39), 's Okay for Me to Be Moe for Little Sisters'), NULL, 'https://ebd.cda.pl/800x450/380645251');
