INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1487, CONCAT('Pokemon: The Origin'), CONCAT('Pokémon are marvelous creatures that come in a variety of types and sizes, with abilities, powers, and personalities as diverse as they are numerous. Doctor Yukinari Ookido has dedicated his life to studying these fascinating beings, that can be caught, trained, traded, and battled against each other. There', CHAR(39), 's only so much he can do from his lab though. With this in mind, Ookido entrusts two young boys with a Pokémon of their own and a computerized encyclopedia to catalog them. One of them, Green, is brash, passionate, slightly arrogant, and Doctor Ookido', CHAR(39), 's own nephew. The other boy, Red, is equally passionate, and filled with a wide-eyed, mildly naive sense of wonder.<br><br>Pokémon: The Origin follows Red in his journey through the region of Kanto in his attempt to complete his "Pokédex" by capturing and cataloging all the Pokémon that exist. Along the way he', CHAR(39), 'll discover there', CHAR(39), 's more to himself and his goals than he originally thought. Red will have to put both himself and his Pokémon to the test in special Gyms whose leaders are steps along the way to the Pokémon League, in order to challenge the Elite Four and become a Pokémon League Champion.<br>
<br>Aside from his goals to become a Champion, Red has other problems brewing. There are others who capture and train Pokémon for more sinister reasons, with the infamous criminal organization Team Rocket being one of them. If Red can defeat them, fellow trainers, his rival Green, and wild Pokémon all through Kanto, he just may fulfill his own dream, and Doctor Ookido', CHAR(39), 's as well.'), 5, '2013-10-02', NULL, '', '21 min. per ep.', 'https://cdn.myanimelist.net/images/anime/7/53701.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (643, 1487, 4);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3704, 1487, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3705, 1487, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3706, 1487, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3707, 1487, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1599, 1487, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1600, 1487, 96);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1601, 1487, 3);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27192, 1487, 1, CONCAT('Red'), '2013-10-02', 'https://ebd.cda.pl/620x368/6545542c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27193, 1487, 2, CONCAT('Cubone'), '2013-10-02', 'https://ebd.cda.pl/620x368/6547641f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27194, 1487, 3, CONCAT('Giovanni'), '2013-10-02', 'https://ebd.cda.pl/620x368/654926d1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (27195, 1487, 4, CONCAT('Charizard'), '2013-10-02', 'https://ebd.cda.pl/620x368/655010f8');
