INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1537, CONCAT('Recorder to Randoseru Mi☆'), CONCAT('Third season of Recorder to Randoseru.'), 1, '2013-07-08', '2013-09-23', 'Summer 2013', '3 min. per ep.', 'https://cdn.myanimelist.net/images/anime/6/50651.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (656, 1537, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3821, 1537, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3822, 1537, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1655, 1537, 55);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28178, 1537, 1, CONCAT('Recorder and Ransel Mi'), NULL, 'https://www.mp4upload.com/embed-07eri1r2sj4x.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28179, 1537, 2, CONCAT('Sayo and Shelter from the Rain'), NULL, 'https://www.mp4upload.com/embed-mrf1gn10g2vq.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28180, 1537, 3, CONCAT('Inborn Nature and Illegality'), NULL, 'https://mp4upload.com/embed-bwscooaa5s6y.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28181, 1537, 4, CONCAT('Atsushi and the Student Teacher, Miss Kawauchi'), NULL, 'https://mp4upload.com/embed-w0vxp5yfq523.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28182, 1537, 5, CONCAT('Atsushi and the White-Spotted Longhorn Beetle'), NULL, 'https://mp4upload.com/embed-vf36snazruka.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28183, 1537, 6, CONCAT('Take and Job Hunting!'), NULL, 'https://mp4upload.com/embed-ic77p5lb2w1n.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28184, 1537, 7, CONCAT('Tiny and Days of Anguish'), NULL, 'https://mp4upload.com/embed-hx940wlao6t9.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28185, 1537, 8, CONCAT('Soul Brother and Real Brothers'), NULL, 'https://mp4upload.com/embed-9kph0r8hjylk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28186, 1537, 9, CONCAT('Shaky Loves and Horror! A Midsummer', CHAR(39), 's Nightmare!!'), NULL, 'https://mp4upload.com/embed-iqekb2iamxy8.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28187, 1537, 10, CONCAT('Everyone and Summer Vacation - Part 1'), NULL, 'https://mp4upload.com/embed-gvwzd9qg8gsh.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28188, 1537, 11, CONCAT('Everyone and Summer Vacation - Part 2'), NULL, 'https://mp4upload.com/embed-wz40seayfppj.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28189, 1537, 12, CONCAT('Mi is for Me and You and Everyone'), NULL, 'https://mp4upload.com/embed-v67cod44rpv6.html');
