INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1553, CONCAT('Rikei ga Koi ni Ochita no de Shoumei shitemita.'), CONCAT('It is widely believed that science can provide rational explanations for the countless phenomena of our universe. However, there are many aspects of our existence that science has not yet found a solution to and cannot decipher with numbers. The most notorious of these is the concept of love. While it may seem impossible to apply scientific theory to such an intricate and complex emotion, a daring pair of quick-witted Saitama University scientists aim to take on the challenge.<br>
<br>One day the bold and beautiful Ayame Himuro outwardly declares that she is in love with Shinya Yukimura, her fellow logical and level-headed scientist. Acknowledging his own lack of experience with romance, Yukimura questions what factors constitute love in the first place and whether he is in love with Himuro or not. Both clueless in the dealings of love, the pair begin to conduct detailed experiments on one another to test the human characteristics that indicate love and discern whether they demonstrate these traits toward each other.<br>
<br>As Himuro and Yukimura begin their intimate analysis, can the two scientists successfully apply scientific theory, with the help of their friends, to quantify the feelings they express for one another?<br>
<br>[Written by MAL Rewrite]'), 1, '2020-01-11', '2020-03-28', 'Winter 2020', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1432/103533.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3858, 1553, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (3859, 1553, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1670, 1553, 122);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1688, 1553, 1);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1689, 1553, 33);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28397, 1553, 1, CONCAT('Science-types Fell in Love, So They Tried to Analyze It.'), NULL, 'https://ebd.cda.pl/620x368/440334982');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28398, 1553, 2, CONCAT('Science-types Fell in Love, So They Tried Experiments.'), NULL, 'https://ebd.cda.pl/620x368/4429979af');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28399, 1553, 3, CONCAT('Science-types Fell in Love,So They Try Planning a Date'), NULL, 'https://ebd.cda.pl/620x368/448325367');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28400, 1553, 4, CONCAT('Science-types Fell in Love, So They Tried Going on a Date.'), NULL, 'https://drive.google.com/file/d/1Fxz3fR4bJv9-z6hVDSQVI5zz6v46HVFb/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28401, 1553, 5, CONCAT('Science-types Fell in Love, So They Tried Holding a Meeting.'), NULL, 'https://drive.google.com/file/d/1woA8P5YKNd2suUYKKbZzJy0JZ7Wwj1lr/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28402, 1553, 6, CONCAT('Science-types Fell in Love, So They Tried Kissing.'), NULL, 'https://drive.google.com/file/d/1bnTVPeQ-ZsbZRxAhtqoh4pG72kAk96E5/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28403, 1553, 7, CONCAT('So They Tried Having a Drinking Party.'), NULL, 'https://drive.google.com/file/d/1cfIxC0QVKv5IICH4DvWdRl_INpCc9dLA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28404, 1553, 8, CONCAT('Science-types Fell in Love, So They Tried to Gather Evidence of Love'), NULL, 'https://drive.google.com/file/d/1J5oAsXmTRc2AZK1jbqeXyIGl5tp_KcfI/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28405, 1553, 9, CONCAT('Science-types Fell in Love, So They Tried Attending a Training Camp in Okinawa.'), NULL, 'https://drive.google.com/file/d/12qI9SMXsVTWOQLaVWmAQiwdJbpbsgEVg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28406, 1553, 10, CONCAT('Science-types Fell in Love, So They Tried Giving Presentations.'), NULL, 'https://drive.google.com/file/d/1oYI6hZGateZ2HAT4d804JP70afaX1ljK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28407, 1553, 11, CONCAT('Science-types Fell in Love, So They Tried Having a Fight.'), NULL, 'https://drive.google.com/file/d/1cQIHbz6OIZzHe1xJKF4vps3FqkBLDpC0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (28408, 1553, 12, CONCAT('I Knew I Could Fall in Love with You, So I Tried to Prove it'), NULL, 'https://ebd.cda.pl/620x368/50446162c');
