INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1624, CONCAT('School Rumble Ni Gakki'), CONCAT('We still have no idea what', CHAR(39), 's really going on with this show, beyond the fact that the weirdness is piling up!<br>
<br>Curry-fiend Karasama remains oblivious to Tenma', CHAR(39), 's crush, and Harima still hasn', CHAR(39), 't confessed his true feelings to Tenma. But hey, the thug', CHAR(39), 's got an excuse since he', CHAR(39), 's caught up with his comic career and knee-deep in a blizzard of deadlines! Meanwhile, the love triangles are ever-shifting thanks to wannabe cupids and runaway brides.<br>
<br>Even when you throw in a bit of cyborg love, a shipwreck, and a fugitive red panda–seriously, that ain', CHAR(39), 't even scratching the surface. You are encouraged to scratch the pig, though. He likes it! And something rumbles in the next to last episode, no matter what I say next.<br>
<br>School Rumble–The absolutely funniest show you’ll ever see that', CHAR(39), 's not about anything that rumbles... Ever!<br>
<br>(Source: Funimation)'), 1, '2006-04-03', '2006-09-25', 'Spring 2006', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/5/75490.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (693, 1624, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4043, 1624, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4044, 1624, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1747, 1624, 132);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1778, 1624, 38);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1779, 1624, 22);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1780, 1624, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29660, 1624, 1, CONCAT('Scramble Reloaded! Superstar Request! Scandalous Restart!'), '2006-04-03', 'https://drive.google.com/file/d/1hT6PHuW4aD4t94pOb1dSWnfuCTXmcjOw/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29661, 1624, 2, CONCAT('Strategies, Battlefields, Friends'), '2006-04-10', 'https://drive.google.com/file/d/1bkbJClrYK50uMuO_G9qZEMEE_v7wJKNL/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29662, 1624, 3, CONCAT('Beautiful Beast vs. Beautiful Beast! God of War vs. God of Warfare! Teacher vs. Student!'), '2006-04-17', 'https://video.sibnet.ru/shell.php?videoid=4103672');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29663, 1624, 4, CONCAT('Wild Ideas about the Play! Wild Ideas at the Bathhouse! Wild Ideas about Rice Balls!'), '2006-04-24', 'https://drive.google.com/file/d/194I6RBxyXv6xAEkILuyPBgefv-pMhoCA/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29664, 1624, 5, CONCAT('Hostesses Are Culture! Comics Are Culture! Cake is Also Culture!'), '2006-05-01', 'https://drive.google.com/file/d/1jusDM03rB18T1kOgi1aF_4bjR1fG0mAU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29665, 1624, 6, CONCAT('Sleeping Beast! Kiss Impossible! Finale!'), '2006-05-08', 'https://drive.google.com/file/d/1qsNZaKdhRnspiHz43eAmtBQatTnjDyqk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29666, 1624, 7, CONCAT('Fight, Hunter! Fight, Eater! Fight, Part-Time Worker!'), '2006-05-15', 'https://drive.google.com/file/d/1H3wrOFJGLU2GzciHo8DEA2WbWJsH7_6F/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29667, 1624, 8, CONCAT('Bam ★ Birth of a Girls', CHAR(39), ' Basketball Club! Bam ★ If You Please! Bam ★ Swing Set of Tears!'), '2006-05-22', 'https://video.sibnet.ru/shell.php?videoid=4103727');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29668, 1624, 9, CONCAT('Pass! / Dribble! / Shoot!'), '2006-05-29', 'https://drive.google.com/file/d/1hYnscfcmCDhM3GwcRKAD0lnWYY6fLUGT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29669, 1624, 10, CONCAT('Hee! / Hee Hee! / Hee Hee Hee!'), '2006-06-12', 'https://drive.google.com/file/d/1yAynwUggA7jMgzulLH9_KUt5UqREOktl/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29670, 1624, 11, CONCAT('Napoleon, Between Life and Death... Nishimoto, Between Sex and Self-Control... Sara, Between Saintliness and Self...'), '2006-06-19', 'https://drive.google.com/file/d/1jztUB9c8uz5cbjvgz1TQZ6aO_BFCSq02/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29671, 1624, 12, CONCAT('Perfect, Forbidden! Entry, Forbidden! Shorts, Forbidden!'), '2006-06-26', 'https://drive.google.com/file/d/1t35_AfG7Mdy3PWkt8ZH5gtRyvHt2URJg/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29672, 1624, 13, CONCAT('When I Turned Around, There He Was. In Karasuma', CHAR(39), 's Name. All Mysteries Revealed!'), '2006-07-03', 'https://drive.google.com/file/d/1b9KAUMkBbQPtLKWHgQQhoKu_MUZSIr_T/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29673, 1624, 14, CONCAT('At El Cado... In America (26f)... With America (26h)...'), '2006-07-10', 'https://drive.google.com/file/d/14cryXJQCHO3jxoBRGqhJ8Vu9gJLTqZBT/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29674, 1624, 15, CONCAT('A Man Shut Out, A Man Left Out, A Man Tested Out'), '2006-07-17', 'https://drive.google.com/file/d/1bdEkQyMWwatH-9esGTxX2TmT0CecKak8/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29675, 1624, 16, CONCAT('I Don', CHAR(39), 't Want to be Tied to Anyone, I Don', CHAR(39), 't Want to Go to School or Home Anymore, Under the Dark Veil of Night.'), '2006-07-24', 'https://drive.google.com/file/d/14nR8RwMZDQavsjw1XZHf0rtiJYe4G0zs/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29676, 1624, 17, CONCAT('Eri', CHAR(39), 's Escape, Harima', CHAR(39), 's Lullaby, The False Bride.'), '2006-07-31', 'https://drive.google.com/file/d/1Rjg4AOHICADPcIKGpzIirWzvp8MlGeTN/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29677, 1624, 18, CONCAT('The Sweet Trap of Work, The Sweet Trap of the Classroom, The Sweet Trap of Celebrity.'), '2006-08-07', 'https://drive.google.com/file/d/1x7X3oAuNURjtbmOEhQazC0N0H-fFYBsU/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29678, 1624, 19, CONCAT('Here, There and Everywhere, Christmas! A Dash for Christmas! A Shattered Christmas!'), '2006-08-14', 'https://drive.google.com/file/d/1fKPVsBhP30z6BFayH3hUJ6uhAODoT53F/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29679, 1624, 20, CONCAT('More Than Friends... Less Than Lovers... Up Until Then.'), '2006-08-21', 'https://drive.google.com/file/d/15r-CkFSHrH6cKU3EPAtXlTbikoZliJC1/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29680, 1624, 21, CONCAT('This is School Rumble... It Really is School Rumble... It', CHAR(39), 's School Rumble, I Tell You!'), '2006-08-21', 'https://drive.google.com/file/d/127pVqIblkpak81sfKE_sQvNMCQ5t0a_G/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29681, 1624, 22, CONCAT('First Dreams. Lion', CHAR(39), 's Dance. New Year', CHAR(39), 's.'), '2006-08-28', 'https://drive.google.com/file/d/1flJUkNMzqynJm3obm2ka7OCHv5vxVWbf/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29682, 1624, 23, CONCAT('Dream Jumbo. Dream Jump. Dream, uh, Press.'), '2006-09-04', 'https://drive.google.com/file/d/1AtVGUGDGvH89P96IBfo0SfiEc0VZ5K0z/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29683, 1624, 24, CONCAT('Southern Rainbow 2-C! Yakumo of the Mysterious Island! The Seven Seas!'), '2006-09-11', 'https://drive.google.com/file/d/1uHibbB83cW9S5HmycxeVIrZDrPToXdWz/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29684, 1624, 25, CONCAT('It', CHAR(39), 's So Romantic, Harima! Get Published in Zinegama, Harima! Come On, Harima!'), '2006-09-18', 'https://video.sibnet.ru/shell.php?videoid=4103824');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29685, 1624, 26, CONCAT('.'), '2006-09-25', 'https://drive.google.com/file/d/1brnGH0IKIncDoGc-bLk-jE-7CKYC5r6h/preview');
