INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1636, CONCAT('Seiken no Blacksmith'), CONCAT('Forty-four years ago, the surviving nations of the Valbanil War declared peace and forbade the use of the devastating demon contracts that ravaged the land. Now, inexperienced knight Cecily Cambell is eager to follow the example of her family and protect the people of the city using the sword she inherited from her father.<br>
<br>Her first challenge arises in the market. A crazed swordsman wreaks havoc upon civilians and Cecily jumps into action to restore order. Overwhelmed, her weapon shatters, but a skilled stranger wielding a strange-looking sword intervenes. With the situation diffused, Cecily heads to a local blacksmith in an effort to restore her family heirloom. However, she finds out that her savior—the blacksmith Luke Ainsworth—may be the only person capable of such intricate repairs. Determined to have her treasured sword repaired, she seeks out the man who rescued her.<br>
<br>However, a group of bandits suddenly attack a convoy headed for the city. The assailants look inhuman, and an ice demon appears. Luke suspects the use of a demon contract and calls upon a sacred power to defeat them. Meanwhile, a shadowy hooded figure lurks, watching from a distance. Who is this mysterious evildoer, and what does his appearance mean for the pair?<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2009-10-03', '2009-12-19', 'Fall 2009', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/15940.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4070, 1636, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4071, 1636, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4072, 1636, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1760, 1636, 17);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29861, 1636, 1, CONCAT('Knight'), '2009-10-03', 'https://video.sibnet.ru/shell.php?videoid=662992');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29862, 1636, 2, CONCAT('Devil', CHAR(39), 's Contract - Valbanill'), '2009-10-10', 'https://video.sibnet.ru/shell.php?videoid=662997');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29863, 1636, 3, CONCAT('Demon Sword'), '2009-10-17', 'https://video.sibnet.ru/shell.php?videoid=663013');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29864, 1636, 4, CONCAT('Pledge'), '2009-10-24', 'https://myvi.ru/player/embed/html/oGHQECAAifjjU_dOxm1AGwaG6AuVQWg-4FjAHxwF8HftJ_o1UDJ1agJDaDxXrdZwV0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29865, 1636, 5, CONCAT('Ties - Together'), '2009-10-31', 'https://myvi.ru/player/embed/html/oS8Fi68TMdiVRZZZ8Xag3DjLCyFcsvNrwjv-huloenG0h4K-aGOcLTGn39XenCOOL0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29866, 1636, 6, CONCAT('Princess'), '2009-11-07', 'https://video.sibnet.ru/shell.php?videoid=663017');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29867, 1636, 7, CONCAT('Family'), '2009-11-14', 'https://vk.com/video_ext.php?oid=169916132&id=163397418&hash=8983018f98ffe183&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29868, 1636, 8, CONCAT('Departure - Resolution'), '2009-11-21', 'https://vk.com/video_ext.php?oid=169916132&id=163396506&hash=d6e47b8bd0bb75ee&hd=2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29869, 1636, 9, CONCAT('Remnants - Lisa'), '2009-11-28', 'https://video.sibnet.ru/shell.php?videoid=663502');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29870, 1636, 10, CONCAT('Victim of Love - Tragedy'), '2009-12-05', 'https://myvi.ru/player/embed/html/obYm4cE8lFAIKtycqBTLmgu8viwAW6nLwkC1mHPaiTMHx4pp-VvtifWTX3NijDa2w0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29871, 1636, 11, CONCAT('Truth'), '2009-12-12', 'https://video.sibnet.ru/shell.php?videoid=663622');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29872, 1636, 12, CONCAT('Blacksmith'), '2009-12-19', 'https://myvi.ru/player/embed/html/oIrrMjCf4-1gnk5tzKBUe02-4HcH0DGOqjJFG8kkrAZeXjsNSyyP35JoF37eluhve0');
