INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1632, CONCAT('Seikai no Senki II'), CONCAT('Due to a lack of ambassadors for the recently-conquered worlds the rapidly advancing fleet of the Bebaus brothers leave behind, Lafiel is appointed Territorial Ambassador of the planet Lobnas II. Upon arriving to the planet Jinto and Lafiel discover that the planet was used by the United Mankind as a prison planet and now has a million prisoners on the only inhabited island. The prisoners are parted in three blocks. The western where women are housed, the eastern belongs to the men and the central is mixed under the restriction that all prisoners living there are sterilized. The women in the western sector want to emigrate from the planet of fear for the men and when they do the men in the east rebel, overthrowing the guards and capturing Jinto to try to stop the emigration of the women. At the same time an enemy fleet heads toward the system forcing Lafiel to abandon Jinto.<br>
<br>(Source: ANN)'), 1, '2001-07-11', '2001-09-26', 'Summer 2001', '25 min. per ep.', 'https://cdn.myanimelist.net/images/anime/12/61109.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4066, 1632, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4067, 1632, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1755, 1632, 111);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1791, 1632, 20);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1792, 1632, 25);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1793, 1632, 45);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29836, 1632, 1, CONCAT('Operation Hunter'), '2001-07-11', 'https://mp4upload.com/embed-mcrjld5cjnpd.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29837, 1632, 2, CONCAT('Planet of Exile'), '2001-07-18', 'https://mp4upload.com/embed-redg8hdyexs6.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29838, 1632, 3, CONCAT('Emigration Plan'), '2001-07-25', 'https://mp4upload.com/embed-rjqj5swlacgk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29839, 1632, 4, CONCAT('The Hunters'), '2001-08-01', 'https://mp4upload.com/embed-9r4oe4ta5r75.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29840, 1632, 5, CONCAT('Rebellion'), '2001-08-08', 'https://mp4upload.com/embed-3qrxgiek6zvl.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29841, 1632, 6, CONCAT('Abh Hell'), '2001-08-15', 'https://mp4upload.com/embed-al53k7xaeshn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29842, 1632, 7, CONCAT('The Flag of Gasarus'), '2001-08-29', 'https://mp4upload.com/embed-n7cme95chsoo.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29843, 1632, 8, CONCAT('Things to Protect'), '2001-09-12', 'https://mp4upload.com/embed-vmhkc7tnkm03.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29844, 1632, 9, CONCAT('To Lay Down the Bow'), '2001-09-21', 'https://mp4upload.com/embed-czdhgy41u49b.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (29845, 1632, 10, CONCAT('An Abriel', CHAR(39), 's Tears'), '2001-09-26', 'https://mp4upload.com/embed-d324sr80r7eb.html');
