INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1651, CONCAT('Sekai Seifuku: Bouryaku no Zvezda'), CONCAT('Asuta Jimon, a runaway, is wandering the streets at night when he has a chance encounter with a young girl collapsed beside her tricycle. After he offers her some food, she is moved by his kindness and asks him to join her organization, offering him a face mask and a sweet bun. In need of a place to stay, Asuta decides to play along and accepts her offer, adopting the nickname "Dva." <br>
<br>Little does Dva know, this cute girl is Kate Hoshimiya, the leader of Zvezda, a secret organization bent on world conquest. However, he soon realizes the true weight of her words as peculiar happenings rope him deeper into Zvezda and its eccentric members—the samurai-like vanguard Itsuka Shikabane, tech-genius Natalia "Natasha" Vasylchenko, troublesome Yasubee "Yasu" Morozumi, ex-gangster Gorou Shikabane, and multi-purpose robot Roboko Tsujii. <br>
<br>With "White Light," a powerful organization of justice, and the entire Japanese government against them, can Zvezda really dominate all humanity and let their light shine throughout the world?<br>
<br>[Written by MAL Rewrite]'), 1, '2014-01-12', '2014-03-30', 'Winter 2014', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/2/56133.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4109, 1651, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4110, 1651, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4111, 1651, 9);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1777, 1651, 6);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30058, 1651, 1, CONCAT('Conquer All Humans'), NULL, 'https://myvi.ru/player/embed/html/oFxB-qgsU9bKaiEual-WPDJp9PjejG9recqeHtngYVIPDnIUqyvfwKspgy3ELXa8b4NJm6OdpusM1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30059, 1651, 2, CONCAT('From the Dining Table To the Grave'), NULL, 'https://myvi.ru/player/embed/html/oawAjmv2JI7NiZD2-8l-x4Z7e5U5Z0MTbjxMqCRX6Yekqa79RdjeOmU0U_0257nwwL1IXP5FuaM41');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30060, 1651, 3, CONCAT('Hiding Behind Smoke and Mirrors'), NULL, 'https://myvi.ru/player/embed/html/oiAIr2Gz06kRXZ83Ff8n5KHNnCaNyheWPar6F6ca5PJN7PSvSZMh_O1Sbn-0A6xCz2-0xikLkgTU1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30061, 1651, 4, CONCAT('Udo', CHAR(39), 's in the Cold Ground'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1378554');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30062, 1651, 5, CONCAT('White Robin in Danger'), NULL, 'https://myvi.ru/player/embed/html/oAcVrVJhYtjBu9tmTNrkjoUFJscuyjoHq3SFieB8yyhnus75NSu_2h5co6HqnfFqecUOQu_M9cdI1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30063, 1651, 6, CONCAT('After School Treasure Club (Part 1)'), NULL, 'https://myvi.ru/player/embed/html/oq62QZ7bx-SX-3K1bvQH9ruV4OO1kduwqlU6rc_MI-x3nQwSLcMIAtW_bnHGBUaI20iQeOGRzmO81');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30064, 1651, 7, CONCAT('After School Treasure Club (Part 2)'), NULL, 'https://myvi.ru/player/embed/html/o1HpVjisZOlZ7xIQA-BJR7zqC8yFeerEucCTn6MJ1m2oiahUj61WP9qLzf2MZROgUR9tvNTGK41Q1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30065, 1651, 8, CONCAT('The Falcon Has Landed'), NULL, 'https://myvi.ru/player/embed/html/o6zK0GeVep25AogS_zqA7ypV8Gs9j08viBqzmpv5zHLa6A703IYww6wHWBlVvN6YTW9CBFAwaCTQ1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30066, 1651, 9, CONCAT('Steamy Masquerade'), NULL, 'https://myvi.ru/player/embed/html/oa7_tVQrHMQwpkrhw_VZqYVgH_lMR1wmxlmntHVNaopEFBJcwOvwerqJCrdkGp3bG-89Vyb2bl8I1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30067, 1651, 10, CONCAT('Not All Quiet on the West Udogawa Front'), NULL, 'https://video.sibnet.ru/shell.php?videoid=1433987');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30068, 1651, 11, CONCAT('All That Remains of Conqueror', CHAR(39), 's Dreams'), NULL, 'https://myvi.ru/player/embed/html/oDLfSezhTvqGUxhlCgk05fDd1ioHZyTZkuj1MYo6rcmoMkajoNfod6KLx6DphJ57-EQISlRuueiA1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30069, 1651, 12, CONCAT('May the Light of Zvezda Shine Throughout this World'), NULL, 'https://myvi.ru/player/embed/html/oVS6q3HTSZTKCklDZpWicfw39zCh54NK5bSownxrfXN2Hhj-SYyevfq0zvakUW4g-XjIgNtM-NkQ1');
