INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1685, CONCAT('Shakugan no Shana'), CONCAT('The world has become a slaughtering ground for the Crimson Denizens, mysterious beings from a parallel universe who thrive on the life energy of humans. These merciless murderers only leave behind scant remainders of souls called "Torches," which are mere residues that will eventually be destroyed, along with the very fact of the victims', CHAR(39), ' existence from the minds of the living. In an ambitious endeavor to put an end to this invisible, hungry massacre, warriors called Flame Hazes relentlessly fight these monsters.<br>
<br>One fateful day, Yuuji Sakai ceases to be a regular high schooler—he becomes trapped in a crevice of time and is suddenly attacked by a Denizen. Coming to his rescue just in the nick of time is a nameless hunter who seems no different from an ordinary young girl except for her blazing eyes and burning crimson hair. However, before Yuuji can learn anything more about his situation, he discovers that he has already been reduced to a Torch—merely a scrap of memory waiting to be extinguished.<br>
<br>[Written by MAL Rewrite]'), 1, '2005-10-06', '2006-03-23', 'Fall 2005', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/21197.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4173, 1685, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4174, 1685, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4175, 1685, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4176, 1685, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4177, 1685, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1818, 1685, 31);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1866, 1685, 30);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (1867, 1685, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30515, 1685, 1, CONCAT('The End to Everything, the One Beginning'), '2005-10-06', 'https://drive.google.com/file/d/1yHLZYad4P3G7cQ-27gGl8kq8mAE5_8LH/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30516, 1685, 2, CONCAT('The Lit Flame'), '2005-10-13', 'https://drive.google.com/file/d/173Y-8GgCOkxhD79ukWv2CG5locBXpoL3/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30517, 1685, 3, CONCAT('The Torch and The Flame Haze'), '2005-10-20', 'https://drive.google.com/file/d/19hLfBo60vUgbm0WC-HJ_-l9ZDiBPR3Tn/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30518, 1685, 4, CONCAT('The Confused Flame Haze'), '2005-10-27', 'https://drive.google.com/file/d/1yX5niLVoZbq-v8Q1ovD2fsFyUvjW7s-j/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30519, 1685, 5, CONCAT('Respective Thoughts'), NULL, 'https://drive.google.com/file/d/1rPdkutA2RCVCE6aD3Otr84IKul-c6FeK/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30520, 1685, 6, CONCAT('Complication. Activation. Confrontation'), NULL, 'https://drive.google.com/file/d/12RQ5opwf4RWMFz1DT8uqUA-ukqVw8wdc/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30521, 1685, 7, CONCAT('The Two Flame Hazes'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4054051');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30522, 1685, 8, CONCAT('The Beautiful Goblet'), NULL, 'https://drive.google.com/file/d/1q5PRedXNQFF2B3iOijIh497L666YyBjl/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30523, 1685, 9, CONCAT('The Poolside of Love and Desire'), NULL, 'https://drive.google.com/file/d/1-iea_0PpC4_QbL6KnvlFTBuPEbs61Zln/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30524, 1685, 10, CONCAT('Entangled Feelings'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4054080');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30525, 1685, 11, CONCAT('Yuuji, Shana and a Kiss'), NULL, 'https://ebd.cda.pl/620x395/567336557');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30526, 1685, 12, CONCAT('The Flower that Blooms in the Cradle'), NULL, 'https://ebd.cda.pl/620x395/56733928d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30527, 1685, 13, CONCAT('Declaration of War Behind The School'), NULL, 'https://ebd.cda.pl/620x395/567337118');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30528, 1685, 14, CONCAT('A Great Person'), NULL, 'https://video.sibnet.ru/shell.php?videoid=4054114');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30529, 1685, 15, CONCAT('The Day the Flame Was Born'), NULL, 'https://ebd.cda.pl/800x450/56734169a');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30530, 1685, 16, CONCAT('Slaying Hand of Shakugan'), NULL, 'https://ebd.cda.pl/800x450/567344032');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30531, 1685, 17, CONCAT('A New Chapter'), NULL, 'https://ebd.cda.pl/620x395/5673443eb');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30532, 1685, 18, CONCAT('Shattered Wish'), NULL, 'https://ebd.cda.pl/800x450/567339522');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30533, 1685, 19, CONCAT('Within the Battle'), NULL, 'https://ebd.cda.pl/620x395/56734343c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30534, 1685, 20, CONCAT('Heartless Wirhelmina'), NULL, 'https://ebd.cda.pl/620x395/567344904');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30535, 1685, 21, CONCAT('Diverging Feelings'), NULL, 'https://ebd.cda.pl/800x450/56734018d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30536, 1685, 22, CONCAT('The Flickering Flame'), NULL, 'https://ebd.cda.pl/620x395/56733864e');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30537, 1685, 23, CONCAT('Battle at the Palace of the Stars'), NULL, 'https://ebd.cda.pl/620x395/567338987');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (30538, 1685, 24, CONCAT('Crimson Thoughts'), NULL, 'https://drive.google.com/file/d/1GmZRsJilbzSRDmEoeIBIJUtI7DRSgMWg/preview');
