INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1814, CONCAT('SteinsGate'), CONCAT('Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Rintarou founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable "gadget" the trio have created is a microwave that has the mystifying power to turn bananas into green goo.<br>
<br>However, when Rintarou decides to attend neuroscientist Kurisu Makise', CHAR(39), 's conference on time travel, he experiences a series of strange events that lead him to believe that there is more to the "Phone Microwave" gadget than meets the eye. Apparently able to send text messages into the past using the microwave, Rintarou dabbles further with the "time machine," attracting the ire and attention of the mysterious organization SERN.<br>
<br>Due to the novel discovery, Rintarou and his friends find themselves in an ever-present danger. As he works to mitigate the damage his invention has caused to the timeline, he is not only fighting a battle to save his loved ones, but also one against his degrading sanity.<br>
<br>[Written by MAL Rewrite]'), 2, '2011-04-06', '2011-09-14', 'Spring 2011', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4490, 1814, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4491, 1814, 3);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1964, 1814, 38);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32620, 1814, 1, CONCAT('Turning Point'), '2011-04-06', 'https://drive.google.com/file/d/1Tz_o9CXMpRMh4j6f8I4Z4iYaVtCnMW4O/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32621, 1814, 2, CONCAT('Time Travel Paranoia'), '2011-04-13', 'https://drive.google.com/file/d/1igPAIuMx_-UUq5cPfzIHnjFnXpWEZ16a/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32622, 1814, 3, CONCAT('Parallel World Paranoia'), '2011-04-20', 'https://drive.google.com/file/d/1-bLQTDJ79cve8y3RGxe6us8aVnU_Igiu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32623, 1814, 4, CONCAT('Interpreter Rendezvous'), '2011-04-27', 'https://drive.google.com/file/d/15OD69hBTpsNAjfz5hW7WjO_zuVPQIId-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32624, 1814, 5, CONCAT('Starmine Rendezvous'), '2011-05-04', 'https://drive.google.com/file/d/1SSvNn5o7SgKzdHC9nkajaWKkaZ46HefV/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32625, 1814, 6, CONCAT('Butterfly Effect', CHAR(39), 's Divergence'), '2011-05-11', 'https://drive.google.com/file/d/1AQ9u_jXAeG8gvrU5lSRijWQvGe3ScflD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32626, 1814, 7, CONCAT('Divergence Singularity'), '2011-05-18', 'https://drive.google.com/file/d/1LRQ90BOojPxbA3Eggh5wQohZGSa_5GpB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32627, 1814, 8, CONCAT('Chaos Theory Homeostasis I'), '2011-05-25', 'https://drive.google.com/file/d/1wIodTBxfbXBc0crqPKcL4J-yPwNi6cki/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32628, 1814, 9, CONCAT('Chaos Theory Homeostasis II'), '2011-06-01', 'https://drive.google.com/file/d/1lYeP4IDN58qFq27ZkmkNeTa0DBiqxhbM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32629, 1814, 10, CONCAT('Chaos Theory Homeostasis III'), '2011-06-08', 'https://drive.google.com/file/d/197boFxWVSdQRaSVWWOGwVo1d1_4YrTRp/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32630, 1814, 11, CONCAT('Dogma in Event Horizon'), '2011-06-15', 'https://drive.google.com/file/d/1xdTo9QKTGyEgInvyyeMMdPdyipEME7bS/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32631, 1814, 12, CONCAT('Dogma in Ergosphere'), '2011-06-22', 'https://drive.google.com/file/d/1Udw6Y3ZV6-p5PkyWwaaFWpp9bTmcr7By/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32632, 1814, 13, CONCAT('Metaphysics Necrosis'), '2011-06-29', 'https://drive.google.com/file/d/1YrdEInBwLZoPsRYxI3SkpGNuJ4FsA3VH/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32633, 1814, 14, CONCAT('Physically Necrosis'), '2011-07-06', 'https://drive.google.com/file/d/1q12pfmkx7OwkZDuxUAJxNo6yZIClbpyG/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32634, 1814, 15, CONCAT('Missing Link Necrosis'), '2011-07-13', 'https://drive.google.com/file/d/1AQpAmd4d5FcgYXskTJhefurUbNX1amyt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32635, 1814, 16, CONCAT('Sacrificial Necrosis'), '2011-07-20', 'https://drive.google.com/file/d/1s9NqNylCuUv0JBOGeJKbaksJQKSjFP6l/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32636, 1814, 17, CONCAT('Made in Complex'), '2011-07-27', 'https://drive.google.com/file/d/1h8xWkp9--086T1Ej0t9OOi_bKbBwXeOi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32637, 1814, 18, CONCAT('Fractal Androgynous'), '2011-08-03', 'https://drive.google.com/file/d/1n_SUDQrjH-SfCJjrLijknjZ3WCNEevGu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32638, 1814, 19, CONCAT('Endless Apoptosis'), '2011-08-10', 'https://drive.google.com/file/d/1_uIOsCWi-SnmeZB8sMPnrQnI_dpJePq3/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32639, 1814, 20, CONCAT('Finalize Apoptosis'), '2011-08-17', 'https://drive.google.com/file/d/14qf9PYVDmwwTjOm3ElvmauGz2ElUnSdY/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32640, 1814, 21, CONCAT('Paradox Meltdown'), '2011-08-24', 'https://drive.google.com/file/d/17sGt7ZDABMati5wDkVYuHw41CVDQD16-/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32641, 1814, 22, CONCAT('Being Meltdown'), '2011-08-31', 'https://drive.google.com/file/d/1IfQAwBvuDL3Ck9QbPi6AfjRmQEm9eZ2B/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32642, 1814, 23, CONCAT('Open the Steins Gate'), '2011-09-07', 'https://drive.google.com/file/d/1q8z-KSrjJUVjyjhDhodllg1qmJKRHoII/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32643, 1814, 24, CONCAT('Achievement Point'), '2011-09-14', 'https://drive.google.com/file/d/1WTZG4UNJQ7ycbdqsSrfkG2IRMMrRZk8y/preview');
