INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1829, CONCAT('Sumomomo Momomo: Chijou Saikyou no Yome'), CONCAT('Koushi Inuzuka is a smart high school student who aims to become a public prosecutor. Unfortunately for our good guy, he was born into a martial arts family whose head (ie his father) only knows one language: violence. When Koushi was still a baby, his father made a pact with his biggest rival to marry Koushi to his opponent-turned-friend', CHAR(39), 's daughter. The union of the two blood lines is supposed to bring forth Earth', CHAR(39), 's strongest martial arts clan. <br>
<br>Skip forward: Koushi is in high school, oblivious to the marriage arranged for him at his birth. Enter Momoko Kuzuryuu: sugar bomb, airhead, loli martial arts artist and Koushi', CHAR(39), 's self-proclaimed bride (the strongest on Earth, no less). Her wish for sexual intercourse meets with Koushi', CHAR(39), 's square refusal as he has absolutely no desire to get it on with someone who looks like she could be his little sister, not to mention that he doesn', CHAR(39), 't have the foggiest idea who she actually is. <br>
<br>Meanwhile, a war has broken out between the martial arts families. For Koushi, this means that numerous fighters are out to challenge/assassinate him. As if that weren', CHAR(39), 't bad enough, our protagonist also has a fight phobia due to a traumatic incident that took place in his childhood. Now it', CHAR(39), 's up to Momoko and her superhuman fighting skills to protect her "husband." Will the two sweethearts survive the trials and tribulations ahead of them? More importantly, will Momoko get her way receiving a baby from Koushi? <br>
<br>(Source: Kotonoha) '), 1, '2006-10-06', '2007-03-16', 'Fall 2006', '24 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/2357.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (762, 1829, 2);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4526, 1829, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4527, 1829, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4528, 1829, 7);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (1983, 1829, 196);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32847, 1829, 1, CONCAT('The Strongest Fiancé on Earth'), '2006-10-06', 'https://video.sibnet.ru/shell.php?videoid=635152');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32848, 1829, 2, CONCAT('Natural Exploding Girl'), '2006-10-13', 'https://video.sibnet.ru/shell.php?videoid=637886');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32849, 1829, 3, CONCAT('Caught in the Zoo'), '2006-10-20', 'https://video.sibnet.ru/shell.php?videoid=636862');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32850, 1829, 4, CONCAT('The Immoral Assassination Plot'), '2006-10-27', 'https://video.sibnet.ru/shell.php?videoid=636858');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32851, 1829, 5, CONCAT('Clash! Momoko VS Iroha'), '2006-11-03', 'https://streamtape.com/e/3keWk8QzRaHd1pz/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32852, 1829, 6, CONCAT('The Tiger Assassin, Appears!'), '2006-11-10', 'https://streamtape.com/e/1jKAVQGPexI0Rx/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32853, 1829, 7, CONCAT('The Invisible Link'), '2006-11-17', 'https://streamtape.com/e/1W86AdZmYJh6wZ/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32854, 1829, 8, CONCAT('The Underclassman Who Calls Upon Storms'), '2006-11-24', 'https://myvi.ru/player/embed/html/oROKTAZPhGP1-_yRyoclhHPJbx_uzX6wsh8e5keoDBZOb_PvNIdNTYTb7o77_m7iF0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32855, 1829, 9, CONCAT('The Heroine of Tragic Love'), '2006-12-01', 'https://myvi.ru/player/embed/html/on37DPs2iCweFw_SbVWthE75m3FVTeuKEtZI_4b0TwoJ1ca27mmnyDFYX92qsaZnx0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32856, 1829, 10, CONCAT('Sanae', CHAR(39), 's Fiancé Appears'), '2006-12-08', 'https://streamtape.com/e/vgzwjBqJD7FwwG/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32857, 1829, 11, CONCAT('Heaven', CHAR(39), 's Punishment Warrior Horse Mask, Arrives'), '2006-12-15', 'https://myvi.ru/player/embed/html/oahiz8flVSC8NwuPiaBBH6P0Z3zXUSFqMa1upDlOeMTAB8_xA2nv1hQzhhaVpRbEP0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32858, 1829, 12, CONCAT('The Day of a Cold, Hanzou', CHAR(39), 's Situation'), '2006-12-22', 'https://myvi.ru/player/embed/html/owQ-kFRq6KNMDCbkslryp7pFM5dsDovzHAGozbreU7dAqxD4V84FUGg6L0GnaUQyc0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32859, 1829, 13, CONCAT('Confrontation of Rivals! The Horse and the Tortoise'), '2007-01-12', 'https://video.sibnet.ru/shell.php?videoid=647840');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32860, 1829, 14, CONCAT('The Love Chaos in the Haunted House'), '2007-01-19', 'https://myvi.ru/player/embed/html/oUBUwD7A-zhNM2ub4iCq2CSqj_PdAzypEy5lL-Sd1IlN9o2wWlZWp-t3CCfvBQklA0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32861, 1829, 15, CONCAT('Saigou', CHAR(39), 's Love'), '2007-01-26', 'https://myvi.ru/player/embed/html/oxJYEBLKzLKCMg0g5QoUgwLAHTRDHh54JZyuAu0sMqnaGeeS_iM80x_HBzrXQLEvt0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32862, 1829, 16, CONCAT('How to Destroy a Fatigue Period'), '2007-02-02', 'https://myvi.ru/player/embed/html/o8ErMVAo6gj7vk8TZ21OHaHeZ5jcPlbLbPk-YqQhRZauERx9TeC8-4PGFx5jQD65Y0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32863, 1829, 17, CONCAT('Fierce Fight! The Tiger Brothers'), '2007-02-09', 'https://myvi.ru/player/embed/html/oex5ZEfbLPzYkzsD39GPy4IUkEM2hQIWG8rFl12gV7Dnqe1nWwTF5ubi5WV_yMm5B0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32864, 1829, 18, CONCAT('A Welcome Party with Yaminabe!?'), '2007-02-16', 'https://video.sibnet.ru/shell.php?videoid=647795');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32865, 1829, 19, CONCAT('The Housekeeper Came!'), '2007-02-23', 'https://streamtape.com/e/A0rXrYV93ACmxe/');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32866, 1829, 20, CONCAT('Together with Fate...'), '2007-03-02', 'https://myvi.ru/player/embed/html/oUzthphsUDiFcDLDnWkQHsJl2V53sRtfl4ji43a0KZ8Fe1ZIwqkdP1AGuPfgmkN2V0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32867, 1829, 21, CONCAT('Respective Thoughts...'), '2007-03-09', 'https://myvi.ru/player/embed/html/oWjiRuHX2AERpOockizUnDJYGnvHBPNbnfdlLaepwP19hLO1GYeYUjKmbuc26RF2G0');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (32868, 1829, 22, CONCAT('To the Usual Days'), '2007-03-16', 'https://myvi.ru/player/embed/html/o7VV1jmIkXYrRmxbWYwm4EIKCqlP_IbJPdcjbqB3LlDQQ2jvzJOr6DE6GnoBek6Y70');
