INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1930, CONCAT('Tomodachi Game'), CONCAT('High school student Yuuichi Katagiri cherishes his close circle of friends, composed of four classmates: Yutori Kokorogi, Shiho Sawaragi, Makoto Shibe, and Tenji Mikasa. However, when the funds for the upcoming school trip are stolen, the incident causes Shiho and Makoto—who had been tasked with collecting the money—to distance themselves from the rest of their class.<br>
<br>Soon after, Yuuichi and his friends are deceived into meeting up and knocked unconscious by unknown assailants. After waking, the group find themselves confined in a white room with controversial figure Manabu-kun, who reveals that one of the five has gathered them together to clear their personal debt of twenty million yen. To pay off the amount, they must participate in a variety of psychological games that will test the true nature of their friendship and humanity.<br>
<br>Distressed and isolated from the outside world, Yuuichi and his friends need to cooperate to complete the games. But as their concealed feelings and problematic pasts begin to surface, their seemingly unbreakable bond may soon shatter into irreparable pieces.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-04-06', '2022-06-22', 'Spring 2022', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1247/121345.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (803, 1930, 1);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2094, 1930, 41);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2145, 1930, 37);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2146, 1930, 4);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2147, 1930, 9);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34306, 1930, 1, CONCAT('Huh? Yuichi-kun Suspects His Friends?'), '2022-04-06', 'https://ebd.cda.pl/620x395/11547530d7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34307, 1930, 2, CONCAT('You Have a Lot to Say to Me, Don', CHAR(39), 't You?'), '2022-04-13', 'https://drive.google.com/file/d/1uSdzwDL5TrfGdXuQN3CnSyBh_cjev9Hj/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34308, 1930, 3, CONCAT('There', CHAR(39), 's No Way I', CHAR(39), 'd Believe That'), '2022-04-20', 'https://drive.google.com/file/d/1H5kH5r-rPquI0wIXw8K9htnVtnvH_S-k/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34309, 1930, 4, CONCAT('Seriously? That', CHAR(39), 's So Cringe'), '2022-04-27', 'https://drive.google.com/file/d/1zMthE0817SSFxqrL01NpnDbKr8Rv8zPP/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34310, 1930, 5, CONCAT('Yuichi-kun, You', CHAR(39), 're Pretty Dumb, Aren', CHAR(39), 't You?'), '2022-05-04', 'https://drive.google.com/file/d/1juAyKeXg3GbAq8qeoieaSN-HJumh3Gjo/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34311, 1930, 6, CONCAT('I Really Can', CHAR(39), 't Be Friends with a "Murderer"'), '2022-05-11', 'https://drive.google.com/file/d/15nBgnTCxp090bTfx_c6NTWl_Y66oTSEi/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34312, 1930, 7, CONCAT('I', CHAR(39), 'll Take 20 Million Yen Worth of Your Life'), '2022-05-18', 'https://drive.google.com/file/d/1UaAWT8Z9j2cNzkAdH_dVHd1zLXOV6Az0/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34313, 1930, 8, CONCAT('It', CHAR(39), 's a Game Where You Wait, and Wait, and Wait... and Keep Waiting'), '2022-05-25', 'https://drive.google.com/file/d/1_FEwjcFHg-tPjQrd6S-WEoHG3CWmsZrG/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34314, 1930, 9, CONCAT('Hurry Up and Switch Sides'), '2022-06-01', 'https://ebd.cda.pl/620x368/11711807ad');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34315, 1930, 10, CONCAT('The Third Game Is Over!'), '2022-06-08', 'https://ebd.cda.pl/620x368/1182650375');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34316, 1930, 11, CONCAT('Do You Really Have Nothing You Care About?'), '2022-06-15', 'https://ebd.cda.pl/620x368/11828147d5');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34317, 1930, 12, CONCAT('What', CHAR(39), 's Most Important to Me Is...'), '2022-06-22', 'https://drive.google.com/file/d/1o9oaq3pDzA1s8mByfex0PHXXX_sTMWGY/preview');
