INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1973, CONCAT('Uchouten Kazoku 2'), CONCAT('After uncovering the truth behind their father', CHAR(39), 's untimely death, life for the four Shimogamo brothers returns to relative peace with each trying to live up to their father', CHAR(39), 's greatness in their own way. For the eldest, Yaichirou, who aims to become the next Trick Magister and leader of the tanuki society, it starts with reinstating the popular shogi tournament. For Yajirou, it is restoring his former shapeshifting abilities, whilst little Yashirou is content with continuing his work at the family’s factory. But for the third son, Yasaburou, it simply means embracing the "fool', CHAR(39), 's blood" he inherited from his father and living a carefree but interesting life. This, of course, includes hunting for the mysterious and elusive snake-like creature known as a tsuchinoko, and causing ripples of trouble at every turn.<br>
<br>However, these ripples threaten to turn into waves with the return of Nidaime, the estranged son of the brothers', CHAR(39), ' tengu teacher, Professor Akadama. Nidaime bears a grudge against not only his father, but his father', CHAR(39), 's apprentice Benten as well. His loyalties suddenly brought into question, Yasaburou must use his tanuki wit to appease all sides without getting caught in the crossfire, before the delicate balance between human, tengu, and tanuki is overthrown and all hell breaks loose.<br>
<br>[Written by MAL Rewrite]'), 1, '2017-04-09', '2017-06-25', 'Spring 2017', '23 min. per ep.', 'https://cdn.myanimelist.net/images/anime/8/85354.jpg');
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4921, 1973, 13);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4922, 1973, 12);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4923, 1973, 6);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4924, 1973, 9);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (4925, 1973, 8);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2140, 1973, 52);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34856, 1973, 1, CONCAT('The Nidaime', CHAR(39), 's Homecoming'), '2017-04-09', 'https://www.mp4upload.com/embed-bzteu93cbfyk.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34857, 1973, 2, CONCAT('The Conjurer Tenmaya'), '2017-04-16', 'https://www.mp4upload.com/embed-bh0kl6ka8274.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34858, 1973, 3, CONCAT('The Scent of Europe'), '2017-04-23', 'https://www.mp4upload.com/embed-w2yh104kgn48.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34859, 1973, 4, CONCAT('The Tanuki Shogi Tournament'), '2017-04-30', 'https://www.mp4upload.com/embed-niaq4h235nfn.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34860, 1973, 5, CONCAT('Daimonji Luxury Liner Battle Continued'), '2017-05-07', 'https://www.mp4upload.com/embed-38ulidg445vs.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34861, 1973, 6, CONCAT('Arima Hell'), '2017-05-14', 'https://www.mp4upload.com/embed-hlsxwirgprwv.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34862, 1973, 7, CONCAT('The Friday Club Once More'), '2017-05-21', 'https://drive.google.com/file/d/0BzPe0Wj3xolQMm81dzJsTWRrUEk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34863, 1973, 8, CONCAT('Ebisugawa Kaisei', CHAR(39), 's Secret'), '2017-05-28', 'https://www.mp4upload.com/embed-vw0qeli361np.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34864, 1973, 9, CONCAT('The Various Nidaime'), '2017-06-04', 'https://www.mp4upload.com/embed-yf0ex1qsunxu.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34865, 1973, 10, CONCAT('The Day the Trick Magister Is Chosen'), '2017-06-11', 'https://www.mp4upload.com/embed-b5tch3aistoo.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34866, 1973, 11, CONCAT('The Blood of the Tengu, the Blood of the Fool'), '2017-06-18', 'https://www.mp4upload.com/embed-i45dqwwmmcig.html');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (34867, 1973, 12, CONCAT('The Red String of Fate'), '2017-06-25', 'https://video.sibnet.ru/shell.php?videoid=3044912');
