INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (1980, CONCAT('Ueno-san wa Bukiyou'), CONCAT('As the head of her middle school', CHAR(39), 's science club, it', CHAR(39), 's only fitting that Ueno is also a brilliant inventor. With devices that can convert any liquid into drinkable water, deodorize the most foul smells, or even generate dark matter to be used as a means of concealment, it seems like nothing is beyond Ueno', CHAR(39), 's capabilities. However, she doesn', CHAR(39), 't invent these devices for the advancement of mankind. Rather, the one force that motivates her is love, the only phenomenon she can', CHAR(39), 't quite figure out.<br>
<br>Ueno is head over heels for Tanaka, her nonchalant fellow club member. Yet, because she is too nervous to confess her love and he is too oblivious to notice her affection, her love life is completely stagnant. In Ueno', CHAR(39), 's mind, if she could just expose him to perverted situations, then surely he', CHAR(39), 'd get flustered and fall for her, right? Assisted by her stone-faced classmate and dedicated wingwoman Yamashita, Ueno employs her many inventions on Tanaka in a lewd manner in hopes that he may one day understand how she feels.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2019-01-07', '2019-03-25', 'Winter 2019', '12 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1874/111374.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (823, 1980, 2);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2148, 1980, 107);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2194, 1980, 16);
INSERT INTO AnimeThemes(BindingID, AnimeID, ThemeID) VALUES (2195, 1980, 13);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35056, 1980, 1, CONCAT('ROCKER-KUN / KUMATANDER NO. 2'), NULL, 'https://ebd.cda.pl/620x368/34507873c');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35057, 1980, 2, CONCAT('DASH-TAN / 1-7-6 PROTECTIVE GEAR'), NULL, 'https://ebd.cda.pl/620x368/3450790b6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35058, 1980, 3, CONCAT('THE KILT HIDE / GARAKUTAN'), NULL, 'https://ebd.cda.pl/620x368/3450793c1');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35059, 1980, 4, CONCAT('UENO NO. 13 / The SummonStat'), NULL, 'https://ebd.cda.pl/620x368/3450796d2');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35060, 1980, 5, CONCAT('THE P-SPECTER / THE PE RESERVER'), NULL, 'https://ebd.cda.pl/620x368/345079944');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35061, 1980, 6, CONCAT('II UMBRELLA / E-Q BOOSTER'), NULL, 'https://ebd.cda.pl/620x368/3450805da');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35062, 1980, 7, CONCAT('PANTY ROTI / THE GATCHA-PORTER'), NULL, 'https://ebd.cda.pl/620x368/34508084f');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35063, 1980, 8, CONCAT('COITSU NATE LUNA D/Pero-Lilion'), NULL, 'https://ebd.cda.pl/620x368/3450811b6');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35064, 1980, 9, CONCAT('JIGATIGHTS / SQ-WATER'), NULL, 'https://ebd.cda.pl/620x368/34508147d');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35065, 1980, 10, CONCAT('KANCHIKAN / REPARA-TE'), NULL, 'https://ebd.cda.pl/620x368/3450817f8');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35066, 1980, 11, CONCAT('INVISI-BLOOMER / THE REAR-SKIRT'), NULL, 'https://ebd.cda.pl/620x368/3450820c7');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (35067, 1980, 12, CONCAT('GAN-Q / BALLET-TAN'), NULL, 'https://ebd.cda.pl/620x368/345082307');
