INSERT INTO Animes(AnimeID, AnimeTitle, AnimeDesc, TypeID, AiredBegin, AiredEnd, Premiered, Duration, PosterUrl) VALUES (2072, CONCAT('Yofukashi no Uta'), CONCAT('Kou Yamori is an average middle school student who struggles with grasping the complex concept of love. Because he sees little sense in surrendering to the norm, he soon stops going to school. Plagued with insomnia due to his idleness, Kou begins roaming the lonesome streets at night.<br>
<br>One night, Kou encounters a bizarre girl named Nazuna Nanakusa who believes that people stay awake during the night because they are dissatisfied with how they spent their day and cannot rest until they release their inhibitions. Nazuna offers to help Kou with his sleep issues and invites him over to her place, where she convinces him to share a futon with her. Feeling uncomfortable, Kou only pretends to doze off—which is when Nazuna suddenly bites his neck, revealing herself to be a vampire!<br>
<br>While Kou thinks the bite will turn him into a vampire, the specifics of transforming are not that simple. In order to change, he must be bitten by someone he truly loves. Ready to let go of his dreary mortal life, Kou decides on a new goal: he will fall in love with Nazuna and become a vampire himself.<br>
<br>[Written by MAL Rewrite]<br>'), 1, '2022-07-08', '2022-09-30', 'Summer 2022', '22 min. per ep.', 'https://cdn.myanimelist.net/images/anime/1045/123711.jpg');
INSERT INTO AnimeDemographics(BindingID, AnimeID, GroupID) VALUES (859, 2072, 1);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5151, 2072, 7);
INSERT INTO AnimeGenres(BindingID, AnimeID, GenreID) VALUES (5152, 2072, 10);
INSERT INTO AnimeProducers(BindingID, AnimeID, ProducerID) VALUES (2245, 2072, 37);
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36318, 2072, 1, CONCAT('Night Flight'), '2022-07-08', 'https://ebd.cda.pl/620x368/1138663712');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36319, 2072, 2, CONCAT('Do You Do Line?'), '2022-07-15', 'https://drive.google.com/file/d/1eVqMSCuL7E-LKjL-5wDetBH21AnwOE0N/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36320, 2072, 3, CONCAT('A Lot Came Out'), '2022-07-22', 'https://drive.google.com/file/d/19Ui0ZFjkcPye5WLKXO1A8_yysxQ1lKvR/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36321, 2072, 4, CONCAT('Isn', CHAR(39), 't This a Tight Squeeze?'), '2022-07-29', 'https://drive.google.com/file/d/14C7Mjc6Q9EsZy6tBRTr3OoEBiL90R8gm/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36322, 2072, 5, CONCAT('Well, That', CHAR(39), 's a Problem'), '2022-08-05', 'https://drive.google.com/file/d/11F0KNiwNz9xXPmoxcp75XsMY4LbDScBt/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36323, 2072, 6, CONCAT('Might as Well Have Fun'), '2022-08-12', 'https://drive.google.com/file/d/1IAN9x30fztUWsZCo6ee_d5KNqyxgWNSM/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36324, 2072, 7, CONCAT('Reproduce'), '2022-08-19', 'https://drive.google.com/file/d/1vbr5ZcdPvdK9iSQLZdhznUuzSkIyUKcD/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36325, 2072, 8, CONCAT('All of Us'), '2022-08-26', 'https://drive.google.com/file/d/10tOrH4P0ahXVuRC8IPw9iHKfJojLnHgk/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36326, 2072, 9, CONCAT('No Fair'), '2022-09-02', 'https://drive.google.com/file/d/1arGA6RLUjuxbQKrs0ut7tTB7Q7hINPXu/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36327, 2072, 10, CONCAT('Enlarge the Peeping-Tom Photos'), '2022-09-09', 'https://drive.google.com/file/d/1-7GxIo0Bl-apwkhV0KVbS5iJEFSxwzgB/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36328, 2072, 11, CONCAT('Do You Know What a Vampire Is?'), '2022-09-16', 'https://drive.google.com/file/d/1sHPiCOMwNi2oColkNWRi4cE7tZU9utgr/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36329, 2072, 12, CONCAT('My Mom', CHAR(39), 's Out Tonight'), '2022-09-23', 'https://drive.google.com/file/d/1Zn_awB1jQWsze4xUA1_HfNEcrcJaYkue/preview');
INSERT INTO Episodes(EpisodeID, AnimeID, EpisodeNr, Title, Aired, PlayerUrl) VALUES (36330, 2072, 13, CONCAT('Call of the Night'), '2022-09-30', 'https://drive.google.com/file/d/1a6bfJeM_0G7FgkwRZEz3Jf6eDUFGlrp5/preview');
