INSERT INTO Producers(ProducerID, ProducerName) VALUES (1, 'Toei Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (2, 'Production I.G');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (3, 'OLM');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (4, 'ufotable');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (5, 'Gonzo');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (6, 'A-1 Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (7, 'Shaft');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (8, 'Hoods Entertainment');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (9, 'Studio Junio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (10, 'Tezuka Productions');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (11, 'Studio Kai');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (12, 'Seven Arcs');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (13, 'Doga Kobo');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (14, 'Kyoto Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (15, 'Animation Do');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (16, 'Studio Gokumi');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (17, 'Manglobe');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (18, 'AIC');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (19, 'Anima&Co.');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (20, 'Gainax');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (21, 'Madhouse');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (22, 'CloverWorks');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (23, 'TMS Entertainment');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (24, 'CygamesPictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (25, 'Artmic');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (26, 'HOTZIPANG');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (27, 'Sunrise');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (28, 'Fanworks');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (29, 'Felix Film');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (30, 'Diomedéa');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (31, 'J.C.Staff');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (32, 'Studio Fantasia');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (33, 'AIC Spirits');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (34, 'asread.');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (35, CONCAT('Brain', CHAR(39), 's Base'));
INSERT INTO Producers(ProducerID, ProducerName) VALUES (36, 'Bridge');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (37, 'LIDENFILMS');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (38, 'White Fox');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (39, 'DandeLion Animation Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (40, 'Jumonji');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (41, 'Okuruto Noboru');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (42, 'Pierrot');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (43, 'Satelight');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (44, 'Zexcs');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (45, 'TROYCA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (46, 'Studio Deen');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (47, 'Khara');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (48, 'EMT Squared');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (49, 'Lerche');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (50, 'SILVER LINK.');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (51, 'Connect');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (52, 'P.A. Works');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (53, 'NAZ');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (54, 'Imagineer');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (55, 'Seven');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (56, 'Shin-Ei Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (57, 'WAO World');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (58, 'Passione');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (59, 'Fifth Avenue');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (60, 'SANZIGEN');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (61, 'TYO Animations');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (62, 'Lay-duce');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (63, 'feel.');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (64, 'Trigger');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (65, 'Hal Film Maker');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (66, 'Yostar Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (67, 'Dynamo Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (68, 'Studio Colorido');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (69, 'team Yamahitsuji');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (70, 'Signal.MD');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (71, 'CANDY BOX');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (72, 'Hotline');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (73, 'MAPPA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (74, 'Gathering');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (75, 'Kinema Citrus');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (76, 'Palm Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (77, 'Bones');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (78, 'Actas');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (79, 'Orange');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (80, 'LandQ studios');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (81, 'David Production');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (82, 'Creators in Pack');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (83, 'Millepensee');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (84, 'GEMBA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (85, 'Studio 4°C');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (86, 'Bandai Namco Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (87, 'Ordet');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (88, 'teamKG');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (89, 'Namu Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (90, '8bit');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (91, 'Studio Blanc');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (92, 'AIC Build');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (93, 'Nomad');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (94, 'Silver');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (95, 'Arvo Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (96, 'Xebec');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (97, 'CoMix Wave Films');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (98, 'Tatsunoko Production');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (99, 'Group TAC');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (100, 'Haoliners Animation League');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (101, 'Telecom Animation Film');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (102, 'Graphinica');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (103, 'Blade');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (104, 'Science SARU');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (105, 'Bouncy');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (106, 'Project No.9');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (107, 'Lesprit');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (108, 'GoHands');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (109, 'Yumeta Company');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (110, 'Studio Flad');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (111, 'Nut');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (112, 'Tama Production');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (113, 'AIC PLUS+');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (114, 'Encourage Films');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (115, 'A-Real');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (116, 'SynergySP');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (117, 'Vega Entertainment');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (118, 'Platinum Vision');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (119, 'Studio Bind');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (120, 'Adonero');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (121, 'Asahi Production');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (122, 'Zero-G');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (123, 'Hoods Drifters Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (124, 'Shuka');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (125, 'Pierrot Plus');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (126, 'AIC Classic');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (127, 'Bee Train');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (128, 'TNK');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (129, 'Arms');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (130, 'Lapin Track');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (131, 'Shirogumi');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (132, 'Studio Comet');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (133, 'Square Enix Visual Works');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (134, 'Studio 3Hz');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (135, 'None found,');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (136, 'add some');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (137, 'A.C.G.T.');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (138, 'EKACHI EPILKA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (139, 'studio MOTHER');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (140, 'HORNETS');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (141, 'DLE');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (142, 'AIC ASTA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (143, 'Tokyo Kids');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (144, 'Minami Machi Bugyousho');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (145, 'Pine Jam');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (146, 'AtelierPontdarc');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (147, 'Pastel');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (148, 'Strawberry Meets Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (149, 'GEEK TOYS');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (150, 'Studio elle');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (151, 'l-a-unch・BOX');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (152, 'Karaku');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (153, 'K-Factory');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (154, 'Kitty Film Mitaka Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (155, 'Geno Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (156, 'Nexus');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (157, 'Plum');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (158, 'Wit Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (159, 'Sunrise Beyond');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (160, 'B.CMAY PICTURES');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (161, 'W-Toon Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (162, 'DMM.futureworks');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (163, 'Nippon Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (164, 'Radix');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (165, 'C-Station');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (166, 'Ezόla');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (167, 'C2C');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (168, 'ENGI');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (169, 'Studio LAN');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (170, 'XEBEC M2');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (171, 'Polygon Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (172, 'Ajia-Do');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (173, 'Daume');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (174, 'Marvy Jack');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (175, 'Artland');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (176, 'Studio VOLN');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (177, 'Dongwoo A&E');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (178, 'Jinnis Animation Studios');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (179, 'Datama Film');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (180, 'Production IMS');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (181, 'Studio Ghibli');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (182, 'Gallop');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (183, 'Team TillDawn');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (184, 'Studio PuYUKAI');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (185, 'Production Reed');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (186, 'Saetta');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (187, 'Larx Entertainment');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (188, 'Studio Flag');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (189, 'AXsiZ');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (190, 'APPP');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (191, 'Tomovies');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (192, 'LIDENFILMS Kyoto Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (193, 'Maho Film');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (194, 'Yaoyorozu');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (195, 'Studio A-CAT');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (196, 'Studio Hibari');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (197, 'Assez Finaud Fabric');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (198, 'PrimeTime');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (199, 'Gaina');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (200, 'Yokohama Animation Lab');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (201, 'Kachidoki Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (202, 'Tear Studio');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (203, 'Studio Kafka');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (204, 'Bee Media');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (205, 'Code');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (206, 'Office No. 8');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (207, 'Majin');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (208, 'ACC Production');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (209, 'Seven Arcs Pictures');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (210, 'Tengu Kobo');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (211, 'Triangle Staff');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (212, 'Thundray');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (213, 'P.I.C.S.');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (214, 'Studio M2');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (215, 'Imagin');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (216, 'Wolfsbane');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (217, 'Bibury Animation Studios');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (218, 'production doA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (219, 'OZ');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (220, CONCAT('Children', CHAR(39), 's Playground Entertainment'));
INSERT INTO Producers(ProducerID, ProducerName) VALUES (221, 'ILCA');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (222, 'Studio Palette');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (223, 'domerica');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (224, 'Twilight Town');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (225, 'Trans Arts');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (226, 'Ginga Ya');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (227, 'BigFireBird Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (228, 'Revoroot');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (229, 'Toho Interactive Animation');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (230, 'I.Gzwei');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (231, 'Tokyo Movie Shinsha');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (232, 'Kamikaze Douga');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (233, 'Acca effe');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (234, 'Giga Production');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (235, 'Studio Lings');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (236, 'DR Movie');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (237, 'BreakBottle');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (238, 'Gambit');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (239, 'BeSTACK');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (240, 'Robot Communications');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (241, 'Gainax Kyoto');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (242, 'Lide');
INSERT INTO Producers(ProducerID, ProducerName) VALUES (243, 'Studio Moriken');
